### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by AidanG1** [futo-org/grayjay-android#1]
There is currently no readme for this project. The readme should link to the Gitlab, explains what Grayjay is, and show the logo.

**Comment by McIrco95** [comment]
#Grayjay 
The Grayjay app by FUTO is aiming to make it easy to follow creators not platforms by providing one unified player and feed showing you videos from many different sources like Youtube, Odysee, Rumble, Patreon and more. 

You can find more information and download the app on grayjay.app

Bug reports and feature requests can be send as issues here on GitHub or thru the app. 

The code is on GitLab:
https://gitlab.futo.org/videostreaming/grayjay

**Comment by McIrco95** [comment]
Without a readme this project seams abandoned
The fact that there are no reactions to the issues is not helping
I wrote a litle something that would be much better then nothing (plasee make it a readme)
I forgot the zulip link 
Finding the different websites where info is scattered is hard right now
