### ISSUE TITLE
[Feature Request] Full screen on Dex Mode

### ISSUE THREAD

**Issue by FloatingLizard** [futo-org/grayjay-android#100]
Hello,

  I mostly use DEX and GrayJay can not expand to full screen and if does half the videos are visible.  Now this should be a feature request and I was not able to the possibility.

**Comment by Zvonimir-FUTO** [comment]
Hey, it's been a while. Is this an issue for you?

**Comment by FloatingLizard** [comment]
I have not tried…. Let me check..On 24 Sep 2024, at 16:39, Zvonimir-FUTO ***@***.***> wrote:﻿
Hey, it's been a while. Is this an issue for you?

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
