### ISSUE TITLE
YT timestamps not supported

### ISSUE THREAD

**Issue by JustCryen** [futo-org/grayjay-android#102]
Links with an embedded timestamp play the video from the beginning, example:  
https://youtu.be/itQLBGQyTX8?t=1563

Additionally, sharing a video with a current timestamp would also be really convenient but that's more of a feature request than an issue.

**Comment by koen-futo** [comment]
This has been implemented in a previous build.

**Comment by JustCryen** [comment]
Weird, it doesn't seem to work for me.
Maybe it's not released yet?

**Comment by koen-futo** [comment]
I just tested it on the production build with your link.

Are you sure you:
1. Are on the sideloaded build (playstore build cannot handle links)
2. Did you allow Grayjay to open supported links?

**Comment by JustCryen** [comment]
Yes and yes.
I'm currently on GrayJay v227, manual update check returns "Already on the newest version"
YT plugin is on version 164 and when checking for updates it returns "Plugin fully up to date"

The link opens with GrayJay fine but from the beginning or automatically on the previously watched timestamp but it doesn't even attempt to load the one embedded in the url.

**Comment by koen-futo** [comment]
I will reopen the issue and investigate

**Comment by JustCryen** [comment]
I was thinking about it and I think I have two possible theories about why it's not working currently for me.

1. Maybe it's the resume playing dialog box requiring an interaction and blocking the timeline progress from reaching the time from the link.
2. Since I'm using sponsorblock, maybe it is what's blocking the timeline progression.

It doesn't help that I have the resume watching aligned with the start of the advert segment but it's likely either one or the other. I've tried disabling the SB for testing this for you but the setting slider seems to be "stuck" in the enabled position so I've given up trying to disable it for now.

Btw, I'm using sponsorblock with manual skip mode, so it never skips by itself. I'd rather have the option to choose which adverts from what creators I'm allowing but that actually sounds like a feature that might also block other means of skipping the video from working correctly.

**Comment by Kelvin-FUTO** [comment]
Without Sponsorblock, it appears to work correctly.
After I enabled Sponsorblock, it started failing, and immediately skip to the start.
Disabling it again makes it work again.
After moving a little, I can see it detecting the timestamp skip and it forwarding again.

So I'm pretty sure its conflicting Sponsorblock chapters. The way Sponsorblock chapters work in Grayjay is that they try to interlace with video chapters, this is where things probably go wrong. I'll see if I can investigate it soon.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
