### ISSUE TITLE
[Bug] Patreon plugin failed, entirely

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/grayjay-android#1020]
# Summary
Patreon plugin completely failed. Can't import channels; can't load channels.

# Reproduce
Load or import channels

# Observed result
Loading channel (Road Guy Rob)
![Screenshot_20240522_010330_Grayjay.jpg](https://github.com/futo-org/grayjay-android/assets/45671764/b1673d13-83b3-4360-b729-1c6ef190be43)

Attempt to import channel (Coffeezilla)
![Screenshot_20240522_010438_Grayjay.jpg](https://github.com/futo-org/grayjay-android/assets/45671764/21666c3c-83bf-457e-b3f6-2fce27839444)

# Version details
- Samsung Galaxy S22; OneUI 6.1
- Android 14
- Grayjay 242 release
- Patreon plugin 14

**Comment by VoxelPrismatic** [comment]
Also:
I did try to re-login, both with and without clear. Didn't work.

**Comment by Kelvin-FUTO** [comment]
I'm working on Patreon today. So I'll make sure this gets fixed.
