### ISSUE TITLE
[Bug] Can't unsubscribe from certain channels unless I remove them from groups first

### ISSUE THREAD

**Issue by nastynick64** [futo-org/grayjay-android#1021]
Futo version: version 242
Phone: Pixel 5 running GrapheneOS (Build number: 2024051500)
Android version: Android 14
(idk if any of this info is relevant or if I did it right, but let me know.)

I subscribed to tyler1 (channel name: [loltyler1](https://www.youtube.com/channel/UCwV_0HmQkRrTcrReaMxPeDw)). I put him in a channel group called "Gaming". I unsubscribed (without removing from the channel group) cause I'm not interested in League of Legends, but his videos kept showing up anyways. Then I removed him from the channel group and THEN unsubscribed, now, the videos doesn't show up.

Same happened with a channel called "[Papa Gut](https://www.youtube.com/@PapaGut)", it was in group called "Commentary"

I'm pretty sure I unsubscribed from some channels that we're in a group before, and this didn't happen. Maybe because I was using an older version of the app, or maybe it has something to do with these channel somehow (I don't know how this stuff works), so I decided to provide the names and links to these channels.

**Comment by TheDeviantCrafter** [comment]
Same issue here. Hitting the unsubscribe button would appear to work, but the creator would still be in my subscription feed. Removing them from the music list and then unsubscribing worked.

Grayjay version: 264
Youtube plugin version: 209
Signed in: yes

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the upcoming release (v265).
