### ISSUE TITLE
Autorotate Settings and Sensitivity Issues

### ISSUE THREAD

**Issue by domglusk** [futo-org/grayjay-android#1027]
The autorotate options don't respect my phones settings, where I have disabled it. This is when the option "Auto-Rotate" is set to "Same as System" AND disabled, autorotation still occurs. 
The other issue is autorotate is extremely sensitive, if I barely move my phone when walking around it'll rotate to horizontal and vertical and vice versa over and over again. Changing the "Auto-Rotate Dead Zone" does nothing, at least from what I can tell. 
The expected behavior is when hitting the fullscreen button it'll rotate horizontally and never rotate until I exit fullscreen and it rotates back to vertical. 

Info:
Version - 242
Version Type - Release
Phone - Samsung S21
Android - 14
One UI version - 6.1

**Comment by xephos1one** [comment]
For the future: Please open one issue for each problem you have instead of putting multiple problems in one issue (after checking if they might already exist)
Your second issue is #67

**Comment by domglusk** [comment]
Sorry I will do that if I have another issue to report, thanks!

**Comment by Zvonimir-FUTO** [comment]
Will be solved through #67
