### ISSUE TITLE
[Bug] Grayjay doesn't interrupt/will not be interrupted by playback

### ISSUE THREAD

**Issue by BakuretsuEnjoyer** [futo-org/grayjay-android#1039]
On Android audio playback usually stops any other playback. For example, starting a video from the YouTube app interrupts audio playing from Spotify and vice versa. When starting playback on Grayjay the previous playback keeps playing simultaneously with grayjay. Likewise, starting playback on another application doesn't interrupt Grayjay's playback and both play simultaneously.

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
