### ISSUE TITLE
Aggressive Autorotate

### ISSUE THREAD

**Issue by lolakuti** [futo-org/grayjay-android#1041]
The auto rotate is very aggressive even after Disabling /setting as system(disabled) /setting Deadzone at max (20°)

The app is practically irritating when trying to watch lying down

Info:
Version - 242
Version Type - Release
Phone - Moto Edge 30
Android - 13

**Comment by dcalitri** [comment]
I have the same issue too.

**Comment by dcalitri** [comment]
It also leads to a double overlay of the video ui.

**Comment by xephos1one** [comment]
Duplicate of #67

**Comment by KannaHayabusa** [comment]
So glad that I paid for something the devs have not fixed for more than half a year!

**Comment by Zvonimir-FUTO** [comment]
Will be solved through #67
