### ISSUE TITLE
[BUG] Automatic liking on policentric

### ISSUE THREAD

**Issue by Five-ostriches-in-a-trenchcoat** [futo-org/grayjay-android#1042]
At times when I go back to videos I haven't fully watched, they show me that I already liked them, when my habit is to like videos only in the end (earliest when patreon supporters start to scroll by). I couldn't reproduce it, but it happend on a video I started ~8h ago, stopped it after 30%ish, watched multiple others and came back to it a few minutes ago, with the like being now 1 instead of 0 and being blue.
I will try to make more tests, and see if I can reproduce it reliably.

**Comment by Five-ostriches-in-a-trenchcoat** [comment]
The fastest it happend to me was on a 45 minute video, after watching 4½ minutes and coming back to it after 30 minutes. Have forgotten to note how I "exited" the video.

**Comment by VoxelPrismatic** [comment]
I know that I managed to vote on a few things, and now it's at 0. When I remove my vote, it reads -1.

**Comment by golgothan666** [comment]
are the videos in playlists, because that's what's happening to me

if i like one video in a list... they all get liked

and the weird thing with negative counts as well

**Comment by Hanif-F** [comment]
Happened to me, and the video wasn't in a playlist. I remember it's happening since the very start when Grayjay was just released, although, I might be mistaken.

**Comment by TerryMartinez** [comment]
I have that "problem" on UNWATCH Videos ....
they are alll liked at least Once even if NOBODY using this app watched it !!!

**Comment by Five-ostriches-in-a-trenchcoat** [comment]
So, the videos I watch are not in a playlist. I'm now sure that it doesn't happen for me when I end the video by either closing grayjay or close the video in the miniplayer via the X. It does happen definitivly when the videos are in a queue, and I suspect it also happens when I end a video by just selecting a new one to play. I am absolutly not opposed by these, would just have liked to know that befor I noticed it or found something in the settings, even if it cannot be disabled. I would even go so far to say this is probably a feature, especially for the queue, so that content gets the response it probably deserves, when people generally probably don't go back to like videos they've watched.
This is why I'm going to close this issue.
