### ISSUE TITLE
Can't set up link handling

### ISSUE THREAD

**Issue by NightWatchman** [futo-org/grayjay-android#1043]
- Nothing Phone 2a
- Android v14
- Android security update April 1, 2024
- Google Play system update May 1, 2024
- GrayJay app v236

When I attempt to set up "Link Handling" from the settings menu, I get the error: "Play store version does not support default URL handling."

I'd love to set this up, since it's currently quite annoying trying to add a video I saw via the web browser to my GrayJay playlist.

**Comment by xephos1one** [comment]
Related to #905 where I didn't get an answer to my questions I asked (after the issue got closed).

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Comment by luleyleo** [comment]
I still get this error on the current Play Store version (278). Is this a regression or has this never actually been fixed?

**Comment by Zvonimir-FUTO** [comment]
> I still get this error on the current Play Store version (278). Is this a regression or has this never actually been fixed?

This is intended behavior on Play Store version to avoid being removed from it.
