### ISSUE TITLE
[Bug?] Some videos are unavailable 

### ISSUE THREAD

**Issue by Koolkide900** [futo-org/grayjay-android#1044]
I tried looking up this video

https://www.youtube.com/watch?v=NmJvUsNcA2s

on Grayjay and it would not appear regardless of attempting to open the link through the app or searching for it with various search terms.

**Comment by xephos1one** [comment]
Is it "Boarder 70"?
It is loading for me when I searched for the URL (in the subscriptions tab).
Grayjay version 236, YT-Plugin version 177.

But...
If I now click on the link in the search history it doesn't open a video and instead shows 1 search result "Riders Republic"
But that's a different issue.

**Comment by Koolkide900** [comment]
Still not loading, even if I type the link into the subscriptions tab.
Grayjay Version 253, Youtube Version 187

**Comment by sun1423** [comment]
in my subscriptions channels most videos don't appear thought they appear in YT or newpipe perfectly

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Comment by TheDeviantCrafter** [comment]
Youtube automatically generates "Name - Topic" channels for music creators. I'm unable to find any of those when searching. If I manually navigate to a topic channel from a video I have saved in an imported Youtube playlist, Grayjay fails to display any videos.

**Comment by Zvonimir-FUTO** [comment]
@TheDeviantCrafter could you please open a new issue for this and link channel/videos examples?
