### ISSUE TITLE
[Feature request] multiple device shared

### ISSUE THREAD

**Issue by Nman9000** [futo-org/grayjay-android#1046]
I would like a way for users like myself who have multiple devices that I use to watch content on, to share the subscriptions, playlists, history, etc. between the devices. I generally use my phone while at work and when I get home I would like to be able to just pull up that video on my tablet and just continue where I left off. 
Thank you.

**Comment by golgothan666** [comment]
i think they would need to charge a subscription fee, because that would require a centralized server, as i believe the data is only stored locally (except for Polycentric)... unless they offered a pairing feature, that would link the devices directly to each other's IP addresses somehow

**Comment by grayjay-support-FUTO** [comment]
This is something that is already being worked on. We developed a sync as it was needed for Desktop application that is being worked on as well. It will be released in the next version of Grayjay.

**Comment by Zvonimir-FUTO** [comment]
Sync has been implemented in version 265 of Grayjay.
