### ISSUE TITLE
YouTube - Unable to resolve host

### ISSUE THREAD

**Issue by 1VeeVoo** [futo-org/grayjay-android#1047]
I just downloaded the universal release and imported my backup (up until yesterday I used the play store version) and I got this issue:

"Unable to resolve host "www.youtube.com"
No address associated with hostname (152)[35-36]"

I already tried disabling and re-enabling the plugin, as well as reinstalling. This started happening on the play store version too.

Latest version used, Poco x3, rooted, with evoX surya latest version

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
