### ISSUE TITLE
Older unwatched videos disappear from the subscription feed

### ISSUE THREAD

**Issue by ThePrivacyPlayer** [futo-org/grayjay-android#1048]
Hello,

I haven't found this issue reported yet, but it appears that videos from the subscriptions tab are not shown anymore after a few days, though not consistently.

This means that if I've watched all videos in the last few days, my subscriptions feed shows empty. Every once in a while, a slightly older video or two will show up, and even more rarely I'd get a full feed of unwatched videos (which is what I'm expecting to happen all the time).

This means that if I want to watch older videos from my subscriptions, (possibly because the video was long and I didn't have the time to watch it before), I'd have to go to each specific channel and scroll down until I find it, which is not convenient.

I searched for a setting to control this, but didn't find any. Is this the intended behaviour? If so, would it be possible to add a setting for choosing which behaviour we prefer (hiding or not videos in subscription feed that are older than x days)?

Thank you!

**Comment by VoxelPrismatic** [comment]
Can you double check your options here? Mine are set to only display videos. Not posts or upcoming live streams.
![Screenshot_20240604_215526_Grayjay](https://github.com/futo-org/grayjay-android/assets/45671764/d3a684c7-e98d-4d29-a689-76b8b6675a16)

**Comment by ThePrivacyPlayer** [comment]
Still the same even with just videos selected, however it shouldn't matter, if I want to view everything, the app should be able to pull everything and have a neverending feed, right?

They managed to have a neverending feed for home page a while ago, and it should work the same way for subscriptions.

**Comment by VoxelPrismatic** [comment]
Well yes, but if your 'Watched' button is disabled, then that explains why you don't see anything after watching everything :/

**Comment by ThePrivacyPlayer** [comment]
Well, that's not what I'm saying in my post. What I'm saying is that older **Unwatched** videos stop showing in the subscriptions feed after a few days, and I just see the most recent Unwatched videos, but not the rest, and don't have a way to view the older Unwatched videos unless I go to each creator's tab individually.

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
