### ISSUE TITLE
[Bugs] Youtube - unavailable video/no sources found

### ISSUE THREAD

**Issue by UnknownUsernme** [futo-org/grayjay-android#1049]
After clicking on a video in my home/subscriptions tap the video would start to load for about 2-5 seconds then the error message pops up, however when searching the video via the link the error message pops up almost instantly and this video is the only one that I've found that has this issue (link to video https://www.youtube.com/watch?v=qCZX73RUV0w). I've tried disabling and re-enabling the youtube plug-in, logging out and back in, reinstalling the plug-in, and clearing the cashe but the video still has the error, app version 242 and youtube plug-in version 177.

Also when clicking back on the error message while rotated in landscape it locks the rest of the app in landscape until you click on another video and rotate back to portrait or close another video, however the second method does not work with the video with the first issue described above.
![Screenshot_20240531_123909_Grayjay](https://github.com/futo-org/grayjay-android/assets/163794269/367ea4e6-a0b2-4127-a47e-49816da11e27)
![Screenshot_20240531_133623_Grayjay (1)](https://github.com/futo-org/grayjay-android/assets/163794269/2371feca-a189-495a-b117-8c67a7785b8d)

**Comment by grayjay-support-FUTO** [comment]
The video you linked has been privated so it's impossible to view it even on youtube website unless you have special access to it.

**Comment by easter-eat-ser** [comment]
The exact same issue is still affecting me while watching YouTube videos, but not livestreams(archived or no). GrayJay has slowly been cycling through different video platforms(e.g. iOS) shown in the picture quality settings - does this have anything to do with it? Enabling the authenticated player does not help

**Comment by PseudoMortus** [comment]
So I had this issue within the last few days and upon preliminary tests found that turning off, "Use login for video details," worked around issue. I don't know if it's an actual work around or if it just worked on my end, someone else may need to test to be sure.

**Comment by support-grayjay** [comment]
@UnknownUsernme I couldn't find the video in question. Could it be just that it is in fact deleted?

**Comment by UnknownUsernme** [comment]
@support-grayjay sorry for the wait, I forgot that I made this but here's an update. The video was previously marked as age restricted and demonetized, I don't know if the original video was deleted or privated but it was reuploaded not to long after and worked normally after that and
I've had no other issues simmiler to this
