### ISSUE TITLE
[BUG] skippimg/fast forwarding with unexpected behaviour when video is flipped

### ISSUE THREAD

**Issue by B00fie** [futo-org/grayjay-android#1052]
On mobile, İf a video is playing on full screen, when you tap one side couple of times, video is skipped/ forwards x seconds (as normal) also continiual of tapping more  extends the forward skip time. During this extended tapping if you flip your phone screen, no matter if you tap the opposite side, skipping is done on the previous side.

Expected behaviour:
While continiually tapping (to right for forwarding for ex.) swapping the screen flips the video (thus landing my right as backwards). After the flip, I would expect the continiual tapping on the right to roll video backwards (add on backwards skip)

While this might be expected behaviour on my use case, some people might use the old way so a toggle switch for this option seems more viable

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
