### ISSUE TITLE
Password confirmation/unhide for auto backup

### ISSUE THREAD

**Issue by FraYoshi** [futo-org/grayjay-android#1056]
When setting up an automatic external backup, the user is prompted for a password but there is no confirmation nor an un-hide option, so the user cannot really be sure if they mistyped it.

Proposed solution:
- un-hide pass
- confirm pass
- both
- both, but if un-hide is pressed, confirmation is not needed.

**Comment by grayjay-support-FUTO** [comment]
Duplicate of #210.
