### ISSUE TITLE
YT on home feed only loading 14 videos

### ISSUE THREAD

**Issue by SilverWerewolf** [futo-org/grayjay-android#1059]
As per title, my app is only pulling through 14 videos from my YT account to the home page. 

Have tried rebooting app and plugin updates.

Android 10 Sony Xperia XZ2

**Comment by Gquitto** [comment]
Same problem here, only difference is thar my home loads 27, then a blank space, and it won't load anything else. Only happens in the home screen, subscriptions page loads as it should 🤔.

Xiaomi 13T Pro running Android 14
![Screenshot_2024-06-10-23-30-41-556_com futo platformplayer-edit](https://github.com/futo-org/grayjay-android/assets/43350280/a9f05dab-ef00-4737-b8b6-504506755081)

**Comment by RediTafa** [comment]
I have the same issue and mine reloads the same videos.

**Comment by strangelyinteresting** [comment]
in the sources tab, try signing out of the source you're having the issue with and sign back in again. that fixed it for me.

hope that helps you!

**Comment by Gquitto** [comment]
Damn, that actually solved it, thanks!

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
