### ISSUE TITLE
Autozooming problem

### ISSUE THREAD

**Issue by karolchilinski** [futo-org/grayjay-android#1061]
It autozooms all by itself with me without zooming in that is kinda annoying.

https://github.com/futo-org/grayjay-android/assets/97901412/deea6e78-570c-44ff-8d95-03a5d40813a8

**Comment by xephos1one** [comment]
How about some more information?
Grayjay Version,
phone model and version...

**Comment by b-risk** [comment]
I believe this is a feature and the video you are playing is a wide video so when you zoom in it snaps to as big as it can get.

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
