### ISSUE TITLE
Overrides system auto brightness

### ISSUE THREAD

**Issue by pozer89** [futo-org/grayjay-android#1069]
Changing brightness in app. (Usually by accident) turns off system auto brightness. 

I've narrowed it down to this app. If I change the on-screen brightness, it overrides the system brightness. I believe the issue is when exiting full-screen mode, it restores the system brightness  to last known but doesn't turn the system auto-brightness back on. I keep finding my system auto brightness toggled off. So when you go outside, the screen appears black. For now the fix is to turn the settings off. So the app can't change the screen bightness.

**Comment by VoxelPrismatic** [comment]
![Screenshot_20240613_205301_Grayjay](https://github.com/futo-org/grayjay-android/assets/45671764/fc9209a9-adb5-4047-a689-28819fd3645b)

**Comment by JustCryen** [comment]
Turning off the app control over system brightness has an additional benefit of allowing you to get really dark when watching something at night!

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
