### ISSUE TITLE
YouTube importing stuck forever (workaround found)

### ISSUE THREAD

**Issue by iForkU** [futo-org/grayjay-android#1073]
Added YouTube to account to  GrayJay and importing subscriptions failed multiple times: it would get stuck during the import process and only 1 would be imported. Solution that worked for me was to let import list load until GrayJay slowed it to avoid rate limit (set to 200) and doing multiple imports.

No issues with playlists (few playlists, thousands of videos), or twitch (only 20 free subscriptions)

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
