### ISSUE TITLE
YouTube playlist import only showing watch later and liked videos

### ISSUE THREAD

**Issue by Scoots1994** [futo-org/grayjay-android#1076]
I see a "failed to fetch" with a yt playlist URL for each playlist in my account that it is not showing.

I've reset and re setup several times.  Subscriptions import fine.

**Comment by TerryMartinez** [comment]
interesting !

**Comment by Ser-Bul** [comment]
Youtube plugin version?

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
