### ISSUE TITLE
"Plugin updates available" pop up

### ISSUE THREAD

**Issue by Thatstinkyguy** [futo-org/grayjay-android#1078]
Would it be possible to have the "Plugin updates" popup (when starting the app) not list the plugins that aren't installed, and only show available updates for ones that are installed?

Thanks for your time!

Here's an image of what I'm talking about:
![Screenshot_20240615_181937_Grayjay](https://github.com/futo-org/grayjay-android/assets/87314623/f71a32d1-f35f-4967-89d7-a750b02eb32d)

**Comment by VoxelPrismatic** [comment]
Each source has a "check for updates" option. Disable those and you should be all set!

**Comment by Thatstinkyguy** [comment]
> Each source has a "check for updates" option. Disable those and you should be all set!

Thanks for the info. I stumbled upon it myself and forgot to close this. Thanks again!
