### ISSUE TITLE
Error popup

### ISSUE THREAD

**Issue by dcalitri** [futo-org/grayjay-android#1084]
![Screenshot_20240620_000644_Grayjay](https://github.com/futo-org/grayjay-android/assets/71895943/ba119c1a-4968-4604-8190-6d0309c2f590)
I often get this error when I am refreshing my subscriptions. I wonder if this has to do with the subscription rate limit thing.

**Comment by Zvonimir-FUTO** [comment]
Are you still experiencing the issue? Quick fix would be removing the channel from Creators page and adding it again although we could improve the error message.

This happens when creators link changes but after some update we improved handling of that so should be fixed.

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
