### ISSUE TITLE
[BUG] Video stalls when internet connection is interrupted and then resumes.

### ISSUE THREAD

**Issue by pearcebasmanm** [futo-org/grayjay-android#1085]
Expected behavior would be buffering until the connection is re-established, but instead it buffers indefinitely. 

Cannot reproduce this behavior by manually disabling and enabling wifi. Seems to only happen when the disconnection is triggered for other reasons (like a too weak signal).

Version: 242
Sources Confirmed Affected: Youtube
Device: Pixel 6 (which is known to have some connectivity problems)

Workaround: Close video and reopen it from the top of history.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
