### ISSUE TITLE
Allow Deletion of Polycentric Comments

### ISSUE THREAD

**Issue by ungstein** [futo-org/grayjay-android#109]
Currently, there is no way to delete comments posted via Polycentric. I have tried exporting my profile to a web browser, however, it appears it is incompatible with "polycentric.io".

**Comment by lolguy91** [comment]
And editing

Cuz I keep misspelling words

**Comment by Gigaspike** [comment]
Yeah edit and delete would be nice

**Comment by koen-futo** [comment]
Delete will be added next build.
