### ISSUE TITLE
[Issue] Videos only appear while refreshing

### ISSUE THREAD

**Issue by patrbraun** [futo-org/grayjay-android#110]
My videos in the subscription tab only show up and are interactable while I'm refreshing the video list. Once it finishes refreshing they dissapear. 

I'm on a Samsung Galaxy Note 9.

**Comment by Kelvin-FUTO** [comment]
I suspect this was fixed in last version (190) if not, it will likely be fixed in the upcoming version tomorrow (191).
If its not fixed after that, feel free to reopen this issue.

**Comment by patrbraun** [comment]
Unfortunately on 192 my videos no longer show up at all.

**Comment by Kelvin-FUTO** [comment]
Version 193 (YT v148) fixed some issues related you YT accounts with non-english language. For some people this caused channels to show no content. This might be related to this.
