### ISSUE TITLE
Channel not showing up in search suggestions/results

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#111]
Channel does show up in YT results

![image](https://github.com/futo-org/grayjay-android/assets/129423944/a9bdcb8d-8599-4f22-a12e-632241ce771b)
![image](https://github.com/futo-org/grayjay-android/assets/129423944/c9bf3f03-69fc-4dcf-8e86-ea67c5fd9cbf)

**Comment by koen-futo** [comment]
" The name of my channel should appear on its own in the results - below the search box - with a magnifying glass symbol (as it happens when using youtube via the web) AND IT DOESN'T SHOW UP AT ALL (whether I'm logged in or not). In the Grayjay app on my phone I don't appear in the search results either, but there at least I can click ENTER and only then it searches for me."

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the latest version of Youtube plugin.
