### ISSUE TITLE
Spotify not working 

### ISSUE THREAD

**Issue by Cederick** [futo-org/grayjay-android#1117]
### What happened?

So I wanted to test out the new Spotify Source but it's not working at all.
All I get is:
[Spotify] unexpected uri (306) [32-33]
Im running the latest version of Android and GrayJay.
Also wanted to mention that open.spotify.com is missing as an option for link handling. That's the URL type for Playlist and Songs.

### Grayjay Version

249

### What plugins are you seeing the problem on?

All

### Plugin Version

2

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by QofWands** [comment]
I have the same issue

**Comment by contactnat** [comment]
Same problem here

**Comment by tarikki** [comment]
Same here, but only happens when I'm signed into Spotify in Grayjay.

When not signed in:
![Screenshot_20240805-053529](https://github.com/user-attachments/assets/fe26ea90-5fb7-43fe-85fb-8058c4eb4d47)

When signed in:
![Screenshot_20240805-053611](https://github.com/user-attachments/assets/46b6af25-b2f7-4519-9082-60eacc818f3a)

Also when signed in and trying to import spotify playlists I get
`unreachable (2498[24-25]), source.getUserPlaylists()`

And when I try to import subscriptions:
`regex error (2984)[8-9]`

It might be of importance that I'm not on a _paid_ Spotify account. No idea if this has an effect 🤷🏼‍♂

**Comment by HerrNamenlos123** [comment]
Same here, getting the error whenever I am logged in, but can't listen to anything if logged out. I am using paid spotify. Is there any workaround?

**Comment by Damienlee69** [comment]
Can concur. Paid Spotify as well. All links/previews invalid.

**Comment by I-I-IT** [comment]
On latest release. Spotify working (with imported playlists) for 80% of songs. For some reasons, some songs are just not playing.

**Comment by Zvonimir-FUTO** [comment]
This issues should be solved on the latest version of Spotify. Is anyone experiencing the same issue still?

**Comment by I-I-IT** [comment]
> This issues should be solved on the latest version of Spotify. Is anyone experiencing the same issue still?

Playing songs worked once for an EU artist, but now only **works for non-EU artists**. I am living in the EU. 

I have (449)[28-29] error.


 but home screen is still broken.
![2998](https://github.com/user-attachments/assets/72804e20-bfcd-489c-89c0-7b4c38c14542)

**Comment by I-I-IT** [comment]
> > This issues should be solved on the latest version of Spotify. Is anyone experiencing the same issue still?
> 
> Playing songs worked only once for an EU artist, but now only **works for non-EU artists**. I am living in the EU.
> 
> I have (449)[28-29] error.
> 
> btw home screen is still broken.

**Comment by Zvonimir-FUTO** [comment]
I'm testing from EU as well and I didn't have any issues with playing non-EU artists nor with the home screen. 
Could you provide a bit more information like:

- Are you using a VPN by chance?
- What version of Grayjay are you using
- What version of Spotify are you using
- What Phone are you using on which android version

**Comment by kaidelorenzo** [comment]
What country/region in Europe?
If you VPN to the USA does it still not work?
Can you give some examples of things that don't work? Artists or songs or playlists.

**Comment by I-I-IT** [comment]
> What country/region in Europe? If you VPN to the USA does it still not work? Can you give some examples of things that don't work? Artists or songs or playlists.

I already gave example [above](https://github.com/futo-org/grayjay-android/issues/1117#issuecomment-2308898505).

Yes, even I put my VPN in US it doesn't work.
I am not going to specify the country where I live, and that shouldnt make any difference.

**Comment by I-I-IT** [comment]
https://open.spotify.com/track/5a9vdoeBuXGewh9Oe0CfKA

**Comment by kaidelorenzo** [comment]
thanks. I was able to reproduce the issue.

version 5 should have fixes for both issue.

**Comment by I-I-IT** [comment]
Thank you💛 Yes, I just got an update and playing songs now works flawlessly!!!!

BTW, I am curious what caused the issue.

**Comment by I-I-IT** [comment]
> Song playing wise it was some unhandled subtitle/lyric languages (French and other European languages).
> 
Subs works fine for me in French. (I have Premium).

And yes, home screen is still broken  but I don't really care.

**Comment by kaidelorenzo** [comment]
are you getting the same homescreen error? even after pull down refresh?

**Comment by I-I-IT** [comment]
> are you getting the same homescreen error? even after pull down refresh?

I believe yes. But I don't have any subscribtions on Spotify.

**Comment by kaidelorenzo** [comment]
when you get the chance could you send a screenshot of the home page error?

**Comment by I-I-IT** [comment]
![3031](https://github.com/user-attachments/assets/c40cd26f-5aa8-4635-8859-6dd9c2a6be6b)

**Comment by tarikki** [comment]
Also when trying to to import subscriptions or playlists, the errors mentioned [above](https://github.com/futo-org/grayjay-android/issues/1117#issuecomment-2268074906) still happen.

**Comment by kaidelorenzo** [comment]
I pushed a change that should add little logging to the exception. I left the version number the same so you won't get an update notification but if you reinstall from the sources page it will load the new version. Could you send the new exception text?

**Comment by I-I-IT** [comment]
> I pushed a change that should add little logging to the exception. I left the version number the same so you won't get an update notification but if you reinstall from the sources page it will load the new version. Could you send the new exception text?

Thanks, but could you push an update? Cause I don't want to reinstall the plugin as I would be disconnected from Spotify and the connection process from Spotify is a bit buggy for me. (I fear being locked out)

**Comment by I-I-IT** [comment]
Here is the new message: 

![3099](https://github.com/user-attachments/assets/db0c605b-839d-4d0f-b7ca-b3a97223f863)

**Comment by kaidelorenzo** [comment]
ok i'm not entirely sure what content spotify is serving you but it seems to be an actual spotify artist. grayjay doesn't support linking to channels from the home page so i'm going to ignore content with that kind of artist uri. let me know if that resolves the issue / uncovers something new

**Comment by kaidelorenzo** [comment]
Can someone attempt to import subscriptions and playlists and send their error messages? I added some additional info that would be helpful.

**Comment by I-I-IT** [comment]
> ok i'm not entirely sure what content spotify is serving you but it seems to be an actual spotify artist. grayjay doesn't support linking to channels from the home page so i'm going to ignore content with that kind of artist uri. let me know if that resolves the issue / uncovers something new

I am not sure, but now I have personalized playlists, which is great. Thank you.

BTW, It would be great if

**Comment by I-I-IT** [comment]
I noe have this error on my home:

![3115](https://github.com/user-attachments/assets/8e52a224-44dc-4b48-9a5c-eeb9f20da777)

**Comment by kaidelorenzo** [comment]
I added some logging to figure out what playlist type is causing issues

**Comment by jeankhawand** [comment]
> I added some logging in version 9 to figure out what playlist type is causing issues. Could you send a new exception message?
Hi, I can see from my end this: unexpected uri: spotify:collection:podcasts:episodes

**Comment by kaidelorenzo** [comment]
@jeankhawand is that for the home page as well?

**Comment by jeankhawand** [comment]
> @jeankhawand is that for the home page as well?

Exactly!

**Comment by jeankhawand** [comment]
> version 11 should correctly handle that your episodes alias

Working now!

**Comment by I-I-IT** [comment]
This still happens on v11:

![3168](https://github.com/user-attachments/assets/e08bdf63-75d9-41dd-bf10-df2ff7e5a02d)

**Comment by kaidelorenzo** [comment]
version 12 should have a fix for the thumbnail issue

**Comment by I-I-IT** [comment]
Thanks for the fix 🎆. Although the local playlist conversion pop-up is annoying, just do it silently - I don't need this big (scary) pop-up.

**Comment by kaidelorenzo** [comment]
If folks are still having Spotify issues please re-open this issue or create a new one
