### ISSUE TITLE
Error loading youtube

### ISSUE THREAD

**Issue by Bobertowns** [futo-org/grayjay-android#1122]
### What happened?

Get this error anytime i try to load a youtube video.

![Screenshot_20240708_143732_Grayjay](https://github.com/futo-org/grayjay-android/assets/175053545/745b2eab-dda3-4111-902b-a5a22e801bea)

### Grayjay Version

249

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

184

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by RossmannEnjoyer** [comment]
Getting the same problem here with the same versions, even after reinstalling an older version of the app (240) and the youtube plugin (172). Thanks for posting about this I was about to make one myself.

**Comment by june012006** [comment]
Also getting the same error.   Fully up to date

**Comment by MooMooCow1562** [comment]
Same error, fully up to date.

**Comment by Kartonrealista** [comment]
This doesn't happen when I change the account. This is #999 coming back it seems

**Comment by Bobertowns** [comment]
It does sort of seem like a loggin issue. If you logout you can access videos. But not if loggin into at least my account.

**Comment by PseudoMortus** [comment]
Just tried logging in w/out clearing login credentials post being required to do Captcha and so far it's back online if someone wants to verify if it works for sure.

**Comment by chi1l1l** [comment]
Log out w/out clear then log in working for me.

**Comment by Kartonrealista** [comment]
This seems to be fixed in the newest YouTube plugin update.

**Comment by Bobertowns** [comment]
Yeah seems recent update has fixed this.
