### ISSUE TITLE
YouTube login

### ISSUE THREAD

**Issue by PrzemekSkw** [futo-org/grayjay-android#113]
Hello, I login with my Gmail account and I see my YouTube WebView in app (everything was very small like on computer view in browser). Then after restart app I don't see any subscriptions, history, nothing from my account.
Regards.

**Comment by ImranR98** [comment]
You need to click on your profile picture in the web view that opens up.

**Comment by PrzemekSkw** [comment]
Hi, I'm login now and don't see that WebView but I import my subscriptions and remove home tab. Now it works great but don't see history and it don't sync when I watch on tv. It's possible to do that?

**Comment by ImranR98** [comment]
Yes, you can enable History Sync in the plugin settings.

**Comment by PrzemekSkw** [comment]
I don't have that option:
![Screenshot_2023-10-28-12-14-44-59_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/25219988/6fd4aece-6bc3-43e9-afd5-5e2bbef6bbd8)

**Comment by ImranR98** [comment]
I mean on the sources tab. You can click on the YouTube entry - the same place you went to to log in.

**Comment by PrzemekSkw** [comment]
I check all switches but now have problem too see videos.
![Uploading Screenshot_2023-10-28-12-20-28-88_ca2ad563b57b5497046450f16b7718e2.jpg…]()

**Comment by PrzemekSkw** [comment]
![Screenshot_2023-10-28-12-20-28-88_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/25219988/962c2af7-b034-48cd-a4f9-bcda8852b95c)

**Comment by PrzemekSkw** [comment]
First seconds I see videos but after refresh I see nothing:
![Screenshot_2023-10-28-12-21-48-98_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/25219988/35acf6e8-0d1c-4312-a218-241cb5ce2d6e)

**Comment by ImranR98** [comment]
Can't help you there, the videos show up for me.

**Comment by PrzemekSkw** [comment]
OK, I check only:
- Use login for video details
- Provide YT activity
Now it works fine.
Thanks for help.
