### ISSUE TITLE
Comments not being saved / submitted [polycentric]

### ISSUE THREAD

**Issue by JustCryen** [futo-org/grayjay-android#114]
I just realised that apparently my comments are not being submitted. (Standard comments, not hateful or anything like that)  
They appear to be sent for me, they can be viewed in the comment list just after commenting but when i close the video and reopen it later, or even just after closing it, my comment is not there.  
I'm not sure if they're visible for others and not for me… because I can see other people's comments but at least it looks like I've never commented in the first place.

I think this is a really big problem for a platform that focuses on community interactions.

I commented on both of these videos 2 days ago and today respectively and I can't see both of these comments:
https://www.youtube.com/watch?v=y4brX6x3mrM
https://www.youtube.com/watch?v=ZOQOQqxemOI

**Comment by VidathD** [comment]
I have the same issue. Also, polycentric doesn't seem to save the profile picture. When I close polycentric identity and open again, picture is missing

**Comment by koen-futo** [comment]
This should be fixed in version 190.

**Comment by VidathD** [comment]
On 193. Issue is still there

**Comment by JustCryen** [comment]
Seems to be working for me, I commented today and it's visible, I've just checked.  

I updated the icon on v190 and it's also visible. I'm not sure It'll work if I were to change my profile picture now on v193.  
Keep in mind that the profile picture in the settings once you save goes back to that default bubble but once you comment, it's actually updated.

**Comment by VidathD** [comment]
> Seems to be working for me, I commented today and it's visible, I've just checked.  
> 
> I updated the icon on v190 and it's also visible. I'm not sure It'll work if I were to change my profile picture now on v193.  
> Keep in mind that the profile picture in the settings once you save goes back to that default bubble but once you comment, it's actually updated.

Just checked again. When I click out of video and come back to it comment is missing

**Comment by koen-futo** [comment]
Issue has been reopened... looking for more information.
1. If you are having issues, can you try creating a new polycentric profile in settings -> manage polycentric profile and make a comment, let me know if that works
2. With the broken profile, set your log settings to "information", reproduce the issue, click submit logs, let me know the ID, then set log setting back to none

This would help immensely in solving this issue

If not, I will deploy some changes that make errors in backfilling (submitting to polycentric server) more visible

**Comment by koen-futo** [comment]
I have added more verbose errors on backfilling the server in the latest version. If you encounter one of the following situations:
1. Leave a comment on a video, close video, open video, your comment is not there
2. Leave a like/dislike on a video, close video, open video, your like/dislike is not there

This indicates it failed to backfill the server with your events. In the new version you will see an announcement whenever it fails to backfill.

If you encounter this, please post it in this issue thread.

**Comment by JustCryen** [comment]
4 months of inactivity.  
I think it's safe to say it's fixed or the discussion moved to another place.

**Comment by johnsmith744** [comment]
still not fixed.  I am having the same problem.
