### ISSUE TITLE
Hide from Home option does not hide videos from Subscription page

### ISSUE THREAD

**Issue by gorect** [futo-org/grayjay-android#1147]
### What happened?

When trying to hide videos on the subscription page, the videos continue to to remain. I'm not sure if this is an issue with the app, Youtube plugin, or the new server side adds that are being implemented.

### Grayjay Version

249

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

185

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
No error message is displayed when trying to hide videos from the subscription page.
```

**Comment by TheDeviantCrafter** [comment]
I'm getting the same issue. Hitting "Hide from home" closes the options dialog box but does not hide the video or create any error message. The video stays in my feed even after refreshing or fully restarting the app (settings > force stop).

Grayjay version 264
Youtube plugin version 209
Logged in to my Google account

**Comment by TheDeviantCrafter** [comment]
Hiding a video from the home feed works as intended. This issue only occurs when trying to hide a video from the subscriptions feed.

**Comment by gorect** [comment]
Solution found, thanks!
