### ISSUE TITLE
Mark Watched Option

### ISSUE THREAD

**Issue by gorect** [futo-org/grayjay-android#1148]
### Use Cases

When using other apps like NewPipe, I will use the "Marked Watched" option (similar to the hide from Home option) to manage the list of videos that I have either already watched or don't plan on watching. Currently the Hide from Home option is not working in the Subscriptions page. I am able to get around this now by scrubbing through each video until the end to mark it watched, but this method does not always work.

### Proposal

Add an additional button in the options pop-out that sets the progress option from unplayed to watched.

**Comment by McIrco95** [comment]
That already exists. They call it "add to history". You propobly have to scroll a bit down in the options popup

But for me its to many klicks. I hope for a quicker way to mark watched/not interested

**Comment by gorect** [comment]
Ah thank you, yes I didn't notice that. I have been watching each video and scrubbing to the end to make them fall off the queue.

**Comment by support-grayjay** [comment]
There is an when pressing on cogwheel to "Add to history" which is also tilted "Mark as watched".
