### ISSUE TITLE
Storage Permissions

### ISSUE THREAD

**Issue by Mik39907** [futo-org/grayjay-android#115]
Version information (version_name = 181, version_code = 181, flavor = stable
Device information (brand= samsung, manufacturer = samsung, device = dm3q, version-sdk = 33, version-os = samsung/dm3qxeea/dm3q:13/TP1A.220624.014/S918BXXU3AWGJ:user/release-keys)

does not allow me to give permission to storage for daily backup I only can give camera or notification but storage is not an option

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
