### ISSUE TITLE
Email confirmation for purchase

### ISSUE THREAD

**Issue by rabaimorp** [futo-org/grayjay-android#1158]
### Use Cases

Avoid accidental purchases to a broken/wrong email. In the in-app purchase.

### Proposal

In the in-app license purchase, before inputing payment details, the email field could require to type in your email twice, to make sure it the right one, and only allow proceeding if they match.

This could have saved my email to futo support. While making sure the email is right is the user s responsibility, I think a confirmation can't hurt.

**Comment by Zvonimir-FUTO** [comment]
This has been added in the upcoming release.

**Comment by rabaimorp** [comment]
yessir

**Comment by nick-morhun** [comment]
Still not implemented.

**Comment by Zvonimir-FUTO** [comment]
> Still not implemented.

Good catch! This was actually implemented before but we completely rewrote our payment library and forgot to add that in.
Reopening until it's implemented again.
