### ISSUE TITLE
[Feature Request] Make youtube shorts stay vertical when full screened

### ISSUE THREAD

**Issue by timmyp53** [futo-org/grayjay-android#116]
Youtube Shorts Don't Stay Vertical in full screen. Simple enough. Hope this is developed.  Thank you for hard work.

**Comment by Philippe-Choquette** [comment]
Wait, are you saying I can't watch the adorable, passive-agressive shorts of the Under Studio channel using Grayjay? 😢

**Comment by Zvonimir-FUTO** [comment]
This has been implemented in the latest version of Grayjay.

**Comment by PhilC813** [comment]
> This has been implemented in the latest version of Grayjay.

This is a bit difficult to test when #282 is still open; "shorts" don't appear in any channel. Unsure why this is low priority.

**Comment by Zvonimir-FUTO** [comment]
> > This has been implemented in the latest version of Grayjay.
> 
> This is a bit difficult to test when #282 is still open; "shorts" don't appear in any channel. Unsure why this is low priority.

Unlike 282, this issue is opened for having vertical videos full screened vertically instead of landscape. Which has been implemented.
