### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by that404nerd** [futo-org/grayjay-android#1166]
### Use Cases

It would be great if grayjay supports selecting multiple accounts from the sources tab. Really helps people who are managing multiple accounts (with different emails).

### Proposal
I think that adding an option in the settings menu to show a popup that asks the user to select the account that they want to use would be great as well. Or just adding an option in the sources tab that allows for selection between multiple accounts with different emails.

**Comment by that404nerd** [comment]
10 days and no response....

**Comment by lmsalustri** [comment]
Repo is unmoderated

**Comment by that404nerd** [comment]
> Repo is unmoderated

Where should i report then? Even this repo mentions that its an issue tracker...

**Comment by that404nerd** [comment]
Can anyone please respond?
