### ISSUE TITLE
[UI Optimizations/Bugs] Auto rotate sensitivity and offline playback toast repetition

### ISSUE THREAD

**Issue by r9119** [futo-org/grayjay-android#117]
# Device and software details:
Device: Samsung S22
Android version: 13
One UI version: 5.1
GrayJay version: 181 Release

# Issues:
### Toast spam/repetition when using offline play
Just recently noticed that when a video/audio is being played "offline" after its downloaded, a double toast appears saying "Offline Playback" and this toast gets redisplayed every time the app is **opened**, **closed** or when the **settings page is opened**. I've not experienced any other "bugs"/repetitions etc. on any other toast, just the offline playback one.
![image](https://github.com/futo-org/grayjay-android/assets/59576343/c1454875-e0f3-49b1-9fd7-d85e7e4cb142)
### Auto rotate dead zone
Been using grayjay for a while now and one thing that I instantly noticed was the sensitivity of the auto rotate, and the lack of change with an increase in dead zone in the settings.
Unsure if this is due to my device or not, but iirc I had a similar issue with earlier versions of newpipe but which got fixed a while back.

**Comment by Zvonimir-FUTO** [comment]
Rotation issues will be resolved through #67.

Toast doesn't appear anymore every time app is opened, closed or when the settings page is opened but it still does show twice.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the latest version of Grayjay.
