### ISSUE TITLE
Icons doubles in fullscreen video playback 

### ISSUE THREAD

**Issue by SomeonePL** [futo-org/grayjay-android#1175]
### What happened?

Just installed and updated YouTube plugin, selected first video. While rotating phone to play video in fullscreen video playback settings icons double and overlay itself.
1+ 7t Pro with Oxygen OS 12.1
![Screenshot_2024-07-21-22-10-39-75_ca2ad563b57b5497046450f16b7718e2](https://github.com/user-attachments/assets/e8a23d88-a5f4-4f3f-83d8-97d2d64e514d)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

186

### When do you experience the issue?

- [x] While logged in
- [X] While logged out
- [ ] N/A

**Comment by m-kuzmin** [comment]
Can confirm, happens when logged in too.
