### ISSUE TITLE
Option for automatic resume from time left off on previously played video

### ISSUE THREAD

**Issue by Nman9000** [futo-org/grayjay-android#1178]
### Use Cases

I would likecthe option to automatically resume a video from where I left off on instead of having to start the video and click on the resume option within a certain timeframe. I would like this to apply to both individual videos and those in a playlist like the watch later.

### Proposal

I think it would be best for this to be a toggle option in the settings for the app itself and to include the ability for it to apply to single videos only, videos in a playlists only, or both. For videos that have been fully played just have it restart from the beginning instead as usual.

**Comment by lmsalustri** [comment]
Duplicate of #1035

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #400.
