### ISSUE TITLE
Cannot use YouTube account without any channels

### ISSUE THREAD

**Issue by ChaoticNeutralCzech** [futo-org/grayjay-android#1179]
### What happened?

I wanted to set up Grayjay for my under-18 sister. Without logging in, the homepage is for the US (as opposed to NewPipe, which follows the local country) so not relevant for her, so she wanted to use her YouTube account. My parents cleared her access to non-Kids YouTube and removed any restrictions. She still cannot set up a channel to upload videos with but can log in and watch in the regular YouTube Android app.
After clicking the Login button,  
![loginbutton](https://github.com/user-attachments/assets/0fc90e4b-e14a-4f3e-a968-d13bb144b5cb)  
she signs in with her Google account. Then, she is pointed to account selection:
![selectchan](https://github.com/user-attachments/assets/b5bcc590-a045-4375-a3ed-8ab88d40fb1b)  
Selecting the only option, "No channel" (red) leads to a page at https://kids.youtube.com/t/restricted_access?blocked=2  
![nomobile](https://github.com/user-attachments/assets/c2e3f2e9-631a-4395-a77d-4ac62eff1e40)  
The only way to exit this page is the "×" button, which leaves her logged out as far as Grayjay is concerned.  
This is really strange because she can access the full YouTube, not just YouTube Kids, including her subscriptions, playlists etc. within this browser:  
![zvon](https://github.com/user-attachments/assets/b36407b3-099e-46c8-9230-cd489cc3f2da)  

Please allow the use of YouTube accounts with no channels. I will add any information from her or the parents' accounts, or logs, if necessary.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

186

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by lmsalustri** [comment]
Unrelated to GrayJay. The account in question appears to still be a YouTube Kids account. This is a Google issue.

**Comment by ChaoticNeutralCzech** [comment]
So Grayjay uses the YouTube _mobile_ website (which the underage account cannot access) to scrape data such as the video stream and recommended videos despite presenting the YouTube _desktop_ site for login purposes?

**Comment by lmsalustri** [comment]
It would appear so. I'm not a dev or anything, but I'd recommend opening a feature request for this since it isn't a bug in GrayJay.

**Comment by ChaoticNeutralCzech** [comment]
Thanks, I'll tell her to open another Google account. Closed; feel free to message me if you want to add anything and I'll try to reopen the issue.
