### ISSUE TITLE
[Issue] Download exports not working

### ISSUE THREAD

**Issue by r9119** [futo-org/grayjay-android#118]
# Device and software details:
Device: Samsung S22
Android version: 13
One UI version: 5.1
GrayJay version: 181 Release

# Issue:
When trying to export an audio/video file that was downloaded nothing happens, a toast pops up to indicate the export is happening but nothing is exported to the `/Internal storage/Music/Grayjay/` directory.
On first export, the directory is created but nothing further happens.
![image](https://github.com/futo-org/grayjay-android/assets/59576343/5f579b6d-0aff-4065-a2de-f271002b1239)
(Screenshot taken around 20:19 PM)
![image](https://github.com/futo-org/grayjay-android/assets/59576343/ac3dee04-9085-48db-b5fb-cfcb59000e6f)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
