### ISSUE TITLE
Controls improperly labeled for screen reader accessibility

### ISSUE THREAD

**Issue by dangero2000** [futo-org/grayjay-android#1181]
### What happened?

I'm visually impaired and use the TalkBack screen reader. Many buttons have no content labels, and it's guess work finding out what everything does. Examples include the search and cast buttons, as well as other buttons in the creators tab.
To fix this, you can use the android:contentDescription attribute. For buttons that change status when tapped, like the video player's play/pause button, you can use the View#setContentDescription(CharSequence contentDescription) attribute.
I'm not a developer. I got this information from the Android Accessibility Help page. I also used Google's Accessibility Scanner application, which will scan the app for issues and report them to you. That's how I found the help article. You can find Accessibility Scanner on the Play Store, and it's pretty easy to use.
Android Accessibility Content Labels Help Page: https://support.google.com/accessibility/android/answer/7158690?hl=en#zippy=%2Cview
Accessibility Scanner on Google Play Store: https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US

![share_1534440599039905042](https://github.com/user-attachments/assets/154bc621-46b6-489e-8cf4-b03ddb593999)

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### Plugin Version

12

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by dangero2000** [comment]
A few updates:

* Shortly after submitting my issue, I discovered [this issue](https://github.com/futo-org/grayjay-android/issues/292) which was quite similar to mine. Unfortunately, it was given the enhancement and low priority labels. Accessibility is not an enhancement, nor should it be dubbed low priority. I am willing to pay an extra price of Futo's choosing for the app in order to incentivize razing priority for this issue from low to high.
* I made a topic about this on Futo's Zulip server as well.
* Someone posted [another issue](https://github.com/futo-org/grayjay-android/issues/1381) about keyboard shortcuts. While it is an important accessibility fix that should be addressed, I feel it is important to point out that making your app completely usable via a keyboard does not necessarily make it screen reader accessible. Screen readers for mobile devices are designed to work primarily with touch screens and not keyboards. That being said, it is still an important fix that should be considered.

**Comment by grayjay-support-FUTO** [comment]
Let me try to clarify how we use these labels. **Bug** label is generally used when something isn't working, while **Enhancement** is generally used for improvements and new features, as described in their descriptions.

As for priority, **High Priority** is assigned for bugs that make nothing work, or Youtube not work for all users. **Medium Priority** is also assigned for bugs that break stuff for a lot of users and pretty much everything else is **Low Priority**. Although that doesn't mean your issues at the bottom of the queue. They might even get solved before some Medium Priority issues, depending on the issue of course.

Hope this clarifies few things. There are a LOT of bugs and improvements to be done on the app and there is only so much time in a day. But we will get to all of them eventually, some sooner, some later :)

**Comment by dangero2000** [comment]
I appreciate your response to my issue, and I apologize for any potential misunderstandings. That being said, I do believe that based on your description of the labels, the bug and high priority labels can apply here as well. After all, it could be said that the entire app is rendered unusable for people such as myself due to the present bugs. I would still be happy to pay extra money for this, as I am happy to support both Futo and the GrayJay app.

**Comment by grayjay-support-FUTO** [comment]
Well we appreciate your understanding and there is no need pay extra money for us to improve this, although we considered Donation button for users who are willing to give more regardless.

This is an easy fix and something like this will probably land in the next release and we appreciate you pointing things like this to us.
