### ISSUE TITLE
Airplay is not working with LG TV

### ISSUE THREAD

**Issue by SourabhTest** [futo-org/grayjay-android#1183]
### What happened?

It's trying to connect to my LG tv (Airplay), but it's failing to connect. Doesn't stop connecting.

I can't use FCAST, since it is not an android TV and I can't download it.

I'm using Nothing phone CMF.

LG tv model : UQ8050PSB

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Closing issue due it becoming stale.
