### ISSUE TITLE
Watch Later - Videos Added in Random Order

### ISSUE THREAD

**Issue by Fluffgar** [futo-org/grayjay-android#119]
Videos added to the 'Watch Later' playlist do not appear in the order added. 

Further, moving them manually does not fix this. Despite appearing to be in the right order, when played the next video is incorrect. 

No descernable logic for the order they appear is apparent.

**Comment by jonathancutting** [comment]
Same issue here. If the watch later playlist is empty before adding videos, then videos appear in the playlist in the order added. However, manual reordering of the playlist items is cosmetic only; when the playlist is reloaded, the items again appear in the order they were added—all reordering changes lost.

I don't know if this affects other, user-created, playlists, but I suspect it does the same to those.

**Comment by Kelvin-FUTO** [comment]
In upcoming version 278+, the watch later playlist order is persistent (it wasn't originally).
