### ISSUE TITLE
[Plugin] Allow access to local storage during authentication

### ISSUE THREAD

**Issue by xlash123** [futo-org/grayjay-android#1196]
### Use Cases

I am working on writing a plugin for a platform, but this platform does not use cookies for authentication. Instead, it sets an authentication token inside the browser's local storage. Then for any authenticated API calls, it adds the auth token as a URL query parameter.

Since the current method of plugin authentication relies on cookies, I have no way to extract this token and use in the plugin.

### Proposal

Potentially, the configuration could allow for specifying the key name(s) of the desired data to read from the local storage, and then the resulting data is stored in the plugin's `config` variable, perhaps as `config.secrets.<key-name>`.

So for example, I could define a configuration as:
```json
"authentication": {
    "loginUrl": "https://example.com/login",
    "localStorageKeys": ["authToken", "someOtherData"]
}
```

And in the plugin code, I could use it as:
```js
const response = http.GET(`https://example.com/subscriptions?authToken=${config.secrets.authToken}`);
```

**Comment by Zvonimir-FUTO** [comment]
This is not the best implementation for storing authentication data and users authentication data would be exposed to the developer of plugin which we are trying to avoid.

It would help also if you mentioned the name of the platform and feel free to discuss stuff like that on https://chat.futo.org/
