### ISSUE TITLE
The "polycentric" comment toggle state is confusing

### ISSUE THREAD

**Issue by Matti-Koopa** [futo-org/grayjay-android#12]
A toggle text label that represents a current state and completely changes once activated is very confusing. A user can't see what the current state is and what the other state is at a glance.

I think a "tab" design pattern, where the two options "Platform" and "Polycentric" are always visible, but the active one has a colored line under it, would be more suited instead of a toggle button.
Example: https://m3.material.io/components/tabs/overview#34192702-8a18-4da7-b2cf-d1579632cb96

**Comment by yuckdevchan** [comment]
This is implemented.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay with _Polycentric_ and _Platform_ tabs. Feel free to open a new issue if you are still encountering this.
