### ISSUE TITLE
[Youtube] No video found (471)[5-6]

### ISSUE THREAD

**Issue by Luxwho** [futo-org/grayjay-android#1207]
### What happened?

Ever since last youtube update, the app plays no videos. I have tried rolling back and it doesn't work. I have tried complete wipe of grayjay and files and reinstall the hard way and get same error for every single video. 

I waited 24 hours to see if anyone else encountered this and have seen no one with the same problem. 

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

188

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
Unavailable video
[Youtube] No video found (471)[5-6]
```

**Comment by codebymatter** [comment]
I've heard there are previous build version from not sure APKmirror. I can't seem to find an aechive of prevuous Grayjay builds from FUTO. You'll miss out on Privacy Mode but if it worked for you before, then that's really all I can suggest to you.

**Comment by Luxwho** [comment]
After a couple days of not touching anything, Grayjay started working without issue. 
My conclusion is that it was on youtubes end trying to block grayjay
