### ISSUE TITLE
Youtube plugin loops video after detected blocking atempt

### ISSUE THREAD

**Issue by jiweigert** [futo-org/grayjay-android#1209]
### What happened?

YouTube Videos start from scratch after 10-15 sek of play and after second detected blocking attempt from yiutube

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

188

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by jiweigert** [comment]
Android version 13
Mobile RealMe 8

**Comment by somewhiteguy** [comment]
Plays the first 25 seconds, then replays from the start.
Reinstalled/updated plugin, and issue remains.

**Comment by lmsalustri** [comment]
Duplicate of #1188, please close @jiweigert (Repo is unmoderated)

**Comment by support-grayjay** [comment]
Duplicate of #1188.
