### ISSUE TITLE
Search only within a channel

### ISSUE THREAD

**Issue by unoukujou** [futo-org/grayjay-android#1210]
### Use Cases

I don't know if this is possible but if we can just search within one specific channel that would be really useful.

**Comment by VoxelPrismatic** [comment]
Go to a channel page and click search

**Comment by unoukujou** [comment]
> Go to a channel page and click search

Works!

So maybe have some indication that you're searching the channel only. It looks identical to the regular search so I didn't even think to actually try. I thought it just opened up a regular search.

**Comment by Philippe-Choquette** [comment]
> So maybe have some indication that you're searching the channel only. It looks identical to the regular search so I didn't even think to actually try. I thought it just opened up a regular search.

I created the issue #1476 to suggest that they make it more clear. It's indeed so unclear that I also thought that there was so such feature.
