### ISSUE TITLE
Unable to play videos on IPv6 only network 

### ISSUE THREAD

**Issue by vslmc** [futo-org/grayjay-android#1211]
### What happened?

Unable to play videos on IPv6 only network

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by support-grayjay** [comment]
@vslmc Could you please confirm if this is still the issue in the latest version of Grayjay (v264)?

**Comment by support-grayjay** [comment]
Closing issue for being stale.
