### ISSUE TITLE
Failed to download source: Web [403] error

### ISSUE THREAD

**Issue by ScottWilliamAnderson** [futo-org/grayjay-android#1212]
### What happened?

Hi,

I have been having trouble downloading from YouTube, as I'm now getting a 403 error for any attempts to download any video.
I get "Failed to download source: Web [403] error" after adding any video to the download queue (screenshot attached)
![Screenshot_20240802-225235_Grayjay](https://github.com/user-attachments/assets/dfc75e14-7155-44d6-81d7-4509e6768730)

I've checked currently open & closed tickets in this grayjay repository. This does not seem to be a duplicate of https://github.com/futo-org/grayjay-android/issues/1139 #1139 as the videos play fine when streamed from the home page. It seems coincidentally only the same web error code.

It also doesn't seem to be a duplicate issue of https://github.com/futo-org/grayjay-android/issues/1026 #1026, as I can watch the full length of any video when streaming.

I have disabled all VPN or connection blockers that may impact a connection to the YouTube servers (duckduckgo app tracking is disabled, all VPNs are off)

I've tried all the tricks mentioned in #1026, namely:
- rebooting the app
- changing WiFi/data connection
- toggling authenticated playback in the settings
- log out of YouTube (both with & without the Clear cookies)
- delete & reinstall grayjay
- delete & reinstall YouTube extension

I'd like to share the logs from my app, so I've enabled verbose logs in my settings & restarted grayjay. Except there is a button "Submit Logs" which doesn't seem to do anything. I hope it does indeed share them with you even though there is no visual feedback to the user. If there is any other way for me to access the logs (I'd like to read them too! It would avoid having to ask here :) let me know!

Many thanks,
Scott

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

188

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by lmsalustri** [comment]
#1139 is a duplicate of #1026 so it shouldn't still be up, but the repo is unmoderated and it's up to the author to close.

**Comment by ScottWilliamAnderson** [comment]
> #1139 is a duplicate of #1026 so it shouldn't still be up, but the repo is unmoderated and it's up to the author to close.

One does not allow for any videos to be played while the other allows for the first minute to play. They both end up failing in the app. Neither provide logs. I don't think they're duplicate until you can read the logs & confirm that? 

Best to keep their duplicate discussion to those issues, and not here.

**Comment by ScottWilliamAnderson** [comment]
Updating the YouTube extension version 190 has fixed the issue. Closing for now.
