### ISSUE TITLE
Patreon: Failed to retrieve subscriptions (Memberships not found)

### ISSUE THREAD

**Issue by Carpender** [futo-org/grayjay-android#1215]
### What happened?

Device: Motorola Edge 20 Lite
OS: Android 12
App Version: 253 (release)
Extension Version: 15

After successfully logging in to my Patreon account and attempting to import my subscriptions, I'm met with the following error:

**Failed to retrieve subscriptions.**
[Patreon] Memberships not found (265)[2-3]
`source.getUserSubscriptions(...)`

![Screenshot_20240802-212504_1](https://github.com/user-attachments/assets/29ddb735-ab6f-47ea-887a-4eecd748afcd)

I've attempted several of the basic troubleshooting steps, but nothing resolved the issue and the error code never changed.

- Logging out and logging back in to the Patreon extension
- Reinstalling the Patreon extension
- Uninstalling Grayjay and logging in to Patreon on an otherwise clean Grayjay installation
- Attempting to import Patreon subscriptions from other wireless networks (in case it was due to a firewall issue on my home network),

I searched through previous tickets to confirm that I'm not posting a duplicate issue, but didn't find any that were an exact match. Issue #639 is very similar, but has a different number appended to the error code (260 instead of 265). It is NOT a Patreon account set up through Google, so I don't believe it's related to errors exclusive to Google logins like #75. I attempted to pull a verbose log from Grayjay, but it only seemed to upload the log file somewhere without giving me a copy to view myself.

If there is any other information required from me to help resolve the issue, please let me know. Thanks!

### Grayjay Version

253

### What plugins are you seeing the problem on?

Patreon

### Plugin Version

15

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by MNarath1** [comment]
Same issue trough it seem to be able to actually retrieve creators on patreon but is unable to get the list i am currently subscribed/membership too like in the error discribed above so even if i manually subscribe to a creator trough greyjay on patreon and have an active membership it will still not show me payed content of said creator

**Comment by Gotrees** [comment]
I have been having the same issue.
Device: Samsung Galaxy S23 Ultra
OS: Android 14
App Version: 259 (release)
Extension Version: 15

**Comment by ilanRosenbaum** [comment]
I have been having the same issue as OP.

Can't retrieve memberships and can't view any other Patreon content.

Device: Pixel 9 Pro XL
OS: Android 14
App Version: 259 (release)
Extension Version: 15

**Comment by ktman77** [comment]
I've also run into the same issue with the same error code, so I don't have any Patreon content in the grey jay app

Device: Motorola razr plus 2024
OS: Android 14
App Version: 259 (release)
Extension Version: 15

![Screenshot_20240904-224453_Grayjay](https://github.com/user-attachments/assets/0436f281-c8b7-4c70-9ae7-2246a5161f55)

**Comment by jaxiiruff** [comment]
The plugin for Patreon has not worked for almost 2 months now. I would argue it is the most important plugin in the app after Youtube yet gets pretty much no updates. Cant believe I paid for this pseudo open source bs. And the fact that you actually cant even view the logs without just mindlessly submitting them is bs. Gives you no insight into what went wrong besides a meaningless error code.

If FUTO actually respected potential contributors we would not have to wait eternally for their tiny dev team to fix things. Its why you see the pull requests stagnate and they even removed a PR where they ask a contributor to sign a CLA. Trash.

**Comment by eXWoLL** [comment]
Plugin still not working. 
Open Source my ass...

**Comment by palmerbomber1** [comment]
I dont yet know how to sub to an issue on mobile outside of commenting:
I see that tags were added 2 weeks ago, i finally got around to trying to figure out why Patreon wasnt loading anything anymore. After a full reinstall of version 264 im getting the same error of 265 (2-3) when trying to reimport my subscriptions, both VPN on and off. Not sure my phone specs are needed, but i can edit if wanted

**Comment by petathames** [comment]
Fresh install of Grayjay on OnePlus 12r. Same issue as OP when trying to import patreon subscriptions.

**Comment by kaidelorenzo** [comment]
Should be fixed with version 16 release

**Comment by Carpender** [comment]
> Should be fixed with version 16 release

OP here—Version 16 of the extension got rid of the error code on my end. Finally got my Patreon subscriptions to import for the first time since installing the app, and it looks like everything from text posts to videos are running just fine. Thanks again!
