### ISSUE TITLE
Blocking prevention fails and YouTube video restarts

### ISSUE THREAD

**Issue by remcomeeder** [futo-org/grayjay-android#1218]
### What happened?

On every YouTube video I play I first get 4-8 messages that the blocking attempts are bypasses but after 30-60 seconds of play time there is another blocking attempts which causes GrayJay to restart the video.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

188

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by lmsalustri** [comment]
@remcomeeder Duplicate of #1188 please close (Repo is unmoderated)

**Comment by remcomeeder** [comment]
Duplicate
