### ISSUE TITLE
unable to playback any of my own channels videos when logged in

### ISSUE THREAD

**Issue by DazzaJay** [futo-org/grayjay-android#1219]
### What happened?

When logged in with my YouTube account, if I try to play my own channels videos (@DazzaJay) I get the "Block detected" popup. And the video never plays.
Download also does not work, with a 403 error.

If I sign out of the YouTube plugin, my own videos play just fine, and downloading works too.

So, for some reason, this only affects the videos of the user that is logged in to the plugin. No other channels are affected.
![Screenshot_20240804-212131](https://github.com/user-attachments/assets/83511d1d-7aeb-46d6-9cc0-7521d3d24dcb)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

190

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Logging is enabled in the app, however I recieve "Please enable logging to submit logs" when trying to access them.
```

**Comment by thecatontheceiling** [comment]
I can also reproduce this when I have "Provide YouTube with activity" (or some other option idk) enabled.

**Comment by support-grayjay** [comment]
@DazzaJay Apologies for the very late reply on this but are you still affected by this issue on the latest version of Grayjay (v264) and Youtube (209)?

**Comment by thecatontheceiling** [comment]
I am no longer affected, an update from a while ago fixed it

**Comment by DazzaJay** [comment]
> @DazzaJay Apologies for the very late reply on this but are you still affected by this issue on the latest version of Grayjay (v264) and Youtube (209)?

Disabling "use login for channels" and "use login for video details" fixed it months ago....  (Checking as I type this)... 

Yep, after reenabling both if those, my own videos still play. So it looks like it's fixed. 

(Sorry for the delayed reply, my phone doesn't seem to be receiving any notifications from github.)

**Comment by Zvonimir-FUTO** [comment]
No worries, thank you both for the feedback. Closing issue.
