### ISSUE TITLE
No play on android box

### ISSUE THREAD

**Issue by sun1423** [futo-org/grayjay-android#1220]
### What happened?

latest app plays on amdroid mobile phone, but when I install in on android 12 based tv box . it just.play once then never play again.  strage behaviour and no error display.. just doesn't play.  tried installing universal pack multi times. no luck

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

190

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
Grayjay doesn't have an android TV version yet but we may work on this in future.
