### ISSUE TITLE
Subscription groups not included in export.zip

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/grayjay-android#1234]
### What happened?

Subscription groups are not added to the export.zip, meaning you can spend upwards of an hour tediously copying each subscription

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### Plugin Version

n/a

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
We have implemented this and is currently in testing phase, should be release with the next Grayjay release v265.
