### ISSUE TITLE
Plugin YouTube failed 

### ISSUE THREAD

**Issue by Flatmotion1** [futo-org/grayjay-android#1235]
### What happened?

For a few weeks now I'm getting errors on refreshing my subscription tab, no exceptions. I have no channel subscribed with the name Vidgeo. Plugin version 185-191
![Screenshot_20240809-123141_Grayjay](https://github.com/user-attachments/assets/a1523ff3-00fa-40c4-873f-84399e3d1673)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

185-191

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Uploaded
```

**Comment by VoxelPrismatic** [comment]
Try checking your subscription groups, if you have any

**Comment by Flatmotion1** [comment]
> Try checking your subscription groups, if you have any

I had to enable the tab because I disabled it. Nothing shows up, the tab is empty. 
![Screenshot_20240820-092033_Grayjay](https://github.com/user-attachments/assets/de3fc80c-e079-469a-9dd1-668d34c1bcd6)

**Comment by support-grayjay** [comment]
@Flatmotion1 Apologies for the late reply. Are you still affected by this issue on the latest version of Grayjay and Youtube?

**Comment by Flatmotion1** [comment]
@support-grayjay no worries, apologies for my late reply. 
At this point in time my videos load fine. I have other UI issues. Also it seems like I'm able to load most of my playlists now - yay. 
Thanks for your continued work on this app.
