### ISSUE TITLE
Failed to fetch playlists from YouTube 

### ISSUE THREAD

**Issue by Flatmotion1** [futo-org/grayjay-android#1236]
### What happened?

Since the YouTube plugin issues started with 185,186 I have not been able to pull my playlists from the YouTube client. The only lists that show up are liked videos and watch later, all other lists generate errors and can't be imported 
![Screenshot_20240809-123119_Grayjay](https://github.com/user-attachments/assets/81d9ceb5-862e-4753-9011-d698641e1a2e)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

185-191

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Uploaded
```

**Comment by Kelvin-FUTO** [comment]
Issue was found, and will be a 2-part fix.
Some playlists might be fixed with the upcoming youtube plugin update.
(Playlists containing only videos from the same author, including the one in your screenshot)
Others will be fixed with next app update.

**Comment by Flatmotion1** [comment]
Thank you very much!
