### ISSUE TITLE
Player overlay toggle switch

### ISSUE THREAD

**Issue by WheelMonkey** [futo-org/grayjay-android#1250]
### Use Cases

The ultimate goal is to listen to music videos in a playlist, but in audio only format. This saves data & will allow the user to decide whether they want to watch the actual music video or to just listen to the audio only for long trips and playlist is selected of songs already added in order.

This is also available for people that just listen to podcast or sleep videos and don't require to watch the video to help get to sleep.

### Proposal

I want to keep my video popup window on screen & continue to play a video, but hide it to the side of my phone screen & stay in the same off side position hidden when a new video plays.
(currently it moves back to the center of my phone screen after every new video) 
We could also have it where if you hit a toggle within the popup, it will change from video playback to audio only playback & minimize the popup screen to the notifications area of my phone. (Currently the toggle you have in the popup just closes the picture in picture feature and it stops playing the app)

If I need to reopen the popup window, I can make it reappear on my phone screen, by pressing the notification from my notifications area & the popup window will reappear on my phone screen again in the center.

The final picture attached would be hopefully the end goal for the notifications area of my phone to make it easier to re-open the popup window.

The notification could have all the information to stay the same, but if you press on the picture box, it will reopen the popup window. I have added text to help folks to understand by pressing the video window to make it reappear.
![Screenshot_20240816_222013_Samsung Internet](https://github.com/user-attachments/assets/91e09956-2913-47bd-b84f-a469761670a5)
![Screenshot_20240816_221943_Samsung Internet](https://github.com/user-attachments/assets/f3e8d753-4ddd-4bd5-98b0-cbe01a48eaa5)
![20240816222847](https://github.com/user-attachments/assets/c28af711-299d-417e-b8f0-2c3c518628d2)

### References

- #1226 car mode (similar needs)

**Comment by VoxelPrismatic** [comment]
1. This is a smasnug specific issue of not showing the player in the notifications center
2. IIRC, there is a headphones button to the left of play/pause you can press which will simply hide the video popup
3. Have you tried this "Background" button? It will hide the video completely
![Screenshot_20240820-110859_1_1](https://github.com/user-attachments/assets/650a1ce8-e54a-411c-9c58-6e97c45a2c4b)

**Comment by WheelMonkey** [comment]
OK correct, it does work correctly for pressing the background button to accomplish hiding the screen. Thank you for that help.

Now the 2nd part to this question, if you hide the "video" portion of the song playing, does it change the stream to audio only thus reducing the data speed transferred to reduce buffering lag and not using so much data or does it just hide the screen and still play at the same amount of data being used?

So if a video being "viewed" uses 60mb of data, but an audio only stream "not viewed video" uses 3-4 mb of data, will hiding the video change the data used? If it auto switches to audio only data streaming, that would be great.

The reason I ask, some people can't afford unlimited data plans and so this would help save the consumer a good amount of data while using this app. It is already saving some data from no ads through YouTube BS interface, but the question is, will it reduce my data usage by switching to "audio only"?

The download feature usually does not work, which is understandable, but it is, what it is with that feature.

I have a list of usually 20-25 songs I play to get my day started and if I can cut a good amount of data usage by using "audio only", that would help me in the long run, not to hit the data cap, and be reduced to 2g speed.

Thank you.

**Comment by VoxelPrismatic** [comment]
The background mode only reduces data usage on YouTube, where you can see that the video turns black completely. On other platforms, like Rumble, pressing the background button will do nothing and you will still see the video.

If the video turns black, you can rest assured that you are saving data.

**Comment by MKBontwikkeling** [comment]
On YT you can select an Audio only stream. With Oddysee videos there are only video streams.

**Comment by support-grayjay** [comment]
The Music as different type of media inside core of Grayjay will be implemented through #381.
