### ISSUE TITLE
YouTube links from Google Search don't open

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#1254]
### What happened?

I clicked on a link in Google search results and happens the following:
![Screenshot_20240820-210108](https://github.com/user-attachments/assets/33470094-cca8-47d6-910e-cf3cbe68bebb)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

191

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
This is the same scenario to opening YouTube videos on Yahoo Search.

Whn you tap on a YouTube video from a Google Search or Yahoo (in my case), you will be viewing said video in a mobile-friendly page displayed for easily navigating out of and back to search results page.

In order for Grayjay to open the recognizable YouTube link, you need to tap on the video title once yiu start playing said video to actually open it on YouTube's website and only then will Grayjay open the video successfully.

The mobile-friendly video page is also a very lengthy URL thst includes Google domain so thst is why you're experiencing said issue.

You could always have Google set to display desktop version and your issie won't happen as a YouTube vifeo in Google search desktop mode will direct to YouTube.com

**Comment by Kelvin-FUTO** [comment]
The plugin didnt support /c/ url pattern yet. This has been added in a plugin update.
Also added code that strips said suffixes, but I believe that wasn't the main issue.
