### ISSUE TITLE
Auto-rotate / Orientation issues

### ISSUE THREAD

**Issue by Giesa-lab** [futo-org/grayjay-android#1260]
### What happened?

After reading all the various bugs and issues that folks are having, with auto-rotate settings, it seems clear to me that they can All be solved with the addition of TWO extra options in the settings menu for this item. IMHO GrayJay is trying to be too clever in this regard. 

So, the current options are.... 1. Disabled  2. Enabled  3. Same as System 

For various reasons, many people are having trouble with this setting, and the Auto-rotate Dead Zone setting. By adding the following 2 options, I believe that this is what most people are really looking for in the behaviour. The original options can stay too. 

So, please add options... 4. Always Portrait  5. Always Landscape 

The coders can fix the other reported issues at their leisure, while phone users can do option 4, and tablet users do option 5. 

Also, this setting should apply to the behaviour of the entire App, and Not just the Player. This way, EVERY menu/listing/player can appear in a user's preferred orientation. Those who don't experience any issues, can use the original options.

Like/comment on my post if you agree !

### Grayjay Version

249

### What plugins are you seeing the problem on?

All

### Plugin Version

N/A

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
N/A
```

**Comment by codebymatter** [comment]
I have auto-rotate set to Same As System. So no auto-relating bc it can get annoying on commutes. I just discovered the swip up to go landscape and swipe down to go back to portrait gestures.

And I thought my phone had a sensitivity issue.  I like the gestures so I don't have to smear my phone's screen with my greasy hands on lunchbreak or struggle a bit to hit Square instead of play-finder.

**Comment by xephos1one** [comment]
Related to #67 
The rotation issue should be fixed in the upcoming version

**Comment by Giesa-lab** [comment]
@xephos1one  and everybody... 
With new version 259 release this issue is VERY MUCH WORSE !!! 
Auto-rotate ...
"Same as System" 
DOES NOT FOLLOW SYSTEM SETTINGS ! 

Bypass Rotation Prevention 
"This may cause unexpected behaviour, and is mostly untested." 
Unexpected behaviour yes, and Now it does NOT Rotate at all in any mode EXCEPT in Full screen Player ! 

This maybe is "mostly untested" by developers, but I can assure them; This IS "Extensively Tested" by the users, and it DOES NOT work at all anymore... 🙄☹️

**Comment by Giesa-lab** [comment]
With V262 the rotation issue is FIXED, so far as "Same As System" option is concerned, and now every menu does follow system settings on Android 9+ with the exception of the settings menu, which still shows in Portrait mode, no matter which setting us chosen. Maybe this is enough to satisfy, all but the most critical of users?  What do other users think, is this good enough?

**Comment by Zvonimir-FUTO** [comment]
Will be solved through #67
