### ISSUE TITLE
Watch later auto download queue issue.

### ISSUE THREAD

**Issue by KdntNinja** [futo-org/grayjay-android#1261]
### What happened?

If you set your watch later playlist to automatically download and you move the position of one of the videos in the order of the list, it then re-downloads the entire watch later playlist.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

192

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Comment by KdntNinja** [comment]
> This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

I have had no issue with it recently, thank you for the fix.
