### ISSUE TITLE
Missing names and like count on YouTube plugin

### ISSUE THREAD

**Issue by sebasdt** [futo-org/grayjay-android#1262]
### What happened?

![Screenshot_20240823_133844_Grayjay](https://github.com/user-attachments/assets/d8ee0583-c2a1-4e24-89e3-a0d15e91fd34)
![Screenshot_20240823_133836_Grayjay](https://github.com/user-attachments/assets/24017160-6bdb-4adb-9648-8c6fb1402933)

I was using grayjay from a Cold start, it auto updated did a full restart off the app and it bugged out. The comments aren't showing channel names nor like count. (See attached screenshots)

Restarting the app and even hard stop the app didn't fix it.

The next best thing I did was sign in and out of the plugin, still not resolved. 

Last step I've tried was enabled logging, it says that's there's not yet a file. 

Device information: 
Samsung galaxy tab S6 lite
- android 14, oneui 6.1
- grayjay via apk 
- mostly default settings

Thanks for the help in advance!
Sk.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

192

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
This is a known issue as of the last two Grayjay builds. Apparently, the names and pike counts can be seen with Privacy Mode enabled. Hopefully, it is resolved.

**Comment by sebasdt** [comment]
Thanks!
Enabling privacy mode fixed it, al be it temporarily as restarting the app disables it.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
