### ISSUE TITLE
Is sponsorblock supported? 

### ISSUE THREAD

**Issue by lamyergeier** [futo-org/grayjay-android#1264]
### What is the docs issue?

Please clarify if Sponsor block is supported or not. I am using v253. Can't find any sponsorblock related settings.

**Comment by lamyergeier** [comment]
@ThunderHen could you please tell where to specify this in the settings of the app?

@Eliya-Manoj Where is the YouTube add-ons settings?

**Comment by Eliya-Manoj** [comment]
Sources -> Youtube -> SponserBlock

![Screenshot_20240826-214920_Grayjay_1.jpg](https://github.com/user-attachments/assets/241429c0-90d5-4b4a-81b9-ba8dab90036b)
