### ISSUE TITLE
Rumble Plugin "Failed To Get Channel" and "Stream Was Reset" Errors

### ISSUE THREAD

**Issue by skdecoteau** [futo-org/grayjay-android#1265]
### What happened?

GrayJay stopped retrieving videos for several of the Rumble creators I'm subscribed to. The rest take a really long time to load. 

For the ones that don't load anything at all, I eventually get one of two error messages: 

"[Rumble] Failed To Get Channel (undefined). (151)[2-3] source.getChannel(...)" 

or "[Rumble] stream was reset: CANCEL (149) [18-19] source.getChannel(...)" 

This was working fine as of two days ago. I also checked for updates for both the app and the plugin and everything is up to date.

I just realized that I didn't have logging enabled so I just enabled it. Will update this report if I see anything relevant.

Edit: Forgot to mention, I'm on a Pixel 7a with latest version of Android 14.

More edits: fixed screenshots and formatting.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

44

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by skdecoteau** [comment]
Here are the correct screenshots of the errors:

![Screenshot_20240825-082521~2](https://github.com/user-attachments/assets/31bc3593-8489-4305-8fbc-9e853ea3199c)

![Screenshot_20240825-082821~2](https://github.com/user-attachments/assets/fe64d764-64cf-41ae-ae5c-040a775c06a3)

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
