### ISSUE TITLE
Unavailable Video Youtube

### ISSUE THREAD

**Issue by Br0ck25** [futo-org/grayjay-android#1266]
### What happened?

A lot of YouTube videos will not play and I get a popup saying Unavailable Video [YouTube] No video found (473)[2-3]

![Screenshot_20240825_085731_Grayjay](https://github.com/user-attachments/assets/e4f4abce-2dd1-4bb7-9cff-48a4faae9d4a)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

192

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
For YT videos that you've previously sewn or playlisted in Grayjay, they appear to be viewable, right? Then the Video Unavailable message appears.

It's inly when you visit the Creator's page that you'll notice the video is no longer listed. Why? It was removed. Creator removed the video or could ve a DMCA takedown.

**Comment by anuragtyagi-dev** [comment]
No , sometimes the live video that has just ended or even is live have same issue. 
I've faced this multiple times.

**Comment by codebymatter** [comment]
> No , sometimes the live video that has just ended or even is live have same issue. I've faced this multiple times.

That's because yiu need tobwait until video becomes playable outside of Live state. I've had that issue before when attempting to view a video that went live and ended a few minutes ago. Wait what 15-30 mins or try again later.

**Comment by anuragtyagi-dev** [comment]
> > No , sometimes the live video that has just ended or even is live have same issue. I've faced this multiple times.
> 
> That's because you need to wait until video becomes playable outside of Live state. I've had that issue before when attempting to view a video that went live and ended a few minutes ago. Wait what 15-30 mins or try again later.

Yes , This method is working. Thanks 👍🏻

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
