### ISSUE TITLE
YouTube: invalid iOS source response

### ISSUE THREAD

**Issue by vladimmi** [futo-org/grayjay-android#1275]
### What happened?

When I play any video and bot detection fallback was used, video only plays first minute or less. After that (or even quicker, just trying to rewind somewhere ahead) "Invalid iOS source response" message appears and video restarts.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

193

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Graves-Aedan** [comment]
I've been having this issue too, it started happening on a previous plugin version and we promptly got an update which gave us the additional message "Invalid iOS source response", but it didn't seem to fix the issue

**Comment by Adriel3233** [comment]
I've also have the same issue, it started happening a few hours ago and when play the video gave us the additional message "Invalid iOS source response", but it didn't seem to fix the issue, and it restarts back to the beginning of the video.

**Comment by madpete76** [comment]
Also suffering from this with YouTube, started a couple of weeks ago, the app is fully upto date and the plugin is now 196, but it's been the same problem on previous plugins too.

I reinstalled the plugin, but it didn't help.

**Comment by FoolHen** [comment]
Same here, can confirm that turning off the VPN fixes it.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (209) of Youtube. Feel free to open a new issue if you are still encountering this.
