### ISSUE TITLE
Don't even use buggy grayjay

### ISSUE THREAD

**Issue by ForJesusmygod** [futo-org/grayjay-android#1277]
### What happened?

I'm disappointed in the creator. YouTube and Rumble do not work on the app There's too many bugs, too much shit going on. Not anything works. The only thing that works is my downloaded music And just to let you know, that only worked when everything else was fine I'm going back to Rumble This is the worst app I've ever used. There's too many issues and too many stupid people that refuse to fix the issue.

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube, Rumble

### Plugin Version

185

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by anuragtyagi-dev** [comment]
Dear Developer Team , Please close this issue as solved. These people do not appreciate this platform then there's comment doesn't matter.
