### ISSUE TITLE
Refresh button on subscriptions menu

### ISSUE THREAD

**Issue by sun1423** [futo-org/grayjay-android#1280]
### Use Cases

On android tv or box, there is no way to refresh subscriptions channels updated contents as most of time old contents appear.. there should be a clickabke button to update contents of subscriptions chanels latest videos.

### Proposal

add a clickable button to update subscriptions channels contents

**Comment by codebymatter** [comment]
This sounds more like something that would be adopted to a tablet/desktop version of Grayjay. I had previously tried it on a tablet and going from that to Android TV, I can that issue already. It's probably why Fcast exists. Use your ohone as the source and TVs/PCs/Tablets as the external devices. We'll jyst hae to wait a bit more on tbe desktop version.

**Comment by support-grayjay** [comment]
This will be resolved through #74.
