### ISSUE TITLE
Larger rotate deadzones

### ISSUE THREAD

**Issue by Roman19S** [futo-org/grayjay-android#1282]
### Use Cases

I find that I tend to shift a lot while watching videos and rotating the screen when I don't intend to, but I hate the inconvenience if manual rotation.

### Proposal

Can you add larger deadzones like a 30 degree or 40 degree?

**Comment by xephos1one** [comment]
Duplicate of #67 
Should be fixed in the upcoming version

**Comment by Zvonimir-FUTO** [comment]
Will be solved through #67
