### ISSUE TITLE
Blurry thumbnails on Android 13 media player

### ISSUE THREAD

**Issue by Roman19S** [futo-org/grayjay-android#1284]
### What happened?

In the media player on my Murena Fairphone 4 running /e/OS 2.3 (based on Android 13), I expect the thumbmail to look clear in the player like this YouTube example:
![Screenshot_20240902-102150_Firefox](https://github.com/user-attachments/assets/2e32ffff-1bf3-420d-acd1-f2182fa11267)
Instead, it looks blurry like this:
![Screenshot_20240902-102021_Grayjay](https://github.com/user-attachments/assets/d307b2b4-4764-43d1-9987-b4c92a84d830)
Grayjay is the only app so far that I have noticed this problem in.

### Grayjay Version

253

### What plugins are you seeing the problem on?

All, Youtube, Odysee

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Kelvin-FUTO** [comment]
Fix should be deployed (v261)
