### ISSUE TITLE
Import subscription feature broken 

### ISSUE THREAD

**Issue by Flatmotion1** [futo-org/grayjay-android#1285]
### What happened?

Trying to update my subscriptions on the YouTube plugin via subscriptions import but comes back with an error. Failed to retrieve subscriptions. 
![Screenshot_20240903-053111_Grayjay](https://github.com/user-attachments/assets/693b1f4f-b12e-4fc8-8073-9b62807ca63e)

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

194

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
I do not know how and want able to find it online
```

**Comment by Kelvin-FUTO** [comment]
From what I can see, Its trying to redirect you to the login page.
As if your login was invalidated.
Try logout ('without clear' may allow you to skip credentials)
And then login again.

And see if this issue still occurs.

**Comment by Flatmotion1** [comment]
That worked. Playlist import however still doesn't work beyond like videos and watch later. I already posted an issue a couple weeks ago. Thanks for your help

**Comment by Kelvin-FUTO** [comment]
Closing this, I believe a fix for your other issue is also deployed (or will be in next Grayjay version).

**Comment by Flatmotion1** [comment]
thanks!
