### ISSUE TITLE
YT Switch to Landscape format = crash 

### ISSUE THREAD

**Issue by Buc-germany** [futo-org/grayjay-android#1286]
### What happened?

When I want to watch a youtube video in landscape format on my smartphone, the app crashes and I end up on the desktop of my Huawei P30 Pro NE

### Grayjay Version

258

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

194

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Mohamed6935** [comment]
Same here. Infinix note 7, android 10

**Comment by usertoroot** [comment]
Does it just fully crash? No exception dialog?

**Comment by ChrisopherU08** [comment]
Yeah Full crash with no exception when entering landscape
Galaxy S9 on Android 10

**Comment by 4cer** [comment]
Also consistently happens on Huawei P20 Pro version 258, seems video-platform-indeoendent, but confirmed to happen with the following sources:
YouTube v. 194
Rumble v. 45
BitChute v. 4
Odysee v. 38
Twitch v. 18

# Steps to replicate:
1. Open Grayjay application 
2. Open a video from any platform named above 
3. Rotate phone sideways or press the full-screen button

**Comment by usertoroot** [comment]
Looking at this now.

**Comment by codebymatter** [comment]
I swapped Kick with Dailymotion and seaech for old videos through the plugin and haven't wxperienced the full-screen bug. Note I've also been tuning to a Rumble livestream for 2 hours with at least an hour on fullscreen before switching to background mode on the new Grayjay update. Haven't tried YouTube yet but will post if it occurs.

**Comment by Lasion** [comment]
Confirmed, last hotfix solved the issue. Thanks ☺️

**Comment by jimmybigbaws** [comment]
Sorted. Thankyou very much

**Comment by usertoroot** [comment]
Thanks for being so quick to report!

**Comment by usertoroot** [comment]
@Buc-germany please close if solved

**Comment by Buc-germany** [comment]
Thank you 👍
