### ISSUE TITLE
Can't import playlists from Spotify 

### ISSUE THREAD

**Issue by EctoplasmChasm** [futo-org/grayjay-android#1289]
### What happened?

Whenever I want to import a playlist on Spotify I get an error that states "Failed to retrieve playlists. [Spotify] unreachable (2498) [24-25] Source.getUserPlaylists (. . .)"
So far I've tried reinstalling the Plugin and logging in and out of Spotify.
My plugin is up to date (Version 2) and my app is on version 259 which should be the latest version at the time of writing.

![Screenshot_20240904-070631](https://github.com/user-attachments/assets/cd0e56dc-7fe0-4467-be77-cef9d4d8f098)

### Grayjay Version

259

### What plugins are you seeing the problem on?

Other

### Plugin Version

2

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Failed to retrieve playlists. [Spotify] unreachable (2498) [24-25] Source.getUserPlaylists (. . .)
```

**Comment by codebymatter** [comment]
A future update to Spotify plugin mught fix those issues. TBA for now.

**Comment by kaidelorenzo** [comment]
@EctoplasmChasm Do you by chance have playlist folders? There is a bug that I fixed that caused a similar error message.

**Comment by EctoplasmChasm** [comment]
@kaidelorenzo Not that I'm aware but ATM I'm only on mobile. But whatever you fixed it worked for me! Thank you so much! :)

**Comment by support-grayjay** [comment]
This issue has been fixed in the latest version of Spotfiy plugin.

**Comment by laurentjuma** [comment]
Still not working...

**Comment by kaidelorenzo** [comment]
I added additional logging in version 9. Could you send the new exception message?

**Comment by kaidelorenzo** [comment]
This may have been resolved in the past with some changes. Please reopen the issue with an updated error message if you're still experiencing this issue
