### ISSUE TITLE
Main page randomly updates when coming out of a video

### ISSUE THREAD

**Issue by mystica555** [futo-org/grayjay-android#1292]
### What happened?

When I load the application, I see a certain list of videos on the main page. 

I attempt to watch a video, and instead of tapping on the video title I apparently seem to tap on the creator's name instead and instead of getting the video I want I get the creators channel. So I hit back.

AND INSTEAD OF SHOWING ME WHAT I JUST SAW THE ENTIRE DAMN PAGE UPDATES RANDOMLY 

SOMETIMES 

THERE IS NO DETERMINISM TO IT 

WHY CAN'T THE PAGE JUST STAY THE SAME UNTIL I MANUALLY REFRESH IT?

This is literally maddening. I get so bloody angry when this damn page decides update because I couldn't hit the video I wanted, I go back to the page, and then everything instantly changes and no longer can I find the video I was trying to watch! Why does this happen?? 

Make it stop!

### Grayjay Version

259

### What plugins are you seeing the problem on?

Other

### Plugin Version

The app itself it's not a broken plugin

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
I have no log. But I could provide a video. This is maddening.
```

**Comment by usertoroot** [comment]
It should stay the same until you manually refresh it. I'll have a look.

**Comment by usertoroot** [comment]
I think it can be explained by the fact that if the data is 60 seconds outdated, it refreshes. Maybe it makes sense to have the default be, no refresh unless manual, like the subscriptions page. I am also looking at potentially making this a setting.

**Comment by usertoroot** [comment]
Proposed fix is out, hopefully release today or tomorrow.

**Comment by mystica555** [comment]
Thank you! The refreshing-sometimes is the one thing that is making going back and forth between list of videos, watching a video, and back to list of videos such a frustrating experience.

**Comment by Kelvin-FUTO** [comment]
Change should be deployed (v261)
