### ISSUE TITLE
Add the option to remove the "Recommended" tab

### ISSUE THREAD

**Issue by AnasImr** [futo-org/grayjay-android#1298]
### Use Cases

this is helpful for people who don't want to be distracted & only wanna focus on the content part of the video they're watching.

### Proposal

just add the option to remove the "Recommended" tab that's on the bottom of the video player screen :)

**Comment by I-I-IT** [comment]
I closed my [issue,]() I will copy it here for reference

> Use Cases

>In latest release, there is now a "Recommendation"button next to comments. By default it is off, but it is very tempting to select it. The issue is that this is distracting and bother me for various personal reasons.

>The problem is that Youtube also inserts random, unrelated videos (such as news or items you might like). Below are recommendations about a video about Harris. As you can see plenty of unrelated. You will need to disable VPN to see this.
Screenshot_20240907-001655
Proposal

>Being to disable the recommendation item showing ul generally, or on a per-source basis.

**Comment by AnasImr** [comment]
This feature was thankfully added in v264, thanks again, Now we want this feature/bug fixed in - #1300

**Comment by I-I-IT** [comment]
Nice. They really move fast. #1300 I don't mind the Home tab though.
