### ISSUE TITLE
Can't activate key while video playing

### ISSUE THREAD

**Issue by Matti-Koopa** [futo-org/grayjay-android#13]
It throws this error message. But after a restart it says "paid" so I guess the message is just wrong.
![Screenshot_20230907-223456](https://github.com/futo-org/grayjay-android/assets/10476794/e923a43d-6b44-46a3-bc77-b5eb23a5e700)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
