### ISSUE TITLE
Exiting Fullscreen view not rotating to Portrait view (Auto-Rotate OFF)

### ISSUE THREAD

**Issue by codebymatter** [futo-org/grayjay-android#1301]
### What happened?

I have noticed the new Tabs including Recommendations, nice! I viewwd a few videos today and the app is functioning well. I decided to watch a livestream video and when I go to Fullscreen mode, the video will not rotate to landscape.
NOTE: Auto-Rotate setting in-app had stayed to Same as System for 10 months with the System settings having auto-rotate Off as well. I noticed this issue afrer updating to 262. Previous versions did not present this issue.

I decided to change the Auto-Rotate setting in-app to Disabled. I went back to the livestream video, enter Fullscreen by Swipe or Square icon, and it does go Fullscreen in Landscape. It's only when ai exit Fullscreen, the app remains in Landscape view.

I do not have the Portrait Fullscreen mode toggled on. It's off. Not into Vertical videos. Anyway, the temporary fix for this problem without having to Enable System Rotate, is to have the phone in Landacape position, while out of Fullscreen mode, and to turn the phone 90° from Horizontal position to vertical/portrait position. The app will then go into Portrait view.

Edit: Found out that swiping or tapping square to exit fullscreen and waiting for app to go back to portrait mode and vice versa from portrait to landscape results in transition working. As long as you do not turn your phone while entering/exiting fullscreen mode then it works.

On Android 12 (not 13, sorry it's 12) using Galaxy A03s on default app launcher using latest build version of Grayjqy ver. 262.

### Grayjay Version

262

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by usertoroot** [comment]
Will fix on monday

**Comment by edo9300** [comment]
Other than having this behavior as well, I noticed that while watching a video in landscape turning the phone 180° will not flip the video anymore

**Comment by usertoroot** [comment]
Works for me, which Android version/device? which version of the app @edo9300  ?

**Comment by edo9300** [comment]
Just updated to 262 on android 11

**Comment by codebymatter** [comment]
> Just updated to 262 on android 11, using a zenfone max pro m1 with arrow OS

I can confirm this as well. I haven't noticed this until now. With Auto-Rotate disabled  or Same aa System fullscreen display will not flip 180° if I turn the phone with the volume rocker up or turn again 180° with the Assistant button up.

**Comment by dankxylese** [comment]
Can confirm this issue on Android 13, AOSP based ROM on Poco F5. 

For me the whole fullscreen experience is broken. Right after the update, the video would go vertical fullscreen - centered with black bars on the top and bottom. I always have my system auto rotate off. As I enabled the auto rotate in my system, the video could go landscape fullscreen, but only if the phone is physically landscape. When I watch videos is bed, the phone is in such a position that keeping auto rotate on, would cause the video to get rotated 180 from the main view - vertical full screen but up upside down.

Now, if I turn auto rotate off while it's in horizontal fullscreen, it would be preserved in the future when I went fullscreen, but only in one position - where the charging port is on the right. Even if I turn auto rotate off on the opposite landscape position. Doing this though, would cause every exit out of fullscreen to not restore the vertical orientation, with the app unusable unless I toggle auto rotate, or kill the app.

This is a major regression, and makes the app way less convenient to use. Please consider reverting the changes made to how full screen works.

**Comment by jmcgaughey** [comment]
Doing the same thing on my Samsung a53 5g. Started after this update

**Comment by codebymatter** [comment]
Loaded the new update and it seems to have resolved nowm Thanks very much FUTObl team and @usertoroot for the timely response; closing thread.

**Comment by edo9300** [comment]
Working for on my end as well too
