### ISSUE TITLE
Allow to hide distractions ("recommendations")

### ISSUE THREAD

**Issue by I-I-IT** [futo-org/grayjay-android#1302]
### Use Cases

In latest release, there is now a "Recommendation"button next to comments. By default it is off,  but it is very tempting to select it. The issue is that this is distracting and bother me for various personal reasons.

The problem is that Youtube also inserts random, unrelated videos (such as news or items you *might* like). Below are recommendations about a video about Harris. As you can see plenty of unrelated. You will need to disable VPN to see this.
![Screenshot_20240907-001655](https://github.com/user-attachments/assets/b94ac93b-c746-4143-87ae-a4d3fdc2373b)

### Proposal

Being to disable the recommendation item showing ul generally,  or on a per-source basis.

**Comment by AnasImr** [comment]
you're right
I made the same feature request some hours ago
in #1298

**Comment by I-I-IT** [comment]
I didn't excpect so many people to use Grayjay and file an issue so quick. :) 👍Great to see the app success though.

Closed and I copied the issue in your thread.
