### ISSUE TITLE
Rotation works when phone is upside down

### ISSUE THREAD

**Issue by djsusanoo** [futo-org/grayjay-android#1312]
### What happened?

When I turn my phone upside down it rotates back into portrait in wrong orientation. Before this update it wouldn't do anything like that. Like if I accidently tilt the phone the wrong way it will rotate full 360.

https://github.com/user-attachments/assets/763d79fd-9c94-4bbe-b756-30c20da24edb

### Grayjay Version

262

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by samir-nmx** [comment]
This is a good thing imo. I sometimes use my phone upside down when it's charging.

Please don't disable 180° rotation, just add a setting for it if it annoys some people.

**Comment by usertoroot** [comment]
I added a setting, default off.

**Comment by support-grayjay** [comment]
This has been fixed in the latest version of Grayjay.
