### ISSUE TITLE
Hide  More Tabs

### ISSUE THREAD

**Issue by SyCoREAPER** [futo-org/grayjay-android#1314]
### Use Cases

Tabs such as FAQ, Sources and Privacy Mode are t regular use tabs. Even if they are to somez the ability to be able to hide them won't hurt anyone. 

### Proposal

Add Toggles for all tabs or at least the ones listed above.

**Comment by SyCoREAPER** [comment]
While this appears to mainly apply to tablets especially since the bottom row is cluttered with these, it would be nice to have the option as a whole.

**Comment by jmcgaughey** [comment]
I 2nd that.

**Comment by usertoroot** [comment]
Done

**Comment by usertoroot** [comment]
Correction, we had some issues with this during QA, so its been postponed until a later build

**Comment by SyCoREAPER** [comment]
Obviously this being a open source project this isn't meant to come across ungrateful which it's not. 

That's at least a good step I can work with in the meantime.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
