### ISSUE TITLE
Screen turns off while video is playing

### ISSUE THREAD

**Issue by samir-nmx** [futo-org/grayjay-android#1316]
### What happened?

Wakelock doesn't seem to work anymore after latest update. 

If I look away from the phone, the screen will dim and turn off after the system timeout, even though it's playing in the foreground. 

This didn't happen on older versions, it only went to sleep if the video was paused or had ended.

### Grayjay Version

262

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by codebymatter** [comment]
I already reported this issue a couple days ago. A fix is coming Monday today, keep an eye on it.

**Comment by samir-nmx** [comment]
> I already reported this issue a couple days ago. A fix is coming Monday today, keep an eye on it.

Oh, thanks for the info!

I did try to look for an existing issue first, but must have missed your report.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
