### ISSUE TITLE
Recent videos playlist

### ISSUE THREAD

**Issue by smithzvk** [futo-org/grayjay-android#1317]
### Use Cases

Have a list of recently played videos.  This would be nice as videos are automatically removed from the watch later play list once completed. Useful for finding that video you watched recently, but much more useful if you fell asleep while watching and your watch later gets cleared out, or if you find that videos were silently playing in the background through your Bluetooth headphones.  This would allow you to easily recover those videos you saved but didn't actually watch.

### Proposal

Make every played video add to a recently watched playlist (perhaps after a 10 seconds delay). Older entries in the playlist should be removed at some user specified time (e.g 10 days).

This playlist should appear with other playlist, perhaps adjacent to the watch later queue/playlist.

**Comment by usertoroot** [comment]
What would be the difference between this and the history tab?

**Comment by smithzvk** [comment]
No real difference, I wasn't aware of the history feature.  To others that might find there way here, this is under the "More" menu.
