### ISSUE TITLE
Kick video not appearing on search

### ISSUE THREAD

**Issue by helbetmathias** [futo-org/grayjay-android#1318]
### What happened?

For example I installed kick plugin. Everything works great on home page. But when I try using it to search for things nothing shows up blank screen. I wanted to follow adin Ross but I can't

### Grayjay Version

262

### What plugins are you seeing the problem on?

Kick

### Plugin Version

10

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by usertoroot** [comment]
Please try out creator search:
1. Click on creators
2. Click on search
3. Search for AdinRoss
That should work

It does not show up in video search because Kick does not support video search.
