### ISSUE TITLE
Since the latest update, GrayJay misbehaves when dealing with landscape/portrait switching

### ISSUE THREAD

**Issue by thecatontheceiling** [futo-org/grayjay-android#1319]
### What happened?

I'm using a Samsung Galaxy S9 running unmodified Android 10 with the latest version of GrayJay installed at the time of writing.

Ever since I updated to the latest release, I'm getting an issue when I turn off auto-rotation on my phone. GrayJay used to handle this really well by being able to push me into landscape when fullscreening a video and then putting me back into portrait when closing the video or un-fullscreening.

Now it seems like if I fullscreen with auto-rotation turned off it will permanently lock me into landscape even after I close the video until I exit out of the app and relaunch.

### Grayjay Version

262

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by codebymatter** [comment]
I already reported this issue. usertoroot respojded with a fix coming Minday. Keep an eye for it.
