### ISSUE TITLE
Auto rotate diabled bug

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#1320]
### What happened?

 When i hold the phone in landscape and swipe up to go fullscreen i get fullscreen portrait

When holding the phone in portrait and exiting fullscreen i get the lanscape view 

Rotating the phone when in a wrong state changes to the propper state

Settings
Auto rotate: disabled/same as system 
Fullscreen portrait: off
Bypass rotaion prevention: off

### Grayjay Version

262

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
I've already stated this issue a couple of days ago amd according to usertoroot, the issue will be fixed on today so perhaps a patch update will come today as well.

**Comment by usertoroot** [comment]
Should be fixed
