### ISSUE TITLE
Fullscreen not rotating right

### ISSUE THREAD

**Issue by jmcgaughey** [futo-org/grayjay-android#1321]
### What happened?

When swiping up to fullscreen the vodeo it only fullscreens one way now. Also when minimizing or fullscreening the video it stays in landscape/portrait mode unless i tilt the phone in the direction of landscape/portrait mode at the exact time im swipe down to min the video. Didn't do this before the update.

### Grayjay Version

262

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by codebymatter** [comment]
This issue has alreasy been mentioned in an earlier Issue Post and also on mine on-top of another issue relating to Transitioning of view modes.

usertoroot stated a fix would be worked on today. Perhaps the patch update will be today as wrll.

**Comment by jmcgaughey** [comment]
Thank you for your response

**Comment by usertoroot** [comment]
Should be fixed

**Comment by jmcgaughey** [comment]
it is fixed now with the new update
