### ISSUE TITLE
Creator/Channel Playlist Do Not Load

### ISSUE THREAD

**Issue by Mathew-88** [futo-org/grayjay-android#1322]
### What happened?

I go to creator tab, click on one of the creators and head to Playlists, however, there are no playlists—just pure empty screen.

### Grayjay Version

262

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

202

### When do you experience the issue?

- [X] While logged in
- [x] While logged out
- [ ] N/A

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
