### ISSUE TITLE
Import subscriptions from ytfzf

### ISSUE THREAD

**Issue by asdfghjkl403622** [futo-org/grayjay-android#1323]
### Use Cases

I use ytfzf to watch youtube on my computer, and I'd like to import the subscriptions from there to grayjay. 

### Proposal

[subscriptions copy.txt](https://github.com/user-attachments/files/16947487/subscriptions.copy.txt)
here is my personal subscriptions file. as you can see every line is just a link to a youtube channel. if there is a conversion tool available that I'm not aware of that would be really nice :D

**Comment by Kelvin-FUTO** [comment]
We already support newline seperated import.
First line has to be "Subscriptions" in said file.
Then Settings=>Import Data => Import Line Text File (.txt)

**Comment by asdfghjkl403622** [comment]
> We already support newline seperated import. First line has to be "Subscriptions" in said file. Then Settings=>Import Data => Import Line Text File (.txt)

It might have not worked because all the links in the file are in the old yt link format?
