### ISSUE TITLE
Youtube: Failed to retrueve subscriptions

### ISSUE THREAD

**Issue by xoores** [futo-org/grayjay-android#1326]
### What happened?

Tried to import subscriptions from my youtube account - it errored out on JSON parsing:

![Screenshot_20240910_214222_Grayjay](https://github.com/user-attachments/assets/83ac0204-3f3e-49e3-afb1-ae7b6d02f049)

### Grayjay Version

262

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

203

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by xoores** [comment]
(Tried to get logs from app, but when I clicked on "submit logs" it just said that it has uploaded my logs somewhere and showed some UUID in toast - wth? 😳)

**Comment by DatPika** [comment]
Getting the same thing here.
![Screenshot_20241009_184751_Grayjay.jpg](https://github.com/user-attachments/assets/02fa6d14-abd1-4572-8f70-c23f1ca9028c)

**Comment by xoores** [comment]
Hope they fix this :shrug:

I got no reaction at all however.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version Youtube plugin (209). Are you still encountering this issue?

**Comment by xoores** [comment]
I don't as I uninstalled grayjay - it was unuseable without Youtube and there was no reaction to this bugreport at all. 🤷 Thanks for the info though.

I will probably try again in future if things get better.

**Comment by support-grayjay** [comment]
Apologies for the late reply, we are trying to improve on that as you can see.
Thank you for the quick reply though. I will be closing this issue since this should be fixed but if you encounter the same error, feel free to reopen the issue.
