### ISSUE TITLE
Rumble vids won't download via add to playlist.

### ISSUE THREAD

**Issue by AceODay** [futo-org/grayjay-android#1328]
### What happened?

On my Samsung Galaxy S22 Android version 14,
Evey video I try to download via "add to playlist" will not download due to not finding a valid source for audio. 
Changing the target bitrate or target resolution doesn't change the outcome. Adding the video to a new playlist then setting that playlist to download doesn't change the outcome. Reinstalling the plugin doesn't change the outcome.

However, I can tap on download under the actions tab to successfully download the video.  Sometimes that video will show up in the downloads section and sometimes it won't.
![Screenshot_20240910_210941_Grayjay](https://github.com/user-attachments/assets/8f23ab2f-1269-4de6-8d89-ad832a0cbf81)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

45

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by kaidelorenzo** [comment]
This is an issue with the Grayjay app. It also applies to BitChute. The plan is to get a fix into the next release
