### ISSUE TITLE
Rumble import subscriptions are wrong

### ISSUE THREAD

**Issue by SunnyDaze** [futo-org/grayjay-android#133]
I'm getting a completely wrong subscription list when I log into Rumble and import my subscriptions. The import list is missing most everything. There are a few subscriptions that are the same, and a lot of the channel subscriptions I've never heard of.

**Comment by DrLegitamate** [comment]
I have the same problem. I'm subscribed to 6 channels on Rumble but it tries to import 20+ channels that are irrelevant to my profile

**Comment by koen-futo** [comment]
Some fixes were made to this recently. If this is still an issue, please reopen the issue.
