### ISSUE TITLE
Rotation lock bug

### ISSUE THREAD

**Issue by mingyee2** [futo-org/grayjay-android#1331]
### What happened?

Simply put, once fullscreened, I expect the rotation lock button to keep the rotation locked. Instead, no matter which state the button is in, the video rotates as the orientation of my phone changes. I have tested that this occurs regardless of system setting for rotation lock.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by codebymatter** [comment]
Enable Full-Auto Rotation Lock to keep the fullscreen view fixed to 90° landscape (as in landscspe with cameras on left and USB-C port on the right)

I noticed the rotation lock icon while watching videos but seems to dk notbing. I have System Rotation Off and Rotation in-app set to Same as System.

It's not an issue to me as the transition from Potrait to Landscape works again as of v. 264 but thought I'd mention it.

**Comment by mingyee2** [comment]
Thanks. That did indeed return behaviour to something usable.

Nevertheless, with the setting off, I believe the behaviour is bugged, since I think that setting is only supposed to govern landscape to reverse landscape and vice versa, not landscape to portrait, etc.

**Comment by itsvrl** [comment]
Also bugged on GrapheneOS. Every other app I have on the phone works normally, only the grayjay app that have this behavior.

**Comment by Zvonimir-FUTO** [comment]
Is this still present in the latest (v264) version of Grayjay and did you enabled "Allow reverse portrait" by chance?

**Comment by mingyee2** [comment]
I just tested, and it appears to be, yes. With #1332 closed by the upcoming version, that should be all the rotation behaviour on my wishlist :). Looking forward to it!
