### ISSUE TITLE
Upside down rotation still causes rotation to reset to portrait

### ISSUE THREAD

**Issue by AnnieTheEagle** [futo-org/grayjay-android#1332]
### What happened?

When I rotate my device upside down (something that often happens when I'm lying in bed on my side, watching videos in landscape), the app still rotates back to 0° portrait even with the new "Allow reverse portrait" option disabled.

This is unlike any other video player I've used where rotating from 90 (landscape) to 180, causes the app to stay in landscape. Even most system apps and non multimedia apps do this.

Expected behaviour:
When "Allow reverse portrait" is disabled: The app should stay in the most recent landscape rotation, rather than resetting back to 0°
When "Allow reverse portrait" is enabled: The app should rotate to 180° (portrait but upside down).

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Allvaldrsson** [comment]
There's a setting called "Full auto rotate lock" that restores the feature to its previous function. I'm not sure what they were attempting to solve.

**Comment by usertoroot** [comment]
There are a few overlapping use-cases here:
1. There are people who disable auto rotation (either by using rotation lock on the player, disabling rotation on system or disabling rotation entirely) but still want to be able to have the landscape view rotate (but always stay in landscape). For these people we encourage to use the rotation lock or disable automatic rotation entirely in the settings.
2. There are people who like auto rotate to enter/exit fullscreen mode. This is the default behaviour.
3. There are people who want the rotation lock to disable ALL rotations, even rotating between the 2 landscapes when in fullscreen. For these people the setting "Full auto rotate lock" exists.

**Comment by AnnieTheEagle** [comment]
> There's a setting called "Full auto rotate lock" that restores the feature to its previous function. I'm not sure what they were attempting to solve.

Doesn't change the behaviour for what I'm seeing either. 

Allowing upside down portrait or not, in what conceivable scenario should the device being held in a 180° rotation result in a 0° rotation actually being displayed and everything being upside down.

I'm surprised this hasn't been fixed. I remember seeing this bug months ago and it's one of the last blockers from getting me to switch over from ReVanced or NewPipe.

**Comment by usertoroot** [comment]
Does one of these cases solve it for you? What is your final goal?

The way I am reading your post you want when you manually enter fullscreen, to not automatically rotate out of fullscreen when you rotate your phone to one of the portrait views.

In this case you can either use rotation lock, disable auto rotation in settings or disable rotation on the system.

**Comment by AnnieTheEagle** [comment]
> There are a few overlapping use-cases here:
> 
>     1. There are people who disable auto rotation (either by using rotation lock on the player, disabling rotation on system or disabling rotation entirely) but still want to be able to have the landscape view rotate (but always stay in landscape). For these people we encourage to use the rotation lock or disable automatic rotation entirely in the settings.
> 
>     2. There are people who like auto rotate to enter/exit fullscreen mode. This is the default behaviour.
> 
>     3. There are people who want the rotation lock to disable ALL rotations, even rotating between the 2 landscapes when in fullscreen. For these people the setting "Full auto rotate lock" exists.

No I understand that. I am in the camp of option 2, where I use auto-rotate to enter/exit fullscreen. However, I dont ever hold my device upside down to exit a landscape orientation. None of my other apps do this (multimedia or not). 

To prove this, simply open up Firefox (or any fork thereof, e.g. IceRaven) and rotate your device landscape, now hold it upside down portrait, it will stay in the previous landscape orientation (whether you went from 0 -> 270 -> 180 (stays at 270), or 0 -> 90 -> 180 (stays at 90).

My end goal is to be able to use Grayjay in bed (I allow myself 1-2 educational videos before sleeping [usually Chess -- right now]). A lot of people will lie in bed on their side. If you want to watch in landscape, while laying on your side, your physical device must be upside down (90 degrees rotation on your physical person, 90 degrees rotation on the phone). But I want the videos to remain landscape (i.e. fullscreen), just like any other app I have does, without needing to manually toggle rotation lock every time.

**Comment by AnnieTheEagle** [comment]
> The way I am reading your post you want when you manually enter fullscreen, to not automatically rotate out of fullscreen when you rotate your phone to one of the portrait views.

Incorrect. I want it to:
1) Automatically enter fullscreen when going from 0 -> 270 or 0 -> 90.
2) Automatically exit fullscreen when going from 270 -> 0 or 90 -> 0.
3) Not change orientation at all when going from 270 -> 180 or 90 -> 180.

This is how almost every other app I have installed works (3). I can think of only one app that didn't do these three things by default, and (3) was resolved with a simple "Disallow upside-down rotation" in the settings (after which it did exactly as described in the 3 points above).

**Comment by AnnieTheEagle** [comment]
@usertoroot If it helps, I'm willing to actually record a video (not screen recording) of what I mean. With an example app showing the correct behavior too (I'll just use Firefox, as I mentioned it before).

Would this help you visualise my issue?

**Comment by usertoroot** [comment]
OK I believe I understand what you are suggesting
1. Automatically enter fullscreen when going from portrait/reverse portrait to landscape/reverse landscape
2. Automatically exit fullscreen when going from landscape/reverse landscape to portrait
3. Not change orientation at all when going from landscape/reverse landscape to reverse portrait
Is that correct?

**Comment by AnnieTheEagle** [comment]
> OK I believe I understand what you are suggesting
> 
>     1. Automatically enter fullscreen when going from portrait/reverse portrait to landscape/reverse landscape
> 
>     2. Automatically exit fullscreen when going from landscape/reverse landscape to portrait
> 
>     3. Not change orientation at all when going from landscape/reverse landscape to reverse portrait
>        Is that correct?

I suppose so yes, but one could also just exclude reverse portrait -> landscape/reverse landscape from (1) and just not handle reverse portrait at all (which is what I assumed `Allow reverse portrait` being disabled would do).

**Comment by AnnieTheEagle** [comment]
`Allow reverse portrait` ON:
* Any -> 90 - Rotates to landscape.
* Any -> 180 - Rotates to reverse portrait.
* Any -> 270 - Rotates to reverse landscape.
* Any -> 0 - Rotates to portrait.

`Allow reverse portrait` OFF:
* Any -> 90 - Rotates to landscape.
* Any -> 180 - **Nothing happens, it stays in the previous rotation it was in before** (This is Firefox's behaviour)
* Any -> 270 - Rotates to reverse landscape.
* Any -> 0 - Rotates to portrait.

**Comment by usertoroot** [comment]
Thanks for the explanation I think that makes sense. Will look at it for the next build. For a temporary workaround I hope disabling auto rotation will suffice for now.

**Comment by AnnieTheEagle** [comment]
> Thanks for the explanation I think that makes sense. Will look at it for the next build. For a temporary workaround I hope disabling auto rotation will suffice for now.

Thanks, would you be able to reply on this thread once it's resolved? I do hope it can be resolved as having to manually toggle auto-rotation is really annoying and I often end up just switching back to ReVanced, which isn't ideal of course given it's dependence on microG.

**Comment by SupremeLobster** [comment]
The issue seems to be a conflict between autorotate settings and the "allow fullscreen portrait" setting being enabled. Fullscreen portrait should ONLY be allowed on videos that have a portrait aspect ration, and ONLY if the setting is enabled. It makes not sense to enter fullscreen portrait mode on a video that is not portrait. Seems like an easy fix: just check the aspect ratio of the video. This is exactly the behavior of the official YouTube app, and it works pretty well. It also makes a lot of sense

**Comment by GinaBnina** [comment]
Just fix this rotation problem already!! It is very buggy.
Still no portrait mode on fullscreen.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the upcoming release (v265).
