### ISSUE TITLE
Profile image doesn't match with the channel

### ISSUE THREAD

**Issue by RatuscaF** [futo-org/grayjay-android#1335]
### What happened?

![Screenshot_2024-09-14-16-46-11-138_com futo platformplayer](https://github.com/user-attachments/assets/58b6c5a1-a6fd-4170-8980-1c4422a6c0a1)

### Grayjay Version

262

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

204

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
This is a old and known issue. Profile pictures appearing on the wrong channels. A simple feed refresh clears the problem up. It's not irksome in any way but it might to others.

**Comment by RatuscaF** [comment]
For me refreshing doesn't solve anything. I really think it's an easy fix, I don't know why they haven't done it already

**Comment by Zvonimir-FUTO** [comment]
Does this still happen on the latest version of Youtube plugin?

**Comment by RatuscaF** [comment]
Solved!

**Comment by Zvonimir-FUTO** [comment]
Good to know. Closing issue.
