### ISSUE TITLE
Option - Limit some creators from main subscription feed

### ISSUE THREAD

**Issue by nbuhrke1** [futo-org/grayjay-android#1338]
### Use Cases

There are some creators that either update several times a day or have multiple streams running at the same time. This can clutter the subscriptions tab and fill up the majority of the first videos with all the same creators.

I still want to be subscribed to those creators, but only want to access their content when I'm looking for their group.

For example, the YouTube channel lofi girl has several radio streams running simultaneously. I have her placed in a group of creators titled "Music." I'd love to access their content, but only when I'm looking for music content creators. Otherwise, her and a few other similar channels fill up most of my initial subscriptions tab.

### Proposal

A solution that I think might fix this is providing the option to limit some channels from the main subscriptions feed and to keep them just to their assigned groups.

**Comment by nastynick64** [comment]
I was thinking the exact same thing! In my case, I have subscribed to a couple of news channels. But every news channel seem to upload like 12 videos a day or something, which just fills up too much of the feed making it very difficult to find content from other creators.

**Comment by codebymatter** [comment]
> I was thinking the exact same thing! In my case, I have subscribed to a couple of news channels. But every news channel seem to upload like 12 videos a day or something, which just fills up too much of the feed making it very difficult to find content from other creators.

I see Grouping creators by content type being useful here. Set one group for News and another for whatwver it is you want to name it and view Syb feed that way. More ideas are welcimed of course.``

**Comment by support-grayjay** [comment]
This should be solved with Subscription Groups.
