### ISSUE TITLE
[BUG] Download All on watch later playlist attempts to re-download

### ISSUE THREAD

**Issue by Craft-CM** [futo-org/grayjay-android#1339]
### What happened?

I hit Download All on my watch later playlist.
Thw app downloaded them.
Now it is attempting to re-download them but fails on about 8 of them.
I clear the downloaded failed pop-ups and the tile icons in the download tab.
- Errors range from no source, no audio, to cannot read properties of null (twitch)
Everytime I refresh the app, it attempts to auto download the same failed videos.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### Plugin Version

YT 204, Twitch 18, Rumble 45

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by support-grayjay** [comment]
Could you explain on hitting download all? That button should be replaced delete all if the playlist is already downloaded.

**Comment by Zvonimir-FUTO** [comment]
This should be fixed in the latest version of Grayjay.
