### ISSUE TITLE
zoomed in player

### ISSUE THREAD

**Issue by ratbastardcitrus** [futo-org/grayjay-android#1345]
### What happened?

when i go to a video not in fullscreen on the app instead of showing the video in its correct aspect ratio it zooms way in and crops most of the video out. 
![Screenshot_2024-09-18-23-09-32-70_692607d6162f2fc937d276a7f6a1b050](https://github.com/user-attachments/assets/b34497c2-b6ec-4a01-8a25-6c6e3dbacbfa)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by support-grayjay** [comment]
Could you provide a bit more information on reproducing this? Is this still happening on the latest version of Youtube plugin?

**Comment by Zvonimir-FUTO** [comment]
Closing as stale.
