### ISSUE TITLE
[Fdroid] Can't install Youtube plugin update

### ISSUE THREAD

**Issue by sinjoe** [futo-org/grayjay-android#1346]
### What happened?

![Screenshot_2024-09-20-17-22-16-95_1](https://github.com/user-attachments/assets/f571308a-7529-47b9-a4cd-5b47993c27e0)

### Grayjay Version

253 (Fdroid)

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

204

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

Temporary workaround

>UPDATE:
after re-installing the apk from the site, youtube plugin updated successfully
>
_https://github.com/futo-org/grayjay-android/issues/1346#issuecomment-2364184379_

**Comment by codebymatter** [comment]
Noticing that youreon an old build of Grayjay. Not sure if that has anything to do with the plugin not updating.

**Comment by lumpsoid** [comment]
same for me

apk from github

Grayjay Version
253

What plugins are you seeing the problem on?
Youtube

Plugin Version
185

**Comment by cosmicrabbit452** [comment]
Should be manditory that either: scripts have a minimum version for compatilability, or F-droid releases on major changes like 264

**Comment by lumpsoid** [comment]
@cosmicrabbit452 
than, maybe make this error clearer to end users?
like "your application version is not compatible with the new plugin version"

**Comment by beatgammit** [comment]
App has been updated to 264 on F-droid, and YouTube plugin installs for me. This can probably be closed.
