### ISSUE TITLE
F-Droids Updates take way too long, either fix that or remove the support label

### ISSUE THREAD

**Issue by MrRulf** [futo-org/grayjay-android#1347]
### What happened?

Fdroid updates just take too long. With plugins that get updates inside the app this is an issue because right now an update for the youtube plugin just doesn't work and since it works on my friends phone it looks like the version I'm (stuck) on because I got it from fdroid is the issue. 
This isn't the first time this happened, in fact fdroid takes multiple versions for every update (altough versions are skipped then), however the resulting problems really hurt the reputation of the project, so I'd suggest to either remove the "official supported" on the fdroid download, recommend the play store or direct download or fix those issues on the fdroid download. 

### Grayjay Version

253

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

185-205

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by cosmicrabbit452** [comment]
I think it's wonderful that Grayjay can self update, but I prefer to have as few apps as possible have the permission to install things on my phone. As its imperative for functionality, F-Droid releases should at least be prioritized when its known platform plugins (that offer to update without version checks) have a required minimum version.

**Comment by cyraid** [comment]
Are there any developers actually reading these issues? Legitimately asking, not trying to be a jerk.

**Comment by codebymatter** [comment]
> Are there any developers actually reading these issues? Legitimately asking, not trying to be a jerk.

They are. You're also more than welcomed tto hop onto the FUTO chat if you have any questions for the team on Zulip. It's like Discord chat.

https://chat.futo.org/

**Comment by MrRulf** [comment]
Great to see Zulip in action ^^
For now I switched over to the PlayStore version (trough AuroraStore), but I immediatly got the info that the version is limited compared to the fdroid version, which makes the update issue with fdroid even more relevant imo. 
Anyway, will check out Zulip now, maybe I'll find some info on this topic there, wasn't able to find any info in the github issues. If I find something I try to repost it here cuz having somebody ask here if devs even read this kinda tells that I'm not the only one not knowing if there is even anything happening on this. 
Devs are obviously welcome to give us some feedback about the situation themselves aswell ;)

**Comment by Kelvin-FUTO** [comment]
Sorry for the late reply.
We're aware of the issue, it seems something start going wrong with fdroid deployment a while back. But we didn't notice.

That being said I believe the FDroid issues were solved last week.

I'd say our recommended way of using Grayjay is just sideloading it from our official website (https://grayjay.app).
It has an auto-updater built in.

And yes, we do read the issues, but because our attention is currently split with the desktop version, we switch between mobile and desktop in waves, fixing a bunch of issues in bulk.
We recently added someone on the team to go through every issue and manage things a bit better (hes currently going through the backlog), as we lack the time to properly filter through everything ourselves.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed :)

**Comment by NTpspE** [comment]
This appears to be happening again, the app keeps prompting to update from within, showing a warning that in the future it "might update from any source" which worries me as I don't want it to auto update to the play store version.

I'd rather stick to the F-droid repo where I manage most apps on my device.

**Comment by Zvonimir-FUTO** [comment]
You can disable **Check** (for update) inside **Settings** > **Auto Update** and continue updating through F-droid

**Comment by NTpspE** [comment]
Oh thanks! That helps, so at least I'm not getting the update prompt every time I update it now :D 
Do you know when it'll be updated on the f-droid repo?
