### ISSUE TITLE
4:3 video show white bars on top

### ISSUE THREAD

**Issue by edo9300** [futo-org/grayjay-android#1348]
### What happened?

On android 14, When watching a 4:3 video, there is a row of white pixels on the top of the video player, on the sides where the black bars are
![Screenshot_20240921-132326_Grayjay](https://github.com/user-attachments/assets/9609d359-9f25-406f-ba22-b97f7eb28dc8)
(If you zoom in the PIC and look at the top it's noticeable, the zoom rectangle is there only to show what the aspect ratio of the video is), this is also present when you don't watch the video full screen.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by edo9300** [comment]
This also happens when watching for example a 16:10 video on a 16:9 display, in which case, the whole top row of pixels will be white

**Comment by support-grayjay** [comment]
Will be resolved through #315.
