### ISSUE TITLE
[Issue]  Subscriptions

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#136]
The content from my subscriptions doesn't show up in subscriptions panel
![Screenshot_20231031-155054266](https://github.com/futo-org/grayjay-android/assets/120592808/c16c5c6a-c95c-44f0-a98f-de653eef2e2f)

**Comment by Sebas-Re** [comment]
I also have an issue with subscriptions, mine don't sync properly.
Comparing grayjay notifs with YouTube's, some vids and lives don't show up.

Here's an example from within grayjay

![image](https://github.com/futo-org/grayjay-android/assets/32151264/5dadc9b7-49d0-4469-8dd0-01662aef9d9c)
![image](https://github.com/futo-org/grayjay-android/assets/32151264/a4c17318-68a5-43e0-b14f-924e602969d2)

**Comment by Darkvramp** [comment]
You have to have  videos selected at the top of the subscription tab

**Comment by Kelvin-FUTO** [comment]
Yea, videos was disabled in your filters, so I'm closing this for now.
Note that subscriptions system had several changes recently which may fix some of the other things mentioned.
