### ISSUE TITLE
Can not update youtube plug in

### ISSUE THREAD

**Issue by zbyszek-24** [futo-org/grayjay-android#1366]
### What happened?

When trying to update youtube plug in I get error:
***DashManifestRawSource*** is not defined (1662)[31-32]
Note:
Plugin has the embeded version but thats just because I reverted it due to this error. On one of the newer versions the same problen ocurred.

### Grayjay Version

242

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

177

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by serossi** [comment]
how about updating grayjay first before opening a bugreport on a development platform ?
current is 264

seriously wtf

**Comment by zbyszek-24** [comment]
> how about updating grayjay first before opening a bugreport on a development platform ? current is 264
> 
> seriously wtf

I didn't realise, that was dumb, sorry...
