### ISSUE TITLE
Not going to sleep

### ISSUE THREAD

**Issue by bortan1** [futo-org/grayjay-android#137]
After the video I watch ends (YouTube video), the phone should realise it's not being used anymore and the inactivity time should start counting down until it reaches the value I have set in my phone settings. This is not happening and after the video ends, the phone stays up until battery dies or I notice it and turn it off or exit the app.

**Comment by Darkvramp** [comment]
This should be a setting to toggle on and off yes. Or to match system settings.

**Comment by QuintenMadari** [comment]
The screen never goes to sleep on video end or pause and causes unnecessary battery draining. A settings toggle would be useful.

I read through the issue list to see if someone already mentioned this. Thanks! Hope this will be addressed.

**Comment by koen-futo** [comment]
For normal videos this was fixed quite a while ago but there were some conditions in some devices that would not trigger the proper event (i.e. when headphones disconnect or a live stream ending suddenly). A fix has been added to the next version.
