### ISSUE TITLE
Loop not working for offline videos

### ISSUE THREAD

**Issue by Opening-Button-8988** [futo-org/grayjay-android#1371]
### Device Info

Pixel 7, GrapheneOS build number 2024091900 Android v14.

### What happened?

Enabling the loop option for videos does not work for offline videos.

Same issue as issue #490 and still not fixed.

I would provide logs under "Relevant log output" but I don't know where to copy the log from.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Closing as stale.
