### ISSUE TITLE
Full screen not working right

### ISSUE THREAD

**Issue by signo-codebase** [futo-org/grayjay-android#1375]
### What happened?

Going into full mode makes a white banner appear on top (exactly where the notification badges are). This happens both in vertical and horizontal full screen. The banner is always "on top" with respect of the phone, no matter the rotation. 
Huawei Nova 5t. Android. Default configuration. Youtube version 205.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
Closing as stale.
