### ISSUE TITLE
[Feature Request} Scrub Bar / Playback Bar

### ISSUE THREAD

**Issue by kaseyprichard** [futo-org/grayjay-android#138]
Suggestion would be to allow clicking anywhere on the scrub/playback bar to scrub or seek similar to YT on Android. 

Another option would be to increase the size of the "dot" that you are required to click on in order to scrub (if click-anywhere is not possible) to make it easier. 

I find myself constantly not able to scrub the video forward because I am either clicking on the line without thinking...or unable to get the exact right spot on the playback dot.

**Comment by Zvonimir-FUTO** [comment]
Clicking on the playback bar is possible with the latest version of Grayjay. As for the better more granularity, it will be solved through #62
