### ISSUE TITLE
Playlist not working [youtube]

### ISSUE THREAD

**Issue by AgentZod** [futo-org/grayjay-android#1382]
### What happened?

Some playlist have converted to course in new YouTube update. 
The playlists which are now under courses cannot be saved as playlist on grayjay.
Asking to fix this or make courses to be saved.
![Screenshot_20241003-140326](https://github.com/user-attachments/assets/b61d411a-fbae-4c3b-acc6-3c4dd3f8bc3e)

### Grayjay Version

242

### What plugins are you seeing the problem on?

Youtube

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by grayjay-support-FUTO** [comment]
Thank you for reporting this. We will investigate this.

**Comment by fyreswan** [comment]
I also have this issue 
![Screenshot_20241009-004428](https://github.com/user-attachments/assets/7a12257d-e9a4-49d8-893a-acf1ff7592a7)

**Comment by Allvaldrsson** [comment]
I'm also experiencing this issue. Attempts to troubleshoot have been unsuccessful. 

GrayJay v264
YouTube Plugin v205

**Comment by thecatontheceiling** [comment]
I am also experiencing same issues on all playlists on my phone. Latest version of GrayJay and the YT plugin. Can provide more info if requested.

**Comment by moaz-ahmed** [comment]
Same issue as @thecatontheceiling

**Comment by Kelvin-FUTO** [comment]
New Youtube plugin update (v209) implements the new playlist model and should fix this.

**Comment by thecatontheceiling** [comment]
The issue is fixed now on my end. Good work Kelvin :)
