### ISSUE TITLE
All sources turned on. After blocking a few alt-right creators from my feed, only 4 videos total come through the feed, out of all sources

### ISSUE THREAD

**Issue by TheGalexio** [futo-org/grayjay-android#1385]
### What happened?

As title states. There are a few nuggets of good stuff in non-youtube sources. But to get through them I have to filter/hide a few conspiracy theorists from my feed. The unfortunate result is that after filtering a couple of them, my feed is abruptly cut to 2-3 videos TOTAL out of all the sources turned on.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by cyraid** [comment]
You probably could've just said "a few unwanted videos" lol .. But a way to hide channel and sync to YT would be nice.

**Comment by GOLDKatastrophe** [comment]
Same issue. After hiding 2 creators I have this issue, any random 2. Clearing the hidden items fixed it but diminishes the use of the feature.

**Comment by codebymatter** [comment]
I have had to block channels a few times on the home feed for suggestions. I had not done tbis in
 roughly 6 minths as I rarely ever look at the Home feed. The Subscriptions feed is set to open first ecery time I launch the app.

Can tbis function be inpeoved upon? Sure. Show a lisf of blocked creators. I'd imagine this list will need to be stored alongside with user settings, plugins, followed creators, etc. I only have 6 creator profiles blocked and cannot see their content which means it works but unable to comment on bugs.

**Comment by Zvonimir-FUTO** [comment]
Closing as stale.
