### ISSUE TITLE
Lock screen rotation is not functional.

### ISSUE THREAD

**Issue by GenericUsernameIsNotAvailable** [futo-org/grayjay-android#1388]
### What happened?

Ive waitied a bit before raising this issue to see if it would get a quick fix. It hasn't.

The screen rotation lock button no longer locks the screen. Its very annoying as if im lying down, the phone will go to portrait, whereas it needs to be landscape.

Please make it so the screen lock, actually locks the position in place again.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Philippe-Choquette** [comment]
OP hasn't replied, but I have this exact same issue once I enable the "Fullscreen portrait" option. After it's enabled, the video player rotates freely, and the lock rotation button state is ignored. It's by far the most problematic issue I've been experiencing with Grayjay.

**Comment by GenericUsernameIsNotAvailable** [comment]
Within settings, there is now an option to "lock rotation". Even between landscape and landscape reverse. Although portrait video isnt seemingly functional at the moment, my initial issue raised has been resolved.
