### ISSUE TITLE
Watch History is not Backed Up When Exporting Data

### ISSUE THREAD

**Issue by dyllan500** [futo-org/grayjay-android#1397]
### What happened?

When exporting your Grayjay data from the settings and creating a backup zip of your data. Watch history is not backup and saved. This means that when you import your data to a new device your watch history is not imported. 

### Grayjay Version

264

### What plugins are you seeing the problem on?

Other

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
We have implemented this and is currently in testing phase, should be release with the next Grayjay release v265.
