### ISSUE TITLE
Age restricted videos not working 

### ISSUE THREAD

**Issue by Samo4051** [futo-org/grayjay-android#1401]
### What happened?

Age restricted videos load only 4 second of the video then stop working and lead to no error spotted by the app 

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
There is no error detect by the app
```

**Comment by nastynick64** [comment]
Having the same issue on my end.

**Comment by support-grayjay** [comment]
This will be resolved through #1423.
