### ISSUE TITLE
Polycentric import and export needs an improvement

### ISSUE THREAD

**Issue by TheQuickFox** [futo-org/grayjay-android#1404]
### Use Cases

When making an export of my Polycentric ID + history, I now get a huge text string that I can copy to the clipboard. This causes the phone to freeze and storing the text string to a text editor risks corrupting it.

### Proposal

I suggest GrayJay changes the export to a compressed file such as a .zip file which can be saved to storage and for example copied to PC for backup or imported to another phone.

### References

- #1074

**Comment by Zvonimir-FUTO** [comment]
This should be fixed in the latest version of Grayjay. App shouldn't crash and you can scan/show QR code when importing/exporting. If you are still encountering the issue feel free to open it up again.
