### ISSUE TITLE
Youtube fail to play, fail to load ump 

### ISSUE THREAD

**Issue by William35680** [futo-org/grayjay-android#1406]
### What happened?

You tube video fail to play and getting error message fail to load ump try restarting plugging/app, however still the same issue when restart, also video download doesn't show mp4, it shows ump. 
![Screenshot_20241016-214555](https://github.com/user-attachments/assets/fe14f8e7-fd86-4db8-a8a6-82f78fe35e68)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Kelvin-FUTO** [comment]
A Youtube update was made last week which should fix this.
For UMP fallback specifically only WEBM is implemented right now, this should not affect playback however as far as I know.

**Comment by Xono2** [comment]
Keep having the same issue, tried uninstalling but didn’t work.

**Comment by Zvonimir-FUTO** [comment]
> Keep having the same issue, tried uninstalling but didn’t work.

We have another issue opened for this https://github.com/futo-org/grayjay-android/issues/2185

We are looking into UMP again to see what can be improved but is hard to fix these kinda issues without reproduction.
