### ISSUE TITLE
youtube playlist not loading

### ISSUE THREAD

**Issue by jmcgaughey** [futo-org/grayjay-android#1408]
### What happened?

the playlist are not loading at all on youtube

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by donottellmetonottellyou** [comment]
I am having the same issue, cannot load any YouTube playlists from the creator tab

**Comment by FireNinja7365** [comment]
Same issue, mine is only loading liked videos and watch later

**Comment by donottellmetonottellyou** [comment]
Appears to be fixed in 209

**Comment by FireNinja7365** [comment]
Fixed for me as well

**Comment by jmcgaughey** [comment]
seems to be working better

**Comment by jmcgaughey** [comment]
seems to be working better after the couple yt updates
