### ISSUE TITLE
[Issue] Playlists

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#141]
Just cant import my playlists
![Screenshot_20231101-101236_Grayjay](https://github.com/futo-org/grayjay-android/assets/120592808/ffe26ac1-8d1a-48e8-81e2-5d8d79b9432e)

**Comment by grisevg** [comment]
Can you not make multiple duplicated issues please - https://github.com/futo-org/grayjay-android/issues/241
