### ISSUE TITLE
Age restricted video freezes from time to time when watching it

### ISSUE THREAD

**Issue by dcalitri** [futo-org/grayjay-android#1411]
### What happened?

When I started watching an age restricted video on the app I would get a failure to stre (or download) IOS and the video would freeze from time to time.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

205

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale.
