### ISSUE TITLE
Comments not posted, likes not working

### ISSUE THREAD

**Issue by 42O69420** [futo-org/grayjay-android#1412]
### What happened?

When i comment on videos, my comment appears to post but when i refresh it is instantly deleted. it appears on the more>comments page but not on the video. when i like videos or comments and refresh the button appears as liked but the like counter is reset to what it was before. this issue has been happening for a few months now and is annoying as hell, the only way others have found to fix this involves resetting app data, which isn't an option as i have lots of downloaded videos that are not on youtube anymore that i don't want to lose

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by support-grayjay** [comment]
I wasn't able to reproduce this. Could you provide the link to the video where you commented and your Polycentric username so we can look further into this?

**Comment by eddbird** [comment]
> I wasn't able to reproduce this. Could you provide the link to the video where you commented and your Polycentric username so we can look further into this?

@support-grayjay This appears to be the same issue with the same cause as noted in #1074. Trying to delete a comment seems to cause a loop of some kind where a total reset is the only fix. Reliably causes this exact issue.

**Comment by support-grayjay** [comment]
Thank you for linking this. I'm able to reproduce the bug now but it acted differently in my case where I deleted old comment from the video, comment on the same video again, open video again and new comment shows up, delete new comment and comment again, reopen video again and _oldest_ comment is showing.

We will investigate this.

**Comment by 42O69420** [comment]
it just started working for me today thx 4 fixing it 🎉
