### ISSUE TITLE
[Bug] YT stops playing after 5 sec when connected to a VPN

### ISSUE THREAD

**Issue by HalbautomatikToastgeraet** [futo-org/grayjay-android#1414]
### What happened?

YT stops playing the video after 5 sec, but the audio i still running. But only when connected to a vpn.

https://github.com/user-attachments/assets/04266f77-0e93-40cb-8daf-de82ced97969

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

206

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by support-grayjay** [comment]
I was not able to reproduce this with Wireguard VPN connection. Could you please again with the latest version of Youtube (209) and report back? Also which VPN were you using?

**Comment by HalbautomatikToastgeraet** [comment]
I checkt and it looks like its fixed. But I had the problem when using Proton VPN connected to a german server.

**Comment by HalbautomatikToastgeraet** [comment]
Wissenstest und die Jugendflamme.
