### ISSUE TITLE
Grayjay doesn't properly handle Odysee scheduled videos

### ISSUE THREAD

**Issue by I-I-IT** [futo-org/grayjay-android#1415]
### What happened?

Odysee now has a scheduled video options. The issue is the video will appear in my sub feed as normal videos (no indication that it isn't live yet), and when I click on it it says access is forbidden.

An example below with a video from NBTV.
![2272](https://github.com/user-attachments/assets/50f0a870-4f0a-4c1f-8aa1-fc2b9e2e61b4)
![2271](https://github.com/user-attachments/assets/99d03207-5959-4143-a674-df5077ba44da)
![2273](https://github.com/user-attachments/assets/8f72ff4f-3c58-477c-91c5-cce131f4798c)

A hotfix will be to hide the video until it is available. A more permanent fix would be to indicate it is scheduled but allow access to the video description.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Odysee

### Plugin Version

38

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by kaidelorenzo** [comment]
I'm having trouble finding an example scheduled video to test against. Do you know of any currently scheduled videos I can look at?

**Comment by I-I-IT** [comment]
I know that [SwitchedLinux](https://odysee.com/@switchedtolinux:0)does stream every sunday so that could be it.[All Things Secured](https://odysee.com/@AllThingsSecured:9) also sometimes stream. If you pushed an update, I could let you know the next time I see one.

**Comment by kaidelorenzo** [comment]
Version 42 should properly handle scheduled videos
