### ISSUE TITLE
[Feature Request] Video Time and Date

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#142]
Would be great if we had the time&date of the videos just like YouTube has

**Comment by HafizBeyy** [comment]
![Screenshot_20231101-101619_Grayjay](https://github.com/futo-org/grayjay-android/assets/120592808/1ff67a95-01ce-4c6d-8c65-b87061fa89b5)

**Comment by Kelvin-FUTO** [comment]
This was a bug for people using non-english Youtube accounts. This was already the case for everyone else.
This has been fixed in 193.
