### ISSUE TITLE
YouTube playlists will not open in Privacy Mode

### ISSUE THREAD

**Issue by codebymatter** [futo-org/grayjay-android#1422]
### What happened?

Edit: Searched YT playlists will not open in version 208 regardless of Privacy Mode being On or OFF.
The YT updated about an hour ago. The Privacy Mkde has been a useful feature since its implementation as I can view/listen to playlists without YT having to suggest similar videos. I've encountered a bug whem attempting to open a searched playlist

The images below show it:
![Screenshot_20241018-221602_Grayjay](https://github.com/user-attachments/assets/ad974e77-27e8-488c-bebd-2c9aa461e917)

![Screenshot_20241018-221617_Grayjay](https://github.com/user-attachments/assets/95c8fdca-c6c7-44ee-8f27-16aa74e94e13)

![Screenshot_20241018-221622_Grayjay](https://github.com/user-attachments/assets/5f289761-22a2-4b2a-9a9c-4adfe4a8e0bc)

![Screenshot_20241018-221700_Grayjay](https://github.com/user-attachments/assets/b6a77a6c-1c30-4455-94de-2f105b459eef)

![Screenshot_20241018-221705_Grayjay](https://github.com/user-attachments/assets/b8dd2386-9360-465e-bfd4-134e33185a21)

![Screenshot_20241018-221711_Grayjay](https://github.com/user-attachments/assets/e1fa38b2-425d-4d8c-a98d-a3a961165da8)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
I am able to open playlists while in Privacy Mode from other plugins (excluding Spotify bc of Auth check), and still in Privacy Mode, my saved playlists open and play.

When Privacy Mode is OFF, YT playlists DO open and play, by the way. Thank you for reading and I shall aeait for a fix. 

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

208

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
n/a
```

**Comment by Gotrees** [comment]
I'm having the same issue, although I don't use privacy mode. It was working fine last night but not anymore.

**Comment by captfleshstick** [comment]
![Screenshot_20241019_004614_Grayjay](https://github.com/user-attachments/assets/53ccd6d1-52c3-4e73-97c0-63f93a420574)
Same here i have the exact same issue but I'm not on privacy mode. It was working well and then all of a sudden it hasn't worked in about a month now. Hope this gets sorted out soon.

**Comment by codebymatter** [comment]
> ![Screenshot_20241019_004614_Grayjay]
Same here i have the exact same issue but I'm not on privacy mode. It was working well and then all of a sudden it hasn't worked in about a month now. Hope this gets sorted out soon.

YT playlists open and played just fine laat week with and without Privacy Mode on version 206. In case anyone suggests to rollback to version 207, the YT plqylist bug still psrsiats.

**Comment by Caotenhoch2** [comment]
I'm experiencing the same issue when trying to open Youtube playlist, Saved Playlist work. It does not matter whether privacy mode is on or off

**Comment by Kelvin-FUTO** [comment]
New Youtube plugin update (v209) implements the new playlist model and should fix this.
