### ISSUE TITLE
Playlist for subscription do not or won't load. WHY. FIX IT ASAP.

### ISSUE THREAD

**Issue by Arnec21** [futo-org/grayjay-android#1427]
### What happened?

I expected to see the subscription playlist open so I can pkay a video.
Fix it asap.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### Plugin Version

208

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by mathlover2** [comment]
I am having this same issue. As far as I can tell, this is an issue with the YouTube plugin

**Comment by codebymatter** [comment]
Already posted this 2 days ago, [Issue#1422.](https://github.com/futo-org/grayjay-android/issues/1422#issue-2598676751) Surely they're working on it. It's no ghost crew.

**Comment by Kelvin-FUTO** [comment]
New Youtube plugin update (v209) implements the new playlist model and should fix this.

**Comment by Arnec21** [comment]
Hello.
  

  
Yes it is now working.
  

  
Thank you.
  

  

  
  
Armand Crepeau
  

  

        
  
  
>
