### ISSUE TITLE
Patreon Download 

### ISSUE THREAD

**Issue by 3phac** [futo-org/grayjay-android#1429]
### Use Cases

I would like to request a possible feature. Since patreon begin to store the video inside the platform is not possible to download the videos. I am patreon for many producers and I wish to download some video what is no longer possible.
I would like to request the patreon video download option for grayjay.

Thanks 

### Proposal

I would like to request a possible feature. Since patreon begin to store the video inside the platform is not possible to download the videos. I am patreon for many producers and I wish to download some video what is no longer possible.
I would like to request the patreon video download option for grayjay.

Thanks

**Comment by 3phac** [comment]
What I mean is that patreon used to host the videos on YouTube, this is no longer the case and since they change the hosting is no longer possible to download new patreon videos

**Comment by 3phac** [comment]
Good evening.
I have tried it really does not work 
![Screenshot_2024-11-05-22-20-38-879_com futo platformplayer](https://github.com/user-attachments/assets/5358827e-e48a-43b4-8858-f02dd3c49efa)
![Screenshot_2024-11-05-22-17-40-157_com futo platformplayer](https://github.com/user-attachments/assets/976ca51d-099e-4850-aa73-c329dc684193)
![Screenshot_2024-11-05-22-17-35-180_com futo platformplayer](https://github.com/user-attachments/assets/46d99e59-16df-438f-8b08-97487a0b6ae8)
![Screenshot_2024-11-05-22-17-22-459_com futo platformplayer](https://github.com/user-attachments/assets/1e88be84-36df-44b6-a209-537c116fcbcc)

**Comment by kaidelorenzo** [comment]
Yes that looks exactly like the issue my fix will resolve. The plan is to include it in the next release of Grayjay. It's not an issue with the Patreon source so it will need to wait until the next Grayjay release.
