### ISSUE TITLE
Your app is fucking annoying It's just one stupid ass feature 😡🖕

### ISSUE THREAD

**Issue by ForJesusmygod** [futo-org/grayjay-android#1430]
### Use Cases

This app is goddamn shit. Will you stop fucking going down every time I'm trying to skip You're the fucking stupidest fucking app creator into goddamn universe. If you just make it to where I can fast forward without the fucking piece of slutty shit, playing another video, that'd be fucking amazing. But so far, you're a fucking idiot. This is pissing me off, you dumb bastard. Just let me fast forward without playing another fucking goddamn video, you stupid fucking PIG!

**Comment by Disbreez** [comment]
What a sad, sad person. Have your issues with the app but bugs don't make devs bad people. Totally unnecessary

**Comment by support-grayjay** [comment]
Closing this issue due to the inappropriate tone and manner in which it was opened.
