### ISSUE TITLE
No playlist header found

### ISSUE THREAD

**Issue by Blobfish90** [futo-org/grayjay-android#1433]
### What happened?

![Screenshot_20241021_164615_Grayjay](https://github.com/user-attachments/assets/43a523fa-2526-4e4c-bd5d-00f2b497c609)

No header found when trying to copy paste playlists from YouTube any tips to resolve this?

Thanks team!

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
Have you tried removing the saved playlist and copying over again. I have 3 playlists saved from YouTube as of the last 8 months and fven version 207 and 208 of YouTube plugin broke YouTube plqylists, the issue you're experiencing may have to do with the changes made to Playlist viewing according to Kelvin.

**Comment by Blobfish90** [comment]
Hi yes unsaved the playlist and shared it to grayjay still saying the same
thing....

**Comment by codebymatter** [comment]
Does the error message only appear when adding that one playlist or is it present when adding/saving any other YouTube playlist?

**Comment by Blobfish90** [comment]
It seems like the playlists that are already saved that ive had for a month
works but when I try to share new ones recently and copy them over from
YouTube to grayjay have been saying this error....its been any type of
playlist i tried to add, maybe 10 different playlists recently which been
saying the same error message but the older ones that been there for a
while work...weird.

**Comment by Zvonimir-FUTO** [comment]
Should be fixed in version 214. Feel free to reopen if you are still encountering this issue. Closing.
