### ISSUE TITLE
Youtube loading issue   Failed to load next  page plugin [Youtube] 500 2951(6-7)

### ISSUE THREAD

**Issue by i3130002** [futo-org/grayjay-android#1436]
### What happened?

While scrolling though the home feeds, user will reach a point that the Youtube feed beaks. 

![image](https://github.com/user-attachments/assets/c74306ae-01ce-45af-99ac-44ac7dd6d4f5)
![image](https://github.com/user-attachments/assets/9669323d-4582-4ae3-9184-0aa0fe73309a)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube, Odysee, Rumble, PeerTube

### Plugin Version

209

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
Couldn't figure-out how to export the error logs.
```

**Comment by Zvonimir-FUTO** [comment]
The bug should be fixed in the latest version of Youtube plugin.
