### ISSUE TITLE
Add "music.youtube.com" to the open by default selection list.

### ISSUE THREAD

**Issue by shininghero** [futo-org/grayjay-android#1442]
### Use Cases

I am attempting to use Grayjay fully hands-free, giving voice commands to the built-in assistant to open songs as desired.  This will allow me to keep my eyes on the road as I request songs to play.

### Proposal

The built-in Google Assistant responds to song inquiries with music.youtube.com URLs, which are currently not available in the Open by Default list of URLs.

Adding this URL would allow for much more hands-free use of Grayjay.

### References

- #1160  URL mentioned briefly in a comment.

**Comment by Zvonimir-FUTO** [comment]
This has been implemented in the upcoming release (v265).
