### ISSUE TITLE
Download Failed 

### ISSUE THREAD

**Issue by FlatEarthDisciple** [futo-org/grayjay-android#145]
Download Failed. Reason: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout

![Screenshot_20231101_070446_Grayjay](https://github.com/futo-org/grayjay-android/assets/131295842/d39e1b74-9762-4e55-926a-a271dade3401)

**Comment by JustCryen** [comment]
I'm not sure what's the source of your video but I've noticed that downloads only work for YT and not other sources. At least not for Odysee.

**Comment by FlatEarthDisciple** [comment]
Issues still persist with latest update. Regardless of connection, (WiFi, LTE), Java net exceptions occur. (Timeout, and Connection Reset).

I have not successfully downloaded any YouTube video.

**Comment by koen-futo** [comment]
> I'm not sure what's the source of your video but I've noticed that downloads only work for YT and not other sources. At least not for Odysee.

@JustCryen This has to do with lack of support for HLS downloads, it will be added at some point though. With regards to that specific video, we will investigate.

**Comment by neosurat** [comment]
This issue is not for specific video. It happens to almost all video download. Atleast it happens to me. 
![Uploading Screenshot_20231211-011908_Grayjay.jpg…]()

**Comment by koen-futo** [comment]
HLS download support has been added as of the new version.

**Comment by glitch-method** [comment]
i get this error whenever byterange concurrency is set above 2 threads.

**Comment by rui-costa** [comment]
> i get this error whenever byterange concurrency is set above 2 threads.

Your comment just saved me a lot of headache. Turned the threads to 1 and works without issues.

Maybe a suggestion to add that as a tip for the error in the downloads section "try reducing the download threads"

**Comment by FlatEarthDisciple** [comment]
GrayJay's development has advanced far beyond this issue. I now consider the issue resolved and closed.
