### ISSUE TITLE
altPages is impossible to use ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by FireNinja7365** [futo-org/grayjay-android#1454]
### Affected Pages

https://github.com/futo-org/futo-keyboard-layouts/blob/main/LayoutSpec.md

### What is the docs issue?

No matter how i make the syntax for a custom layout to edit the symbols pages it always gives errors or doesn't do anything, even giving the entire documentation a read through and giving an ai the documentation i still can't figure out how to edit the symbols page

**Comment by support-grayjay** [comment]
Please open an issue on FUTO Keyboard repo instead of Grayjay's.

https://github.com/futo-org/futo-keyboard-layouts/issues
