### ISSUE TITLE
Can't login to Kick and Spotify

### ISSUE THREAD

**Issue by obakha** [futo-org/grayjay-android#1457]
As for kick, when I click on the Sign In button, it switch to browser mode, and it just keeps showing an endless loop of the site loading.

And same for Spotify, but when the app switch to browser mode, then it just displays a blank dark screen with no text, no options to type email, and password.

**Comment by codebymatter** [comment]
I had an issue with Spotify plugin in version 2 where Spotify-related creator profiles will not load and read an error. It had happened woth any Spotify-specific crrator profile so I logged off completely osed the app. Opened it again, signed in and I was able to play Spotify content again.

If this doesn't work for you, try Re-Install to rollbacl to version 2 and sign in to your account. If you're able to play Spotify content, then update to larest version and if working still, you're good to go.

**Comment by obakha** [comment]
It's fixed, Thanks!

**Comment by garbb** [comment]
I had the same issue with logging in to kick and I had to update the chrome app on my phone and then it worked. I think grayjay is using chrome for the login process.

**Comment by kaidelorenzo** [comment]
Yeah i think updating chrome and the android system webview could definitely be important for login functioning reliably. i'll make an issue to consider if there is a way to detect out of date webviews and inform the user somehow
