### ISSUE TITLE
Playlists *Still* Do Not Load from Creators' Profile

### ISSUE THREAD

**Issue by Mathew-88** [futo-org/grayjay-android#1467]
### What happened?

Go to a creator or a channel; click playlist, gives blank space.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

209

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Hey I couldn't have reproduces this. Is the issue present for you for every channel and every playlist of specific ones?

Here, try opening playlists from TierZoo for example: https://www.youtube.com/@TierZoo

**Comment by Philippe-Choquette** [comment]
@Zvonimir-FUTO I have this issue on every channel I checked, including the one of TierZoo you referenced.

For context, I just installed installed Grayjay from the arm64-v8a APK on your website, which is the supported ABI of my SoC, and followed by activating my license, updating all plugins, and restarting the app. So this issue occurs on a brand new install.

**Comment by Zvonimir-FUTO** [comment]
Tried to reproduce it by being logged out but with no avail.

**Comment by Zvonimir-FUTO** [comment]
Unfortunately, you now only see the toast message so try to screenshot it or something so you can read the UUID.
We have a fix for this so it automatically copies the UUID to the clipboard and it will be released in next release (v265).

**Comment by Philippe-Choquette** [comment]
I've taken a screen recording to show you exactly what happens and how I've enabled logging. However, the logging doesn't seem to work as expected (see the toast message at the end).

You can see that this time, the playlists of most channels do load, with the exception of "Unbox Therapy". However, yesterday, shortly after I had installed Grayjay, both of the 2 channels I was subscribed to at the time couldn't load the playlists (hence why I jumped on this GitHub issue). Furthermore, during my attempts, there was always at least one instance where each of the channels' playlists didn't load. In other words it seems very random.

https://github.com/user-attachments/assets/b3532ac0-5322-4c14-a794-772c7c56606f

**Comment by jmcgaughey** [comment]
having same issue. that playlist above doesn't even load for me either. really no playlist except dailymotion (does load playlist) out of that and rumble (doesn't load pl), and youtube (doesn't load pl)

**Comment by Zvonimir-FUTO** [comment]
Hey everyone we just released a hotfix so this should be fixed in version 213 of Youtube plugin. Please update and report back.

**Comment by Mathew-88** [comment]
> Hey I couldn't have reproduces this. Is the issue present for you for every channel and every playlist of specific ones?
> 
> Here, try opening playlists from TierZoo for example: https://www.youtube.com/@TierZoo

Hello, I apologize for the very late reply. Yes, the issue is present for every channel, including the link that you provided me.

**Comment by jmcgaughey** [comment]
seems to have fixed the issue for me thank you.. from samsung a53 android 14

**Comment by Philippe-Choquette** [comment]
It also seems fixed for me, but I've experienced slow loading of playlists (with no UI element to indicate it) on at least one channel I tested

**Comment by Philippe-Choquette** [comment]
> Fixed for me too but not all playlists are loaded. Could it be linked to the number of playlists of the creator? Seems to happen when there are more than 29/30 playlists on creator's page.

I just checked and I can confirm this. It seems to cap playlists at 29.

**Comment by Zvonimir-FUTO** [comment]
@Mathew-88, @29axe & @Philippe-Choquette Pushed a fix in version 214 and now there is no limit. Thank you for your help. 

Closing the issue.
