### ISSUE TITLE
Twitch import subscriptions not working

### ISSUE THREAD

**Issue by nicola02nb** [futo-org/grayjay-android#1472]
### What happened?

It gives an error when clicking import subscriptions o  twitch plugin
![Screenshot_20241112_094406_Grayjay](https://github.com/user-attachments/assets/49491dd8-8c6d-4438-968f-2137a9d1c3a0)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Twitch

### Plugin Version

18

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Can you try logout and login back in then try again?

**Comment by nicola02nb** [comment]
Yep, fixed with it...

**Comment by Zvonimir-FUTO** [comment]
Great! Closing the issue.
