### ISSUE TITLE
Rumble videos description cut off.

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#1474]
Video link https://rumble.com/v5o7m1q-dc-swamp-declares-war-on-trump-in-senate-battle-to-replace-mitch-mcconnell-.html

Rumble, videos, description is cut off on grayjay

> "JOIN The Benny Brigade: https://www.bennyjohnson.com/brigade Check Out Our Partners: Hillsdale: Go to https://www.hillsdale.edu/benny to enroll in FREE Courses American Financing: Save with http://www"

**Comment by kaidelorenzo** [comment]
Version 46 loads the entire description
