### ISSUE TITLE
Spotify monopolizes playlist search results / Playlists completely unusable

### ISSUE THREAD

**Issue by portablevampire** [futo-org/grayjay-android#1477]
### What happened?

Lately when searching playlists, I find that very frequently 100% of the results are spotify, even when previous searches of the same term have also yielded results from other sources. (Youtube, Soundcloud, etc) When this happens, disabling Spotify as a source just makes the results empty. The only fix seems to be force closing the app and restarting it. This fix is only temporary, though, as searching the same term later has a high likelihood of yielding only spotify results again.
Pictured: Playlist results for the term "doobie brothers minute by minute full album" 
![Screenshot_20241113_041047_Grayjay](https://github.com/user-attachments/assets/300a302c-a6d5-4af9-af4e-5dd5a13ba2af)

Pictured: Playlist results for the same search term after disabling Spotify plugin
![Screenshot_20241113_041118_Grayjay](https://github.com/user-attachments/assets/ea77d6e4-a198-4739-b282-e92ea7580f42)

Pictured: Playlist results for the same search term after force closing and restarting the app (from android settings)
![Screenshot_20241113_041150_Grayjay](https://github.com/user-attachments/assets/cb2a5c5b-e857-48bd-beaf-a705f56ce312)

### Grayjay Version

264

### What plugins are you seeing the problem on?

All, Other

### Plugin Version

4

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Couldn't reproduce this.

**Comment by portablevampire** [comment]
If it helps, I'm using a Samsung Galaxy S20 FE 5G (SM-G781U) running Android 13.

**Comment by portablevampire** [comment]
Accidentally closed this while attempting to make a comment with additional info, sorry.

If it helps, I'm using a Samsung Galaxy S20 FE 5G (SM-G781U) running Android 13.

**Comment by portablevampire** [comment]
Currently attempting to find playlists for The Cranberries album "No Need to Argue" and am facing this issue again no matter how many times I force quit and restart. In addition, I'm also getting the following error when Spotify is enabled:
![Screenshot_20241116_003221_Grayjay](https://github.com/user-attachments/assets/269d8370-5ad3-41cb-b57c-c190edca1631)

**Comment by portablevampire** [comment]
Still unable to access any non-spotify playlists, but the search isn't giving me an error anymore... however I have a new problem in that if I try to play ANY spotify tracks (from within a playlist or otherwise) it will be completely silent. no sound will play whatsoever. Spotify is the only plugin that seems to have this issue.

Starting to suspect the spotify plugin just really hates me, specifically, and wants to make listening to full albums as difficult and annoying as possible for me

**Comment by portablevampire** [comment]
The spotify plugin is fully up to date, by the way. Version 5 at the moment

**Comment by portablevampire** [comment]
Now version 6 and still plagued by the same issues, no change.

Would greatly appreciate some indication that this is being looked into at all.

**Comment by portablevampire** [comment]
Uninstalled and reinstalled the app entirely, which seems to have fixed the issue of spotify being silent. I still can't access playlists from literally any other source, but at least I have *some* playlists. Whatever. That said, it's created a new problem, which I'm sure you're all excited to hear about!

The new problem is as such: if I am listening to a spotify playlist or track, sometimes the music will randomly decide to pause. No big deal, just unpause it right? Wrong! If I unpause it, unless I go to the extra trouble of opening up the app (as opposed to unpausing it from the lockscreen/notification bar) the music source will switch from Grayjay over to the official spotify app (which I still have installed because there are precious few functions in the spotify app that do not exist within Grayjay, which I very occasionally need.) and this is very annoying for two reasons: 1) for some reason, the quality within the official spotify app is worse. and 2) when the track finishes, it will play random recommended music (which is exactly why I prefer to use grayjay over the official spotify app, because I hate that.)

**Comment by Zvonimir-FUTO** [comment]
This was amusing read ^^
Let's try to keep one issue per bug you found. As I understood Spotify monopolizing playlist search results is resolved?

Please open new issues for new bugs.

**Comment by portablevampire** [comment]
Will do in the future, wasn't sure if doing so would be annoying or clog up the issues (given how many I was having)

The issue seems to be fixed now though I think, for now at least. I feel like I'm going to jinx it by saying that... I'm once again getting Youtube results in playlist searches, anyway. Have yet to see Soundcloud, but it might be that I'm not searching for things that would yield Soundcloud playlists. I rarely use soundcloud for anything anyway. I'll keep an eye out...

If the issues with Spotify pausing etc come back, I'll start a new issue.
