### ISSUE TITLE
Holy shit grayjay's youtube video that i just watched a few days ago has removed from youtube

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#148]

**Comment by candroid-man** [comment]
Yeah, it's terrible, but this isn't the place to talk about it lol please close this

**Comment by HafizBeyy** [comment]
> Yeah, it's terrible, but this isn't the place to talk about it lol please close this

Just looking for somewhere to discuss abt that. If you can provide a source for that reason you can ensure Ima immediately close this one
