### ISSUE TITLE
Cannot import playlist to Spotify - Error converting playlist

### ISSUE THREAD

**Issue by PickMeNow** [futo-org/grayjay-android#1481]
### What happened?

Clicked to convert or import Spotify playlist, end up with always the same error.

Failed to convert Playlist
Screenshot:

![Screenshot_20241114-062408](https://github.com/user-attachments/assets/ab1836d0-3518-4a2e-bd9f-6a9e7e19e44e)

After the error need to restart the app. 

### Grayjay Version

264

### What plugins are you seeing the problem on?

Other

### Plugin Version

4

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
Yes this is a known issue ever wince the plugin became accessible. You are unable to Import playlists from Spotify to Grayjay, but you can search for your playlists and copy them to your Playlists collection.

You will see some of your playlists /apbums recently plqyed in [Home] tab. Aa for searching your playlists, you can either play your playlist from Spotify and wait a few minutes to see it on [Home] tab or search the playlist!(s) by title in [Playlist] tab. It is quite annoying to search for your playlists at least for now, but I have been able to find all of my privated playlists.

**Comment by PickMeNow** [comment]
I can find them, but once I try to play a song it tells me I need to convert, and the error shows up. For the other playlists I was able to add them, just this specific one, I am having this issue, either by importing the playlist or accessing on playlist on the "home" tab. Tried also sharing the playlist to the app and I get another issue. In attachment

**Comment by PickMeNow** [comment]
Strange was able to fix by doing a clone of the playlist inside Spotify, hope this helps other users which are experiencing the same problem
