### ISSUE TITLE
Constant Video Buffering

### ISSUE THREAD

**Issue by Kofigox** [futo-org/grayjay-android#1485]
### What is the docs issue?

As of recently any YouTube video I've watched on grayjay that's longer than 5 minutes has had buffering issues even though my internet is not slow.
The video takes a few seconds to load but after playing for around 5 to 7 minutes, it starts to buffer.
I tested the normal YouTube app and even Revanced and they both don't have an issue loading videos even at 1440p for Revanced. This issue is not resolved when I lower the video quality to 720p and seems to worsen when I'm watching a stream. It also seems to affect the speed of downloads which was really good at first but is now unreliable. Not sure what the issue could be but I did see someone with a similar problem around 4 months ago but back then it did not affect me.

Grayjay Version
264
YouTube Version
213 

### References

- #1164

**Comment by Zvonimir-FUTO** [comment]
Could you please provide the version of Youtube and Grayjay?

**Comment by Kofigox** [comment]
> Could you please provide the version of Youtube and Grayjay?

Grayjay Version
264
YouTube Version
213

**Comment by Zvonimir-FUTO** [comment]
Couldn't reproduce this, this one might be a hard one to replicate.

**Comment by Kofigox** [comment]
What do you suppose the issue could be?

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Zvonimir-FUTO** [comment]
Not sure, will have to investigate more during the working hours.

**Comment by Kofigox** [comment]
Okay. I greatly appreciate your quick response.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Zvonimir-FUTO** [comment]
Could you try enabling "Force Experimental UMP Streams" in Youtube plugin settings and see if it changes anything or it stays the same? If it stays the same then it's the issue with UMP streams but that could be hard to troubleshoot so will take time.

**Comment by Zvonimir-FUTO** [comment]
It appears Youtube is starting to throttle iOS streams for some users luckily we worked on UMP in advance.
