### ISSUE TITLE
Only notify for relevant plugin updates

### ISSUE THREAD

**Issue by lu4p** [futo-org/grayjay-android#1487]
### What happened?

There's a constant nagging about installing updates for plugins I've never even enabled.

![Screenshot_20241116_233214_Grayjay](https://github.com/user-attachments/assets/9855acd7-be45-40c5-acde-aaa108404e5b)

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
You can disable plugim updates to check and apply automatically by going to the Plugin settings of each plugin and Turn both settings off.

I had done that 2 months ago and I hqve not seen update notifs for the othet plugins other than the ons that I use.

**Comment by Zvonimir-FUTO** [comment]
> You can disable plugim updates to check and apply automatically by going to the Plugin settings of each plugin and Turn both settings off.
