### ISSUE TITLE
Prevent accidental closure of the comments editor

### ISSUE THREAD

**Issue by Philippe-Choquette** [futo-org/grayjay-android#1497]
### Use Cases

If you accidentally tap the space around the floating comments editor window, the window is dismissed and the comment you were in the process of writing is lost. This is most likely to occur when you are reaching the top of your keyboard.

### Proposal

- Prevent the comments editor window from being dismissed when tapping the space around it
- Add a confirmation dialog (Discard/Stay) to the "Cancel" button

If the former point can't be implemented, the confirmation dialog should be implemented for any situation where the window is dismissed. Alternatively, comments could be saved as draft so that they reappear when the comment editor is reopened.

**Comment by Zvonimir-FUTO** [comment]
Will be resolved through #439.
