### ISSUE TITLE
Failed to load playlist plugin [Youtube] 

### ISSUE THREAD

**Issue by pocokmocok** [futo-org/grayjay-android#1501]
### What happened?

I tried to open a playlist from a link. 
Also can't search for playlists or import them. 
![Screenshot_20241121-150340_Grayjay~2](https://github.com/user-attachments/assets/383b54f2-9f16-4cee-b9cc-960935cd219a)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

214

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Knolka** [comment]
For me, I can access previously downloaded playlists thru the YT plugin but I am unable to search new existing playlists via the plugin. It just spins and shows blank results. Ever since yesterday but i haven't tried in a while so dunno how long its been buggy.

**Comment by pocokmocok** [comment]
> I couldn't reproduce the issue, could you provide a link you are trying to open?

It happens with every playlist. I click on share then Grayjay and then I get that error. Also copying the link to the grayjay search doesn't work either. It gives a blank result page, just like when I search for playlists.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the latest version of Youtube. Thank you guys for reporting.
