### ISSUE TITLE
[Spotify] Home page tracks not showing + unable to import both subscriptions and playlists

### ISSUE THREAD

**Issue by NotSoNitro** [futo-org/grayjay-android#1502]
### What happened?

Getting these errors each time, tried relogging, disabling and re-enabling, nothing seems to be working

![Screenshot_20241121-204228](https://github.com/user-attachments/assets/66d64fac-fe24-4144-86f3-78ef8de51f6f)
![Screenshot_20241121-204232](https://github.com/user-attachments/assets/eaac1ca9-ccb6-49e8-864e-459767d0793f)
![Screenshot_20241121-204236](https://github.com/user-attachments/assets/cdcf2bac-c855-4d58-bebc-0edac273f434)

### Grayjay Version

264

### What plugins are you seeing the problem on?

Other

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by kaidelorenzo** [comment]
Version 9 has a fix for the home page issue and additional exception logging to help with the first two. Could you send some updated exception messages?

**Comment by NotSoNitro** [comment]
@kaidelorenzo here are the updated exceptions

![Screenshot_20241126-151907.png](https://github.com/user-attachments/assets/f0c71954-f2d5-411a-8452-6fc4901603b2)

![Screenshot_20241126-151911.png](https://github.com/user-attachments/assets/1c2645c9-32a7-4c22-9526-385802ffe81a)

**Comment by kaidelorenzo** [comment]
version 10 should fix those errors. let me know if the fix uncovered something new

**Comment by NotSoNitro** [comment]
Seems like everything is working, if anything new does come up I'll make another issue report.
