### ISSUE TITLE
Error for subscribed youtube channel that does not exist

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#1503]
Grayjay error on youtube channele I'm subscribe to channele that does not exist
https://m.youtube.com/channel/UCEzKnQU3lDZnI3NyXRTLEeg
Null cannot be casted to non-null type kotlin. string 

https://m.youtube.com/channel/UCEzKnQU3lDZnI3NyXRTLEeg Youtube Shows "This channel does not exist"

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the latest version of Youtube. Now the error now gives appropriate message. Thank you for reporting.
