### ISSUE TITLE
HTML Lttercode Rendering Error in Video List

### ISSUE THREAD

**Issue by The-jes** [futo-org/grayjay-android#151]
In the Video list the channel name "&" symbol isn't  replaced, see screenshot
![signal-2023-11-01-210503_002](https://github.com/futo-org/grayjay-android/assets/91591803/6711d0e6-644a-4722-9ce9-f99a04020684)

**Comment by The-jes** [comment]
Version Code 181
Version Type release

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
