### ISSUE TITLE
Unorganized Playlist!

### ISSUE THREAD

**Issue by haenjes-hmansor** [futo-org/grayjay-android#1511]
### Use Cases

No Playlist in the application has any type of sorting mechanism. It would be very helpful to have sorting options based on download date (in the download list for example) or even alphabetical. Currently you would have to scroll down all the way to the bottom to reach the last video because there is no option to sort videos descending instead of the standard ascending. Watch later is sorted based on the date the video is added but it's very annoying trying to scroll all the way to the bottom. The downloaded videos list doesn't seem to have any type of sorting.

### Proposal

Add a button "sort by" each time a playlist is open. In the watch later it would be very useful to be able to sort it based on the time video was added but inverted. (First video added the first to appear). Watch later lists are usually packed and its very annoying to keep scrolling down. 

Note that if there isn't available data in the database to sort based on dates, the ability to switch between ascending and descending would make a huge difference. Even a "search in playlist" option would be better than the current situation but not ideal of course because you don't always know the contents of a playlist.

**Comment by Zvonimir-FUTO** [comment]
Will be resolved through #78.
