### ISSUE TITLE
Not able to download videos any longer with latest version grayjay app

### ISSUE THREAD

**Issue by chag2020** [futo-org/grayjay-android#1512]
### What happened?

I recently downloaded the latest version of Grayjay from the Playstore.  Now I can't download videos any longer from the source Youtube.  The 'Download' icon is replaced with the 'Page' Icon.  I have a Samsung Galaxy S10e.  Any suggestions on how to bring the download feature back?  I have the following plugins:  Youtube, Rumble and Odysee.  I don't have the issue with Rumble or Odysee.

### Grayjay Version

264-1-g3a41b89

### What plugins are you seeing the problem on?

All, Youtube

### Plugin Version

215

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
This is expected since Google removed us from Playstore for those features so we had to remove them for Youtube plugin. We prefer side-loading the apk you can download from here: https://grayjay.app/#download

Or install through F-Droid.
