### ISSUE TITLE
Soundcloud could not find channel info error. / subscribe 

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#1519]
Soundcloud could not find channel info error. Can't subscribe either from clicking on channel from video. From https://m.soundcloud.com/reddxy

**Comment by TheDeviantCrafter** [comment]
I've been unable to subscribe to any creator on SoundCloud. No error message, the button just shows a loading icon for a second and then goes back to a blue subscribe button as if nothing happens.
