### ISSUE TITLE
Can't find any way to import my existing YouTube subscriptions

### ISSUE THREAD

**Issue by placidcasual98** [futo-org/grayjay-android#152]
Can't find any way to import my existing YouTube subscriptions without having to manually do it would be a great for an automatic way.
The app on a pixel phone will not let me import my YouTube subscription.cvs file

**Comment by Repa1253** [comment]
Are you logged in to your YouTube account in the app? It should give you the option to import subscriptions once you're logged in.

**Comment by placidcasual98** [comment]
Okay so I click on sources and then the YouTube bit it takes me to a YouTube page to log me in. I go through the procedure my email and password and then it just opens up a YouTube page in the app. Then I can go back and then it doesn't give me an option to import anything. When would it give me the option or is there a button somewhere that I can do it?

**Comment by Repa1253** [comment]
If the login was successful, then you should get a logout button and underneath the options to import playlists and subscriptions.

**Comment by shlok-007** [comment]
I am having the same issue as @placidcasual98 . The import subscriptions option is actually shown after I sign out of YouTube, after which the import subscriptions doesn't work for obvious reasons.

**Comment by andrewbissel** [comment]
+1 the login isn't getting captured by the app. Just opening the web version of YouTube. 

It erroneously shows the signed in state if you sign out from the embedded browser.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
