### ISSUE TITLE
remove tracking string on odysee videos when shareing.

### ISSUE THREAD

**Issue by wiwrut** [futo-org/grayjay-android#1521]
### Use Cases

please remove the tracking part of the url when sharing link for better privacy.
this is repodosable with any video on  odysee using grayjay.

### Proposal

on odysee website  i get https://odysee.com/@teksyndicate:5/pc-build-minisforum-bd790i-ryzen-9,-64gb:5
on gray jay when i share i get https://odysee.com/@teksyndicate:5/pc-build-minisforum-bd790i-ryzen-9,-64gb#5 string
please remove the tracking part of the url. 

### References

https://odysee.com/@teksyndicate:5/pc-build-minisforum-bd790i-ryzen-9,-64gb:5
https://odysee.com/@teksyndicate:5/pc-build-minisforum-bd790i-ryzen-9,-64gb#5 string
string has numbers a letters and no space i did not want to share the full link i hope that's OK thanks for this amazing project devs.

**Comment by kaidelorenzo** [comment]
Version 42 has changed the share URL to match the Odysee format which doesn't have the "#". 

Do note that the string after the "#" is not related to tracking. It is in fact the id of the video.
