### ISSUE TITLE
Subscriptions page empty

### ISSUE THREAD

**Issue by Noisy-Koi** [futo-org/grayjay-android#1523]
### What happened?

For the last few weeks my subscriptions pagr has just been empty regardless of how many times i refresh, restart, update, update sources, restart my device, use different internet sources, etc.
Home works fine, downloads works fine, history and everything works fine but the subscriptions page just has nothing, no videos load at all but it does show the channels that I am subscribed to.

### Grayjay Version

264

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Sorry to hear that, could you tell me which plugins you have enabled and could you please under Creators tab that you have subscribed to them? 

Grayjay doesn't use your plugin account subscriptions but has them saved locally and checks for the new videos from creators you follow.

**Comment by Noisy-Koi** [comment]
> Sorry to hear that, could you tell me which plugins you have enabled and could you please under Creators tab that you have subscribed to them?
> 
> Grayjay doesn't use your plugin account subscriptions but has them saved locally and checks for the new videos from creators you follow.
Does any of this help?

![Screenshot_20241128_094619_Grayjay](https://github.com/user-attachments/assets/fbc654d3-fa25-43e4-bb65-fb8d71e2d3fa)
![Screenshot_20241128_094547_Grayjay](https://github.com/user-attachments/assets/0fac4eae-e798-4c59-9310-1487c9881ab4)
![Screenshot_20241128_094841_Grayjay](https://github.com/user-attachments/assets/7c8e0505-96bc-4478-8e67-dc6ef134681b)

**Comment by Zvonimir-FUTO** [comment]
It appears you have _unselected_ **Videos** pill on subscription page which will filter out all videos. Could you try click in on it again to activate and check again?

**Comment by Noisy-Koi** [comment]
> It appears you have _unselected_ **Videos** pill on subscription page which will filter out all videos. Could you try click in on it again to activate and check again?
>
Ah yup, that was it, not sure when i pressed that, ty

**Comment by Noisy-Koi** [comment]
Closed
