### ISSUE TITLE
No message about scheduled odyssey videos.

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#1527]
I tried to play https://odysee.com/@switchedtolinux:0/illegal-smart-tech:6 and the video shows up as a black video no indicator the video is not available yet. 

scheduled odyssey videos should show a message like this. "Live in 6 hours
November 29, 2024 5:00 PM" I think YouTube plugin dose this already.

**Comment by kaidelorenzo** [comment]
I'm having trouble finding an example scheduled video to test against. Do you know of any currently scheduled videos I can look at?

**Comment by kaidelorenzo** [comment]
Version 42 should properly handle scheduled videos
