### ISSUE TITLE
Clear button on creator search

### ISSUE THREAD

**Issue by woodnt** [futo-org/grayjay-android#1539]
### Use Cases

On the Creator tab, there is a search text input. It would be helpful to implement at X icon that clears the text that had been entered. Currently, the text input must be selected, make sure the cursor is at the end, then delete back, or select all then cut. Be very nice to have another way. 
![Screenshot_20241130_145008_Grayjay](https://github.com/user-attachments/assets/dd95799a-01a3-45d0-8474-694a049be67b)

**Comment by Zvonimir-FUTO** [comment]
This has been implemented in v276.
