### ISSUE TITLE
Replace Email with Github Link

### ISSUE THREAD

**Issue by zellchristensen** [futo-org/grayjay-android#154]
There's an embedded notice about the test version of the app asking users to send an email. I was typing up an email but decided to look for an actual bug tracker and found it in the settings menu. It's probably better to replace that notification with a link to this Github instead.

![Screenshot_20231102-053728_Grayjay](https://github.com/futo-org/grayjay-android/assets/38737447/e216d6a0-381c-4c04-bd8d-d81f064ec55a)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay since we left the test version.
