### ISSUE TITLE
Still failing to load playlist plugin [Youtube]

### ISSUE THREAD

**Issue by Arien02** [futo-org/grayjay-android#1540]
### What happened?

Hi!
The problem reported in issue #1501 is still failing.
Tried in my Xiaomi 14, Grayjay v264 with Youtube plugin up to date (v217), and when opening link same error (https://www.youtube.com/playlist?list=UUhojFzThpgObGHmdMS1rpvA).

![photo_2024-12-01_18-11-02](https://github.com/user-attachments/assets/bc099e06-a477-4be1-b834-6fbd541a67c5)

Something is still wrong anywhere, do you need any other info regarding this issue?
Best regards.

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

217

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in upcoming version of Grayjay. Stay tuned :)

**Comment by Zvonimir-FUTO** [comment]
Fix has been released. Closing issue.
