### ISSUE TITLE
Headphone controle

### ISSUE THREAD

**Issue by dcshorts26** [futo-org/grayjay-android#1548]
### What happened?

I can't play/pause videos with my headphones on my z fold 6. Headphones are galaxy buds 3 pro. Controls work fine on my tab s6 just fine. Tried different versions of grayjay. Can someone help?

### Grayjay Version

242

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

12

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
This will be resolved through #685.

**Comment by dcshorts26** [comment]
I tried that. Still doesn't work

**Comment by Zvonimir-FUTO** [comment]
> I tried that. Still doesn't work

It was not trying to hint you to try anything. I just meant that the bug will be resolved through that ticket so we keep all discussion in same ticket.

**Comment by dcshorts26** [comment]
Found the issue. I had a favorite media control app in the sound assistant app (Good Lock).
