### ISSUE TITLE
[Feature Request] Background Updating

### ISSUE THREAD

**Issue by zellchristensen** [futo-org/grayjay-android#155]
When the app finds new updates, the update progress section prevents the user from using the app.  This progress would probably be better if it happened in the background with a notification that shows the progress or some other method of not locking out the user from using the app in the mean time.

**Comment by Zvonimir-FUTO** [comment]
This will be resolved through #7.

**Comment by support-grayjay** [comment]
This has been implemented. There is now option in settings called "Background download" under "Auto Update".
Setting is disabled by default.
