### ISSUE TITLE
Landscape mode oriented only to one side. 

### ISSUE THREAD

**Issue by benben42** [futo-org/grayjay-android#1554]
### What happened?

After upgrade opening video to landscape (full screen) is oriented only to one side if I flip phone video is upside down. Just like on iPhone

Also auto rotation is too sensitive , where the fine tuning went?

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by edo9300** [comment]
I have the same issue as well, it seems that the same issue as from September is back again https://github.com/futo-org/grayjay-android/issues/1301#issuecomment-2335126036

**Comment by Rocket-PropelledWeeb** [comment]
I have the same issue with landscape locking to one direction, but the auto rotation is the correct amount of sensitive for me. 
Oneplus 7 Pro, Android 11

**Comment by venthewolf** [comment]
Can confirm this bug.

(Oneplus 9 pro, Autorotation disabled)

**Comment by SdoggaMan** [comment]
My comment here is applicable to this (and I think part of the same bug) https://github.com/futo-org/grayjay-android/issues/1572#issuecomment-2533268252

**Comment by edo9300** [comment]
I tried the latest build, 276, that says in the changelog to have fixed this behavior, but the video still doesn't rotate when in fullscreen

**Comment by Zvonimir-FUTO** [comment]
> I tried the latest build, 276, that says in the changelog to have fixed this behavior, but the video still doesn't rotate when in fullscreen

Can you check is the "Always allow reverse landscape auto-rotate" enabled in settings?

**Comment by edo9300** [comment]
I checked and it is enabled, I noticed that if while in fullscreen I enable the rotation lock button on the top, and disable it again so it is white again, the video will auto rotate so long as it remains fullscreen

**Comment by Zvonimir-FUTO** [comment]
We apologies for inconvenience, we will release another build next week which will hopefully be the last nail in the coffin. In the meantime you can use system rotation as a workaround.

**Comment by edo9300** [comment]
@Zvonimir-FUTO tested on the latest version and it's now working fine
