### ISSUE TITLE
YouTube error, fails to load video. 

### ISSUE THREAD

**Issue by CamoWolf1222** [futo-org/grayjay-android#1556]
### What happened?

I attempted to watch a video, and I got this error:
![Screenshot_20241205_180158_Grayjay](https://github.com/user-attachments/assets/ebc73aff-db56-4f92-94fb-b8815e010d30)
[Youtube] Failed to get Cipher due to: Error: Failed to find n decryptor (code) /s/player/3bb1f723/player_ias.vflset/ en_US/base.js (5630)[2-3] [Youtube] Failed to get Cipher due to: Error: Failed to find n decryptor (code) /s/player/3bb1f723/player_ias.vflset/en_US/ base.js (5630)[2-3] 
source.getContentDetails(...) 

I have seen this on another error: #1146, which was labeled as a duplicate of #1026. This specific error was not mentioned in #1026. 

Edit: attemping to load anything (subscriptions,  search results, comments) has also been slow today. 

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

217

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Does this happen for all videos or specific ones? If it's specific to a video, could you link it?

**Comment by Shakool** [comment]
Experiencing the same issue. All videos I tried get me the error message since about 2-3hours

Updated to the latest version, tried login out and in again without results

**Comment by Zvonimir-FUTO** [comment]
We are looking into this. Thank you for reporting.

**Comment by CamoWolf1222** [comment]
> Does this happen for all videos or specific ones? If it's specific to a video, could you link it?

At the time it was all videos, but after letting one video load for about 5 minutes or so, it showed the error. I cannot verify this anymore, because everything seems to load perfectly fine now. Even the slow times for search results and subscriptions are back to normal.

**Comment by CamoWolf1222** [comment]
A new problem has showed itself. Around the 0:59 mark on videos, it pauses and refuses to play again. Video in question: https://www.youtube.com/watch?v=MSVf9EM5Nn4

**Comment by Zvonimir-FUTO** [comment]
This should be fixed in version 218 of Youtube plugin. Please test and report if you encounter any issues.

**Comment by CamoWolf1222** [comment]
It seems to be fixed, closing the issue now.
