### ISSUE TITLE
UI List very narrow, Cannot read title

### ISSUE THREAD

**Issue by yant0** [futo-org/grayjay-android#1558]
### What happened?

![Screenshot_20241206-083015](https://github.com/user-attachments/assets/dd9debab-5594-46bc-a195-54037f0d54ab)

Changes the ui after updating to the latest versiom

### Grayjay Version

268

### What plugins are you seeing the problem on?

Other

### Plugin Version

-

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by kaidelorenzo** [comment]
Could you share your device please? Specifically the display details is what would be helpful.

**Comment by and4ny** [comment]
hi, experiencing the same bug after the latest update. My device is the Unihertz Titan Pocket, 3.1 inch display, 716x720 resolution

**Comment by that404nerd** [comment]
I guess a simple fix would be to check if the mode is portrait or landscape and then just change the view from a simple list like in the previous versions or the new ui if in landscape mode.

**Comment by and4ny** [comment]
app is always in portrait mode, and changing from list to preview does make the titles slightly more readable, but can'tt get to to go back to the list view as before. If I click on a specific channel, I get the original list view for that channel's videos with 1 video per row

**Comment by kaidelorenzo** [comment]
I was able to replicate the issue. @and4ny does this look similar to your device?

![image](https://github.com/user-attachments/assets/54f89c0d-d839-43a4-96ba-07317b9ebca8)

**Comment by kaidelorenzo** [comment]
Ok the incorrect calculation should be fixed with this merge request

https://gitlab.futo.org/videostreaming/grayjay/-/merge_requests/54

**Comment by and4ny** [comment]
@kaidelorenzo yes, looks exactly like that

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.
