### ISSUE TITLE
YouTube videos only playing first minute

### ISSUE THREAD

**Issue by MrGrenadeMcBoom** [futo-org/grayjay-android#1559]
### What happened?

Youtube videos are only playing for the first 59 seconds and then will not load any further video. Issue is repeatable from playlists and from selecting in subscriptions or on the home screen. Issue is not seen on rumble videos. 

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Could you try and go to Youtube plugin settings and try enabling "Force Experimental UMP Streams" and see if that helps?

**Comment by MrGrenadeMcBoom** [comment]
Issue resolved when I moved to a different Wi-Fi network. Not sure what happened as Rumble videos were playing fine but not YT videos. 
    On Friday, December 6, 2024 at 04:33:59 PM GMT+9, Zvonimir-FUTO ***@***.***> wrote:  
 
 


Could you try and go to Youtube plugin settings and try enabling "Force Experimental UMP Streams" and see if that helps?

**Comment by Zvonimir-FUTO** [comment]
It's still hard to discern what caused the issue if Youtube was throttling your playback or not but in future if you encounter the same issue please try forcing experimental UMP streams and check if it helps and reopen the issue or open a new one.

In the mean time closing the issue.

**Comment by CamoWolf1222** [comment]
This still happens intermittently, but most of time a simple reload fixes the issue.

**Comment by itsonlyaudio** [comment]
Happens to me too. When I play the same video in Freetube, it says IP block or deciphering failed, which is consistent with [MrGrenadeMcBoom](https://github.com/MrGrenadeMcBoom)'s observation that moving to a different wifi helps.

**Comment by itsonlyaudio** [comment]
It's most definitely an IP block. Hopping on a VPN fixed it.
