### ISSUE TITLE
Some Odysee videos won't play 

### ISSUE THREAD

**Issue by b-risk** [futo-org/grayjay-android#1560]
### What happened?

I noticed that some new videos on Odysee will redirect to a random unrelated one and error, started happening after a recent plugin update.

### Grayjay Version

268

### What plugins are you seeing the problem on?

Odysee

### Plugin Version

42

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
Failed to get Playback Tracker

[Odysee] Cannot read properties of undefined (reading 'duration') (393)(53-54)

Source.getPlaybackTracker(...)
```

**Comment by Zvonimir-FUTO** [comment]
Could you provide a video on which the bug occurs?

**Comment by b-risk** [comment]
> Could you provide a video on which the bug occurs?

Apologizes I think when I switched apps it refreshed my page and removed my links:
https://odysee.com/@samtime:1/so…-australia-just-banned-kids-from:1
https://odysee.com/@AlphaNerd:8/chinese-hackers-infiltrated-us-telecom:7

**Comment by kaidelorenzo** [comment]
Version 43 should fix the issue

**Comment by b-risk** [comment]
Thanks! The new update fixed it.
