### ISSUE TITLE
overlay behavior change between 262 and 268

### ISSUE THREAD

**Issue by winneratwin** [futo-org/grayjay-android#1561]
### What happened?

When opening the overlay for a video via button or going home, grayjay goes into fullscreen/landscape mode for the miniplayer now. So when you return to the app it is fullscreen instead of portrait mode from which you enter the overlay leading to annoyance un-fullscreening the video. Seems like it might be related to the landscape support the update added.

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by kaidelorenzo** [comment]
should be fixed by this merge request
https://gitlab.futo.org/videostreaming/grayjay/-/merge_requests/55

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.

**Comment by winneratwin** [comment]
No this has not been fixed in v276.
https://github.com/user-attachments/assets/44e2cac9-c3fd-4b51-a044-24fe99abf2e2

**Comment by Zvonimir-FUTO** [comment]
We apologies for inconvenience, we will release another build next week which will hopefully be the last nail in the coffin. In the meantime you can use system rotation as a workaround.

**Comment by kaidelorenzo** [comment]
Take 2 the most recent release should fix this
