### ISSUE TITLE
unable to see rumble channel name. 

### ISSUE THREAD

**Issue by Starduck536** [futo-org/grayjay-android#1562]
### What happened?

I'm unable to see the channel name. There seems to be no banner for this channel. I'm guessing that might be part of the issue.https://rumble.com/user/RedPillPolitics & https://rumble.com/user/ModderPaulScambaits
￼
![Screenshot_2024-12-05_23-03-37](https://github.com/user-attachments/assets/c53884e9-0af5-42c8-a31e-94e1cb6bc852)

### Grayjay Version

268

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

47

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by codebymatter** [comment]
I created a Rumble for content creation and my channel also appears as blank name. Surely, it's something to do with Rumble and not Grayjay and plugin. Least I now know. Thank you for sharing.

**Comment by kaidelorenzo** [comment]
Version 48 should fix this
