### ISSUE TITLE
Rumble, profile picture and banner are not showing.

### ISSUE THREAD

**Issue by Starduck536** [futo-org/grayjay-android#1564]
### What happened?

Rumble, profile picture banner  are not showing up for a specific user.

https://rumble.com/user/ModderPaulScambaits
![Screenshot_2024-12-05_23-18-41](https://github.com/user-attachments/assets/0169171a-2c38-41ef-948b-3d0a75bc654c)

### Grayjay Version

268

### What plugins are you seeing the problem on?

Rumble

### Plugin Version

47

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Starduck536** [comment]
@Zvonimir-FUTO I Apologize for the duplicate issue. Just wanted to point out that I edited the Issue you left open. to include the second link in this post. As the second link has multiple issues with the first one, just had the channel name not visible. Not sure if it makes a difference, just wanted to clarify. Thanks for your time.

**Comment by Zvonimir-FUTO** [comment]
It helps. Thank you for taking the time, we will look into it.

**Comment by Starduck536** [comment]
Can this please be reopened to fix the Profile, picture, and banner? @Zvonimir-FUTO I renamed it and edited the original post so that it's no longer a duplicate And two of the three issues are still present. Thanks.

**Comment by kaidelorenzo** [comment]
Is this not fixed for version 48 based off this issue?

https://github.com/futo-org/grayjay-android/issues/1562

As far as I can tell https://rumble.com/user/ModderPaulScambaits doesn't have a banner nor profile picture

**Comment by Starduck536** [comment]
The channel name shows up I thought the the Channel above had a profile picture and banner I guess not most have been another channel I was looking at my bad. If I find it later on I will let you know feel free to close this. Thanks and have a good rest of your day.
