### ISSUE TITLE
Refreshing subscriptions keeps erroring about a channel I'm not subscribed to anymore

### ISSUE THREAD

**Issue by TangentFoxy** [futo-org/grayjay-android#1565]
### What happened?

1. I refreshed my subscriptions. One of the channels was deleted "for violating our Community Guidelines".
2. I kept refreshing to get through the rest of my subscriptions (I have more than the default limit so I have to refresh multiple times to refresh them all), but it refuses to keep refreshing (it is showing the same number of cached channels on every refresh).
3. I removed the channel so that the error would go away.
4. The error is still appearing for the same channel, even though I am no longer subscribed to them.

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

217

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
(I suggest you modify this template to instruct us on WHERE logs are stored.)
```

**Comment by palmerbomber1** [comment]
Maybe its device specific, Im using Graphene OS and by going to the app info page theres a button to see the apps logs

**Comment by TangentFoxy** [comment]
@palmerbomber1 The channel was undeleted at the same time the plugin was updated, so I can't know whether or not that fixed it.

**Comment by TangentFoxy** [comment]
Just checked on the correct device and no error is appearing. Reproducing, if it does occur again, relies on a channel being deleted, which isn't something any of us can test for, so I'm going to close this. Someone can come along and comment / reference / re-open it if it appears again.
