### ISSUE TITLE
fullscreen, only rotating to one side

### ISSUE THREAD

**Issue by jmcgaughey** [futo-org/grayjay-android#1568]
### What happened?

before when in fullscreen depending on how the phone is flipped no matter rotation mode is on or not it would while in landscape mode flip to what ever side is flipped upward but now stuck to the left landscape only

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
In Settings > Player, to what is Auto-Rotate set for you?

**Comment by Zvonimir-FUTO** [comment]
Related to #1554

**Comment by jmcgaughey** [comment]
its on/unlocked but stuck rotated to the (lean my phone to the left landscape) position. it did this after the last couple updates. it used to rotate in landscape mode to whatever side that is faced up now either with my phone itself in rotaion mode or not. it wont move (only landscape mode it goes into is to the left) if i flip the landscape movie upside down it doesn't flip to the correct position, unless i exit fullscreen mode completely of course.

**Comment by Zvonimir-FUTO** [comment]
Could you please tell me what I asked for? In Settings > Player, what is Auto-Rotate set to?

**Comment by jmcgaughey** [comment]
The first thing i said .its on.

**Comment by jmcgaughey** [comment]
in fullsceen mode when i flip my phone over it stays upside down instead of rotating to the correct position

**Comment by Zvonimir-FUTO** [comment]
> in fullsceen mode when i flip my phone over it stays upside down instead of rotating to the correct position

That is clear.

> The first thing i said .its on.

I'm assuming this means Enabled and not Same as System.

**Comment by jmcgaughey** [comment]
its enabled and not same as system

**Comment by jmcgaughey** [comment]
but even set to same as system and my system auto rotate is not enabled it suposed to (in landscape fullscreen) flip to the correct position. or at least it used to do that.

**Comment by kaidelorenzo** [comment]
Is there no way to get it to rotate while in full screen? Is there any way to make it rotate with some combination of system settings and app rotation settings?

As an aside we might change this decision but it was a deliberate choice to not auto rotate when the app is set to system and auto rotate for the system is off.
