### ISSUE TITLE
[Feature Request] Auto Synced Playlist Downloads

### ISSUE THREAD

**Issue by yunus-cakir** [futo-org/grayjay-android#157]
Like in YT Premium, I would like to add videos to my synced playlists and play them when I don't have internet connection without always hitting the download button

![Screenshot_2023-11-02-15-14-39-605_com google android youtube-edit](https://github.com/futo-org/grayjay-android/assets/83448525/3beb6cac-a0f4-4fbd-90ae-570979e2caef)

**Comment by Matesaktesak** [comment]
This would be really great. I'd like to use it with the 'Watch Later' so that I can always be sure I have something to watch when I go offline (e.g. in a bus when I left my house in a hurry)

**Comment by Matesaktesak** [comment]
This can probably get marked as Closed.

But, new problems have come with the feature - for one, the videos I watch from a download don't automatically get removed from Watch later, so when I delete the file, they get downloaded again when I connect to wifi.

**Comment by support-grayjay** [comment]
Hey @Matesaktesak nice find. I will close this issue. Could you please open a new bug for the issue you are experiencing since this is feature request?

**Comment by Zvonimir-FUTO** [comment]
> This can probably get marked as Closed.
> 
> But, new problems have come with the feature - for one, the videos I watch from a download don't automatically get removed from Watch later, so when I delete the file, they get downloaded again when I connect to wifi.

Just a heads up, the issue you found has been fixed in the upcoming release so stay tuned and thank you for bringing it up :)

**Comment by Matesaktesak** [comment]
You and the Grayjay team are awesome! Thank you very much!
