### ISSUE TITLE
Swipe up to toggle fullscreen stays in portrait mode

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#1571]
### What happened?

~~The first time after restarting the app~~ when i swipe up to toggle fullscreen mode before the video has started playing it opens fullscreen mode but with the video in portrait 
![Screenshot_20241207-004026](https://github.com/user-attachments/assets/62de1473-ef78-442d-ba87-fabe46440d7a)

~~the fullscreen button works as expected but swipe up not. 
When afterwards swiping down to toggle fullscreen and s swiping up again to toggle fullscreen i get normal fullscreen as expected~~
Same thing happens with the fullscreen button

Probably related to #779 

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Seems to only happen when rotation is not "locked" in player. Happens for both Enabled and Same as System in settings.

**Comment by McIrco95** [comment]
For me the rotation lock in the player does not make a difference 
For me it also happens with auto rotate disabled in the settings. 


With auto rotate setting enabled 
and rotation lock in the player in the default position, 
when swiping up to toggle fullscreen before the video starts playing, 
the video opens in portrait 
but when i rotate the phone it switches to landscape. 
But as i said in #1572 normal behaviour now would be for rotation to be locked after swiping up to enable fullscreen

**Comment by kaidelorenzo** [comment]
Should addressed by this merge

https://gitlab.futo.org/videostreaming/grayjay/-/merge_requests/53

**Comment by SdoggaMan** [comment]
My comment here is applicable to this (and I think part of the same bug) https://github.com/futo-org/grayjay-android/issues/1572#issuecomment-2533268252

**Comment by SdoggaMan** [comment]
My comment here is applicable to this (and I think part of the same bug) https://github.com/futo-org/grayjay-android/issues/1572#issuecomment-2533268252

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.

**Comment by McIrco95** [comment]
Its more of a workaround than a fix. I just can't switch to fullscreen before the video starts playing. Making it feel unresponsive. 
But with auto rotate on you can still rotate the phone. Leading to 
![Screenshot_20241214-123313](https://github.com/user-attachments/assets/25a41277-a376-4c61-af10-d76474e3208d)

Also for some strange reason "always allow reverse landscape rotation" works fine in "grayjay unstable v276" but does not work in "grayjay v276". Both apps have sensor permissions so i dont know why.

**Comment by Zvonimir-FUTO** [comment]
Yeah it's more of a workaround since Grayjay doesn't know the videos resolution before the video loads so it doesn't know if it should be full screen landscape or full screen portrait.

We will investigate that UI issues.

We will release another build next week which will hopefully fix it in stable as well.

**Comment by kaidelorenzo** [comment]
These issues should have been address in the most recent update
