### ISSUE TITLE
The new auto rotate is confusing 

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#1572]
### What happened?

I rewrote this a view times but basically 
Nobody wants to watch a video in fullscreen upside down. 
When switching to fullscreen there is no way to influence the orientation of the fullscreen video. 
Therefore how you hold your phone schould always affect the orientation of fullscreen video regardless of rotation settings. 

The way i use the app i dont get auto rotate in fullscreen video regardless of how i set the auto rotation setting
Because currently opening any video swiping up to toggle fullscreen leads to no auto rotation regardless of rotation setting. 

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by ORIOLESFan02** [comment]
I also have this problem. It's starting to get annoying, but something that I can manage. I do hope that this is able to be resolved soon :)

**Comment by obakha** [comment]
Same here, and thanks for working on it.

**Comment by SdoggaMan** [comment]
Echoing this, this was a bug a while back and seems to be re-introduced with the latest Grayjay update. Version 268-release. 
To reiterate the behaviour I'm seeing; with auto-rotate locked, when swiping upwards _before_ the video has loaded, it goes to fullscreen portrait, and when swiping up after it's loaded, it goes to landscape on the left-hand side of the device, and does _not_ autorotate to the right-hand side if you tilt the device. Previous behaviour would rotate to either side independent of auto-rotate lock in Android settings.

**Comment by obakha** [comment]
Hey, new version has come out and I still encounter the same issue, am I the only one?

**Comment by Zvonimir-FUTO** [comment]
We apologies for inconvenience, we will release another build next week which will hopefully be the last nail in the coffin. In the meantime you can use system rotation as a workaround.

**Comment by Zvonimir-FUTO** [comment]
These should be fixed in the latest version of Grayjay.

**Comment by obakha** [comment]
Yeah, it's fixed. Thanks a lot!
