### ISSUE TITLE
Cant update/download youtube plugin

### ISSUE THREAD

**Issue by S42r** [futo-org/grayjay-android#1589]
### What happened?

Updating/downloading plugin is not possible due to error "DashManifestRawSource is not defined (1867)[31-32]
![Screenshot_2024-12-10-02-09-09-45_692607d6162f2fc937d276a7f6a1b050](https://github.com/user-attachments/assets/3838ea39-b726-4302-aac8-da2e08b043d8)

### Grayjay Version

236

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

218

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
Please first update Grayjay to the latest version v268 then update the plugin.
