### ISSUE TITLE
Odysee error failed to get playback tracker. 

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#1590]
Odysee cannot read properties of undefined. { Reading duration.} (395)(53-54)

Link https://odysee.com/@official.benny.bros:e/MarioKart8DeluxeBoosterCoursePassSpinyCup:d

message under the video On the website "@official.benny.bros isn't live right now, but the chat is! Check back later to watch the stream."

**Comment by kaidelorenzo** [comment]
Should be addressed in version 44
