### ISSUE TITLE
Odysee, unknown url format.

### ISSUE THREAD

**Issue by ThunderHen** [futo-org/grayjay-android#1591]
Odysee, unknown url format.
https://lbry.tv/The-%C2%A325%2C000-Pre-Amp-that-went-Wrong---Tom-Evans-Mastergroove-SR-mkIII:c
Redirects to https://odysee.com/The-%C2%A325,000-Pre-Amp-that-went-Wrong---Tom-Evans-Mastergroove-SR-mkIII:c?&sunset=lbrytv

**Comment by kaidelorenzo** [comment]
Should be addressed with version 44

**Comment by kaidelorenzo** [comment]
That link specifically is an old issue. All videos by that creator wouldn't work when entering odysee.com URLs. The "."s in the URL were not handled. The period is now handled in version 45.
