### ISSUE TITLE
Pip extremely unresponsive and glitches out most of the time

### ISSUE THREAD

**Issue by edo9300** [futo-org/grayjay-android#1602]
### What happened?

In the latest version, the pip has become more bugged than usual, now going from video play back to pip mode freezes the apication for a short while and then immediately goes to pip without any animation, also the pip window itself when clicked on it most of the times has its controls outside its view and the video is 1/4th of the current pip area or goes out of its boundary. Attached a video showing this behavior, also at the end of it another issue is shown, where the video controls are duplicated when resuming from pip. All the other applications having pip support don't have these kind of issues.
The phone is an Asus zenfone Max pro m1 running arrow os 11

https://github.com/user-attachments/assets/f22d577c-d141-48f5-be30-a50116dd4696

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

218

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

**Comment by Zvonimir-FUTO** [comment]
Is this issue still present on the new version of Grayjay?

**Comment by edo9300** [comment]
All seems to work fine now

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.
