### ISSUE TITLE
Rotation is very unstable in landscape 

### ISSUE THREAD

**Issue by that404nerd** [futo-org/grayjay-android#1603]
### What happened?

With the new update, the rotation has become too sensitive. When I exit full screen mode, it goes into portrait mode and when I am I minimise the player and try to click on it it goes fullscreen. Here's an example:

https://github.com/user-attachments/assets/78cab870-6643-400f-ab45-82a0fb521641

Please look into this issue. Also the settings page is still in portrait mode. Is there a way to change into landscape? Thanks! 

### Grayjay Version

276

### What plugins are you seeing the problem on?

All

### Plugin Version

219

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

**Comment by Jakob9372** [comment]
Same issue after the update

**Comment by Uddhav07** [comment]
++

**Comment by kaidelorenzo** [comment]
the most recent update includes some tweaks to improve tablet detection. that will prevent most of the issues described.
