### ISSUE TITLE
deleting videos from a downloaded playlist does not to free up space

### ISSUE THREAD

**Issue by ykuksenko** [futo-org/grayjay-android#162]
I created a playlist, added one video and set the playlist to download. As videos are added to the list they get downloaded automatically. However when they are removed from the playlist the used space does not go down in the `Downloads` area.

**Comment by mooneyto** [comment]
I also noticed this, I also noticed videos that were previously downloaded still show the download icon in the creators tab. When I click the option button there is no way to delete. This is a pretty big issue for storage usage.

**Comment by Heartborne** [comment]
I second this.

💡 The option alone of allowing you to manually delete downloads FROM the actual video page (perhaps a "delete" button, next to the "download" one), would be a huge step forward!

It's really cumbersom to: watch a video entry that you had downloaded—out of the tens/hundreds you have in your downloads "folder"—, and, if you want to delete it (as to free up som space) you have to go through your list of downloaded videos, LOOK for that specific entry (mind you, they can't be searched nor organized/sorted), try to find that entry in that unorganized mess and, only then, you'll be able to delete it.

💡  It would also be good to have a button, in the downlads tab to "clear already watched videos", for example

**Comment by ykuksenko** [comment]
Tested this functionality today with version 264. Removing the video from the playlist immediately clears the used space. closing.
