### ISSUE TITLE
[Feature Request] Autoplay after video ends. 

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [futo-org/grayjay-android#165]
Hi, I can't seem to find this option when using the application. Vanced and NewPipe are both able to play a different video after one finishes. I wanted to ask if that feature already exists, and I haven't found it. Or, is this feature not available yet? Thank you for making this beautiful app, and thank you in advance for any information that you are willing to provide.

**Comment by drk002** [comment]
Of course, I miss this option a lot. The program doesn't remember when I finished watching the last video. The "Resume at..." button appears too briefly. Start the video from the moment you last left off, should be entered automatically.

**Comment by BetaMaxHeadroom** [comment]
I guess the way that NewPipe works is that there is an "auto-enqueuing" feature that NewPipe has set by default. So, a list of videos is populated that is related to the video I am currently playing. 

- Is there a way to either generate/import/populate a queue of related videos automatically?
    - I can't imagine the sort order of this using different sources. I would imagine it makes sense to stick with the same source.
- Is there a way to have the video automatically play the next video from the automatically created queue?

As an example use case (and, I realize it is not a very good one), I like to listen to music while I drive (and I use music from YouTube videos). I currently use NewPipe to play music. However, I would prefer to use Grayjay. 
- A benefit of NewPipe is that the next song starts playing without any need for me to interact with the application. 
- If I use Grayjay for music in my car, I will need to take my eyes off the road to look at the screen for the next song to play.

**Comment by Zvonimir-FUTO** [comment]
In **Settings** under **Player**, at the end you can turn on **Enable autoplay by default**.

**Comment by WhitespaceQ** [comment]
What is the algorithm for choosing whats next to play? Only from playlist that's been manually added by the user or it pulls from YouTube recommendation?

**Comment by WhitespaceQ** [comment]
`Enable autoplay by default` still doesn't work if I'm casting using the Chromecast implementation. I haven't been able to try FCast.

**Comment by Zvonimir-FUTO** [comment]
@WhitespaceQ Thanks for reporting, we are looking into it. Please open another bug report for this issue instead of necro-bumping.

From my testing this doesn't work on Chromecast and FCast with stable backend but seems to be fixed on experimental backend.
