### ISSUE TITLE
Stops playing 

### ISSUE THREAD

**Issue by PROd120** [futo-org/grayjay-android#166]
The app keeps stopping and restarting after a minute of playing a video. Currently I am building a list of curators in the app and playing through rumble. I don't know if the issue is with the interface with rumble or something else but every time I try to play a video it stops and restarts after a minute of playing.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
