### ISSUE TITLE
[BiliBili (CN)] failed to acquire mixin_constant(204)[8-9] Plugin [BiliBili(CN)][BiliBili (CN)] failed to acquire mixin_constant (204)[8-9]

### ISSUE THREAD

**Issue by Timoite** [futo-org/grayjay-android#1663]
### What happened?

Both desktop and mobile version of bilibili extension stopped working (unable to fetch contents from channels and play videos from channels)

### Grayjay Version

276

### What plugins are you seeing the problem on?

BiliBili (CN)

### Plugin Version

19

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [ ] N/A

### Are you using a VPN?

No

### Relevant log output

```shell
[BiliBili (CN)] failed to acquire mixin_constant(204)[8-9]
Plugin [BiliBili(CN)][BiliBili (CN)] failed to acquire mixin_constant (204)[8-9]
```

**Comment by kaidelorenzo** [comment]
Should be fixed in version 20
