### ISSUE TITLE
[Feature Request] Add the ability to hide/remove played videos from Subcriptions Tab 

### ISSUE THREAD

**Issue by SeizeOP** [futo-org/grayjay-android#167]
Currently there is an options button next to each video that appears in Grayjay. This option button allows the user to perform a variety of actions including: 

- Queueing the video 
- Downloading the video
- hiding the video from `Home`.
Among other options. 

Coming to Grajay from more traditional RSS and podcast programs the `Subscriptions` tab feels more like a "home" than the actual `Home` tab. For this reason I would be interested to see a feature added to remove a video from ones `Subscriptions` tab either upon finishing the video, or manually via an option button simillar to the `Hide From Home` option.

Maybe The `Hide from Home` and `Hide From Subcriptions` could be combined into a single `Hide Video` selection. 

Sincerely,
 @SeizeOP

**Comment by Robbylikes** [comment]
The ability to hide channels and vids just watched is a good idea.

**Comment by SeizeOP** [comment]
Shortly afterr creating this issue I realized that this is merely a read only mirror of the grayjay GitLab. For this raeson I am going to close this issue.

If anyone is interested i did create an issue on the GitLab repository. Not sure if anything will come of it though. [The issue on GitLab](https://gitlab.com/futo-org/grayjay/-/issues/2)
