### ISSUE TITLE
Release on f-droid

### ISSUE THREAD

**Issue by velo** [futo-org/grayjay-android#168]
Not sure if license allows, but would be awesome to have the grayjay published on f-droid!

**Comment by HafizBeyy** [comment]
Thats a great idea to announce the apps name to more users

**Comment by koen-futo** [comment]
We will do this for sure, its more a time limitation than anything at the moment.

**Comment by Bluscream** [comment]
[Obtainium](https://github.com/ImranR98/Obtainium) works fine with grayjay's website

**Comment by jilv220** [comment]
Or release on izzydroid instead

**Comment by koen-futo** [comment]
https://app.futo.org/fdroid/repo/ It is on the FUTO FDroid repository now.

**Comment by Bluscream** [comment]
> https://app.futo.org/fdroid/repo/ It is on the FUTO FDroid repository now.

Could you please link your f-droid repo somewhere on your front page and not just hidden in some github issue?

**Comment by koen-futo** [comment]
Added a quick mention.

**Comment by RPLgrime** [comment]
> [Obtainium](https://github.com/ImranR98/Obtainium) works fine with grayjay's website

I'm not able to use the Gitlab URL to install with Obtainium.
Am I using the wrong URL?
