### ISSUE TITLE
[Issue] Crash

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#172]
App crashes immediately when watching video at random times

**Comment by Robbylikes** [comment]
Have you updated your OS? Tried clearing cache? Have you looked at other version from the website?

**Comment by HafizBeyy** [comment]
> Have you updated your OS? Tried clearing cache? Have you looked at other version from the website?

My os is lineage os 20 latest version. And yeah, checked for updates im sure this the latest one

**Comment by Robbylikes** [comment]
Have you looked into your android system  WebView version? I've had problems with apps crashing as well when using an open bootloader os. I do believe it is the version of WebView you are using, look for a better one for rooted phones. Don't use Google. If you don't know how to change it use lsposed. Look for WebView install plugin then use the one you want in developer options in settings.

**Comment by HafizBeyy** [comment]
> Have you looked into your android system  WebView version? I've had problems with apps crashing as well when using an open bootloader os. I do believe it is the version of WebView you are using, look for a better one for rooted phones. Don't use Google. If you don't know how to change it use lsposed. Look for WebView install plugin then use the one you want in developer options in settings.

Which lsposed model you recommend. This is the first time making changes on system webview

**Comment by Robbylikes** [comment]
I can't say for sure. You'll have to do some homework and experiment like most of us till you get it right for you.

**Comment by koen-futo** [comment]
Hey guys, this is fixed in version 191 which we will hopefully be releasing today. It was related to Android 9 not support a specific overload of the startForeground method.
