### ISSUE TITLE
Nebula extension fails to open video

### ISSUE THREAD

**Issue by obsgolem** [futo-org/grayjay-android#175]
Whenever I try to open a nebula video I get the following error:
![Screenshot_20231104_123934_Grayjay](https://github.com/futo-org/grayjay-android/assets/1786500/a0ce2d72-208e-47fc-90da-2c43e2da67c0)

**Comment by jp438-2** [comment]
I can confirm that the same happens to me now, whereas it worked a few days ago.

**Comment by koutheir** [comment]
Signing out and in again to Nebula solves the issue for some time, but it's back again when the app is restarted.

**Comment by Kelvin-FUTO** [comment]
This issue was solved a few updates back I believe, so closing it. Was related to authentication expiring for Nebula.
