### ISSUE TITLE
Missing sponsor block.

### ISSUE THREAD

**Issue by xR-Cz** [futo-org/grayjay-android#176]

**Comment by OkieNeck** [comment]
Agreed. This is a deal breaker for me. It's a bummer cause app works great.

**Comment by vfosnar** [comment]
+1 would like to see this as an optional feature

**Comment by williamspacefire** [comment]
Agreed, is there any plan to add SponsorBlock to GrayJay?? This is the only thing holding me from using GrayJay as my main YT player

**Comment by Kelvin-FUTO** [comment]
Due to strong demand version 191 has Sponsorblock for Youtube.
(FUTO respects your decision to use SponsorBlock. But only if you're supporting creators in other ways.)
