### ISSUE TITLE
Update check dialog delay makes a small freeze

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#178]
Hello when I hit manually check updates for the platform player I notice a small freeze in the application and it does not respond to any input until the message shows. I might have hit the update to many times to have that cause this issue but would still like to address this as a bug/issue since resolving this small bit can make the application feel more responsive. [Platform player 181]

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
