### ISSUE TITLE
Cosmetic issue Search bar not autofitting 

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#179]
Hello, I want to address a cosmetic issue. Search bar doesn't autofit. here's a screenshot of that. I have only cropped it vertically not horizontally.
![Screenshot_20231104-235930_Grayjay](https://github.com/futo-org/grayjay-android/assets/34012548/6841a5fd-9119-4a12-a2d7-be9be520eaf2)

 I am on S10 plus. Platform player 181

**Comment by greengeckowizard** [comment]
Cosmetic issue still present on version 190 platform player

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
