### ISSUE TITLE
Cast icon missing when in landscape mode

### ISSUE THREAD

**Issue by xephos1one** [futo-org/grayjay-android#182]
Version: 181

The cast icon is missing when watching in landscape mode
![Screenshot_20231105-111411](https://github.com/futo-org/grayjay-android/assets/39647898/1072a839-e245-4088-a80f-41b75fca8ac7)

For comparism: cast icon available in portrait mode
![Screenshot_20231105-111034](https://github.com/futo-org/grayjay-android/assets/39647898/1e850e5a-4947-4fd6-a35b-fc4eebc6d1fb)

**Comment by koen-futo** [comment]
Added in version 191, looking to release soon.
