### ISSUE TITLE
No zoom in/ Fill in option for videos.

### ISSUE THREAD

**Issue by jahidulislamjahid** [futo-org/grayjay-android#184]
Not an issue actually, just a lack of a feature. There is no option to fill in or zoom in option for video playback. It is essential for some videos to get an immersive experience. So It is a crucial feature that should be added in the next update.

**Issue:** No zoom-in/fill-in button
**Current Behaviour:** 
![Screenshot_20231106-001645](https://github.com/futo-org/grayjay-android/assets/86620754/dd51fcd0-fb61-4db0-94d2-5104ab30532c)

**Expected Behaviour:** 
![Screenshot_20231106-002905](https://github.com/futo-org/grayjay-android/assets/86620754/a14e062d-cf49-4a2b-b5be-24670b8ad1f7)

**Comment by xephos1one** [comment]
Related to #98

**Comment by koen-futo** [comment]
Implemented next build.
