### ISSUE TITLE
Activate button doesn't enter license 

### ISSUE THREAD

**Issue by benninkcorien** [futo-org/grayjay-android#187]
When you click the Activate button in the email that you get after buying the app, you get an error, it doesn't open the app. 

    could not be loaded because:
    net::ERR_UNKNOWN_URL_SCHEME

(Buy - Already bought - manually paste in the key does work)

**Comment by Kelvin-FUTO** [comment]
I'm not 100% sure, but I believe some mail clients do not support custom schemas.
This is partially why we do provide alternative means like the license key or activation url.

**Comment by benninkcorien** [comment]
That must be it. I was using Bluemail (only mail client I've found that lets me send whole domains straight to spam)
