### ISSUE TITLE
Encryption password not masked

### ISSUE THREAD

**Issue by DubbaThony** [futo-org/grayjay-android#19]
While setting up app, and deciding to setup backup folder, an encryption password prompt is given. Im not sure if its bug or design flaw, but the input text was not masked.

About phone:
OnePlus 8T (KB2003)
Android 13
AICP ROM
Magisk, with modules
No Xposed.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
