### ISSUE TITLE
[Feature Request] Include sales tax in the first price that the user sees

### ISSUE THREAD

**Issue by tobeqz** [futo-org/grayjay-android#190]
Hi, today I installed Grayjay and when I when I went to pay the initial price that I saw was €10, but when I clicked further it added the tax to the price and I found out that I had to pay €12,09 instead. I understand that in the US, sales tax tends to be added at the end, but as a European this kind of caught me off guard.

I love this project enough to still pay, but I think for many Europeans this would leave a bad taste in their mouth and they will be more likely to skip the payment.

That's why I suggest the initial price that the user sees should include tax. I think it would also be a possibility to have different behaviors in different regions to reflect what the user is likely expecting.

I want to make a pull request for this myself but I want to verify that you would actually appreciate this change before I put my time into it.

**Comment by Kelvin-FUTO** [comment]
There are several reason why we don't show tax at the initial page yet.
Without exposing the user's IP to external services we cannot determine proper taxation, and any implications that has.
We want users to confirm their actual location as well.
There are also optimization reasons as it was just a basic indicator. 

A small addition we could do is add "+ tax" to at least clarify this for some users.

We don't accept PRs on the core code yet.
