### ISSUE TITLE
NPE for geo-restricted account.

### ISSUE THREAD

**Issue by FlyingBackdoor** [futo-org/grayjay-android#191]
When I try to access a YouTube channel which is restricted, it throws null pointer exception and also doesn't show any video for that specific channel.
![Screenshot_20231106_214258_Grayjay.jpg](https://github.com/futo-org/grayjay-android/assets/31269655/bd34da99-533f-4de0-aae3-aa8f5aecacf2)

**Comment by 42O69420** [comment]
i get the same error but at the top of the home screen when clicking on an age restricted video in a playlist

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
