### ISSUE TITLE
Changelog is always empty 

### ISSUE THREAD

**Issue by spacecowboy** [futo-org/grayjay-android#192]
When app prompts you that there is an update available, clicking 'Show changelog' always just displays "Some changelog", instead of an actual changelog

**Comment by JustCryen** [comment]
I'm sure it worked when I first started using GrayJay but right now it's indeed missing.
There's only something like "example changelog" text and a freezed loading graphics.

**Comment by QantumEntangled** [comment]
Same problem. I have checked every time the app has an update and it never displays an actual changelog, it just shows to "example changelog" or "some changelog" text with a static loading icon below it.

After installing the update, I can open the settings and view the changelog from there just fine. But that defeats half the purpose.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
