### ISSUE TITLE
Can't see all videos on youtube channel

### ISSUE THREAD

**Issue by F1nnM** [futo-org/grayjay-android#194]
Scrolling down on some channels doesn't load more videos; it might be related to members-only videos or channels that I am a member of.

On a channel I am a member on, I can only scroll down about 30 videos (+ all the livestreams they ever had), before reaching the end of the list.

**Comment by Kelvin-FUTO** [comment]
Could you give me some more information, like an example channel.
If your question is how to access membership for Youtube, you can do this by going to your Youtube plugin, and after logging in, toggle the "Use login for Channels", you might also need to enable "Use login for video details" to access the videos.

Note that there is a known issue if you don't use english as your Youtube language, it might cause issues with dates.

**Comment by F1nnM** [comment]
Sorry, if I wasn't clear, English isn't my native language. I am logged into YouTube, I have enabled all the toggles. My language is set to en_DE, so the videos are not sorted correctly, but that's not the issue here. An example would be Dropout ***@***.***). I can see the most recent videos in the app, back to "Who Got High and Reenacted a Concert Using Eggs?". Then more videos should appear below that, but they don't. It doesn't load any more videos into the list view.

**Comment by Kelvin-FUTO** [comment]
@F1nnM I'm having a hard time finding the related content.
I checked the Dropout channel (14.7M subscribers) which loads fine at a glance. can easily see 100+ videos. But I cannot find the video you mention. Not even when I search directly on the website.. So I'm not sure I'm looking at the right one?
Could you perhaps provide a link?

**Comment by F1nnM** [comment]
Ah, it seems like replying via email censored the link. Here's the link: https://www.youtube.com/@dropout
With 14.7M subscribers I'm pretty sure you found the correct one though.

I am a member of this channel, which shows me a lot more videos, that cant be found via search.
On the youtube page on my desktop it looks like this:
![image](https://github.com/futo-org/grayjay-android/assets/12767947/ec562f8a-175f-48a7-a7ed-0fbf085bd53a)

In the grayjay app, however, I can't scroll any lower than this:
![image](https://github.com/futo-org/grayjay-android/assets/12767947/77e12f7c-b0ad-4326-80a8-80e5ffedde11)

Maybe one thing to note, it might help with debugging: Since last time I checked they uploaded two more videos. One members-only and one public. Yet the lower cutoff in grayjay only moved one video.

**Comment by Kelvin-FUTO** [comment]
Can you confirm that maybe you're seeing *only* membership videos when logged in?
I'll certainly investigate. It at least appears to be related to membership.

**Comment by F1nnM** [comment]
I can see both, members-only and public videos:
![image](https://github.com/futo-org/grayjay-android/assets/12767947/2f226ef2-ebb7-44c8-9326-8b36e1234961)
THe first one is members-only, the second one is public.

**Comment by ZiqVoid** [comment]
I came here to see if anyone else was having the same issues, I cannot find videos such as "Chrysopoeia" or "Dead Voxel" by Lena Raine and C418 through regular searching *or* in their channel videos.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale. If you still encounter this issue, feel free to reopen.
