### ISSUE TITLE
Rotation lock should be inverted

### ISSUE THREAD

**Issue by usertoroot** [futo-org/grayjay-android#197]
The rotation lock button in the video player is weird, it shows "what will happen if you tap it" not "this is the current setting, tap to change" which is how I would expect it to work. Like, when you have a volume icon you wouldn't expect it to show "mute icon" when you have sound up and "loud icon" when you are muted

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
