### ISSUE TITLE
Swipe for brightness and audio

### ISSUE THREAD

**Issue by AidanG1** [futo-org/grayjay-android#2]
Swipe for brightness and audio do not allow making the video brighter than screen brightness or louder than device volume. NewPipe and Netflix both allow audio and video controls in full screen that override device settings temporarily.

**Comment by JustCallMeSimon26** [comment]
I actually like the current behaviour and saw it as intended

**Comment by Mik39907** [comment]
I normally use my device on very low brightness cor battery and just because I have no issues using it so but when I watch a video I like to make it brighter for HDR or visibility if a content is darker etc.. revanced allows this and It is way more user friendly

**Comment by Matesaktesak** [comment]
Since the last update I would consider this issue closed.

**Comment by alfonslm** [comment]
@Kelvin-FUTO This seems like a solved issue

**Comment by Kelvin-FUTO** [comment]
Correct, this behavior can be changed in settings.
Because lots of users complained about this new behavior we did disable it by default.
