### ISSUE TITLE
Chapter from previous video shows on next video when using the Queue

### ISSUE THREAD

**Issue by LilyArlatto** [futo-org/grayjay-android#201]
I queued up a couple videos and for once let one auto-play into the other (video ended and the next one in the queue started playing). For some reason, the name of the chapter from the video that just ended was permanently showing beside the timestamp on the new video, which had no chapters in it.

How to recreate:

**This happens specifically on the yt plugin, I'm not sure about others**

1. Start watching a video that you know has a chapter at the very end.

2. Queue another video that has no chapters in it.

3. Let the first video end so it automatically plays the next one.

4. The name of the final chapter on the first video will now show up beside the timestamp (when player controls are showing) for the rest of the video.

_I also want to note that I updated the app around 10 minutes ago, so this is the latest update (Version number 190, release type)_

**Comment by F1nnM** [comment]
You don't even need a queue for that.
I just experienced that, after I simply clicked on a yt video without chapters after watching one with chapters. It even persists through multiple videos.

And all chapters are preserved. Going to any time in the new video shows the corresponding chapter of that timestamp in the first video.

**Comment by LilyArlatto** [comment]
> You don't even need a queue for that.
> I just experienced that, after I simply clicked on a yt video without chapters after watching one with chapters. It even persists through multiple videos.
> 
> And all chapters are preserved. Going to any time in the new video shows the corresponding chapter of that timestamp in the first video.

I wasn't aware that this was just a thing that happened generally, so I wanted to be as specific as possible just in case-- Thanks for adding on and saying that this happens pretty much everywhere though.

**Comment by Kelvin-FUTO** [comment]
This is fixed in version 191. (likely release tomorrow)
