### ISSUE TITLE
Galaxy Fold: Larger Opened Screen View cuts off tops of videos [Screenshot Attached]

### ISSUE THREAD

**Issue by BrotherPanan** [futo-org/grayjay-android#204]
Galaxy ZFold 5
App Version 190

When I watch videos with my ZFold5 opened to the larger screen, the tops of videos are all cut off.

![Screenshot_20231106_205006_Grayjay](https://github.com/futo-org/grayjay-android/assets/63543627/3695db4c-2875-496a-99af-4737da71415b)

**Comment by TheUbMunster** [comment]
I have the same issue on my galaxy fold 3.

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #34.
