### ISSUE TITLE
Metered Mobile Data

### ISSUE THREAD

**Issue by DubZeroSP** [futo-org/grayjay-android#206]
How do I change if the app should use metered speeds or not?

I am having trouble stopping YouTube videos from buffering because Grayjay refuses to use more than 200KB/s of data.

**Comment by greengeckowizard** [comment]
I've have this problem too it stutters a bunch even though my mobile data is clearly capable of handling more download speed and bandwidth.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
