### ISSUE TITLE
Failed to load next page on home

### ISSUE THREAD

**Issue by MidasVE** [futo-org/grayjay-android#207]
![Screenshot_2023-11-07-06-40-46-61_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/26002295/b15c3f2d-c17d-4d5e-a854-509611425da0)
Every time I scroll near to the bottom of the page on the 'Home' tab, I get this error message. I'm on version 190.

**Comment by Kelvin-FUTO** [comment]
@MidasVE Could you tell me a bit more about your settings?
 - Are you logged into Youtube?
 - Anything particular that stands out about your account if you are.

**Comment by MidasVE** [comment]
I am logged in, here are my settings:

![Screenshot_2023-11-07-14-32-04-77_ca2ad563b57b5497046450f16b7718e2.jpg](https://github.com/futo-org/grayjay-android/assets/26002295/9a3a3091-8525-4d7b-93e5-c33b558dfdb5)

![Screenshot_2023-11-07-14-31-51-69_ca2ad563b57b5497046450f16b7718e2.jpg](https://github.com/futo-org/grayjay-android/assets/26002295/670412fa-6a29-47f0-b313-40b54afdb787)
