### ISSUE TITLE
[Feature Request] gestures 

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#214]
Thanks you guys for adding make full screen with swipe up gesture. Can u also add the opposite? I mean can we exit from full screen with swipe down? Just another yt like suggestment

**Comment by Darukutsu** [comment]
You can exit from fullscreen swapping up again. Although swipe down would be more intuitive.

**Comment by HafizBeyy** [comment]
> You can exit from fullscreen swapping up again. Although swipe down would be more intuitive.

Yeah but it looks odd with some way

**Comment by McIrco95** [comment]
Completed
