### ISSUE TITLE
[BUG] Go back gesture at screen edge starts rewinding video

### ISSUE THREAD

**Issue by chief17** [futo-org/grayjay-android#215]
Android device: Pixel 6a
OS: GrapheneOS
Orientation: Vertical
Reproducable: Yes
Steps to recreate: Tap on rewind (left part of the video) multiple times and use the go gack gesture.

Description:
While attempting to use the Back screen gesture over a playing video, the video starts to rewind with increasing steps in seconds. 
It seems the rewind event is being called continuously.
![Screenshot_20231107-232459](https://github.com/futo-org/grayjay-android/assets/10833139/8bc53e14-05ba-4299-8244-b996184a36bf)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
