### ISSUE TITLE
Found a comment that's two days older than the video

### ISSUE THREAD

**Issue by MrSaxowolf** [futo-org/grayjay-android#220]
![Screenshot_20231107-165234_Grayjay](https://github.com/futo-org/grayjay-android/assets/12034504/75c3d362-8520-41d6-b20d-d5e1b44f1149)
![Screenshot_20231107-165232_Grayjay](https://github.com/futo-org/grayjay-android/assets/12034504/7119f5f3-a98c-45ad-bb60-ac876769b875)

**Comment by palmerbomber1** [comment]
I think this might be from how the video was "released" on YouTube. Creators can make a video available only to channel subs before it's available for everyone, and for those non subs it will look like comments were made before the video was released, because in a way they were

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
