### ISSUE TITLE
Comments not loading after mistakenly turning off the display

### ISSUE THREAD

**Issue by technicalsoumyadip** [futo-org/grayjay-android#222]
I was watching a video on YouTube. I might have loaded the platform comment section. Then, I mistakenly turned off the display. After turning it on and unlocking the phone, the video was closed and after this, whenever I open any video, I get the error 'getQueryReferences to https://srv1-stg polycentric.io failed with status code 502. Response body:'. And this is happening only to polycentric comments. This issue is not limited to YouTube videos.
Android version- 14
Android security update- 5 October, 2023

**Comment by greengeckowizard** [comment]
I got the same issue closing the issue I just made #223

**Comment by technicalsoumyadip** [comment]
I am no

**Comment by technicalsoumyadip** [comment]
I am no no longer facing this problem. I am closing this issue.
