### ISSUE TITLE
The Channels(vreators) dont load any videos when i visit their page

### ISSUE THREAD

**Issue by RediTafa** [futo-org/grayjay-android#225]
So i was using YouTube and tried to watch some of the oldest videos of Louis and LTT ,i tried anyway.The issue is prevalent in all creators channels i visit.

Update: 
It seems i was somehow logged out without my knowledge ,so I logged in and the issue seems to have been caused by that .Thank you for your patience and i apologize for the false report!

**Comment by koen-futo** [comment]
Can you please give us more information? Which plugin were you using? Which channels were you trying to open?
