### ISSUE TITLE
File Extraction defect after download

### ISSUE THREAD

**Issue by RediTafa** [futo-org/grayjay-android#226]
When i try to extract a file i have downloaded the extraction button just stops responding and it does not show anything after that.
   No matter how many time i have tried by rebooting the app and by downloading the file again, the option 'Extract' does not respond with anything after i tap it.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
