### ISSUE TITLE
Time since upload on videos always shows 53 years

### ISSUE THREAD

**Issue by RediTafa** [futo-org/grayjay-android#227]
![Screenshot_2023-11-08-11-27-10-221_com.futo.platformplayer-edit.jpg](https://github.com/futo-org/grayjay-android/assets/122567359/23d6e4ff-ec55-4882-908f-4f8116ae9b6a)

![Screenshot_2023-11-08-11-30-18-428_com.futo.platformplayer-edit.jpg](https://github.com/futo-org/grayjay-android/assets/122567359/7d99ab82-6687-43b3-9b67-777fcc5612cb)

**Comment by Kelvin-FUTO** [comment]
This is a known issue related to Youtube accounts with different languages.
A quick fix is not enabling "Use login for channels" and "Use login for video details".
(These toggles do not add anything unless you want to watch membership content anyway)

**Comment by Kelvin-FUTO** [comment]
@RediTafa 
This was fixed in version 193 (YT Plugin version 148)
