### ISSUE TITLE
Allowing empty comment & no ratelimiting

### ISSUE THREAD

**Issue by 0xSegmented** [futo-org/grayjay-android#229]
It is possible to spam comment sections via the grayjay specific comment section. 

Also providing no context inside a comment is allowed.

**Comment by xephos1one** [comment]
Like the one at the bottom at https://www.youtube.com/watch?v=WpnLehvOM6E?

![Screenshot_20240210-093913](https://github.com/futo-org/grayjay-android/assets/39647898/fef35fbf-419d-4aeb-a7a8-0e5b2513780b)

**Comment by 0xSegmented** [comment]
Yes.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
