### ISSUE TITLE
When editing polycentric profile pictures, the manage polycentric identity ui does not update

### ISSUE THREAD

**Issue by AidanG1** [futo-org/grayjay-android#23]

**Comment by yuckdevchan** [comment]
I also have this issue. My icon doesn't even show in comments or on my channel, even by setting it in Harbour.

**Comment by VidathD** [comment]
Same. Also comments disappear

**Comment by koen-futo** [comment]
Several issues related to this have been fixed. Is this still an issue?

**Comment by Zvonimir-FUTO** [comment]
As Koen already stated this seems to be fixed and this is very stale issue so I will close it. Feel free to open a new issue if you are still encountering this issue.
