### ISSUE TITLE
Another account

### ISSUE THREAD

**Issue by xitywampas** [futo-org/grayjay-android#231]
I'm tired of notifications and email from places I give two ducks about. Please compliment a ticket system off something that doesn't require use of an outside account. This is stupid.

**Comment by koen-futo** [comment]
This is what we are going to keep using for now. Maybe in the future we will reconsider. For now we are focused on making the app good and stable.

**Comment by xitywampas** [comment]
Thank you for considering my suggestion. I already have close to 200 Internet accounts. I'm trying to bring that down lol

**Comment by Bluscream** [comment]
Well, that's the whole point of the internet. To have complimenting and competing services. However i think with OAuth your can have a few accounts manage a dozen of services at once.
