### ISSUE TITLE
Rumble feed

### ISSUE THREAD

**Issue by xitywampas** [futo-org/grayjay-android#232]
Rumble just feeds me 1-3 got long videos from people I don't even know. I tried to import my subscriptions but it just shows random people in not subscribed to. I went and added them manually and it still shows the same ones. I hide them and the orange is just blank. I refresh it and it's still blank. I restart the app and all the stuff I've watched and hidden comes back. I can't even use the app at this point.

**Comment by koen-futo** [comment]
Can you please provide more information?

I just tried disabling all plugins except the Rumble plugin. 

The home feed looks comparable to what I see on the Rumble website.

I subscribed to a creator from that home feed, refreshed the subscriptions, works fine.

I clicked on the channel of a specific creator, works fine.

Maybe there are specific creators that are causing issues for you? Please let me know.

**Comment by xitywampas** [comment]
The Rumble feed is weird. It shows me the same creators no matter what. I don't see any of the people in subscribed to.

**Comment by xitywampas** [comment]
I didn't mean to close this . I corrected my phones autocorrect and changed some things for clarity from my first comment below. I hope that makes my issue clearer.

"Rumble just feeds me 1-3 hour long videos from people I don't even know. I tried to import my subscriptions but it just shows the same non-random people I'm not subscribed to. I went and added them manually and it still shows the same creators. If I hide the videos the feed is just blank. I refresh it and it's still blank. I restart the app and all the stuff I've watched and hidden comes back. I can't even use the app at this point." 
If you don't understand that then I don't know what to say, get someone who knows English better to explain it to you, I guess.

 As I was saying, and it never stops showing the same videos. I can watch them and they stay on my feed, that's from all platforms. My home fed only changes like once a day no matter if I watch the videos or not.

**Comment by xitywampas** [comment]
I would provide screenshots or video but I have no clue how to on GitHub. This is my first time on here.

**Comment by DThomas44** [comment]
On my device, after logging into the Rumble plugin & selecting import, it doesn't show my subscribed creators, but instead the creators that are on the home page of Rumble when not logged in.

I am subscribed to 28 creators on Rumble. Currently of the 50 channels listed in the import dialog, only 2 are accounts I'm actually subscribed to.

This plugin worked for me in earlier releases, but I had to uninstall/reinstall the app today after the 192 update due to a different issue.

**Comment by DThomas44** [comment]
My issue is directly in the import process of the rumble plug in, not on any content pages such as home or subscriptions.

When attempting to import subscriptions, I'm getting a random list of creators resembling the Rumble home page. I'm not subscribed to the overwhelming majority of these & the credits I am subscribed to are mostly not seen in the list to select for import.

This Screenshots shows the import process. I'm not subscribed to any of the available options on Rumble. https://linksharing.samsungcloud.com/oCbb3PQLBZ75

**Comment by DThomas44** [comment]
Also note the displayed error is also for a creator I am not actually subscribed to.
