### ISSUE TITLE
Creators page crashing the app while clicking on it

### ISSUE THREAD

**Issue by ohne-ende** [futo-org/grayjay-android#233]
Hi, my phone's language is set to German, so Grayjay sets itself to German in the newest version. So far, so good, I don't need a German translation but it's pretty fine to have it. But since the newest version, Grayjay completely crashes while clicking on the Creators tab and gives me following error lines (inserted from the sharing button):

> Version information (version_name = 190, version_code = 190, flavor = stable, build_type = release)
> Device information (brand= samsung, manufacturer = samsung, device = b0s, version-sdk = 31, version-os = )
> 
> (e, ExceptionActivity, 2023-11-08 18:03:37): Uncaught exception ("Unbekannter Kontext"): length=2; index=3
> 
> java.lang.ArrayIndexOutOfBoundsException: length=2; index=3
> 	at java.util.Arrays$ArrayList.get(Arrays.java:4281)
> 	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:394)
> 	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:450)
> 	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
> 	at android.widget.Spinner.makeView(Spinner.java:773)
> 	at android.widget.Spinner.layout(Spinner.java:720)
> 	at android.widget.Spinner.onLayout(Spinner.java:682)
> 	at android.view.View.layout(View.java:24461)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
> 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
> 	at android.view.View.layout(View.java:24461)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
> 	at androidx.appcompat.widget.Toolbar.layoutChildLeft(Toolbar.java:2207)
> 	at androidx.appcompat.widget.Toolbar.onLayout(Toolbar.java:2146)
> 	at android.view.View.layout(View.java:24461)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
> 	at com.google.android.material.appbar.AppBarLayout.onLayout(AppBarLayout.java:553)
> 	at android.view.View.layout(View.java:24461)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
> 	at com.google.android.material.appbar.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:66)
> 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
> 	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1768)
> 	at com.google.android.material.appbar.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1427)
> 	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1446)
> 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
> 	at android.view.View.layout(View.java:24461)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
> 	at android.view.View.layout(View.java:24461)
> 	at android.view.ViewGroup.layout(ViewGroup.java:7412)
> 	at androidx.constraintlayout.motion.widget.MotionPaths.setView(MotionPaths.java:640)
> 	at androidx.constraintlayout.motion.widget.MotionController.interpolate(MotionController.java:1286)
> 	at androidx.constraintlayout.motion.widget.MotionLayout.evaluateLayout(MotionLayout.java:3572)
> 	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2960)
> 	at android.view.View.measure(View.java:27129)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
> 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
> 	at android.view.View.measure(View.java:27129)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
> 	at android.view.View.measure(View.java:27129)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
> 	at android.view.View.measure(View.java:27129)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
> 	at android.view.View.measure(View.java:27129)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
> 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
> 	at android.view.View.measure(View.java:27129)
> 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4536)
> 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3228)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3533)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
> 	at android.view.Choreographer.doFrame(Choreographer.java:797)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8669)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Other buttons seem to work fine and in the previous version, everything, including the Creators tab, worked just fine when the German translation was not implemented yet. 
Improvement idea: It would be nice to have a seperate language selection option that overrides the system's preference and simply ignores it so users can just use the app with their prefered language rather than what's the OS is set to. There seems to be some language selection point in the options but it obviously doesn't work because it's preferring German rather then English on my device since German isn't integrated into it.

![SmartSelect_20231108_191019_Grayjay](https://github.com/futo-org/grayjay-android/assets/76077900/7afa0474-2d28-4969-85af-5a7eac7f0dc5)

**Comment by koen-futo** [comment]
This is a known issue, will be fixed in the next release.
