### ISSUE TITLE
Allow landscape mode outside of video

### ISSUE THREAD

**Issue by mmehnert** [futo-org/grayjay-android#235]
It would be great, if the app would follow device rotation. E.g. make it possible to browse the video list in landscape. Also when in vertical mode I sometimes put the charging port on top. In this configuration, grayjay is always upside down and does not follow the rotation.

**Comment by Bluscream** [comment]
> It would be great, if the app would follow device rotation. E.g. make it possible to browse the video list in landscape. Also when in vertical mode I sometimes put the charging port on top. In this configuration, grayjay is always upside down and does not follow the rotation.

In the meantime you can use an app like RotationControl or on newer android versions you can use the Sensors off developer quicktile to force a specific rotation

**Comment by Kelvin-FUTO** [comment]
This is not actually a rotation issue but an UI issue.
The current UI is not designed for landscape use in those views, hence we force portrait mode.

We could possibly add a setting that ignores this entirely at the cost of worse usability.

**Comment by Bluscream** [comment]
I have no usability problems with forced landscape for example rn

**Comment by beemandev** [comment]
I always assumed mobiles stay in Landscape mode upside-down so you can retain landscape when lying on your side with device held vertically. Video window has orientation lock button for this though.

**Comment by Kelvin-FUTO** [comment]
We'll add a toggle to bypass our enforced portrait mode in the next version.
With a disclaimer that it was not designed for this yet, as it might have unpredictable UI issues.

**Comment by BlazingSalvo** [comment]
Pretty simple to move the menu options into a vertical stack layout to the left rather than horizontal on the bottom and detect the orientation to set new contentview with the same viewmodel bindings.
I think this is a good feature to add because this has "killer app" potential for Amazon Fire tablets whom Google has feuded with. Lol. In fact, once landscape is available, I'd really suggest getting this onto the Amazon App Store.

**Comment by Kelvin-FUTO** [comment]
Proper UI is planned. We just have other priorities right now.
In upcoming build (194) I did add a toggle that allows you to bypass the rotation lock we have in place.

I do **NOT** recommend using it. It will cause UI issues 
(I would personally not bother reporting the issues, as they become void once we redo it anyway). 
But for those that really want it now. The toggle is there. its called "Bypass Rotation Prevention" all the way at the bottom of settings.

**Comment by Willdrick** [comment]
I don't know how easily implementable it'd be, but a setting to force a specific orientation (lock to 0, 90, 180, 270) would be greatly appreciated. 

As an example usecase, many tablets have the charging port on the same side as the navigation controls (0 degrees) and setting the device on a stand/cradle while charging requires it to be "upside down". Even with the rotation workaround, grayjay refuses to display videos in this orientation

**Comment by 19ATF72** [comment]
@Kelvin-FUTO Thanks for the toggle, does almost exactly what I was hoping for!
Agree with @Willdrick an orientation lock would be great, or ensuring the app respects OS rotation settings e.g LineageOS rotation mode settings.
![438083471_951050053365269_8509002290979614169_n](https://github.com/futo-org/grayjay-android/assets/54142191/7ba8a16d-9103-4516-a623-5cf740ab9683)

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale. Please reopen if the issue is still present.
