### ISSUE TITLE
Fix nebula cookies expiring and fix flow when cookies are expired.

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#237]
Fix Nebula cookies expiring and not having a proper error thrown when they are expired and trying to get a video. Flow should be more graceful (allowing you to login again).

**Comment by mnbvasd** [comment]
Is this a dupe of #175  ?
Sounds like the same issue I've been experiencing

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
