### ISSUE TITLE
[Issue] cant import playlists

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#241]
I think thats because the youtube plugin. Plz fix that

**Comment by dmig** [comment]
Upvoting.
"Import playlists" shows "nothing to import"

**Comment by HafizBeyy** [comment]
@Kelvin-FUTO

**Comment by grisevg** [comment]
Same. I think it's caused by non-English Youtube language. I had my Youtube in russian and had same issue. I switched to English and it works now!

**Comment by HafizBeyy** [comment]
> Same. I think it's caused by non-English Youtube language. I had my Youtube in russian and had same issue. I switched to English and it works now!

Wtf but mine was english , too. What do  you mean with non-english?

**Comment by HafizBeyy** [comment]
@grisevg

**Comment by Mubelotix** [comment]
Changing the language of the youtube official app didn't help

**Comment by HafizBeyy** [comment]
A
