### ISSUE TITLE
[bug] release 191; subscriptions are fetched despite `Fetch on app boot` being disabled

### ISSUE THREAD

**Issue by ykuksenko** [futo-org/grayjay-android#243]
In release 191 subscriptions are fetched 15ish seconds after launching the app despite `Fetch on app boot` being disabled.

**Comment by Kelvin-FUTO** [comment]
After you open the subscriptions tab?
Subscriptions are still fetched when you open the subscription tab I believe. 
We can make an additional setting to disable this as well.

"Fetch on app boot" is used to pre-fetch subscriptions before even opening the subscription tab to get results quicker.

**Comment by Kelvin-FUTO** [comment]
In upcoming 192 (<1 hour) there is a new "Fetch on tab open" setting which you can turn off for the result you are trying to get I believe.
