### ISSUE TITLE
Cannot login to Patreon using apple

### ISSUE THREAD

**Issue by linwiz** [futo-org/grayjay-android#245]
I am unable to login to Patreon using my Apple ID. After entering my ID and password, and verifying my 2FA, I am taken to a page asking if I want to continue using Patreon with my Apple ID. I click continue, nothing happens. I click continue again and it says "My request could not be completed because of an error. Please try again later." clicking cancel doesn't do anything, and clicking X on the login window returns me to Patreon settings without being logged in. 

If more information is needed I will provide it.

Version Code 1
Version Name 190-24-g00e40e8
Version Type debug

**Comment by Kelvin-FUTO** [comment]
We are aware that some logins for third-party authentications don't work.

That being said, I believe Patreon allows you to set a password for a third-party login so you can use both that and normal username/password. This is a temporary workaround.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale.
