### ISSUE TITLE
Subscriptions only showing live videos

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#246]
Hello in the subscriptions it's only showing live videos when I refresh it does nothing it just keeps the live videos at the top.  Platform player version 192

![Screenshot_20231109-173949_Grayjay](https://github.com/futo-org/grayjay-android/assets/34012548/3f15a18a-ee6a-4bd5-acc0-adceaec5885a)

**Comment by greengeckowizard** [comment]
Playing around with those buttons on the top seems to make it work again. Keeping this open so it can be further looked into.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
