### ISSUE TITLE
[Issue] Videos only appear while refreshing

### ISSUE THREAD

**Issue by patrbraun** [futo-org/grayjay-android#247]
I'm not able to reopen #110 but I'm on 192 and now my videos no longer show up at all under my subscriptions tab. Let me know if there is some other info I could provide.

**Comment by DThomas44** [comment]
I had a similar issue (outlined in issue #212). Then today's auto update to 192 completely broke the subscriptions tab for me.

I got it working by uninstalling the app, then downloading a fresh APK from the website. Subscriptions tab is working as expected for me at the moment.

**Comment by patrbraun** [comment]
Oops, I figured a reinstall would probably fix it but just wanted to see if they wanted any information, didn't realize there was another one, I'll close this one then. Thanks

**Comment by Kelvin-FUTO** [comment]
I suspected this might be related to non-english youtube accounts (if you enabled certain settings). It caused channels to return no videos, meaning the live results were empty.
Which was fixed in 193. But not 100% certain.
