### ISSUE TITLE
Rumble Fetches loads of Creators I'm not subscribed to

### ISSUE THREAD

**Issue by beemandev** [futo-org/grayjay-android#249]
Set up a new Rumble account, subbed to one channel, in GrayJay went to Sources/Rumble/Logged In  then Import Subscriptions = 47 creators, I've never heard of.

**Comment by greengeckowizard** [comment]
Kind of like issue #217

**Comment by beemandev** [comment]
No, my issue purely refs the list of creators returned using import subs option of plugin

**Comment by TheQuickFox** [comment]
I got the same issue. When I try to import subscriptions from Rumble I get all sorts of channels I'm not subscribed to, and the channels that I am subscribed to are not in the list.
![Screenshot_20231110-220845](https://github.com/futo-org/grayjay-android/assets/30596092/cd8bdcdb-7a44-4f59-9c2c-7cf49d0c95f9)

**Comment by TheQuickFox** [comment]
Yesterday this issue was fixed for me. I tried the import again and I only got channels that I am actually following.

**Comment by TheQuickFox** [comment]
It seems this one was fixed today. (GrayJay version 195)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
