### ISSUE TITLE
Home tab displays arbitrary videos

### ISSUE THREAD

**Issue by Pandapip1** [futo-org/grayjay-android#250]
First of all, thank you FUTO for this amazing app! There's a small thing (bug? unintentional anti-feature?) I've found.

The home page displays videos from creators I'm not subscribed to and have no reason to want to watch. I believe that whatever recommendation algorithm is being used needs some serious tweaking, and that until it is fixed, the default should be to not display videos from creators you are not subscribed to.

**Comment by Pandapip1** [comment]
At the very least, the home tab should be populated with stuff that is at least adjacent to my subscriptions.

**Comment by koen-futo** [comment]
@Pandapip1 A custom recommendation engine is definitely going to be made in the future where users can choose the recommendation engine they want and this will then become another possible tab most likely.

The current "Home" tab is effectively a collection of all the home feeds for the platforms you have enabled. If you want these to be more personalized, you will need to be logged into the respective platforms.

**Comment by Pandapip1** [comment]
Okay, but at the very least can I hide videos from creators I'm not subscribed to until a custom recommendation engine is made?

**Comment by Kelvin-FUTO** [comment]
@Pandapip1 If you do not care about Home/recommendations, simply turn off the Home tab in settings (Settings=>Manage tabs => toggle the "Home" item).

Home is the home page of the platforms, and their respective recommendation engine. (Becomes personalized after login)
If you're not logged in, and were to just hide all non-subscribed, it would most likely cause a blank screen or only 1-2 videos as they might not be any overlap at all.

I can see a possible argument if you're logged into a platform, but that assumes platforms actually recommend your subscriptions, which is often not the case. Though this would be an option for when we add Home filters.

**Comment by Kelvin-FUTO** [comment]
@Pandapip1 Version 193 has the ability to hide creators from home (home video=>options=>"Hide creator from home"

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
