### ISSUE TITLE
No block option

### ISSUE THREAD

**Issue by Pandapip1** [futo-org/grayjay-android#251]
In the similar vein to my other bug report / feature request, there should be an option for users to block individual creators. Most app stores have this as a requirement, it shouldn't be too hard to implement, and I'm annoyed by specific channels repeatedly being recommended to me that I have absolutely no interest in watching.

**Comment by Kelvin-FUTO** [comment]
Version 193 has a "Hide creator from home" option.
Note that at the moment the only way to "undo" it is by clearing all hidden creators/videos in settings. So keep that in mind.
