### ISSUE TITLE
Swiping down on the video view locks rotation sideways

### ISSUE THREAD

**Issue by F1nnM** [futo-org/grayjay-android#263]
I have not been able to reproduce it, but is happened many times. At first I thought it might just be caused by overly sensitive rotation, but it just happened, when I had my phone fairly stable on my table, slightly propped up.

While in the default vertical view:
![image](https://github.com/futo-org/grayjay-android/assets/12767947/9390da55-0d30-4bf7-9f2a-52b48e4d8571)

When swiping down on the video, to minimize it, sometimes the app rotates so that the left side of the screen would be on the bottom. The video does minimize and we end up here:
![image](https://github.com/futo-org/grayjay-android/assets/12767947/af812891-2343-42c1-bede-1ebaea8a689e)

**Comment by F1nnM** [comment]
Actually I was just able to reproduce it:
Making a up-down motion like this: ^ on the video causes it. Not reliably, you have to play around a little, but I can now make it happen one out of four times.

**Comment by F1nnM** [comment]
And now I can reliably produce it.
It looks like there are two different handlers reacting to swiping in the center of the video.
One for upwards motion for fullscreen and one for downwards motion for minimizing.
Swiping up, then down, without interruption causes it.

**Comment by F1nnM** [comment]
When I leave the app in the sideways state from before, close the p-i-p and reopen the app, I end up here:
![image](https://github.com/futo-org/grayjay-android/assets/12767947/558be163-fef5-48ee-be66-29921b683802)

I don't know if vertical fullscreen is supposed to be a thing, but if it is: Clicking on the black area doesn't bring up the controls and title; only clicking on the video does so.

**Comment by greengeckowizard** [comment]
I've had this happen to me a bunch and it's very annoying.

**Comment by TiberiuNicolae** [comment]
Thank you for explaining why it does that. I can at least reduce this madness

**Comment by KannaHayabusa** [comment]
I really enjoy Grayjay but everything surrounding the rotation just makes me want to go back to ReVanced.

**Comment by Zvonimir-FUTO** [comment]
Rotation issues will be resolved through #67
