### ISSUE TITLE
Video stops to buffer when buffer is non-empty

### ISSUE THREAD

**Issue by Pandapip1** [futo-org/grayjay-android#264]
I'm pretty sure this is a bug with the youtube plugin. It seems to happen ~1/5 of the time, seemingly when grayjay is minimized while paused, then re-opened.

The video just stops and displays an indefinite loading spinner, indicating that the buffer is empty, which is obviously false because when I pause and immediately play (less than ~1/4 second), it reliably starts playing again until a 1-5 seconds later, when it happens again. Leaving it to "buffer" causes the video to start playing again after roughly 3-5 seconds. Restarting grayjay is the only way to reliably stop this bug, except the bug also sometimes disappears at random, causing normal playback to resume.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
