### ISSUE TITLE
A bunch of bugs

### ISSUE THREAD

**Issue by loveuseless** [futo-org/grayjay-android#265]
Not showing vids on any creators page. Showing wrong release date when watching vid.
Showing channel has 1 sub when watching vid.
![Screenshot_2023-11-10-21-45-32-261_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/53101813/8b6d0330-5410-4515-9daa-fe2e4124fcb1)
![Screenshot_2023-11-10-21-45-43-727_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/53101813/1f6fa387-433e-45fa-86f2-36ca874c51ec)
![Screenshot_2023-11-10-21-45-52-805_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/53101813/3b38f154-48fe-4cad-be12-c6c52c0357a1)

**Comment by RediTafa** [comment]
For the videos on every channel you should login with youtube(it worked for me)

**Comment by Kelvin-FUTO** [comment]
Version 193 should fix all these issues (available within an hour)
