### ISSUE TITLE
[Feature Request] Add odysee and other supported platforms to "open by default" list on android

### ISSUE THREAD

**Issue by highghlow** [futo-org/grayjay-android#266]
I subscribe to creators on youtube and odysee using my rss reader. If I'm subscribed on youtube, I can open up the video in grayjay directly from the reader, while with odysee it opens in the browser. Please add odysee.com (and others) to the "open by default", and maybe even allow users to add any link in there (athough, that might not be possible)

**Comment by Kelvin-FUTO** [comment]
Sadly indeed we cannot have open by default customizable.
But indeed we can add it for the plugins we have.

**Comment by highghlow** [comment]
I'm a little bit late, but it's fixed. Now the app opens these links:
 - soundcloud.com
 - nebula.tv
 - rumble.com
 - patreon.com
 - kick.com
 - youtu.be
 - m.youtube.com
 - twitch.tv
 - youtube.com
 - www.youtube.com
 - www.you.be
 - odysee.com
You can enable these as Settings > Apps > Grayjay > Open by default > Add link

**Comment by Philippe-Choquette** [comment]
Grayjay throws an error when sharing this URL to it:
https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1903930520&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true#

It's the URL of some podcast on Soundcloud.

@Kelvin-FUTO
