### ISSUE TITLE
Failed to Fetch youtube.com

### ISSUE THREAD

**Issue by CosmicIndustries** [futo-org/grayjay-android#267]
_Failed to fetch youtube.com when trying to import old subscriptions, new ones work fine._

Description:

  I have been using Grayjay Video App for a while now and was looking to import my old subscriptions from YouTube. However, I ran into an issue where the app is unable to fetch the subscriptions from youtube.com. The following error message is displayed "Failed to fetch youtube.com".

Steps to Reproduce:

1. Open Grayjay Video App.
2. Select "YouTube" as the source platform.
3. Enter login credentials.
4. Tap on the "Import Subscriptions" option.
5. Wait for the app to attempt fetch the remaining old subscriptions.
6. Observe the "Failed to fetch youtube.com" error message.

Expected Result:

The app should be able to fetch the old subscriptions from youtube.com without any error message.

Additional Information:

- New subscriptions added through youtube.com are working fine.
- I have tried logging out of YouTube and logging in again, but the issue persists. 
- I'm using the latest version of the Grayjay Video App.

Please let me know if any further information is required to fix the issue. Thank you in advance.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
