### ISSUE TITLE
Chapters don't work properly in fullscreen

### ISSUE THREAD

**Issue by ugiefiewf** [futo-org/grayjay-android#269]
When watching a video in fullscreen, the chapters don't properly update as the video plays. It stays on the first chapter unless you manually skim through the video (and won't load any chapter if you enter fullscreen fast enough when the video starts). Exiting fullscreen also fixes the issue.

Example video (the one I tested): https://www.youtube.com/watch?v=rCmsoa2Zlhg

**Comment by Kelvin-FUTO** [comment]
This is most likely solved in version 199 including some other chapter accuracy improvements.
