### ISSUE TITLE
visual bug, download rate stacks on channel name with error message present

### ISSUE THREAD

**Issue by palmerbomber1** [futo-org/grayjay-android#274]
I went to download an age restricted video from rSlash not realizing i had the age restricted setting turned off to allow viewing, the download gave an error about the age restriction. After turning it on to allow age restricted content, restarting the app, (it crashed probably because i had 73 videos in the download queue and was watching another, if i reproduce I'll post about that later) and going back to the download tab stacked the download rate over the channel name with the error message under. 

It appears that the error message pushed download rate up

![IMG_20231111_041603](https://github.com/futo-org/grayjay-android/assets/117899984/1274dfc5-afdc-4f01-836e-0129781736fc)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
