### ISSUE TITLE
[Feature Request] - Ntfy notification service 

### ISSUE THREAD

**Issue by Today20092** [futo-org/grayjay-android#275]
I'm hoping for the integration of ntfy, a way to recieve push notifications without the use of Google servers.

https://docs.ntfy.sh/

**Comment by Kelvin-FUTO** [comment]
We don't use Google servers, we don't use push notifications, we have no servers to push notifications from.
Grayjay works almost entirely local, meaning the notifications are handled locally too.

So ntfy wouldn't do anything for us.

**Comment by Today20092** [comment]
Thank you for your reply!
