### ISSUE TITLE
Harbor: Claim Discord is broken

### ISSUE THREAD

**Issue by beemandev** [futo-org/grayjay-android#277]
In Harbor app, when you claim Discord/Login with Discord = An external application Harbor(Test) wants to access your Discord account. Click Authorise = Returns to Harbor = Message "Unable to verify your  account credentials "

**Comment by mraxilus** [comment]
For reference, here's a screenshot of it happening to me:
![Screenshot_20231101-085953](https://github.com/futo-org/grayjay-android/assets/1268439/9696d68e-0dae-4766-a964-9a079bafb7c5)

**Comment by beemandev** [comment]
Yes, it now works for me. Unsure if was just a problem that day or incorrect error message was popping up?

**Comment by beemandev** [comment]
Yes, it now works for me. Unsure if was just a problem that day or incorrect error message was popping up?

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
