### ISSUE TITLE
Search results dissapear after going to channel and going back

### ISSUE THREAD

**Issue by AidanG1** [futo-org/grayjay-android#28]
search anything in the search bar -> tap a channel & let it load -> use a swipe gesture to return to the previous screen (search results) -> the page is blank, repopulates when refreshed.

**Comment by AidanG1** [comment]
This behavior also occurs with playlists

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. 
Feel free to open a new issue if you are still encountering this.
