### ISSUE TITLE
[UI problems] video black bars don't function 

### ISSUE THREAD

**Issue by Maludo99** [futo-org/grayjay-android#281]
When watching videos in full screen, if screen isn't a 16:9 aspect ratio there are black bars on each side of the video. 
Fast forwarding, rewinding, increasing volume and brightness all do not work in these regions

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
