### ISSUE TITLE
[BUG] Subscribing doesn't subscribe on creator page

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#284]
When you hit subscribe on the creator and go to their channel page or creator page it doesn't update the subscription status.

platform player version 193

Here is a screen capture of this in action 🎬 
https://github.com/futo-org/grayjay-android/assets/34012548/24247980-0e79-453d-8849-b8851744f21e

**Comment by greengeckowizard** [comment]
This only occurs if you hit the creator page first and then hit subscribe from when you are on a video and then swipe to close the video and go back to the creator page and you can see that the subscription status hasn't changed.

**Comment by greengeckowizard** [comment]
Doesn't update when you unsubcribe either

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
