### ISSUE TITLE
YouTube feed isn't relevant

### ISSUE THREAD

**Issue by bideco** [futo-org/grayjay-android#285]
Every video from YouTube on my home feed is something I've never watched by someone I've never heard of, is this a bug, is there a toggle somewhere? It fetches my subscriptions correctly because the subscriptions tab shows people I watch, but none of the home feed videos are remotely relevant to my watch history.

**Comment by thebe14** [comment]
It's explained in the faq. Unless you're signed in, each platform doesn't know what to recommend you, so you get garbage. Either sign in or just hide the Home tab for now. They are working on some user recommender engines, if I understood correctly.

**Comment by bideco** [comment]
> It's explained in the faq. Unless you're signed in, each platform doesn't know what to recommend you, so you get garbage. Either sign in or just hide the Home tab for now. They are working on some user recommender engines, if I understood correctly.

I was signed in.
