### ISSUE TITLE
[Feature Request] Change storage location for downloads

### ISSUE THREAD

**Issue by K4TieK** [futo-org/grayjay-android#286]
I think that this would be a reasonable option incase people have a micro sd card which potentially could have more storage than the one based on the device itself.

**Comment by Kelvin-FUTO** [comment]
This should be implemented in upcoming 194 with a complete overhaul of the export file system to work better with some Android versions (SAF).

**Comment by K4TieK** [comment]
Awesome, but when i buy a sd card and insert it into my phone will there be any option to change the storage to the sd card instead of my phone?

**Comment by Kelvin-FUTO** [comment]
Yes, you can set it to whatever location you like. This should already be live. It will ask you to select a directory.
