### ISSUE TITLE
[Issue] cant export music files 

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#287]
Ive just downloaded a video audio only , but cannot export it anyway. I thought that might me cause of a regular issue but realized i can easily export regular videos @Kelvin-FUTO

**Comment by Hellreaver** [comment]
> Ive just downloaded a video audio only , but cannot export it anyway. I thought that might me cause of a regular issue but realized i can easily export regular videos @Kelvin-FUTO

I have the same issue - audio only exports do not work, but video+audio do. Android 14, pixel 8 pro.

**Comment by HafizBeyy** [comment]
> > Ive just downloaded a video audio only , but cannot export it anyway. I thought that might me cause of a regular issue but realized i can easily export regular videos @Kelvin-FUTO
> 
> I have the same issue - audio only exports do not work, but video+audio do. Android 14, pixel 8 pro. 

 Bro plz mention rep admins

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
