### ISSUE TITLE
[Bug] Download via Playlist doesent use "primary language"

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#296]
When  i ad a video with multiple audio tracks to a downloaded Playlist it seams to use a random language. 
In my opinion it should try to download the app language

**Comment by Kelvin-FUTO** [comment]
I believe by default it should automatically select the language you put in settings (Player=>"Primary Language").
If it doesn't do that then thats a bug.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale.
