### ISSUE TITLE
Membership button brings you to previous visited channel

### ISSUE THREAD

**Issue by greengeckowizard** [futo-org/grayjay-android#298]
Hello I have found a bug from which if you hit a membership button on a YouTube video it takes you to at least for mine it took me to the previous channel I visited and not the current channel you are trying to access. I do not have any membership I just wanted to see what it did if it would ask me or not to subscribe to the membership.
 Here's a screen capture of this bug in action 🎬 

https://github.com/futo-org/grayjay-android/assets/34012548/b4860caf-a741-437e-bda2-d34f09f9c80b

**Comment by Kelvin-FUTO** [comment]
Already fixed in the upcoming build (194).
If no membership exists for the current channel, it will not clear it atm.
