### ISSUE TITLE
Damn chapters

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#299]
They are not moving automtically to the next chapter by the video moves. For instance , i was watching a video and the video got the another chapter, but i realized the player didnt. I wanted to ensure cause maybe thats because the creator put the chapter to another second, but when i was moving player manually, the chapter changed the exact time it didnt previous one

**Comment by Kelvin-FUTO** [comment]
I have a hard time understanding what you mean..

Chapters by default are only a visual aid to see the current chapter. They should automatically change as the video plays or you scrub over it.
While scrubbing it will show the current chapter you are scrubbing over.

UI doesn't show chapter separation yet. This is future work.

**Comment by HafizBeyy** [comment]
> I have a hard time understanding what you mean..
> 
> Chapters by default are only a visual aid to see the current chapter. They should automatically change as the video plays or you scrub over it.
> While scrubbing it will show the current chapter you are scrubbing over.
> 
> UI doesn't show chapter separation yet. This is future work.

Ive been suffering to try how to tell things in my mind. So sorry for that comment

**Comment by SupremeLobster** [comment]
> I have a hard time understanding what you mean..
> 
> Chapters by default are only a visual aid to see the current chapter. They should automatically change as the video plays or you scrub over it.
> While scrubbing it will show the current chapter you are scrubbing over.
> 
> UI doesn't show chapter separation yet. This is future work.

Will skippable chapters also show a "skip" button? Like for sponsorblock segments, for example

**Comment by Kelvin-FUTO** [comment]
@SupremeLobster 
Depends on your plugin settings.
If you put it as Manual, it wills how a button at the top of the screen that allows you to skip manually.
If you put it to Automatic, it will give you a small toast message telling you that it skipped it automatically.

**Comment by SupremeLobster** [comment]
> @SupremeLobster 
> Depends on your plugin settings.
> If you put it as Manual, it wills how a button at the top of the screen that allows you to skip manually.
> If you put it to Automatic, it will give you a small toast message telling you that it skipped it automatically.

Oh I see it now. However the problem appears to be that the button does not appear, if you are watching in landscape, until you switch to portrait and then back to landscape. Same thing happens with the chapter strings, where sometimes they dont get updated if you are watching in landscape.

**Comment by Kelvin-FUTO** [comment]
@SupremeLobster Managed to reproduce it, seems something is going wrong with chapter updating in landscape mode. Will investigate and fix.

**Comment by Kelvin-FUTO** [comment]
Right, I believe this has been fixed on the development side, some changes were already made for sub-second chapter accuracy which changed some of this stuff already. I'll add another comment when we release a new stable that contains this fix.

**Comment by Kelvin-FUTO** [comment]
We're deploying the build likely today (196), So I'm closing this.
