### ISSUE TITLE
[Feature Request] Adding unlisted playlists by its URL on the app

### ISSUE THREAD

**Issue by samsunga50** [futo-org/grayjay-android#30]
When using NewPipe it's possible to add unlisted or public playlists by pasting the playlist link in the search bar. Would like this feature in GrayJay as well...

**Comment by Kelvin-FUTO** [comment]
In upcoming version 278+ you can either open a playlist url through Android using Grayjay (if you configured Grayjay as default). Or paste a playlist url directly in the search bar to navigate to a playlist directly (without searching/browsing for it).

@dimyself Regarding some of your questions:
 - Import playlists converts playlists to local on-device playlists. So you can log out if you prefer.
 - We cannot automatically discover unlisted account playlists, or access private account playlists. For the majority of users login makes sense, as they might also want to use login in general for a useful home page. But now you can manually open and save playlists using the methods mentioned above.
 - By default, we exclusively use login for home page and importing, besides that your authentication is exclusively used for stuff you manually opted in for in the plugin settings.
 - You can logout, and then we ditch any authentication you added previously. By default we try to not even use your login except if its required (like import, or a useful home page). Lots of users do actively prefer using the authenticated requests so they have access to more features, and history to show up on their Youtube account.
