### ISSUE TITLE
[Feature Request] Graying out watched videos

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#300]
I use playlists extensively and would advocate for something similar to #189 that can be used across the whole app including playlists (and profile pages etc). Graying out the thumbnail or adding a little symbol (like the download symbol)

**Comment by Doubs115** [comment]
I was also looking for this.
Youtube had a "watched" that would apear in the bottom left of a thumbnail and they removed it after a month for some reason.
A clear symbol, word, or something below the tile saying previously watch is really needed. As well as a filter along with it.

**Comment by Doubs115** [comment]
Coming back with another thought, I would like to see a filter option somewhere. This could show up just on subscriptions or on the homepage aswell.

Like most email services you should be able to select atleast 1 filter: unwatched, watched, newer first, older first, and custom date. Another addition could be additional settings with changing default filters.

**Comment by mnbvasd** [comment]
I'd just like the option for videos to be hidden when watched. I like Newpipes implementation, where there is an option, that can be set with a %age of watch time, or a manual flag.

**Comment by Zvonimir-FUTO** [comment]
Will be solved through #189.
