### ISSUE TITLE
Use player for random YT links

### ISSUE THREAD

**Issue by thebe14** [futo-org/grayjay-android#301]
I'd like to use the awesome player built into grayjay to play YT videos for which I received a link over whatever chat I use. These are sent by friends and are usually from channels/creators I'm not subscribed to.

Even more interesting would be to register the app to handle any URL to YT videos, if the YT plugin is enabled (re-register eac time I enable the plugin). Similar with other plugins/platforms.

**Comment by Kelvin-FUTO** [comment]
This is already works. You likely have the Play store version, which doesn't support this.
Use our own apk from the official website: https://grayjay.app/
You might have to disable the official youtube app url handling and enable Grayjays handling in Android, as we cannot do this within the app automatically.

Re-enabling whenever you enabling the YT plugin is going to be hard, as these things need to be defined at compile-time for android.

**Comment by beemandev** [comment]
That wants to be in the FAQ
