### ISSUE TITLE
Cannot scroll/see all playlists in download section.

### ISSUE THREAD

**Issue by SlyIndigoWolf** [futo-org/grayjay-android#304]
I have downloaded multiple playlists and they auto download anything I add to them which is great. However, on the 'Downloads' tab, I can only see 3 playlists and I cannot scroll to the left to see the others.

Maybe changing the display to a grid setting with the playlist thumbnails would work?

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
