### ISSUE TITLE
Polycentric export from Grayjay and import

### ISSUE THREAD

**Issue by protofolius** [futo-org/grayjay-android#306]
The exported polycentric string from the Grayjay android app can not be successfully imported by

-importing the profile on https://polycentric.io/setup
-installing the "app" and importing (tried to copy the string to a profile.polycentric file for import , stripping the string of the initial polycentric:// part)
-adding the "app" to homescreen and desktop
-scanning the QR code (gives error "there arent any apps on your phone that can use this QR code , while the app is installed and added to the home screen)
-using "share" to send the identity to another app
-pasting the entire polycentric:// string in a browser url field

tried on android and windows using different browsers (edge,chrome,firefox)

**Comment by koen-futo** [comment]
The current Polycentric site it oudated and not compatible with the Harbor/Grayjay Polycentric imports/exports. The promise from the team is that it will be updated soon.
