### ISSUE TITLE
Mini Player Instability

### ISSUE THREAD

**Issue by JDog2pt0** [futo-org/grayjay-android#308]
Use of the mini/overlay/popout player (whatever you want to call it) results in device instability. After X amount of time (it varies) the phone becomes very laggy. Usually either Grayjay ends up crashing, or Mullvad ends up crashing. Stopping Grayjay and restarting fixes it at least temporarily. Using the app full (not minimized) does not seem to cause any issue. 

Pixel 4XL Android 13 (yes it's old, I'm broke)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
