### ISSUE TITLE
Sometimes my like shows as 0, and when I unclick the like, the count shows "-1" likes, which should be impossible.

### ISSUE THREAD

**Issue by qdirks** [futo-org/grayjay-android#310]
It seems to be counted correctly if I close the video and reopen the video, but it kind of freaks me out sometimes, you know, bc I wonder if my like is being counted, and then when I unclick it it shows -1 which is def not what I want.

BTW, I meant on comment likes. I don't recall if this also sometimes happens on video likes.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Comment by qdirks** [comment]
This is not fixed. I will open a new issue with better steps to reproduce. I think I did not include steps to reproduce here because I was on my phone at work at the time and didn't have time.

**Comment by Zvonimir-FUTO** [comment]
Great that will definitely help.

**Comment by qdirks** [comment]
#1360
