### ISSUE TITLE
[Feature request] [QoL] Better landscape formatting

### ISSUE THREAD

**Issue by SevastianGit** [futo-org/grayjay-android#312]
Since we recently got an option to "Bypass Rotation Prevention" I've thought that it'd be great if the current feed styles could better adapt to being in landscape mode (Make things/feed fit in frame properly, etc.) so the app could be fully usable in landscape mode. I initially thought that using the "List" feed style would be the fix to using the app in landscape (and wanted to request to have an option to choose a different feed style for landscape, this might still be good to look into if landscape formatting is fixed) but even then the thumbnails were rather small and there was too much empty space, so I believe it'd be greater if landscape formatting as a whole for both feed styles would be fixed (Make Preview feed style behave in a similar fashion to how it does in the YouTube app, maybe more like the tablet version specifically).

You guys are amazing, thank you for everything you do❤️

**Comment by valdotdev** [comment]
Any updates on this? Not rushing or anything just wondering if there's a timeline. Though having to fullscreen just to view the whole video in landscape is becoming cumbersome especially if you want to watch and see the comments at the same time.

**Comment by koen-futo** [comment]
@valdotdev Sadly not yet, we are very much occupied with the desktop app at the moment. We will resume nailing out features for the Android app once it is out, shouldn't be too long.

**Comment by valdotdev** [comment]
@koen-futo No worries! Thanks for the update!

**Comment by Zvonimir-FUTO** [comment]
Landscape mode has been implemented.
