### ISSUE TITLE
Why no notifications tab?

### ISSUE THREAD

**Issue by samuraiskill** [futo-org/grayjay-android#313]
If you haven't noticed, there is no section to read all the comments you've posted unless you return to the video you've watched. Or am I missing something..? I just don't have a notifications tab. Or the option to have one. Help us out by adding one please. _**Oni**_

**Comment by Zvonimir-FUTO** [comment]
Comments tab has been implemented.

**Comment by PhilC813** [comment]
@Zvonimir-FUTO Probably not the most requested feature, but I don't think Polycentric comments stand a chance against the native platform until we get notified of replies (and maybe also up/downvotes). Currently, if you're curious of possible replies to your comments, it's a manual process that require you to scroll down the whole comments tab.

I know it's possibly difficult to implement, but I would suggest reopening this feature request and possibly renaming it to something like "Implement notifications (push/section) for Polycentric comments", which I believe was what OP really meant to have.
