### ISSUE TITLE
[Bug] "Light leak" (random gray lines) in video player?

### ISSUE THREAD

**Issue by SevastianGit** [futo-org/grayjay-android#315]
Upon using the app extensively, I cannot help but notice these odd, gray lines on top of the screen on each video I watch, if I use any other app to watch videos I get no such weird lines clipping into my videos, so this must be some odd bug.
Here's a screenshot with the gray lines shown (pointed at): https://i.ibb.co/F00JXqC/IMG-20231115-223524.png

Not sure what they really could be.

**Comment by greengeckowizard** [comment]
What phone do you have? 
I have a Samsung S10 Plus and swiping that side gray opens a tool bar or app panel. I'm just wondering if that's your case as it looks like a bug but it just overlays on apps.

**Comment by SevastianGit** [comment]
@greengeckowizard I am aware of the edge panel feature you're mentioning, but I'm on an AOSP custom ROM (on a Samsung device) and this is definitely a part of the app itself.
Using the Rotation Control app I forced the app to be in portrait mode in the video player and you can see that entire "gray line/separator" thing at the top, to me it looks identical to the one just above the navigation buttons (Home, subscriptions, etc.) on the main app screen: https://i.ibb.co/zmHY30r/Screenshot-20231115-233212-Grayjay.png

**Comment by b-risk** [comment]
Happens on Pixel as well

**Comment by Doc-4** [comment]
Have this happening on both a OnePlus 7T Pro and a Pixel 8 Pro, running very different versions of Android. This also happens on external displays, which makes it quite a lot more distracting.

**Comment by SevastianGit** [comment]
I believe this to be one of the just weirder small issues that are still here after multiple updates, left unnoticed, definitely an issue of the app that needs fixing

**Comment by xephos1one** [comment]
Also happening on my Sony Xperia 5V with Android 14 and Grayjay Version 236.
To specify: the lines are left and right of the actual video (or does it continue behind?).
Ony my 21:9 display they therefore exist e.g. on 16:9 videos and as even longer lines next to 4:3 videos.
Zooming into the video to fill the screen removes the lines.

**Comment by SevastianGit** [comment]
> Also happening on my Sony Xperia 5V with Android 14 and Grayjay Version 236. To specify: the lines are left and right of the actual video (or does it continue behind?). Ony my 21:9 display they therefore exist e.g. on 16:9 videos and as even longer lines next to 4:3 videos. Zooming into the video to fill the screen removes the lines.

+1, zooming in does hide the lines
Goofy bug this is

**Comment by b-risk** [comment]
This bug is distracting and potentially harmful to OLED displays, hope they will fix it soon.

**Comment by Doc-4** [comment]
This bug and the bug where some videos have the last few seconds truncated have been here since the alpha client. I really hope they fix these bugs, they've been the last thing holding me off from switching to Grayjay fully since it came out.

**Comment by SevastianGit** [comment]
> This bug and the bug where some videos have the last few seconds truncated have been here since the alpha client. I really hope they fix these bugs, they've been the last thing holding me off from switching to Grayjay fully since it came out.

#36 Known, but apparently not easy to fix, lower priority due to other more important issues existing.

**Comment by michael-oberpriller** [comment]
This can be fixed by setting the background of video_player in video_view.xml.
```
<androidx.media3.ui.PlayerView
    android:id="@+id/video_player"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/black"
    app:default_artwork="@drawable/placeholder_video_thumbnail"
    app:show_buffering="always"
    app:use_artwork="true"
    app:use_controller="false" />
```

**Comment by Doc-4** [comment]
> This can be fixed by setting the background of video_player in video_view.xml.
> 
> ```
> <androidx.media3.ui.PlayerView
>     android:id="@+id/video_player"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:background="@color/black"
>     app:default_artwork="@drawable/placeholder_video_thumbnail"
>     app:show_buffering="always"
>     app:use_artwork="true"
>     app:use_controller="false" />
> ```

Very cool assuming it works! One or two major bugs potentially fixed. Do you intend to file a pull request? If not, I don't mind doing it.

**Comment by michael-oberpriller** [comment]
> > This can be fixed by setting the background of video_player in video_view.xml.
> > ```
> > <androidx.media3.ui.PlayerView
> >     android:id="@+id/video_player"
> >     android:layout_width="match_parent"
> >     android:layout_height="match_parent"
> >     android:background="@color/black"
> >     app:default_artwork="@drawable/placeholder_video_thumbnail"
> >     app:show_buffering="always"
> >     app:use_artwork="true"
> >     app:use_controller="false" />
> > ```
> 
> Very cool assuming it works! One of two bugs that annoyed me greatly potentially fixed. Do you intend to file a pull request? If not, I don't mind doing it.

I believe contributions are not currently being accepted as stated in the contribution guidelines.

**Comment by Doc-4** [comment]
That might be the case. I only glanced and saw that there were open pull requests and that the tab wasn't disabled.

**Comment by b-risk** [comment]
> > This can be fixed by setting the background of video_player in video_view.xml.
> > ```
> > <androidx.media3.ui.PlayerView
> >     android:id="@+id/video_player"
> >     android:layout_width="match_parent"
> >     android:layout_height="match_parent"
> >     android:background="@color/black"
> >     app:default_artwork="@drawable/placeholder_video_thumbnail"
> >     app:show_buffering="always"
> >     app:use_artwork="true"
> >     app:use_controller="false" />
> > ```
> 
> Very cool assuming it works! One of two bugs that annoyed me greatly potentially fixed. Do you intend to file a pull request? If not, I don't mind doing it.

Talk to FUTO on Zulip, I remember seeing somewhere they might have said things might've changed.

**Comment by b-risk** [comment]
> > > This can be fixed by setting the background of video_player in video_view.xml.
> > > ```
> > > <androidx.media3.ui.PlayerView
> > >     android:id="@+id/video_player"
> > >     android:layout_width="match_parent"
> > >     android:layout_height="match_parent"
> > >     android:background="@color/black"
> > >     app:default_artwork="@drawable/placeholder_video_thumbnail"
> > >     app:show_buffering="always"
> > >     app:use_artwork="true"
> > >     app:use_controller="false" />
> > > ```
> > 
> > 
> > Very cool assuming it works! One of two bugs that annoyed me greatly potentially fixed. Do you intend to file a pull request? If not, I don't mind doing it.
> 
> I believe contributions are not currently being accepted as stated in the contribution guidelines.

I asked FUTO on Zulip about this issue and the one where video playback is off centered on phones with a cutout and never got a reply, maybe I would try asking them if they would accept your PR or if they could add it themselves

**Comment by JasonCraft** [comment]
Does this mean you won't be fixing it?
It might seem trivial but hours and hours of those same pixels lighting will eventually cause damage.

Your app is the best I've found for browsing YouTube, please consider it since I'm too worried about my screen to use the app.

**Comment by Zvonimir-FUTO** [comment]
It will be fixed, we are not ignoring it.

**Comment by SevastianGit** [comment]
Ever since the latest v268 Grayjay update I don't see any gray lines in the player anymore on any video!:D Could others confirm before I close this issue?

**Comment by Doc-4** [comment]
The only place I see anything similar is when watching a portrait video not in fullscreen in the negative space, but this hardly matters and goes away in fullscreen. I haven't had a chance to test an external monitor, but I imagine it won't matter, seems like the light leak is finally dead!

**Comment by Zvonimir-FUTO** [comment]
Yes we fixed this in v267 but I forgot to close this one. Thank you guys for your feedback :)
