### ISSUE TITLE
[Feature Request] Automatically add hyphens to key activation 

### ISSUE THREAD

**Issue by chowder3907** [futo-org/grayjay-android#318]
When putting in the activation code, it would be nice if it added in the hyphens automatically when you typed. Maybe a small GUI hint (like a translucent hyphen in place) would be a good way to indicate to the user it'll automatically fill them

**Comment by lflaurflorin** [comment]
As long as it doesn't affect copy and paste, i cam see it work.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale.
