### ISSUE TITLE
Screen don't go to sleep after video is ended

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#322]

**Comment by trosh** [comment]
I confirm this is an issue: last night I fell asleep watching a video and this morning I have OLED burn-in! It's slight, but very noticeable and sharp on dark gray backgrounds 
First time it's happened to me!
I'm now trying to compensate the burn-in by displaying full screen a screenshot of the offending display, with colours inverted:
![Screenshot_20231117_083812_Grayjay.png](https://github.com/futo-org/grayjay-android/assets/3617724/e1a03264-ba06-4785-9676-f0b77e934671)

Anyway, thanks for the hard work!

**Comment by koen-futo** [comment]
This should be fixed in the next build.
