### ISSUE TITLE
Cannot like/unlike video comments or leave a reply

### ISSUE THREAD

**Issue by lflaurflorin** [futo-org/grayjay-android#325]
Hi. 

In version 195, i tested the comments ("platform comments") section to like/unlike comments or leave a reply to them, but it doesn't work. - for YouTube, that is, if it's relevant - for other platforms, I haven't tested this.

Hopefully it can be corrected somehow in the future.

I do like this app so much in rest 🙏 thank you for your efforts!

**Comment by Shihabkh** [comment]
Same

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #97
