### ISSUE TITLE
Implementation of a setting feature to filter tabs by source

### ISSUE THREAD

**Issue by Dr3adN07** [futo-org/grayjay-android#327]
I use twitch to keep up with certain streamers, not to discover new ones. I use YouTube to discover new creators and follow ones I've seen before. Having the twitch plugin active I am shown twitch suggestions on the home tab. It would be nice if I could disable twitch for my home tab, but still be able to find twitch streamers I follow in my subscriptions tab.

**Comment by McIrco95** [comment]
Deactivate 
Sources/Twitch/Visibility/Home
