### ISSUE TITLE
Download playlist button only appears in landscape orientation

### ISSUE THREAD

**Issue by CommanderKittens** [futo-org/grayjay-android#329]
When viewing a playlist, the download button only appears if the rotation is in landscape, not portait.

Pixel 7
Android 14
System display settings:
Display size - largest
Font size - second smallest
Bold text - off

![Screenshot_20231117-064334](https://github.com/futo-org/grayjay-android/assets/97068474/9607eb78-41c2-4a23-a5bb-6ede5f79d8d3)
![Screenshot_20231117-064344](https://github.com/futo-org/grayjay-android/assets/97068474/144bce14-97a0-40bd-8160-19a8a4ceaefc)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
