### ISSUE TITLE
Queue doesn't autoplay the next song

### ISSUE THREAD

**Issue by nater147** [futo-org/grayjay-android#330]
While playing a queue, when it gets to the next video, the autoplay fails to play. I have to manually hit play.

The queue I'm interacting with is all from my downloads, and is all audio with no video.

**Comment by nater147** [comment]
Can't recreate the bug since the latest update. Current version is version 200. I reported the bug on 198. Not sure if it was intentionally fixed.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
