### ISSUE TITLE
Kick plugin misbehaving.

### ISSUE THREAD

**Issue by codebybark** [futo-org/grayjay-android#340]
When I go into search and one character in it gives me a prompt saying
"[Kick (Beta)] [Kick (Beta)] Attempted to access non-whitelisted url: https://search.kick.com/multi _search (19)[24-25].  Plugin [Kick (Beta)]"
And so I try to turn of kick in sources which works untill the app reloads and so does the kick plugin. And so the cycle restarts.

**Comment by Kelvin-FUTO** [comment]
This will be solved in version 199.
Note that this is only relevant for creator search, as Kick does not have video search on their website.
