### ISSUE TITLE
Unknown URL Format YouTube Embed

### ISSUE THREAD

**Issue by peterc-s** [futo-org/grayjay-android#343]
When opening links from websites like Twitter with grayjay set as my default for YouTube links, I get the following error message:
![Screenshot_20231120_180717_Grayjay.png](https://github.com/futo-org/grayjay-android/assets/66807853/d8fd913d-629c-432b-bf60-deeba95b8535)

**Comment by Kelvin-FUTO** [comment]
In Youtube plugin version 156/157 embedded plugins now get rewritten into normal video urls, and thus work.
