### ISSUE TITLE
Settings - Preferred meter quality

### ISSUE THREAD

**Issue by JWhiteford** [futo-org/grayjay-android#348]
There are a few places in the app settings that can be confusing to a basic user. For example in "settings > player > preferred metered quality".

Changing the wording to something less technical would benefit more users.

The order of this setting and the following "preferred quality" sound as if they are in conflict.

Possibly something as simple as:
Label1 = preferred resolution

Label2 = data usage resolution
HelperText = choose a lower resolution when using mobile data

**Comment by Kelvin-FUTO** [comment]
The ordering is indeed wrong (Quality should be first). Metered is not necessarily cellular and is a wider concept, hence the name. Its a name often used in OS as well.

That being said, I will add descriptions that clarify this for sure.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay.
