### ISSUE TITLE
[Issue] importing playlists

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#349]
I know you guys got bored im continuously mention about tthaat but, its very important as for me to access those playlists

**Comment by koen-futo** [comment]
I will look into this soon.

**Comment by HafizBeyy** [comment]
> I will look into this soon.

Thanks! 🙏🙏

**Comment by Ser-Bul** [comment]
Duplicate of https://github.com/futo-org/grayjay-android/issues/85
