### ISSUE TITLE
Error when subscriibing to the Netflix YouTube channel

### ISSUE THREAD

**Issue by AidanG1** [futo-org/grayjay-android#35]
![image](https://github.com/futo-org/grayjay-android/assets/30811794/c6858354-3e5c-4cd6-ae8f-667a20738771)

**Comment by AidanG1** [comment]
![image](https://github.com/futo-org/grayjay-android/assets/30811794/bf86132e-eef4-4491-8c43-35ffd3552ae2)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
