### ISSUE TITLE
[Feature request] option to remove finished twitch livestreams from subscriptions

### ISSUE THREAD

**Issue by Tizitendo** [futo-org/grayjay-android#355]
I want to see the streams that are currently live in my subscriptions, but not the streams that are already over.
There are options in the individual subscription that lets you select to only see livestreams, but this doesn't seem to work, at least in the subscriptions tab. I don't know if that's a big or not

**Comment by Kelvin-FUTO** [comment]
In the subscriptions tab, if you toggle off Videos and Planned, you should already only see live streams.
If this is what you want (and thus already supported), then close this issue.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale.
