### ISSUE TITLE
[Issue] FCasting HLS streams doesn't allow you to select the quality

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#358]
When a HLS stream I'm unable to select the stream quality. It also ignores my default settings in the settings tab.

When it is available at >= 1080p60, the casting device will try to play it at maximum quality, and if it can't keep up, it will fail and drop down to the lowest possible resolution and bit-rate, such as 240p.

**Comment by koen-futo** [comment]
Was this for FCast on Android, Linux, Windows or MacOS?

**Comment by mnbvasd** [comment]
It ignores my settings for FCast on both Linux and MacOS.
I only get the quality degradation on Linux, the Mac can handle the bit rate.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
