### ISSUE TITLE
[Issue] Volume broken for certain codecs/bit rates

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#359]
When watching certain videos from YT with configurable audio, the audio sometimes "jams" at a fairly high volume, or doesn't work. It keeps defaulting to a loud broken one for me.
Neither the phone's volume setting, or the full screen gesture controls work, despite their indicators suggesting they're working. 

In my example:
mp4a40.2 - 133kbps - works as expected.
mp4a40.5 - 198kbps - loud, no control
mp4a40.2 - 391kbps - loud, no control
ec-3 - 387kbps - silent
ac-3 - 391kbps - silent

example video: https://www.youtube.com/watch?v=zE47eoE64Io

Hardware: Fairphone 4
OS: CalyxOS - latest

**Comment by koen-futo** [comment]
That's a lot of good information. Thank you.

"Neither the phone's volume setting, or the full screen gesture controls work"

This indicates that the ExoPlayer volume setting is being ignored... we could try giving ExoPlayer an update soon and hope that helps.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
