### ISSUE TITLE
Problem importing YouTube playlists

### ISSUE THREAD

**Issue by Vallialenz** [futo-org/grayjay-android#370]
I am having problems with trying to import my YouTube playlists to grayjay so I could make offline playlist from them. Am I doing something wrong?
I have described my process in more detail below.

I installed grayjay through the universal Android .APK from the website, I then updated the app and the YouTube plugins and restarted the application.
I then signed in to the YouTube through the plugin which then changed to show the logout buttons and the import buttons. Importing subscriptions worked perfectly and showed all my account's subscriptions.
When trying to import YouTube playlists, I get message "no playlists to import" despite my account having dozen playlists with few hundred videos on them in total. I thought it might be due to my playlists being private so I set them to public and tried again with no luck. I reinstalled the app from a fresh download of the universal .APK before attempting to find my playlists again but I still get "no playlists to import".
I then attempted to manually find my playlist through the search by typing the playlist address as "www.youtube.com..." without the https, but it shows a blank screen after looking like it loaded multiple videos to display, but that didn't work. I tried this with multiple playlists.

Lastly I tried to search for an automatically created YouTube playlist, and the application was able to discover it and show the list of videos, showing that the application should be able to display video lists.

Is this user issue on my part and me doing something wrong or is it a bug with the application? 
I see multiple questions in regard to this issue going as far back as 1 month ago but only answers to it are "did you try just using the import" and "try reinstalling the application". I also saw some mentions about manually importing the playlist with a text file or something, but no instructions on how that works.

Thanks for your time if this is just dumb mistake on my part, but I can't just figure it out.

**Comment by koen-futo** [comment]
There is a known bug with the playlist import, particularly for people who have YT accounts in different regions then english. This is not likely to be a user error.

**Comment by Vallialenz** [comment]
Thanks for your quick response

**Comment by Vallialenz** [comment]
I found a workaround to this problem thanks to your description of this issue.

1. Login to YouTube through grayjay
2. Before selecting your account for the app change your YouTube profile language to English(US), and account location to united states from the drop-down menu at top right
3. Choose the YouTube account for the app after checking the interface is now in English (you may need to login again, or do this on YouTube the site)
4. The app now loads your playlists (at least it did for me, including private ones).

**Comment by oyvigri** [comment]
Omg i wasnt aware of this workaround, and it seems like it still is an issue.
Workaround worked perfectly. Thank you so much!
