### ISSUE TITLE
[Feature Request] simplifing settings

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#374]
The settings are getting bigger and bigger and will be overwelming for new users. Having more options is great. I dont want you to take that away. 
There are ways to simplify the settings without taking settings away. 

Many settings are repeated for different pages 
Adding a global state as default would be an option

Eg
Feed style:  peview (global)/list (global)/"local state"
And only adding the setting to home/search/subs/downloads/playlists if the user asks for that level of granularity

The progess bar is already three times in the settings and might be added to Playlists and downloads someday

**Comment by Kelvin-FUTO** [comment]
They are certainly getting bigger, and there might be easy solutions such as Search which would help with this as well.
Grouping setting values would complicate the code a bit..but might be possible to do dynamically. 
I'll give it some thought.

The most annoying thing is communicating the differences between these global/local stuff intuitively. And more importantly, communicating that it is controllable on a per-feed basis, which is now fairly obvious as everything is on a per-feed basis.

**Comment by Zvonimir-FUTO** [comment]
Search has been implemented and we will keep this in mind and try to improve settings as it grews.
