### ISSUE TITLE
SponsorBlock has almost no settings

### ISSUE THREAD

**Issue by santimaster2000** [futo-org/grayjay-android#377]
Well, basically that, under every other implementation I've seen there is a considerable array of options to tinker with, also, skipable segments are not highlighted.

**Comment by GeoffreyCoulaud** [comment]
I wouldn't mind not having many settings, I'm aware that this costs developer time.
However, I think these are really missing:

- Choosing skipped segment types
- Displaying segments on the timeline

Thanks a lot for the great app Futo :)

**Comment by santimaster2000** [comment]
> I wouldn't mind not having many settings, I'm aware that this costs developer time. However, I think these are really missing:
> 
>     * Choosing skipped segment types
> 
>     * Displaying segments on the timeline
> 
> 
> Thanks a lot for the great app Futo :)

I do mind having less settings, Vanced/Re-Vanced has those settings, and it's 100 % free, don't get me wrong, I like Futo, I like what they're trying to make here, but if you want people to consider switching from Revanced and other apps like that, feature parity is the least you should strive for.

**Comment by Kelvin-FUTO** [comment]
Timeline stuff is indeed something that is planned in the near future. 
(Not just for Sponsorblock, but video chapters in general).
Other options may be added in due time. Most of the current implementation was done quickly one night to give people what they wanted.
It hasn't been at the top of our priority list over critical functionality, not because we never planned to.

**Comment by santimaster2000** [comment]
> Timeline stuff is indeed something that is planned in the near future. (Not just for Sponsorblock, but video chapters in general). Other options may be added in due time. Most of the current implementation was done quickly one night to give people what they wanted. It hasn't been at the top of our priority list over critical functionality, not because we never planned to.

OK, thanks, yeah, I imagined that this was kind of quick and dirty implementation just to get the feature out ASAP.

Happy to hear it will be expanded in the future !
