### ISSUE TITLE
[Request Plugin] Spotify support

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#378]
I had to throw this out there after seeing the request for YouTube music. I would absolutely switch off of xmanager modded Spotify builds if grayjay were to add more music/audio specific plug-ins.

**Comment by birdup000** [comment]
Correction I forgot that SoundCloud 😅

**Comment by Kelvin-FUTO** [comment]
We will look into it in the near future.

If you or anyone wants to tackle it on their own, anyone can develop a plugin.
Documentation is still fairly sparse, but looking at existing plugins and the following docs helps:
https://github.com/futo-org/grayjay-android/blob/master/plugin-development.md
https://github.com/futo-org/grayjay-android/tree/master/docs

**Comment by birdup000** [comment]
> We will look into it in the near future.
> 
> If you or anyone wants to tackle it on their own, anyone can develop a plugin. Documentation is still fairly sparse, but looking at existing plugins and the following docs helps: https://github.com/futo-org/grayjay-android/blob/master/plugin-development.md https://github.com/futo-org/grayjay-android/tree/master/docs

Awesome thanks I'll checkout the plug-in documentation.

**Comment by apoeteo** [comment]
I support this and would love to have Spotify plugin too :heart:

**Comment by Zvonimir-FUTO** [comment]
Spotify plugin has been added. Closing.
