### ISSUE TITLE
Unable to enter fullscreen/landscape

### ISSUE THREAD

**Issue by brandon-futo** [futo-org/grayjay-android#38]
User reports that it says fullscreen is unavailable after tapping the fullscreen button to view a video in fullscreen.

They are also unable to get the video to enter landscape/fullscreen using auto-rotate.

Videos only play in portrait mode.

They are using an Amazon Fire 10 plus 11th generation running Android 9

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
