### ISSUE TITLE
[Issue] Patreon video add to queue and options buttons don't work

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#384]
When viewing Patreon feeds, I'm unable to select the video add to queue, or +Options buttons.
I can only verify that this is an issue for the YT links.

**Comment by Kelvin-FUTO** [comment]
This appears to be a simple missing event for the redirected video UI.
Will be fixed be fixed.

**Comment by mnbvasd** [comment]
This seems to be fixed now, thanks.
