### ISSUE TITLE
[Issue] Negative likes on YouTube video

### ISSUE THREAD

**Issue by WillHynes** [futo-org/grayjay-android#388]
A YouTube sourced video, recently released (27 minutes at time of watching), had -1 likes, and 0 dislikes.

![Screenshot_2023-11-23-18-23-30-18_ca2ad563b57b5497046450f16b7718e2.jpg](https://github.com/futo-org/grayjay-android/assets/123247214/03963efa-43f8-4848-af5f-2817a66e9315)

**Comment by Kelvin-FUTO** [comment]
I have observed it on a video as well. This generally implies it fails to find/parse the ratings. Will be investigated.

**Comment by xephos1one** [comment]
Possibly related to #333

**Comment by Kelvin-FUTO** [comment]
> Possibly related to #333

Platform ratings and Polycentric comments/ratings are seperate systems and thus shouldn't be related

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #333.
