### ISSUE TITLE
Home feed only shows a few videos in List mode

### ISSUE THREAD

**Issue by CygnusiaX1** [futo-org/grayjay-android#389]
After adding several creators to 'Hide Creator From Home', the feed stops getting new content and only shows a few items. If you switch to Preview mode everything shows up, but switching back to List mode goes back to showing (for me) 6 videos. I have cleared the hidden list, and everything goes back to normal. But after adding several creators to the hidden list, it returns to only showing a few videos in the home tab in List mode.

![Screenshot_20231124-103213](https://github.com/futo-org/grayjay-android/assets/50664192/61c72b83-cdf1-42f6-9fd1-dc1699734355)

**Comment by Kelvin-FUTO** [comment]
I believe this is a bug in the pager, where if too many results gets filtered out (and the number of items is less than a full recycler page) it no longer requests the next page. This is a bug.

**Comment by mnbvasd** [comment]
I experience this too, if the last item doesn't go off the page, the buffer won't repopulate and allow me to scroll.

I've paused hiding watched videos now.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
