### ISSUE TITLE
Responsive user interface (WSA)

### ISSUE THREAD

**Issue by bumbummen99** [futo-org/grayjay-android#390]
Since there currently is no desktop build of GrayJay, i did try to use the x86_x64 build combined with the new [Windows Subsystem for Android](https://learn.microsoft.com/en-us/windows/android/wsa/) to run application directly in WIndows 11.

However, this does not seem to work as the scaling of the user interface is too small. In addition to that the application does only seem to allow for phone and tabled screen ratios.

Here is a screenshot on how the application does look in Windows 11 @1440p:
![image](https://github.com/futo-org/grayjay-android/assets/4533331/ee36c5a3-b038-465a-8f7b-92e6ad908174)

**Software & Versions:**
- Windows 11
- WSA 2310.40000.2.0
- Android Platform Tools 34.0.5

**Comment by koen-futo** [comment]
The current UI is focused on having the best possible experience on a phone-sized screen. Tablet UI is in the works.

**Comment by bumbummen99** [comment]
> Microsoft is ending support for the Windows Subsystem for Android™️ (WSA). As a result, the Amazon Appstore on Windows and all applications and games dependent on WSA will no longer be supported beginning March 5, 2025. Until then, technical support will remain available to customers.
Customers that have installed the Amazon Appstore or Android apps prior to March 5, 2024, will continue to have access to those apps through the deprecation date of March 5, 2025. Please reach out to our support team for further questions at [support.microsoft.com](https://support.microsoft.com/). We are grateful for the support of our developer community and remain committed to listening to feedback as we evolve experiences.

https://learn.microsoft.com/en-us/windows/android/wsa/

Since WSA has been deprecated and this issue is specific to it i am going to close it.
