### ISSUE TITLE
Issue: twitch needs more work.

### ISSUE THREAD

**Issue by DOOMMARINE117** [futo-org/grayjay-android#391]
Hi, I manage to login to YouTube, rumble and kick. Couldn't login into twitch. Didn't gave me code to login. 

Please fix this.

I know its in beta.

Great job on the app by the way. 

I like it. Hoping it can be used for it's own videos.

**Comment by Kelvin-FUTO** [comment]
I was able to log into Twitch just fine.
With "didn't gave me code to login"
Do you mean the two factor code not being sent to your mail?
If so that's a Twitch issue, not a Grayjay issue.

Two factor emails can sometimes be slow or other issues can occur.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
