### ISSUE TITLE
[Bug] YouTube videos (in fullscreen) seem to restart from the beginning if you go home or lock your device

### ISSUE THREAD

**Issue by ORIOLESFan02** [futo-org/grayjay-android#394]
Whenever I lock my device or go home, the video does not go back to the spot I was originally at. Let's take for example that I'm 5-10 minutes into a video and then I lock my phone. It goes back to the 6 second mark for some reason (or even the beginning of the video)

I copied and pasted what I said in an email above (and I added something new), but it seems like it only does this in fullscreens now. I also screen recorded it, and for some reason the audio went out of sync, so I do apologize for that as well. Hopefully this helps 

https://github.com/futo-org/grayjay-android/assets/48143202/09fc6ce3-44f9-4008-82c6-bf8a68d88218

**Comment by ThePrivacyPlayer** [comment]
Same here. I've had a few cases where it continued where I left it, but I have no idea how I did that and most of the time it just starts from the beginning.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
