### ISSUE TITLE
Twitch ads

### ISSUE THREAD

**Issue by JustCryen** [futo-org/grayjay-android#397]
I just had a two stage add load with Twitch content.
I'm not sure if that's intentional and I know Twitch support is in beta.
I'm just leaving this here for someone to evaluate in case this behavior is not intentional.

**Comment by venthewolf** [comment]
Can confirm this

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
