### ISSUE TITLE
Grayjay send dns queries to logs.grayjay.app when logs are turned off in settings

### ISSUE THREAD

**Issue by thankyoumichaelbazzell** [futo-org/grayjay-android#401]
In settings under logging I have log level set to none, but the app still constantly sends dns queries to [logs.grayjay.app](https://logs.grayjay.app/). Is there a reason why? Can we shut this off for users who don't want to send logs?

**Comment by koen-futo** [comment]
You are not sending logs unless you enable set a log level and manually click submit. Even when there are exceptions you are not sending logs unless you submit them. If you have an exception and your log level is not set, only the stack trace is sent and no additional information.
