### ISSUE TITLE
Controversial Videos - Download Failure 

### ISSUE THREAD

**Issue by Ruckus42** [futo-org/grayjay-android#402]
Some videos on YouTube are flagged as controversial and are unable to be downloaded. Here's an example:

https://youtu.be/ZIED__euCG0?si=BgmYwpCmQeA_YpQX

YouTube requires an extra click to confirm that the viewer understands the risks of watching such a video. As a result, GrayJay fails to download said video.

**Comment by McIrco95** [comment]
Playing and downloading that video works fine for me
If you get the age restricted popup go to Sources/Youtube/Allow Age Restricted

**Comment by Ruckus42** [comment]
Copy that, did not know that setting was there.
