### ISSUE TITLE
YouTube Clips can't be played

### ISSUE THREAD

**Issue by Immac** [futo-org/grayjay-android#408]
When I try opening a clip I get an error, 
[Clip Example](https://youtube.com/clip/Ugkxz9yVdS6e39ekITaANqwS_irlf_4Lxcwr?si=reSkaPod9brnpfH-)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
