### ISSUE TITLE
Restore backup import playlist issue

### ISSUE THREAD

**Issue by stl3** [futo-org/grayjay-android#414]
Testing on arm64-v8a atm. Was doing a restore backup and reached the point where it asks to restore playlist and it just stays stuck like this for over 10m without progressing, there is also no way to abort out of it.
![image](https://github.com/futo-org/grayjay-android/assets/32008952/f1af6005-35bb-40e5-ab15-2b18e66f3e11)
I will try making a new backup from scratch (reimporting youtube playlists) and try replicating.

**Comment by Kelvin-FUTO** [comment]
Might be that the progress indicator is incorrect and it is continueing, it just takes a bit.
Importing a playlist requires re-fetching every video, which can be time-consuming.
You havent mentioned the size of your playlists, so I cannot really make a determination if this is the most likely cause.

I doubt remaking a backup will make a different, I assume those backups are fine. (The fact that it detects the right amount says enough). Probably something with either the restore, or the size of the playlists. (And possible wrong progress)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
