### ISSUE TITLE
App closes at start of navigation.

### ISSUE THREAD

**Issue by Albert20151** [futo-org/grayjay-android#425]
Have to turn navigation on first then grayjay otherwise grayjay restarts.
Device: galaxy s21 ultra

**Comment by Kelvin-FUTO** [comment]
Could you elaborate what you mean by "navigation"?

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
