### ISSUE TITLE
Return Youtube Dislike doesn't work 

### ISSUE THREAD

**Issue by DUBDUBHUB** [futo-org/grayjay-android#426]
Android Device: **Samsung Galaxy A33 5G**

OS: **Android 13**

GrayJay version: **201**

YouTube plugin version: **150**

Odysee plugin version: **31/32**

Ok so return YouTube dislike does not work, regardless of whether the option is activated or not, I tried restarting my phone and reinstalling my YouTube plugin nothing worked,it doesn't seem to be a problem  return youtube dislike itself

![image](https://github.com/futo-org/grayjay-android/assets/150360681/bcb7780c-fd64-4c99-b702-ad95b34dae27)
![image](https://github.com/futo-org/grayjay-android/assets/150360681/5385c401-4702-409f-8718-5c43af0da477)

![image](https://github.com/futo-org/grayjay-android/assets/150360681/bf27cbad-6ccc-4a80-9653-97ba7944f008)

**Comment by Kelvin-FUTO** [comment]
Ratings in general for youtube are having issues lately. I'll investigate and make sure its fixed in the upcoming build for next week.

**Comment by DUBDUBHUB** [comment]
Hey @Kelvin-FUTO  thanks mate I appreciate it

**Comment by OutrageOrange** [comment]
@Kelvin-FUTO I updated to the most recent plugin version and believe this is Solved!

**Comment by DUBDUBHUB** [comment]
I just update it it works, thanks mate I appreciate it
