### ISSUE TITLE
Video stopping when opening and closing flip phone

### ISSUE THREAD

**Issue by smooney91** [futo-org/grayjay-android#429]
When I flip open/closed Motorola razr the app stops playing both when the app is open and when playing in the background. Also, when I open the app after flipping open/closed the video itself is no longer in the queue and I have to start it again from history.

**Comment by Zvonimir-FUTO** [comment]
Hey this issue is a bit stale. Could you please provide us with an update on this? Is the issue still present?

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
