### ISSUE TITLE
[Feature] QR-code for FCast pairing

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#430]
It would be nice to have, faster FCast connection

**Comment by koen-futo** [comment]
I like the idea, will be implemented. Will need to wait until the receiver ecosystem has been expanded though.

**Comment by koen-futo** [comment]
Grayjay support is finished and will be deployed in the next build. FCast will get updated soon with the change that displays the QR code.

**Comment by Doubs115** [comment]
Was hoping to see some updates to FCast. I know I would like to see more options for that app. It doesn't work on my Tivo 4k.

**Comment by koen-futo** [comment]
@Doubs115 https://github.com/futo-org/grayjay-android/issues/441 can you please provide more details ?

**Comment by Doubs115** [comment]
I added a summery to the issue you created, thanks for making it!

**Comment by teaalltr** [comment]
Thanks @koen-futo, that's amazing! Good job guys!!
