### ISSUE TITLE
Make comment downvote darkening optional

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#433]
![image](https://github.com/futo-org/grayjay-android/assets/34012548/8f2491c7-bb8f-44f4-9445-4a5de19ba93c)

In this video the bottom comment looked like its darker than the rest its on this video. The comments are the polycentric not the platform comments. 
https://odysee.com/the-sat-question-everyone-got-wrong#624c62b79c6d855d0e5741e77d8fddc2be47a6d2

**Comment by birdup000** [comment]
Same functionality you can still like or dislike the comment, and view replies but it's darker for  that one.

**Comment by koen-futo** [comment]
This is a feature where mostly disliked comments are faded in order to have obscene stuff be less visible.

**Comment by birdup000** [comment]
In my opinion I disagree with this feature then it's kinda censoring but not really. This can also poise a accessibility problem too where it's much harder to see the comment for anyone who may have eye problems such as cataracts etc... I hope this feature gets removed or at least automatically disabled and can be enabled in settings as you wish.

**Comment by koen-futo** [comment]
We can add a setting for it, no problem

**Comment by koen-futo** [comment]
@birdup000 I am happy you are happy :)

**Comment by mingyee2** [comment]
@koen-futo Since the option has been added now, this can be closed, no?

**Comment by birdup000** [comment]
> @koen-futo Since the option has been added now, this can be closed, no?

I'll close now
