### ISSUE TITLE
[Feature Request] loop button

### ISSUE THREAD

**Issue by Maludo9** [futo-org/grayjay-android#434]
option to have video loop, so I can Rick Roll myself for hours

-Thank you for your time, and this amazing app! :)

**Comment by koen-futo** [comment]
Planned but not high on the priority list.

As a temporary work around:
1. Create a playlist with the same song twice
2. Loop the playlist

**Comment by Kelvin-FUTO** [comment]
Loop button was added to the upcoming built. It will be a simple toggle in the topright of the video view (next to rotation lock)
