### ISSUE TITLE
Search subscribed channels

### ISSUE THREAD

**Issue by GeorgePapoulidis** [futo-org/grayjay-android#435]
I would like to be able to search though my subscribed channels. I see it as an easy and no bloat option. This way, i can check if i am subscribed to a channel, and even check its other videos etc by pressing on it. It could be implemented in the Subscriptions tab, and when a search is done, only channels matching the search will have their bubbles shown on top of the screen, instead of all of them

**Comment by Kelvin-FUTO** [comment]
Subscription creator search is implemented for upcoming built.

**Comment by Zvonimir-FUTO** [comment]
This has been implemented in latest version of Grayjay.
