### ISSUE TITLE
Allow searching for and looking at YouTube playlists

### ISSUE THREAD

**Issue by BrunoDSL** [futo-org/grayjay-android#436]
While I have seen that the app has good functionality for creating and importing your own playlists, sadly it still lacks the ability to search for playlists and looking at playlists from YouTube channel pages. This is one of the reasons which makes me still rely on NewPipe for YouTube, despite your app being better in many aspects.

**Comment by Kelvin-FUTO** [comment]
@FlagstaffWeb I'm not sure. I just searched for playlists on Youtube within Grayjay and it works fine.
Note that this is not searching for your own playlists, but playlists on Youtube.

If you mean search for your own playlists, that doesn't exist yet but can be added fairly easily.
Seeing playlists of a specific channel isn't implemented either, requires additions to the plugin spec.
But searching for general playlists is (if the plugin implements it)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.

**Comment by aliquantulus** [comment]
2024.10.20 and I can't open playlists from channels?
