### ISSUE TITLE
Not warnning when potentially disguarding comment.

### ISSUE THREAD

**Issue by Doubs115** [futo-org/grayjay-android#439]
When writing a comment, if someone clicks away either on accident or on purpose then it just goes away. This is frustrating especially when writing a big comment and accidentally clicking off to have the whole thing be gone with no way of getting it back.

Solutition/s:
1. Make a confirm discard dialog that if clicked away defaults to keep writing as to prevent double clicks and anything else from ruining a persons day. Ex. youtube.
2. Make drafts somewhat persistant in that if they are either still watching or swap to another app people can be sure that it will be there when they come back. ex. youtube and discord.

Other notes:
I feel as the comment box that pops up should not get in the way of the player, this seems like a little bit of an oversight and plainly annoying. Ex. youtube.

A feature that is half implemented on youtube is the ability to interact with the video while a comment is stored as a draft. This can be really helpfull with things like timestamping. Where the user can put down the keyboard, text stored in page, navigate the video, then re-tap on the comment box/button to be greeted with the text they wrote before.

Lastly, although the timestamp button on youtube is horribly implemented it would be another greatly helpful addition.

**Comment by PhilC813** [comment]
Seems implemented 🎉
Thanks FUTO

![Screenshot_20241214_025631](https://github.com/user-attachments/assets/dfb00043-6d83-43a4-9925-3c8d283906c7)

**Comment by Zvonimir-FUTO** [comment]
This has been implemented in v276.
