### ISSUE TITLE
Can't load videos over WiFi

### ISSUE THREAD

**Issue by CodeNautilus** [futo-org/grayjay-android#446]
As the title says, here's the text of the pop-up displayed when trying to refresh sub feed over WiFi. No issues over data, can't find any router settings or firewall that could be causing it.
![Screenshot_20231205-194905](https://github.com/futo-org/grayjay-android/assets/98363317/26ed56e4-ecf2-4387-8cce-649a214edc94)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
