### ISSUE TITLE
[bug] app fails to launch 

### ISSUE THREAD

**Issue by benninkcorien** [futo-org/grayjay-android#447]
I've been having "hangs or crashes at launch" issues for the past ... week? 

Doesn't even show the app screen in the list of open apps where you can manually kill them. Just the icon at the top. When a screen does show there it's usually plain white. 

(If I exit grayjay there and wait a few seconds and then relaunch it, that often fixes it but not always.)

![Screenshot_20231206-101103](https://github.com/futo-org/grayjay-android/assets/9899593/05f22b8a-20d2-48cb-a5c0-ff29ec35390b)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
