### ISSUE TITLE
Home Page videos have been the same for days.

### ISSUE THREAD

**Issue by bpawnzZ** [futo-org/grayjay-android#448]
It seems as though my homepage videos have been the same for days. Atleast 95% of them. This was not the case until most recent update. Probably about to roll back a version.  Just wanted to officially say something about it.

**Comment by bpawnzZ** [comment]
The issue seems to have fixed itself.  I've been playing around with the app alot more and am really enjoying it. You guys keep it up

**Comment by Kelvin-FUTO** [comment]
Then I assume it was just Youtube having a moment, closing this.
