### ISSUE TITLE
Can't buy a licence, Grayjay shows an error

### ISSUE THREAD

**Issue by driftywinds** [futo-org/grayjay-android#449]
I wanted to purchase a licence to support the development of Grayjay but I'm not able to because the app shows an error. 
This is what it says: -
![Screenshot_2023-12-07-13-11-46-84_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/63164617/68180616-8309-44df-ad6b-a0861adbf2e8)

Can anyone help me out?

**Comment by driftywinds** [comment]
> Duplicate of #442 ? Seems like they're working on it.

You are right, I'll close this issue.

**Comment by Kelvin-FUTO** [comment]
This should have been solved today, no update required.
