### ISSUE TITLE
Duplicate subscription notifications

### ISSUE THREAD

**Issue by brandon-futo** [futo-org/grayjay-android#45]
User reports that subscriptions import in groups of 75 as expected.
However, after each 75, they get a notification for every group of 75 that has been imported so far.
For example, after the 3rd group of 75 has been imported, they get 3 notifications saying that 75 subscriptions have been imported (rather than just one notification for the 75 new imports).

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale. If the user still encounters the issue he can open new issue with fresh information.
