### ISSUE TITLE
Chromecast stops working after waking phone up when sleeping during cast

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#453]

**Comment by koen-futo** [comment]
This is when you are casting using the Chromecast protocol and your phone falls asleep. At some point when you wake your phone back up it wont properly reconnect.

**Comment by jonathancutting** [comment]
I have the same issue with Chromecast. The app still casts, but thinks it's not connected, so no control is possible until connection is severed and then restored.

**Comment by xephos1one** [comment]
@koen-futo my experience is that currently with version 233 it's the other way around:
You cast a video, the phone goes to sleep and after some time the playback on the TV stops with a loading symbol.
As soon as you unlock the phone the playback resumes.

**Comment by koen-futo** [comment]
@xephos1one This last issue you mentioned can be explained by power savings. For ChromeCast, the phone needs to proxy the stream due to CORS restrictions. Consequently, some phones eventually decide to just kill those sockets once it enters power saving mode.

Sadly the only way this can be avoided is by not turning off the screen or using FCast which does not require proxying of streams.

**Comment by xephos1one** [comment]
> This last issue you mentioned can be explained by power savings.

This. After setting the battery usage of the Grayjay app to unrestricted the stream doesn't stop after the phone going to sleep.
As it can be fixed by changing this setting could it be fixed in the code to not put the app to sleep while streaming?

**Comment by koen-futo** [comment]
We already request the app to be kept alive in such situations. However, the OS can just ignore us and seemingly in your situation it does?

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale without feedback.
