### ISSUE TITLE
Buttons Displaying issue

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#455]
Hi every once in a while I get these weird button issues where they dont display properly.

![image](https://github.com/futo-org/grayjay-android/assets/34012548/7aee5d67-8183-462c-9f6d-fa68013b0039)

**Comment by birdup000** [comment]
When you close the video and reopen it that gets it to show properly again.

**Comment by OutrageOrange** [comment]
Your notification bar is also oddly skewed. Is that how your notification bar normally looks?

**Comment by birdup000** [comment]
> Your notification bar is also oddly skewed. Is that how your notification bar normally looks?
@OutrageOrange 

Yeah its normal I'm on a S10 Plus so the camera is there you can see in the image below of the phone

![image](https://github.com/futo-org/grayjay-android/assets/34012548/f198b554-827e-4c8e-81da-beb0eb5ee5bd)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
