### ISSUE TITLE
youtube extension is unable to get all subscriptions

### ISSUE THREAD

**Issue by kusti420** [futo-org/grayjay-android#458]
when importing subscriptions it only gets 1000 subscriptions, as if its scraping the subscriptions from the youtubes frontend, which is also limited to 1000 subscriptions.
![image](https://github.com/futo-org/grayjay-android/assets/75937552/058cbf0a-598f-41d1-9607-ad18625eb53e)

using https://takeout.google.com/ and exporting subscriptions is the only way to see the actual number of subscriptions
![image](https://github.com/futo-org/grayjay-android/assets/75937552/30db2000-8589-4add-ab6a-c8e627294387)

please add an option to import subscriptions from that exported csv file and add a note telling users to not use that other method of getting subscriptions if they have more subscriptions than the youtubes frontend can display

**Comment by koen-futo** [comment]
Next build (coming out today) will have a import dialog where you can import subscriptions via multiple different ways.

![image](https://github.com/futo-org/grayjay-android/assets/129423944/401e9785-0bff-41c9-a654-a21de6089850)

One of these is a text file format that looks like this.

```
Subscriptions
https://www.youtube.com/channel/UCq-Fj5jknLsUf-MWSy4_brA
https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA
https://www.youtube.com/channel/UCbCmjCuTUZos6Inko4u57UQ
https://www.youtube.com/channel/UCpEhnqL0y41EpW2TvWAHD7Q
https://www.youtube.com/channel/UCk8GzjMOrta8yxDcKfylJYw
https://www.youtube.com/channel/UCJplp5SjeGSdVdwsfb9Q7lQ
https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw
https://www.youtube.com/channel/UCvlE5gTbOvjiolFlEm-c_Ow
...
```

**Comment by liam-clink** [comment]
How do you access this dialog? It looks like you're in the home tab, not the sources tab

**Comment by koen-futo** [comment]
Settings -> Import Data
