### ISSUE TITLE
Subtitles render in incorrect order

### ISSUE THREAD

**Issue by stevenkampen** [futo-org/grayjay-android#46]
This sentence comes first

:down:️

And this sentence came afterwards chronologically, but is updated as the top line.
This sentence comes first

**Comment by LeoSaucedo** [comment]
Having this issue as well. So far I have noticed that it only happens with auto-generated captions, when a video has actual captions, they display correctly.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
