### ISSUE TITLE
[Issue] Sponsor block doesn't work when Fcasting.

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#460]
To reproduce, find a video that will probably have sponsors blocked, fcast the video and watch the sponsor segment.
Repeat the process without casting and see sponsors section is removed as expected.

Casting to Linux and Mac Electron receivers.

**Comment by JeremyParry** [comment]
Same issure for me, would be awsome if it did. Casting to a chromecast here.

**Comment by mnbvasd** [comment]
This has started working for me in the past few releases.

I think there maybe some bugs related to when GJ isn't in the foreground or the phone sleeps.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
