### ISSUE TITLE
App takes too long to load on mobile data

### ISSUE THREAD

**Issue by kingshah13** [futo-org/grayjay-android#463]
Whenever I try to open the app on mobile data it first get stuck on black screen after a minute or two it loads the content and after selecting something to play it still take a minute to play

**Comment by buzzat** [comment]
I thought that was because YouTube has been caught slowing down people who use other browsers other than chrome to watch YouTube
....unless I'm spreading propaganda

**Comment by kingshah13** [comment]
SomeOrdinaryGame debunked that mystery. While Google was slowing down YouTube on Firefox it wasn't deliberate. There new adblock bloc system doesn't work well with Firefox and ends causing longer load just to detect adblockers

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
