### ISSUE TITLE
Update broke app

### ISSUE THREAD

**Issue by Allvaldrsson** [futo-org/grayjay-android#464]
I just updated to version 208 and video playback is broken. Upon selecting a video, the screen changes to the video page and instantly closes down. I've tried reinstalling the app and plugins, attempted loading pre-recorded (from multiple plugin sources) and live videos, even simply restarting the phone. Every video fails to load.

GrayJay v208
Pixel 6a
Android 14

**Comment by Kujo929** [comment]
same for me.

tried reinstalling sources and entire app.
tried a phone restart
issue affecting all sources i use

GJ v208
oneplus 11 5g
android 14 (oxygen os 14)

**Comment by Toaster05** [comment]
Suffering the same problem.

Pixel 6
v208
Android 14 5 December 2023

**Comment by MichaelMPM** [comment]
Pixel 7a, agree with OP, update does the same thing as OP.

**Comment by buzzat** [comment]
Signed up for a GitHub to say the same is happening with me, love the app

**Comment by MKBontwikkeling** [comment]
Me too

**Comment by CortlandNation9** [comment]
Same problem here

Grayjay v208
Pixel 7
Android 14

**Comment by Blotz** [comment]
I am having the same issues as above.
Here is the log for the crash via adb & logcat
```
12-09 19:52:28.229 24926 24926 V INTERNAL;MediaPlaybackService: onCreate
12-09 19:52:28.229 24926 24926 V INTERNAL;MediaPlaybackService: onStartCommand
12-09 19:52:28.231 24926 24926 W MediaSessionCompat: Couldn't find a unique registered media button receiver in the given context.
12-09 19:52:28.234  1500 11292 I MediaSessionStack: addSession to bottom of stack | record: com.futo.platformplayer/PlayerState (userId=0)
12-09 19:52:28.237  1500 12755 I MediaSessionStack: onPlaybackStateChanged - Pushing session to top | record: com.futo.platformplayer/PlayerState (userId=0)
12-09 19:52:28.242 24926 24926 I INTERNAL;MediaPlaybackService: Updating notification bitmap=no. channelId=mediaChannel icon=2131231158 video= playWhenReady=true session.sessionToken=android.support.v4.media.session.MediaSessionCompat$Token@88bb6dc
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: Failed to start MediaPlaybackService due to: Starting FGS with type mediaPlayback callerApp=ProcessRecord{1e5a748 24926:com.futo.platformplayer/u0a233} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK]
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: java.lang.SecurityException: Starting FGS with type mediaPlayback callerApp=ProcessRecord{1e5a748 24926:com.futo.platformplayer/u0a233} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK]
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Parcel.createException(Parcel.java:3050)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Parcel.readException(Parcel.java:3026)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Parcel.readException(Parcel.java:2968)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6776)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.Service.startForeground(Service.java:862)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.futo.platformplayer.services.MediaPlaybackService.notifyMediaSession(MediaPlaybackService.kt:286)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.futo.platformplayer.services.MediaPlaybackService.onStartCommand(MediaPlaybackService.kt:68)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4838)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Looper.loopOnce(Looper.java:205)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.os.Looper.loop(Looper.java:294)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.ActivityThread.main(ActivityThread.java:8199)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at java.lang.reflect.Method.invoke(Native Method)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: Caused by: android.os.RemoteException: Remote stack trace:
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2611)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2322)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1679)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13364)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3393)
12-09 19:52:28.243 24926 24926 E INTERNAL;MediaPlaybackService:
12-09 19:52:28.243 24926 24926 V INTERNAL;MediaPlaybackService: closeMediaSession
```
It looks like the app is simply missing some permissions.

**Comment by beamplaza** [comment]
Same issue here

**Comment by rwardlow01** [comment]
Same for me, I tried clearing cache and data, then before and after restoring backup, still didn't work.
GrayJay v208 (I tried going back to v201 and it does work fine so it's definitely an issue with the update)
Android 14 Dec 5th Security Update
Pixel 6

**Comment by Robbylikes** [comment]
Yup broken lost all my subs too.

**Comment by Allvaldrsson** [comment]
@rwardlow01 Can you provide instructions for installing a previous version?

**Comment by rwardlow01** [comment]
I grabbed the version from the Google play store which is still on v201
or you can use a site like apkpure, which has links to all previous versions (use at your own risk): https://m.apkpure.com/grayjay/com.futo.platformplayer.playstore

**Comment by Yostme** [comment]
Same issue on my phone.

version 208
Android 14.  Dec 5th security update (GrapheneOS)
Pixel5a

**Comment by Blotz** [comment]
It looks like android updated [MediaSessionService](https://developer.android.com/guide/topics/media/session/mediasessionservice).

Adding 
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />
```
To android manifest per the documentation appears to fix the problem.
Testing and working on my device.

**Comment by Bluscream** [comment]
```
Version information (version_name = 208, version_code = 208, flavor = stable, build_type = release)
Device information (brand= Lenovo, manufacturer = LENOVO, device = achilles6_row_wifi, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2023-12-09 21:17:04): Uncaught exception ("Unknown Context"): Starting FGS without a type  callerApp=ProcessRecord{de5080a 762:com.futo.platformplayer/u0a207} targetSDK=34

android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{de5080a 762:com.futo.platformplayer/u0a207} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at com.futo.platformplayer.services.DownloadService.notifyDownload(DownloadService.kt:253)
	at com.futo.platformplayer.services.DownloadService.onStartCommand(DownloadService.kt:60)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by AttackOnTyler** [comment]
Same here, Samsung s22+

**Comment by oxygirl** [comment]
Same Issue!
Grayjay v208
Pixel 6
Android 14 (GrapheneOS)

**Comment by Doubs115** [comment]
doubbly same.

pixel7a android 14 calyxOS

**Comment by 0mni** [comment]
`Version information (version_name = 208, version_code = 208, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = oriole, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2023-12-09 23:40:54): Uncaught exception ("Unknown Context"): Starting FGS without a type  callerApp=ProcessRecord{f5e02e0 12220:com.futo.platformplayer/u0a370} targetSDK=34

android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{f5e02e0 12220:com.futo.platformplayer/u0a370} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at com.futo.platformplayer.services.DownloadService.notifyDownload(DownloadService.kt:253)
	at com.futo.platformplayer.services.DownloadService.onStartCommand(DownloadService.kt:60)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
`

Update broke app, another one bites the dust.

**Comment by Bluscream** [comment]
Hotfix has been released, please close

**Comment by barkerd427** [comment]
From where do we install this hotfix? I can't find it.

**Comment by Allvaldrsson** [comment]
@barkerd427 The download on the website has been updated. You can also open Settings within GrayJay and scroll down towards the bottom—you will find a section called "Auto Update" and beneath it lies a button to manually check for updates. The latter is the method I used and it's loading videos fine now.
