### ISSUE TITLE
Non-YouTube sources frequently fail to load

### ISSUE THREAD

**Issue by jonathancutting** [futo-org/grayjay-android#465]
All non-YouTube sources are sketchy, at best. They frequently fail to load or error out when trying to play a video or even list videos from creators. Example error below.
![Screenshot_20231209-165452](https://github.com/futo-org/grayjay-android/assets/20996880/5d6aa8b3-51c8-4d91-983c-b73f203ee6ad)

**Comment by koen-futo** [comment]
Can you please let me know which creator you tried opening? Is this related to a specific creator?

**Comment by jonathancutting** [comment]
It's not related to any specific creator. This particular instance, I was trying to load Tenet Media on Rumble, but, for example, Louis Rossmann's channel on Odyssee is affected, too. It's an intermittent problem that affects Rumble, Odyssey, and Nebula, but not YouTube. When they do work, they play just fine. It's about a 50/50 chance whether those sources will work any given time.

Unsure if related, but Nebula will never play, even when it will load. Nebula is the only source I'm signed into.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
