### ISSUE TITLE
Rumble comments incorrectly requiring signin to view

### ISSUE THREAD

**Issue by ugiefiewf** [futo-org/grayjay-android#468]
Some videos on Rumble require you to sign in to view, like these:
https://rumble.com/v40daty-chickpea-and-chicken-with-crunchy-garlicky-flatbread.html
https://rumble.com/v3v5tk7-judge-rules-its-legal-for-automakers-to-download-and-store-your-text-messag.html

However, others do not require signing in to view comments, such as videos like the ones below:
https://rumble.com/v2ncqhk-the-metaverse-is-the-worlds-deepest-money-pit.html
https://rumble.com/v40dfqv-fresh-and-fit-after-hours-w-king-dre.html

As some videos don't require signin to view comments, I would like to be able to view the comments of those videos without signing in.

**Comment by koen-futo** [comment]
Will fix. Thank you for the report.

**Comment by koen-futo** [comment]
Fixed next build.
