### ISSUE TITLE
Fcast stops working after waking phone up when sleeping during cast

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#472]
This issue sounds liked #453, but with Fcast.

When the phone goes to sleep or losses connection, fcasting breaks, while the video continues to pay.

The indicator is inconsistant, but you can reconnect and control volume, but the other controls are broken.

The easiest way to reproduce is to start casting, switch apps and swipe GrayJay closed and the reload and try to reconnect.

GJ 210
FCast Electron - git master

**Comment by koen-futo** [comment]
This is indeed easily reproducible. Let me give some context why this happens.

When the app is closed, it loses all context of what was playing and once reconnected, FCast does not have enough context for Grayjay to be able to determine what was playing.

For this reason (for now) it is required to keep the app running while casting IF you care about controls. Personally what I do quite often is that I'll just use the TV remote to control playback when Grayjay is closed.

As an alternative solution I will add basic playback controls to the connected casting dialog (where currently the volume slider exists) so you can still control playback even if you do not have a context.

**Comment by koen-futo** [comment]
![image](https://github.com/futo-org/grayjay-android/assets/129423944/3b8b760f-4c23-4e4b-91a4-111485a5429d)

**Comment by mnbvasd** [comment]
That looks great!

I suspected it was probably state related, it sounds like a good solution.
It would be nice to integrate it with #487 if that's possible.

Thanks for your help and great work on this.
