### ISSUE TITLE
Videos start in wrong language

### ISSUE THREAD

**Issue by xephos1one** [futo-org/grayjay-android#473]
Some Videos start in a wrong language.
App language is set to "System" (German) and primary player language is set to "English".

An Example is https://www.youtube.com/watch?v=JTZU7FcAv-Y
In this video after around 3 seconds the video is in Spanish and I have to manually set Audio to "English original".
I think the 3 seconds is because that's when the Spanish feed starts in general - so it's spanish the whole time.
This happens every time I open this video.

This happens in version 201.
Could this be related to #296?

**Comment by Kelvin-FUTO** [comment]
Could be that the YT plugin fails to detect the "english" track. And thus just takes the first appropriate one it finds.
Audio tracks aren't always properly specified in Youtube, but english should always be the default, so i'll investigate.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale.

**Comment by Zvonimir-FUTO** [comment]
> I started to have this behavior too. Some videos always start on English audio track (looks like a synthesized voice) and not in the language of the YouTuber. Everytime I open the same video it defaults to the translated track. I'm running version 276

This is not something that we can control and it seems it's something Youtube is pushing. Brodie Robertson made a good video explaining this: https://www.youtube.com/watch?v=Pk63QMSyg7k

From what I remember, creators can turn this off for their channels but I'm not sure if the individual can turn it off for himself.

**Comment by Zvonimir-FUTO** [comment]
I'll open a new FR for this.

**Comment by JustCryen** [comment]
I started having the same issue.  
Video starts normally with a proper audio track, I can see `UMP fallback` message appear and there's a chance that everything will work as expected.  
But sometimes thale language suddenly changes to German or other language that I have nothing to do with. 
 
Looks like it falls back to the "wrong" audio stream because some kind of issue occurs during playback.  
Audio streams are properly labeled in the selection menu.

**Comment by dimyself** [comment]
> I started having the same issue. Video starts normally with a proper audio track, I can see `UMP fallback` message appear and there's a chance that everything will work as expected. But sometimes thale language suddenly changes to German or other language that I have nothing to do with.
> 
> Looks like it falls back to the "wrong" audio stream because some kind of issue occurs during playback. Audio streams are properly labeled in the selection menu.

i am having this issue now. it only started for me about 1-2 weeks ago.

for me, it happens after i've been watching a video (with the screen off) for a few mins... then all of a sudden, it changes the audio language to german without me even touching the phone.  it seems to happen randomly, and it is infrequent. 

I have to manually change the lang backto english to fix it, or if i kill grayjay and reopen the video it is back to normal english.

this is on the latest version of The plugin and app.
