### ISSUE TITLE
Videos randomly pause

### ISSUE THREAD

**Issue by xephos1one** [futo-org/grayjay-android#474]
Some videos randomly pause during playback.
I sadly haven't found a pattern so far but I have only watched YouTube videos in landscape mode so far.

The playback suddenly stops so I have to bring up the UI and click play to resume the video.

Happening in version 201.

**Comment by Kevinf63** [comment]
Same here.

**Comment by Tsunami014** [comment]
If the playback of the video is faster than you can load the video (from poor wifi connection or something) then it will stop the video until it has enough video stored to continue. You should see this from either the light grey bar (which shows how much video it has loaded so far ready for you to watch) not being there until it finished loading. This *may* be your problem?

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
