### ISSUE TITLE
"Odysee plugin failed" error every time I refresh subscription feed.

### ISSUE THREAD

**Issue by PGQT** [futo-org/grayjay-android#476]
This error only seems to happen when I refresh the feed on the subscriptions tab. The error will come up many times and disappear, then come  back up again, for about 30 seconds after I refresh the videos feed. But again, this only seems to happen in the subscriptions tab.![Screenshot_20231210-085439.png](https://github.com/futo-org/grayjay-android/assets/85464621/9c2e8440-d71e-4ff6-b785-28a8321cf9a3)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
