### ISSUE TITLE
Grayjay Release 210 - Cannot submit Logs

### ISSUE THREAD

**Issue by Kevinf63** [futo-org/grayjay-android#478]
How I spotted the issue:
- Update existing Grayjay Install to Release type version 210.
-  Open Settings, scroll down to logging.
- Set log level to Verbose to anything put none
- Tap submit logs
- The following toast notification comes up...

![Screenshot_2023-12-10-14-50-32-36_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/3584482/b4610e30-b000-4750-ac6a-27121fa8d82e)

Realme GT Neo 2 on ColorOS/Android 13.

![Screenshot_2023-12-10-15-08-01-44_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/futo-org/grayjay-android/assets/3584482/934e34db-5056-4f6e-b67d-1eeca9a6ec79)

**Comment by glitch-method** [comment]
fully closing and restarting the app solved thisfor me -- not sure ha should be necessary though.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
