### ISSUE TITLE
Polycentric/platform comment viewer toggle has incorrectly sized touch target

### ISSUE THREAD

**Issue by ghost** [futo-org/grayjay-android#479]
The touch target for the Polycentric/platform comment viewer toggle under videos seems to be off slightly from what it should be, as when I tap in the lower part of the toggle, it doesn't register, but tapping on the upper part does. Tapping in the middle registers only sometimes.

Edit: This seems to be happening with most touch targets in the app (I also tested the like/dislike, the "More" video option, and the video slider). Either all these targets are off or my fingers are just weird. Tested a Moto G7 Power and an S21, for reference.

**Comment by Zvonimir-FUTO** [comment]
Comments section has been revamped and has tabs instead of pill toggle.
