### ISSUE TITLE
Intermittent incorrect rendering of view counts in european format

### ISSUE THREAD

**Issue by stevenkampen** [futo-org/grayjay-android#48]
![1000000419](https://github.com/futo-org/grayjay-android/assets/898763/084d5272-cb15-4d97-8be2-827c0941615d)

**Comment by stevenkampen** [comment]
In this screenshot, the 290, 368, 32 & 46 figures in the view counts should actually be 290K, 368K, 32K & 46K.

**Comment by andretdias** [comment]
Can confirm this issue

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this. Also what did you mean by "_european format_"?
