### ISSUE TITLE
[Feature request] show context in polycentric comment history

### ISSUE THREAD

**Issue by winneratwin** [futo-org/grayjay-android#483]
Currently there is no way to see which video/stream a comment was posted on. I would love a button to visit the video i made the comment on.

There is also a lack of context for comments that are replies to other comments, currently you can only see replies to your comment and not the parent comment(s).

**Comment by koen-futo** [comment]
This is already designed, waiting on some backend changes on Polycentric before this can be implemented.

**Comment by Zvonimir-FUTO** [comment]
This has been implemented.
