### ISSUE TITLE
Videos from YouTube playlists don't play when casting.

### ISSUE THREAD

**Issue by BrunoDSL** [futo-org/grayjay-android#485]
Title says it pretty much. While I can cast single videos and play them on my TV using a second gen Chromecast, playlists will not play at all. They open and the video gets ready for playback but hitting "play" doesn't do anything, even if you play a single video off the list instead of pressing "play all."

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
