### ISSUE TITLE
Automatically play a recommended video if queue ends or no queue exists

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#486]

**Comment by xephos1one** [comment]
Would be great to have that as a setting that is disabled by default

**Comment by stevecobb76** [comment]
8/10 of my recommendations are safe space woke teenie bopper kid videos!

**Comment by koen-futo** [comment]
@stevecobb76 of course would be an optional feature!

**Comment by Zvonimir-FUTO** [comment]
This has been implemented.
