### ISSUE TITLE
[Feature request] Phone player area as a remote control in casting mode

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#487]
In casting mode, the phone's player area should be allowed to be used as a sort of a remote control, thus increasing the size of the buttons an the gui elements.

For instance, there could be big buttons for the most common things, play/pause (already present), playback speed (that opens a sub-window/fullscreen listview with speeds), optionally volume and some other stuff maybe

**Comment by ggstrader** [comment]
Voicing support as this is my main use case. Setting playback speed would be especially useful. Also, if playback ever gets interrupted, grayjay has no idea where the caster left off and starts playback from 0:00

**Comment by mnbvasd** [comment]
This is related #472

**Comment by Zvonimir-FUTO** [comment]
This has been implemented except playback speed control which will be through #427.
