### ISSUE TITLE
Unable to import YouTube playlists

### ISSUE THREAD

**Issue by AidanBoyer** [futo-org/grayjay-android#489]
When attempting to "Import Playlists" in the Migration portion of the YouTube plugin, I see a "Failed to fetch" toast notification, and after a delay a list of YouTube playlists appears, but the list has not been updated. Playlists created since a previous successful playlist import do not appear, and newly added videos to existing playlists are not shown. A new similar toast notification seems to appear correlated with each subsequent playlist in the list beginning to load.
![IMG_20231211_224820](https://github.com/futo-org/grayjay-android/assets/8503478/44717709-48fe-42fc-9950-54e242a187ae)
I am currently using Version 157 of the YouTube plugin, Version Code 210 of the app on a OnePlus 5T running LineageOS 20.

**Comment by Mubelotix** [comment]
Same on latest version, samsung A20

**Comment by Zvonimir-FUTO** [comment]
Closing since more information is in #85 and is still active.
