### ISSUE TITLE
Loop is broken when enabling 

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#490]
Hi I'm testing the looping feature and it doesn't seem to be functioning at all when you enable it. But it does work after exiting and reopening whatever video you want to have loop on.  Just making the issue because it is a small knit pick.
I think the app should be more responsive where when loop is enabled you don't need to exit the video and reopen for this to work.
Player Version 210

**Comment by Kelvin-FUTO** [comment]
Last time I tested it it worked fine, but I'll retest it, see if something new conflicts with the behavior.

If the icon lights up in blue, it should simply loop the video, in both foreground and background. It only changes a single boolean that alters the next video behavior, so responsiveness of the loop feature should be irrelevant.
The reason why it would not work is if next video/queue behavior fails entirely on your device, which would be a different issue.

Note that loop does not work if you already have a playlist or queue active, but I assume this is not the scenario you have as it should hide the button in those scenarios.

Could you confirm for me if playlists/queues work for you at all? That if you reach the end of a video it automatically goes to the next video?

**Comment by Kelvin-FUTO** [comment]
@birdup000 After we checked this, we did found that apparently the fullscreen toggle was not properly bound.
So if you had this issue in fullscreen mode, then it should be resolved soon. 
Portrait toggle should work fine in your current build, if not, let me know.

**Comment by birdup000** [comment]
> @birdup000 After we checked this, we did found that apparently the fullscreen toggle was not properly bound. So if you had this issue in fullscreen mode, then it should be resolved soon. Portrait toggle should work fine in your current build, if not, let me know.
@Kelvin-FUTO 
yeah I think it was only the full screen I meant thanks for checking it and working on it.

**Comment by koen-futo** [comment]
Should be fixed next update.
