### ISSUE TITLE
Tablet in landscape mode cuts top and bottom portions when viewing a video

### ISSUE THREAD

**Issue by valdotdev** [futo-org/grayjay-android#491]
Hi there! Loving the app so far!

I noticed when using the app and opening a video the top and bottom portions are cut off unless I set it to fullscreen. It was fine at first but gets quite annoying over time.

For reference, I'm using a Galaxy Tab S9+ with a 16:10 aspect ratio.

Thanks.

![Screenshot_20231212_015554_Grayjay](https://github.com/futo-org/grayjay-android/assets/17805772/2ad0f3ca-b3dd-4fd6-b88d-1f0e9f211048)

**Comment by Rundervinkje** [comment]
Happens on older Samsung Tab models also.

**Comment by valdotdev** [comment]
The app basically tries to fit a video horizontally edge to edge but unfortunately the UI wants to squeeze in vertically. Maybe the devs could go the YouTube app route in terms of how they handle video + app UI on tablets in landscape mode. I don't mind the video preview resized smaller to accomodate the other parts of the UI as long as the video is seen in full even outside fullscreen mode.

**Comment by Zvonimir-FUTO** [comment]
Will be resolved through #312.
