### ISSUE TITLE
[Bug] Play button disapears

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#493]
When stoping the video with headphones the play/pause button disappears
![Screenshot_20231212-120110](https://github.com/futo-org/grayjay-android/assets/115875304/210df105-c9a6-4c65-9e87-5dda9d3a8d5e)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
