### ISSUE TITLE
Still cannot import my playlists

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#494]

**Comment by Privacy-Now** [comment]
If I go to settings and then import data (to attempt to import my YouTube subscriptions from NewPipe, the app crashes every time.

**Comment by Ser-Bul** [comment]
> _No description provided._

Man, instead of opening new duplicates of the same issue - just ping the developer in the ticket where we responded at least something - https://github.com/futo-org/grayjay-android/issues/85
