### ISSUE TITLE
PayPal as payment method 

### ISSUE THREAD

**Issue by Plarpoon** [futo-org/grayjay-android#496]
Please enable PayPal as a payment method, the current system accepts exclusively payments with credit/debit cards. I would feel a lot more safe and comfortable using PayPal instead.

**Comment by koen-futo** [comment]
I think it depends on the country which payment options Stripe gives you. Which country are you from?

**Comment by Plarpoon** [comment]
Italy

**Comment by Zvonimir-FUTO** [comment]
Closing issue for being stale. If this is still an issue for you, feel free to reopen
