### ISSUE TITLE
[Enchantment] can we display also playlists?

### ISSUE THREAD

**Issue by HafizBeyy** [futo-org/grayjay-android#498]
Wanna use grayjay as my music but you know downloading them one by one is not pratic at all. So im saying can we see public playlists by searching or pasting link?

**Comment by Kelvin-FUTO** [comment]
You can already search for them. Go to Playlists tab, click the search icon.
Searching here will search for playlists for all enabled sources that can provide playlists (I believe just Youtube right now)

In the near future hopefully you can also view playlists from a specific channel.
