### ISSUE TITLE
Unable to play videos YouTube plug in 

### ISSUE THREAD

**Issue by Goldfire345** [futo-org/grayjay-android#499]
I'm not sure what's going on I'm not able to play a single YouTube video.

I've tried reinstalling the plug in, updating the plug in restarting my phone but I'm honestly getting nothing  i wish i knew what was going on. I'll attach some screen shots of some various errors I've been getting all relating to the plug in failing to load. It seems to still be able to fetch videos to populate my feed but it's not able to play any of them.

![Screenshot_20231214-080457](https://github.com/futo-org/grayjay-android/assets/52189902/388e61db-7fb5-4c69-979d-04214913a179)
![Screenshot_20231214-080341](https://github.com/futo-org/grayjay-android/assets/52189902/b5d5a682-8db9-472c-bef9-6eb4d71c5b03)

![Screenshot_20231214-081145](https://github.com/futo-org/grayjay-android/assets/52189902/6806b6af-f95d-4df4-ab34-e281558b5fda)

**Comment by Kelvin-FUTO** [comment]
The 403 hints to you potentially having "Use login for details" enabled in your Youtube plugin.
If so, and you turn it off, does this solve the issue?

Having this toggle enabled only has benefits if you want to access Youtube membership only content or Youtube Premium benefits.

**Comment by Goldfire345** [comment]
Thanks you for your reply i checked my plugin settings and saw that while I
didn't have use login for details i had use login for channels once i
disabled that videos played again. Thanks for the help.

**Comment by mingyee2** [comment]
@Kelvin-FUTO I assume this can be closed

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
