### ISSUE TITLE
Video options does not show from the creators view

### ISSUE THREAD

**Issue by Michael-Hollister** [futo-org/grayjay-android#5]
App version: 113
Device(s) reproduced on: Pixel Tablet and Pixel 4a

Steps to reproduce:
* Ensure at least one video source is enabled (e.g. Youtube). Search up and subscribe to a creator.
* Go back and tap the creator you just subscribed too in the Creators view.
* Tap the options button on any of the videos from the list on the videos tab. The options menu will not show up.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
