### ISSUE TITLE
storage directory not being used

### ISSUE THREAD

**Issue by glitch-method** [futo-org/grayjay-android#502]
this probably needs to be split into multiple issues but unsure how you'd like that done. i did not see any relevant open issues, so opening new.

- default download location is not exposed to user
- set download location is not being used
- setting downloads/general directories set both instead of just the selected 
- i assume logs should be saved under the "general" directory, but they're not there either

after setting download location and downloading a file, i later updated the app and downloaded more videos, only to find just now that only the first video was saved to the set location. the other videos seem to be saved to a location that has no exposed user access (i don't have root access, so cannot tell where they are -- assuming the app cache).

(please advise on what additional information would be helpful. unfortunately i don't have root access or log files to determine this myself.)

**Comment by stevecobb76** [comment]
Same here! I set save directory to SD card. It saved somewhere else!

**Comment by koen-futo** [comment]
We will investigate.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
