### ISSUE TITLE
teenie bopper videos non stop!

### ISSUE THREAD

**Issue by stevecobb76** [futo-org/grayjay-android#505]
Please for the love of God give me some way to stop the teenie bopper videos. 8/10 times I load or reload the home page, it is flooded with these safe space woke 6 year old kindergarten videos. Block creater does not work. Block does not work. It is to the point that I am willing to pay for youtube again. The feed is not influenced at all by my history!

**Comment by Kelvin-FUTO** [comment]
Options=>"Hide Creator From Home" will remove any videos by said creator from showing up on Home.
I just verified and appears to work fine.

If you're logged into Youtube, you should simply see what you'd always see on Youtube Home.

Feed can be affected by your watch history if you're willing to give youtube your watch information, this is only relevant if you're logged into Youtube.
In the Youtube plugin setting there is a toggle "Provide Youtube Activity" which will cause your Grayjay watch to affect your Youtube home recommendations (and history).

By default we provide Youtube as little information as possible.

**Comment by stevecobb76** [comment]
![Screenshot_20231215_143349_Grayjay](https://github.com/futo-org/grayjay-android/assets/5054136/bbcf4c7e-e563-4f91-a123-c6e64d9bf9bb)
I just tried it. this is NOT  my youtube

**Comment by Kelvin-FUTO** [comment]
Did you login?
Sources=>Youtube=>Login

**Comment by stevecobb76** [comment]
> Options=>"Hide Creator From Home" will remove any videos by said creator from showing up on Home. I just verified and appears to work fine.
> 
> If you're logged into Youtube, you should simply see what you'd always see on Youtube Home.
> 
> Feed can be affected by your watch history if you're willing to give youtube your watch information, this is only relevant if you're logged into Youtube. In the Youtube plugin setting there is a toggle "Provide Youtube Activity" which will cause your Grayjay watch to affect your Youtube home recommendations (and history).
> 
> By default we provide Youtube as little information as possible.

If I block, the video(S) go away until I reload.

**Comment by stevecobb76** [comment]
> Did you login? Sources=>Youtube=>Login

Always logged in on my android to Google, Gmail, and youtube.

**Comment by Kelvin-FUTO** [comment]
You need to be logged in inside Grayjay, Thats separate from what you do in other apps. Other affects are separate from this.

**Comment by stevecobb76** [comment]
> Did you login? Sources=>Youtube=>Login

Always logged in on my android to Google, Gmail, and youtube.

> Did you login? Sources=>Youtube=>Login

![Screenshot_20231215_144639_Grayjay](https://github.com/futo-org/grayjay-android/assets/5054136/89bf86ed-af9d-4b56-a3e5-d2ee14046c40)
Yes I am logged in even though it's too small to read and I can't zoom in at all.

**Comment by stevecobb76** [comment]
> Did you login? Sources=>Youtube=>Login

Always logged in on my android to Google, Gmail, and youtube.

> Did you login? Sources=>Youtube=>Login

![Screenshot_20231215_144639_Grayjay](https://github.com/futo-org/grayjay-android/assets/5054136/89bf86ed-af9d-4b56-a3e5-d2ee14046c40)
Yes I am logged in even though it's too small to read and I can't zoom in at all.

**Comment by stevecobb76** [comment]
I fixed this problem by deleting cache & data. Then I re-logged in and it works with my youtube playlist(s). Thank you. Now I will pay for greyjay.

**Comment by Kelvin-FUTO** [comment]
Note on that screen you showed, you have to press your avatar to select that profile. 
Before that Grayjay doesn't consider it logged in yet, as it doesn't know the profile yet.
(This is a requirement because some people have multiple profiles)
