### ISSUE TITLE
Screencast does not listen to any input after the device has been on stand-by mode

### ISSUE THREAD

**Issue by Ash3781** [futo-org/grayjay-android#506]
Hey, I noticed that when playing a video via the Screencast thingy, then switching my device to stand-by mode (pressing once on the power button) and then waking it up after any amount of time, that then the video controls look like they're working (double press will still do the forward/backward animation, play/pause animation/button etc, but they don't actually do something, just the animation. The progress bar is also stuck at wherever I started the screencast thing, only way to regain control is by stopping the cast and then restarting it, tho sometimes even that does nothing and I have to quit the video

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
