### ISSUE TITLE
Empty videos list on some Rumble channels

### ISSUE THREAD

**Issue by mingyee2** [futo-org/grayjay-android#507]
Videos are not retrieving from some channels. I first noticed that I hadn’t seen any videos from subscriptions that usually posted daily. When I clicked the channel directly, the video list was empty. An example is Glenn Greenwald’s Rumble channel, https://rumble.com/c/GGreenwald. I tested this on at least one additional device also updated to the latest build.

**Comment by YourRedNeckNightmares** [comment]
Same but it appears to be all of rumble on my end

**Comment by Gthbacc** [comment]
Same issue here for all of Rumble. Rumble has been having issues for a while now. It looked like it was fixed last week but it seems like the issues are back.

**Comment by Privacy-Now** [comment]
All of Rumble and Patreon doesn't load for me

**Comment by mingyee2** [comment]
For me, https://rumble.com/user/vivafrei is fine, though. Do any of the others have problems with that channel? Might be a good test for debugging. Of note, one is /c/ and the other is /user/. Could bd a coincidence, could be related. Don’t know.

**Comment by mingyee2** [comment]
Going through my dozen or so Rumble subscriptions, it appears on my end at least it is exactly all the /c/ channels that do not load, and all the /user/ ones behave just fine.

**Comment by mingyee2** [comment]
There is also occasionally a toast that appears when loading subscription updates or some of these channels that says “[RUMBLE] stream was reset: PROT…”, but the rest is cut off.

**Comment by bpawnzZ** [comment]
Same here. For dev this is what I'm seeing

![Screenshot_20231217-031340_Grayjay](https://github.com/futo-org/grayjay-android/assets/151177455/04231bc2-b0ca-40ea-be8c-2e2c0d847d4b)

**Comment by EMAXII** [comment]
Rumble channels not pulling data - confirmed. Update / re-enable fails to rectify.

**Comment by jaypaw549** [comment]
Can't load videos from Rumble channels either.
![Screenshot_20231218-105047_Grayjay](https://github.com/futo-org/grayjay-android/assets/57370260/f8ff1219-b494-481f-a2f9-aed3f8b2560c)

**Comment by koen-futo** [comment]
Fixed next build.
