### ISSUE TITLE
[Issue] Search while seeing a youtube channel doesn't work 

### ISSUE THREAD

**Issue by joaovti** [futo-org/grayjay-android#51]
As the title says, searching while seeing a youtube channel doesn't work, at least for me. After 2 updates the issue still there.
![Screenshot_2023-10-24-21-26-13-748_com futo platformplayer-edit](https://github.com/futo-org/grayjay-android/assets/36377970/344a5eef-b978-4def-8e72-ac0ac006a585)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
