### ISSUE TITLE
Youtube plugin not loading videos, gives connection reset error.

### ISSUE THREAD

**Issue by RazaZaidi2802** [futo-org/grayjay-android#510]
I've been getting this since morning today, 16/12/2023. 
![Screenshot_20231216-234333_Grayjay](https://github.com/futo-org/grayjay-android/assets/58148776/01195ea1-a48e-42f0-af0e-bac7b06e11c4)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
