### ISSUE TITLE
YouTube plugin subscriptions import limit

### ISSUE THREAD

**Issue by AsHperson** [futo-org/grayjay-android#511]
My YouTube subscriptions stopped around the letter I for about 980 total. I know I've got more subscriptions down the alphabet.

**Comment by mingyee2** [comment]
@AsHperson Have you tried importing again? I had that problem before, because there is a limit at once, but when I did it again, it just picked up where it left off. In my case, I had to do it a few times, but I got all of them in the end.

**Comment by AsHperson** [comment]
Thanks for the help, however it shows nothing left to import.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
