### ISSUE TITLE
Exiting video always turns to portrait mode instead of landscape

### ISSUE THREAD

**Issue by Rundervinkje** [futo-org/grayjay-android#513]
Hello,
When starting a video in landscape mode, going full screen, finishing the video and pressing 'back', brings you back to the list view in portrait mode. Desired behaviour is that the lists keep being shown in landscape mode.
Thank you.

**Comment by mingyee2** [comment]
@Rundervinkje Is there a typo? You wrote that it brings you back to list view in portrait mode, but that desired behaviour is lists being in portrait mode.

Is lists being in landscape supported at the moment, though?

**Comment by Rundervinkje** [comment]
@mingyee2 well spotted! Corrected the typo so the feature is up2date.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
