### ISSUE TITLE
[Issue] Backup restore process working different from the steps described in app

### ISSUE THREAD

**Issue by hubdot** [futo-org/grayjay-android#52]
When restoring a backup Grayjay prompts that, to restore certain items - for example Subscriptions, the sources for that need to be enabled prior to recovering the backup.
This is not correct on my device. A backup recovery added all manually added Subscriptions for Youtube I had.

What I did:

1. I created a backup in Grayjay, including sources like Youtube, Twitch and Soundcloud also enabled additional to PeerTube and with some subscriptions that I added manually (not pulled from the Youtube Addon).
2. I uninstalled it and installed it again from the Google Playstore, it only had PeerTube installed and enabled by default.
3. Without installing any sources manually, I recovered my backup, just pressed continue.
4. It recovered the subscriptions for Youtube.
5. The source for Youtube had not been enabled - but it was installed by the backup.
6. It was, however, NOT enabled by the Backup restore.

My assumption: manually added subscriptions can possibly be recovered by the backup even without the source enabled first.

My suggestion would be: change the prompt and remove the message about the subscription recovery or change it to only manually added subscriptions will be recovered.
Also I'd suggest to automatically enable sources when recovering them from a backup, if they had been active before.
Possibly I'd add a hint of having to potentially re-login to all sources manually again after a restore.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
