### ISSUE TITLE
Crash when trying to play in background 

### ISSUE THREAD

**Issue by jchoneandonly** [futo-org/grayjay-android#520]
Whenever I try to play a video and lock my screen or try to play it in the background at all.
I'm running a Google pixel 7 pro

**Comment by koen-futo** [comment]
What background play setting are you using?

**Comment by jchoneandonly** [comment]
Picture in picture. It makes a mini player below. I use that because
otherwise the video only plays audio all the time and sometimes I like to
see what's playing

**Comment by JDog2pt0** [comment]
PiP is very unstable for me as well. I opened an issue a while ago, however I didn't provide any logs. It was just to draw attention mostly. May pull some logs eventually. Background (no PiP) seems to be stable. My kneejerk reaction is that it's a RAM/Mem leak issue since my phone starts crawling shortly before it crashes

**Comment by jchoneandonly** [comment]
i see. that sucks. hopefully they can get that figured out quickly. its a very inconvinient problem.

**Comment by koen-futo** [comment]
It seems to be pretty phone dependent. Can you guys list your device, OS, OS version and app versions please?

**Comment by JDog2pt0** [comment]
Pixel 4XL. GrapheneOS. Android 13. Grayjay 210. Phone is EoL/Extended Support. Unfortunately I need to get some bills caught up before I'm able to upgrade

**Comment by koen-futo** [comment]
I will see if I can acquire a similar device to do some testing. Can you please specify your version of GrapheneOS?

**Comment by JDog2pt0** [comment]
According the website I'm using "13-coral" version 2023122200. 

If you have to go to that much trouble, I wouldn't bother. I'm going to try to upgrade in the next few months. The 4xl is old...

**Comment by jchoneandonly** [comment]
It's looking like the most recent update fixed the problem for me. So far
it's been working well. Again, stock android, pixel 7 pro. Hopefully the
other guy you're talking to here can get his stuff figured out too. Good
luck!

**Comment by jchoneandonly** [comment]
So this problem has returned

**Comment by b-risk** [comment]
> It seems to be pretty phone dependent. Can you guys list your device, OS, OS version and app versions please?

I would like to add that this seems like an issue with the "auto rotate" option in the android operating system conflicting with GrayJay, a way to consistently get a crash is by turning on auto rotate in android settings, going in grayjay and loading a video, rotate the screen to turn on fullscreen mode, rotate it back so the phone is vertical again, and turning off the phone, I have found that disabling auto rotate in android fixed almost all of my crashes.

**Comment by Zvonimir-FUTO** [comment]
This issue seems to be fixed in the latest of Grayjay. Also for rotation issue if you are still experiencing crashes please open a new issue for it.  This should also be fixed with the latest rotation changes that were release few weeks ago.
