### ISSUE TITLE
Unable to handle embed Youtube videos

### ISSUE THREAD

**Issue by guri87-byte** [futo-org/grayjay-android#523]
I setup Grayjay to handle youtube links, so when I link a youtube link on any app it opens with Grayjay.

Unfortunately, it's not able to handle emded yt links.

**Comment by guri87-byte** [comment]
![Screenshot_2023-12-18-16-29-12-19_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/135817352/09bb4aac-e4e7-40ee-9231-c3f4fe945b23)

**Comment by Kelvin-FUTO** [comment]
I'm pretty sure I fixed this last build, are you sure your Youtube plugin is up2date?
If you have the Google Play version of Grayjay, you may have to manually update the Youtube source by going to the source details and tapping "Check for updates".

**Comment by guri87-byte** [comment]
Tried, no luck

**Comment by koen-futo** [comment]
Implemented in the next build.
