### ISSUE TITLE
Please Add Issue Templates to this Github repo

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#528]
I strongly suggest adding issue templates for both bugs and feature requests.

**Comment by koen-futo** [comment]
Any suggestion for what you guys would like to see? I am open to it but it's not something I would like to invest time into at this moment. I would rather focus on making the app better.

**Comment by birdup000** [comment]
> Any suggestion for what you guys would like to see? I am open to it but it's not something I would like to invest time into at this moment. I would rather focus on making the app better.

Here's an example of what I think would be nice in this repo something like this.

https://github.com/Josh-XT/AGiXT/issues/new/choose

**Comment by birdup000** [comment]
#517 Nice example like the Android Version,Plugin Version, etc... for the bug template

**Comment by birdup000** [comment]
@koen-futo  and @Kelvin-FUTO  here is the documentation on how to add the issues template.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

I really think adding this would be helpful for you guys as it has a part where you can see what version of the plugin someone is using if they enter it and also the build of the app incase you already patched it. These are very helpful for numerous reasons this is why I'm suggesting y'all should add this.

**Comment by Zvonimir-FUTO** [comment]
This has been implemented.
