### ISSUE TITLE
[Issue] Download option for Soundcloud audio is labeled as "Download as video".

### ISSUE THREAD

**Issue by hubdot** [futo-org/grayjay-android#53]
When selecting "Options" for a Soundcloud song Grayjay prompts you the offer to "Download as video".

It should be called "Download as audio" instead.

![Screenshot_20231025-032247](https://github.com/futo-org/grayjay-android/assets/64484308/3063ccdf-eb02-4cd0-b859-04e0cd2a28b9)

**Comment by hubdot** [comment]
As posted here: https://github.com/futo-org/grayjay-android/issues/54 I believe the most simple fix is to just call it "Download the media" as the function is already implemented.

This would resolve both items in one swoop I believe.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Now there is an option to download audio only when pressing Download.
Feel free to open a new issue if you are still encountering this.
