### ISSUE TITLE
Rumble channels empty

### ISSUE THREAD

**Issue by aintisaword0** [futo-org/grayjay-android#531]
When trying to directly access the channel of a Creator on Rumble the channel is completely blank. Once I try to go directly to their Channel I also find that the icon in my subscription box goes black. This has happened for multiple subscriptions and I've had to switch to their YouTube channels.

**Comment by JDog2pt0** [comment]
Duplicate of #507

**Comment by koen-futo** [comment]
Fixed in next build.
