### ISSUE TITLE
Youtube Plugin requiring captcha constantly

### ISSUE THREAD

**Issue by mxc0bbn** [futo-org/grayjay-android#535]
This just atarted happening a few days ago. Whenever I either goto the home page or subacriptions a dialog pops up that makes me go through a captcha verification. It happens constantly.

**Comment by koen-futo** [comment]
It sounds like you have a lot of subscriptions. How many do you have?

We already have a smart algorithm that tries to avoid the rate limits. However, if you have 500 subscriptions and refresh 3x within 20 seconds, you will still hit the rate limit.

This will trigger your IP to be temporarily limited (about 24 hours). After these 24 hours you should be fine again.

How many subscriptions do you have? Are there any other interesting things you can think of that may help us?

**Comment by mxc0bbn** [comment]
I have 28 subscriptions; however, it appears to have been resolved.  Since it has been about 24 hours I am assuming your suggestion was correct.  If it happens again I will update the issue.

**Comment by koen-futo** [comment]
Thank you @mxc0bbn feel free to reopen the issue if you encounter it again.
