### ISSUE TITLE
Can't find peertube creators

### ISSUE THREAD

**Issue by Cris-Edmundson** [futo-org/grayjay-android#536]
Was searching for the linux experiment on peertube and wasn't able to find him. Idoes this have something to do with how peertube is federated and what instance he's on?

Having a place to follow peertube folks along side YouTube channels is a huge part of the appeal to me

**Comment by HVinther** [comment]
In my experience the peertube-plugin only shows FUTO. Searching for some generic word like "the" with sources restricted to peertube yields only videos from FUTO.

**Comment by ProgrammerWhoPrograms** [comment]
See the [FAQ](https://grayjay.app/#faq):

> How do I install a specific PeerTube instance?

> Go to this website and enter the URL of your desired PeerTube instance [PeerTube Plugin Host](https://pluginhost.grayjay.app/peertube?url=https://peertube.futo.org) then click "Open in Grayjay" and it will offer to install that PeerTube instance as a plugin.

However, one problem with it is that the resulting plugin doesn't use HTTPS for the config URL (I came here to make that issue).

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
