### ISSUE TITLE
Progress bar in miniplayer doesn't always work

### ISSUE THREAD

**Issue by Roman19S** [futo-org/grayjay-android#537]
I am on A Fairphone 4 running /e/OS with the latest version of Grayjay from Grayjay.app (not Google Play) and I have updated versions of the Odysee and Youtube plugins.

The miniplayer sometimes does not have the progress bar like it's supposed to, especially when I press the down arrow button or slowly swipe the video down into the miniplayer. This happens across Youtube and Odysee videos. Here's an example below:

![Screenshot_20231220-213922_Grayjay](https://github.com/futo-org/grayjay-android/assets/30319719/9d31662c-6bca-4ca3-bb61-76ef52da146d)

But if I flick it down quick enough, it keeps the progress bar like it's supposed to:

![Screenshot_20231220-213927_Grayjay](https://github.com/futo-org/grayjay-android/assets/30319719/19e6d4ff-1356-4788-86e9-33e3f862f36a)

**Comment by CroatZ** [comment]
I had the same problem, which I'm not currently experiencing on the latest update. I do nonetheless have new bug, just sometimes. I have a double progress bar in the landscape mode.

![Screenshot_20240120_101051_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/79144083/f1f3ac3b-6c89-4429-84e7-1dad7fef4a44)

**Comment by CroatZ** [comment]
Great job, tnx.
