### ISSUE TITLE
Make grayjay the default app for opened links.

### ISSUE THREAD

**Issue by RlySkiz** [futo-org/grayjay-android#539]
Currently when browsing reddit or whatever website, when i may click a link it loads up youtube instead, i get an ad, then i first have to watch that ad, then i copy the name of the video, get out of the app, open grayjay, paste the name, finally watch it without more ads.

Is there a way/possibility to make grayjay work on any youtube/twitch link?

Like making it your default app for these links like you do with firefox instead of edge as your default browser.

**Comment by koen-futo** [comment]
![image](https://github.com/futo-org/grayjay-android/assets/129423944/5ce99685-9b87-4fd0-9c20-95ecb4a35c9f)
![image](https://github.com/futo-org/grayjay-android/assets/129423944/7ebde85f-4384-4fe2-b2ed-5f7736933a31)
![image](https://github.com/futo-org/grayjay-android/assets/129423944/43149817-abbd-4505-bcbb-4cb67d867072)

This is already possible. However we cannot do it without user interaction. See screenshots.
