### ISSUE TITLE
[Feature Request] Offer a "Download as audio" option even for video sources like Youtube. 

### ISSUE THREAD

**Issue by hubdot** [futo-org/grayjay-android#54]
While Grayjay offers a video download option it would be handy to have a native option to just download audio (for example for Podcasts done on Youtube).

This option could be offered directly under the "Download as video" option.
It could also be offered as a toggle feature in the settings for those users not wanting to have it come up in the popup.

![Screenshot_20231025-032300](https://github.com/futo-org/grayjay-android/assets/64484308/7935fb99-b7b6-4864-8e3a-a7d5b0164a70)

**Comment by McIrco95** [comment]
You can select non as video quality to only download audio. 
I use a playlist "podcast" to automatically download audio only

**Comment by hubdot** [comment]
True! It's already working.
Maybe the action itself could then just be renamed to "Download the media" instead. This would also fix my other issue here: https://github.com/futo-org/grayjay-android/issues/53

Because it's even called "Download the video" for purely audio sources like Soundcloud. So I guess just calling it media would fix both issues entirely.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Now there is an option to download audio only when pressing Download.
Feel free to open a new issue if you are still encountering this.
