### ISSUE TITLE
Cast don't work with Firecube 4K 2023.

### ISSUE THREAD

**Issue by PrzemekSkw** [futo-org/grayjay-android#542]
I pair Grayjay on android and shows me that is connected but Fcast on Firecube still Waiting for connection.
![Screenshot_2023-12-21-19-00-23-21_ca2ad563b57b5497046450f16b7718e2](https://github.com/futo-org/grayjay-android/assets/25219988/9a854d12-b24c-4e06-8c75-1c47855ed34d)

Regards.

**Comment by koen-futo** [comment]
Amazon typically takes incredibly long to review APKs. For this reason the latest FCast Receiver is not live yet on the Amazon store (submitted a few weeks back). Once it is live, I suspect your issue will go away.

In the meanwhile, I recommend to either use Chromecast or sideload the FCast Receiver APK.

**Comment by koen-futo** [comment]
FCast Receiver on Amazon should be published soon. They recently approved it. Feel free to give it another try whenever you have time. You will know you have the right version if a QR code shows up.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
