### ISSUE TITLE
Patreon plugin broken in general

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#543]
Like #541, but when i tried to click on a cached video in my feed, GJ crashed.
When i try to view a subscription from the creators feed it fails with a (95)[6-7] error.
When i refreshed all the content of the subscriptions feed went missing.
I've tried logging out and in again, etc.

GJ version: 219

**Comment by Kelvin-FUTO** [comment]
Was able reproduce and already fixed. 
Deploying hotfix (221) within an hour.

**Comment by mnbvasd** [comment]
Can confirm the fix worked.

Thanks for the update!
