### ISSUE TITLE
[bug] full screen portrait not following rotate setting

### ISSUE THREAD

**Issue by homeclubber** [futo-org/grayjay-android#545]
Thanks for adding the full screen portrait mode.

Unfortunately it doesn't respect either the setting or the system wide auto rotate.

Enabling at the moment always rotates with device orientation. 

There seems to be a rotational lock icon, but it appears intermittently and doesn't seem to do anything either.

Pixel 5, Android 13/lineage 20

**Comment by Philippe-Choquette** [comment]
Same here on a REDMAGIC 9 Pro running the latest Android 14 build.

**Comment by Zvonimir-FUTO** [comment]
There have been changes to how rotation works few weeks ago and this should be fixed. Feel free to open a new issue if you are still encountering this.
