### ISSUE TITLE
[FEATURE REQUEST] NewPipe Playlist Imports

### ISSUE THREAD

**Issue by MKBontwikkeling** [futo-org/grayjay-android#548]
Great app! If possible could you look into importing playlists from NewPipe? Importing subscriptions is awesome!

**Comment by McIrco95** [comment]
https://grayjay.app/faq.html

**Comment by MKBontwikkeling** [comment]
> https://grayjay.app/faq.html

As far as I can tell playlist imports are platform only. NewPipe has local playlists, so they won't be imported if I import YouTube playlists.

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #16.

**Comment by Beethoven-n** [comment]
> Duplicate of [#16](https://github.com/futo-org/grayjay-android/issues/16).

I'm not so sure of that. #16 covers _subscriptions,_ not _playlists._ Playlists aren't exactly the same thing, after all...
Please reopen this?

**Comment by Zvonimir-FUTO** [comment]
Ahh sorry about that.
