### ISSUE TITLE
[Feature Request] abillaty to cange sub Groups order

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#554]
Imo 
Hold and drag to rearrange order 
Double tap to open (right now hold)

**Comment by koen-futo** [comment]
There are already drag handles in the Groups tab. You can change order here.

**Comment by McIrco95** [comment]
I did not realise that there is a Groups tab. Is there any reason for Groups to be a seperat tab. It seems to me that tab does not serve any funktion that is not also served by the subscriptions tab (other then changing the order of groups). 
Which is why i dident even realise it existed until i read your message multiple times

**Comment by koen-futo** [comment]
It is used for editing groups, removing groups and such.
