### ISSUE TITLE
[Feature] Swipe Controls for Bottom Right Corner Ellipses Context Menu

### ISSUE THREAD

**Issue by jawadakhan97** [futo-org/grayjay-android#555]
hi, thanks for the app i use it all the time

if i could swipe from the bottom right corner with a radal menu or even only swiping up to quickly go in one motion to downloads rather than tapping twice it would make my life slightly easier when im using the app [which is frequent]

**Comment by Zvonimir-FUTO** [comment]
If I understood this correctly, you don't like that you have to click on **More** button to access other menus (tabs) like **Sources**, **Downloads**,  **Comments**. Instead you would like a some more fluid way to access this in one motion by using a radial menu?

It's worth mentioning that now you can **Manage Tabs** in settings and maybe rearrange some so you can access faster ones that you use more frequently. At least while something like this is not implemented.

**Comment by Zvonimir-FUTO** [comment]
Closing issue since there was no feedback from the user.
