### ISSUE TITLE
[Feature Request] Improvements for Group select Creators

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#561]
Having many platforms on grayjay means i have subscribed to "the same" channel sometimes 3-4 times on different platforms. 

When adding creators to a sub group i see the "same" channel 4 times without an indication of what platform. 
A quick improvement would beto make the sorting alphabetic or semi alphabetic so that channels with the same name will all appear together. 

A better longterm solution would be imo to allow some kind of manual or automatic linking of profiles like #244 or #560

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #244.
