### ISSUE TITLE
Need capability to remove creators from groups 

### ISSUE THREAD

**Issue by mingyee2** [futo-org/grayjay-android#569]
Unless I’m mistaken, this is not yet possible. I at least cannot figure out how to do it if it is.

**Comment by McIrco95** [comment]
Works for me 
Open group 
Tap the channel you want to remove 
Confirm popup

**Comment by mingyee2** [comment]
@McIrco95 Oh, you are indeed correct. Wasn’t a particularly obvious method to me, but maybe I’m just silly. Closing the issue, then.
