### ISSUE TITLE
[Issue] Hide video button for home feed is a bit broken

### ISSUE THREAD

**Issue by greengeckowizard** [futo-org/grayjay-android#57]
Hello, everytime I try to hide a specific video it keeps popping back in my home feed when I reopen the application. 

Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release})
Device information (brand= samsung, manufacturer = samsung, device = beyond2q, version-sdk = 31, version-os = )

**Comment by candroid-man** [comment]
For me, it never actually goes away. It's as if the button doesn't do anything

**Comment by greengeckowizard** [comment]
Issue is still present in 191 platform player

**Comment by Majber** [comment]
Issue is still present in 192 platform player

**Comment by Kelvin-FUTO** [comment]
This was fixed in 193.
