### ISSUE TITLE
Odysee videos inconsistent 

### ISSUE THREAD

**Issue by aintisaword0** [futo-org/grayjay-android#572]
Sometimes videos play with no issues and other times the plugin fails. Whenever a video fails it has the same unusual play time listed. Screen shot included. 
![Screenshot_20231224_214918_Grayjay](https://github.com/futo-org/grayjay-android/assets/94582486/dcd3987e-d06a-4d9d-86c9-91a18d66894a)

**Comment by koen-futo** [comment]
I think Odysee added another version to how they show videos. I will look at this today.

**Comment by koen-futo** [comment]
Fixed next build.
