### ISSUE TITLE
No 60fps option for 720p video on YouTube

### ISSUE THREAD

**Issue by astrodroid7** [futo-org/grayjay-android#58]
YouTube and NewPipe both have options for 60 frames per second on their 720p video playback on gameplay footage provided by YouTube creators but it is not utilized in GrayJay. 

Even Louis Rossmann's previous and current videos provides 720p60 in YouTube and NewPipe but only 720p30 is available in GrayJay.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
