### ISSUE TITLE
This YouTube video can't be played

### ISSUE THREAD

**Issue by LorneCash** [futo-org/grayjay-android#584]
https://youtu.be/CPVF9J2k_M4?si=4st90ixmTcQ5J6zo

![Screenshot_20231227-154016.png](https://github.com/futo-org/grayjay-android/assets/17584221/b0fdccab-c9af-4338-82bf-6cd305b3bf23)

I'm assuming the reason why is that in the YouTube app it shows this dialog box before the video will play.

![Screenshot_20231227-154106.png](https://github.com/futo-org/grayjay-android/assets/17584221/fbb4c453-7b8b-4795-a58e-a10a79cb675f)

**Comment by Kelvin-FUTO** [comment]
In version 222 (YT v161), a new setting was added to the Youtube plugin called "Allow Controversial Restricted".
When enabled it will allow you to bypass this check and play the video in Grayjay.
The dialog should also be improved to say so.
