### ISSUE TITLE
[Bug] Keyboard Phones ENTER key broken 

### ISSUE THREAD

**Issue by StrataWare3376** [futo-org/grayjay-android#592]
Pressing the ENTER key on Keyboard phones will highlight and then select the first available item. In Search bar, this means it highlights and then ENTERs the first suggestion rather than ENTER'ing the prompt in the text bar, and under the video section this selects the top video and ENTERs. This makes proper searching unusable. Please Fix this, I have had zero issue with any other apps like this before. 
Tested with Unihertz Titan Pocket and BB Key2 LE.

**Comment by koen-futo** [comment]
Will be fixed in the next release.
