### ISSUE TITLE
[BUG] Video layout keeps on Bugging out.

### ISSUE THREAD

**Issue by Crushvar** [futo-org/grayjay-android#599]
Since the last update occurred, I've had an odd problem where a second set of icons would appear whilst I was watching a video along side a second bar at the bottom to view the time in the video. It doesn't always occur, but it also starts to lag a little around the time this happens. The lag might just be the WiFi, but I have to constantly resort to 4G just to get a good quality picture on 1080p, sometimes even 720p. But thank you for the service. I have already paid (though I forgot the license key, so I'll do it again!) and I hope your endeavours pay off.

**Comment by xephos1one** [comment]
Like in #582?
If yes you can close this issue as it's a duplicate.
If no please explain what icons you mean that are double
