### ISSUE TITLE
[Feature Request] Swipe down on full screen to exit full screen 

### ISSUE THREAD

**Issue by EricsenSemedo** [futo-org/grayjay-android#60]
Currently, you have to swipe up from exactly in the middle of the video to exit full-screen or rotate your phone out of landscape mode to exit full-screen mode. It would be more intuitive to swipe down instead. A big plus would be the ability to create custom constraints or window where you could swipe down and exit full screen.

**Comment by McIrco95** [comment]
Swiping up could be used to start casting. Like flicking it up to the tv.

**Comment by Kelvin-FUTO** [comment]
This was added a while back, so closing this.
