### ISSUE TITLE
cast icon no longer showing up for chromecast

### ISSUE THREAD

**Issue by advanture-space** [futo-org/grayjay-android#601]
Happy new year!

So first chromecast never worked. Then it started working after update. After yet another update it was working almost perfect.

A while ago it stopped working after an update. I don't get any cast icon anymore at all.

Is there any way to force the cast icon to show up?

Are any debug logs needed? Please tell me how to get them or add a function to view them.

Would be really great if this regression could be fixed.

I only have a simple chromecast. Not AndroidTV. Therefore cannot install FCast Receiver. Unfortunately, meanwhile I have to go back to the official YouTube app.

**Comment by advanture-space** [comment]
I am an idiot. I disabled casting in the settings. I thought that means me casting live to video. Since I don't use my phone for that, I thought I disable that for safety to avoid accidental casting. But that casting actually means stuff like chromecast.

Just usability issue. Maybe casting in settings could be renamed to "casting to TV" or something? Imagine one day you implement casting to youtube. Then this needs to be renamed anyhow. (Not a feature I personally need.)

Thank you!

**Comment by koen-futo** [comment]
Good to know, thank you!
