### ISSUE TITLE
Nebula asks me log in to view video

### ISSUE THREAD

**Issue by GeorgePapoulidis** [futo-org/grayjay-android#604]
Trying to open a nebula video redirects me to log in (error: (104) [8-9]). I dont even have a nebula account and appart from that, i think it compromises my privacy

**Comment by McIrco95** [comment]
Nebula is not free. So without logging in (with a paid account) you can not watch the content.

**Comment by koen-futo** [comment]
@McIrco95 is correct. Closing this issue.

**Comment by koen-futo** [comment]
I just tried on the nebula website and was able to watch multiple videos for free without any issues. Back when it used to be a 1 video free trial. Does anybody know what is up with this?
