### ISSUE TITLE
Full-screen not staying in full-screen mode in any orientation

### ISSUE THREAD

**Issue by EricsenSemedo** [futo-org/grayjay-android#61]
Whenever I full-screen a video it automatically goes to a landscape orientation but sometimes I just want to hold it in a portrait orientation but when I do so it automatically exits full screen. Effectively, I can't watch it in the portrait orientation while full-screen.

**Comment by EricsenSemedo** [comment]
Also I'm not sure if this is intended but this occurs in the home menu too. I can't just rotate to landscape or portrait orientation I'm not sure exactly when this happens.

**Comment by koen-futo** [comment]
Portrait full screen support is planned, not done yet.

**Comment by Zvonimir-FUTO** [comment]
Closing for being stale. If it's still an issue then please open a new one.
