### ISSUE TITLE
Incorrect user email address field sanitization.

### ISSUE THREAD

**Issue by TxRxSR** [futo-org/grayjay-android#610]
Both periods (.) And plus-signs (+) are, in fact, legal characters for use in routable email addresses across the globe. The GrayJay app currently blocks the use of email addresses containing these characters. 

As a side-note, so called "plus-addressing" is a recommended strategy for organizing emails automatically, and also for differentiating an email address used simultaneously among multiple sites.

**Comment by Zvonimir-FUTO** [comment]
Closing as stale.
