### ISSUE TITLE
Fullscreen glitch

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [futo-org/grayjay-android#621]
A while ago, making videos fullscreen would cause this glitch that made the video unwatchable in that mode.
IIRC, I was on the same version as I am on now (222).
![Screenshot_20240104-215024](https://github.com/futo-org/grayjay-android/assets/38004699/96387aa5-b937-4c0a-ba35-4d4866b73145)
It's gone now. I'll keep you updated if it comes back.

**Comment by koen-futo** [comment]
Closing this for now, please reopen if you experience the issue again.
