### ISSUE TITLE
YouTube plugin crashes when scrolling through Home

### ISSUE THREAD

**Issue by aintisaword0** [futo-org/grayjay-android#623]
Every time I get a couple pages down on the Home tab I get an error message and videos will no longer load on the tab.
![Screenshot_20240105_092929_Grayjay](https://github.com/futo-org/grayjay-android/assets/94582486/a8c24709-bbb1-4d68-8bdb-e5723fd911d4)

**Comment by aintisaword0** [comment]
That fixed it. Thanks for the help.

**Comment by Kelvin-FUTO** [comment]
In version 278+ (YT V165) it now prompts to relog easily. This hopefully resolves/clears it up for people encountering this.
