### ISSUE TITLE
[Feature Request] Another column

### ISSUE THREAD

**Issue by EricsenSemedo** [futo-org/grayjay-android#63]
Sometimes there's enough space to fit another column of videos for example:
![Screenshot_20231025_023608_Grayjay.jpg](https://github.com/futo-org/grayjay-android/assets/99306164/342b635a-531f-49df-94bb-1ae9e78e0db8)

This has enough space for another column. You could have a setting to enable auto columns where it could dynamically create another column depending on the space or the user could select 2 or more columns. The default should be 1 column.

**Comment by Zvonimir-FUTO** [comment]
This should be implemented with the new landscape mode update.
