### ISSUE TITLE
Fcast streams broken for Electron

### ISSUE THREAD

**Issue by mnbvasd** [futo-org/grayjay-android#635]
After upgrading to GJ v225, it is unable to reliably fcast  to the electron receiver.

When trying to stream a YT, GJ keeps disconnecting and reconnecting to the fcast receiver, starting and stopping the stream in a connection loop. This makes it unusable.

If i go into settings while it is falling, the fcast stream will work uninterrupted, with GJ not trying to reconnect.

**Comment by koen-futo** [comment]
Having a look now. Are you sure your Electron app is up-to-date? You can right-click the tray icon and click check for updates.

**Comment by koen-futo** [comment]
I just tried reproducing but if you are on the latest version, it should work fine.

**Comment by koen-futo** [comment]
If you continue having issues, please let me know.

**Comment by mnbvasd** [comment]
Thanks @koen-futo, I just rebuilt the client, (aarch64), and it has only fixed the normal streams. It would be nice to have a version miss-match error message somewhere to prevent people from making that mistake again.

Live streaming still has identical behaviour to what I described above, and so is still broken.

**Comment by koen-futo** [comment]
I'll confirm live streaming though the change should not have anything to do with the type of content being played.

**Comment by koen-futo** [comment]
I will release a hotfix build reverting this change, it seems too impactful right now.

**Comment by mnbvasd** [comment]
Thanks for sorting this so quickly

**Comment by koen-futo** [comment]
Build should be up, hopefully it fixes you issues.

**Comment by mnbvasd** [comment]
The fix doesn't seen to be working for me (226).

**Comment by koen-futo** [comment]
Can you describe your issue more exactly? You connect to Electron desktop and you are having issues when casting live streams specifically?

**Comment by koen-futo** [comment]
Reproduced it, working on a fix for the Electron app.

**Comment by mnbvasd** [comment]
I go into GJ, select the casting button, and select the target receiver.

I then select a live stream from my feeds, and it starts to cast.

The receiver then starts to load, as soon as the video starts to play, it stops and tries to reload it.
GJ then makes the cast icon grey, flashes the notification "Connecedt to device..." or "Connecting". The icon goes blue again, and the cycle repeats.

**Comment by koen-futo** [comment]
Deployed a fixed version.

**Comment by mnbvasd** [comment]
That seems to fix now. Works great for both live and vods.

Thanks.
