### ISSUE TITLE
Ex/import subscription groups

### ISSUE THREAD

**Issue by Bluscream** [futo-org/grayjay-android#640]
Please add this so i can have my groups on all devices

**Comment by priyamkalra0** [comment]
I assumed that groups would be included in the export and reset grayjay. Oops. +1 for this.

**Comment by chriskeeble** [comment]
Please add this - groups is a key feature for me in order to share my settings / subscriptions between devices.

**Comment by Zvonimir-FUTO** [comment]
We have implemented this and is currently in testing phase, should be release with the next Grayjay release v265.
