### ISSUE TITLE
Remember volume/brightness throughout playlist

### ISSUE THREAD

**Issue by Bluscream** [futo-org/grayjay-android#642]

**Comment by koen-futo** [comment]
Next version will have the option to use system volume/brightness which should solve your issue.

**Comment by Bluscream** [comment]
> Next version will have the option to use system volume/brightness which should solve your issue.

No. This is not what i mean. I am using GrayJay's local controls often because
1. it's just more comfortable than using the devices controls for volume/brightness 
2. some more modern devices have ridicilous audio curves (1 volume step is the difference between no sound at all and getting my ears blasted off)

So i often just put me device volume on half so i can use grayjay's slider to get finer control over everything in the lower half.

**Comment by koen-futo** [comment]
The on-screen controls will remain, but they will control your system volume and brightness instead, so the issue you mention in your response should also be solved.
