### ISSUE TITLE
[question] how to show merchandise products like in rossmann channel?

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#664]
From a creator/plugin dev point of view, how can I show the merchandise products? Is there something to implement? Is it a webpage parser?

**Comment by koen-futo** [comment]
The next version of the app will include it in the tutorial videos but you just need to put your link on the harbor account. Here is the video if you want to watch it now https://releases.grayjay.app/tutorials/monetization.mp4

The store data url format can include multiple stores (separated by a space) and is compatible with:
1. Magento
2. Shopify
3. Spring
4. SquareSpace
5. Wix
6. WooCommerce

Alternatively:
1. You can input a link to a JSON file, example: https://announcements.grayjay.app/demo.json
2. You can put a JSON format into the store data url field with the same format as point 1
3. 
I hope this helps.

**Comment by teaalltr** [comment]
Great! Thank you!
