### ISSUE TITLE
[Bug] Phone/App lag

### ISSUE THREAD

**Issue by DavidusRidero** [futo-org/grayjay-android#69]
I had marked a large number (~1000) of videos to be downloaded as audio. The app just hangs along with the device.

It recovers after a minute or two

It maybe due to it fetching the 1080p thumbnails of all the videos

Petition to disable viewing the ongoing/scheduled downloads

**Comment by Zvonimir-FUTO** [comment]
@DavidusRidero Is this still the issue in the latest version of the app? 
Are you talking about downloading from Youtube or something else? 
Could you also provide information on which device are you using?

**Comment by DavidusRidero** [comment]
Apologies for the delay.

**Comment by DavidusRidero** [comment]
Am i to post any issues/opinions about the current version, in this thread or am i to create a new one. They are more of an UI/UX thing and I'm uncertain about posting them in a technical place.

**Comment by Zvonimir-FUTO** [comment]
> Am i to post any issues/opinions about the current version, in this thread or am i to create a new one. They are more of an UI/UX thing and I'm uncertain about posting them in a technical place.

Please open a new issue for each separate issue/feature request/UI change. Also the better you explain and visualize it the better we can understand it.

> Apologies for the delay.

No worries :)

> So far the previous issue is gone entirely. The app is snappy and responsive.

Closing since issue has been resolved.
