### ISSUE TITLE
Cannot scroll downloaded playlists/ No way to view all downloaded playlists

### ISSUE THREAD

**Issue by PhumeleleTom** [futo-org/grayjay-android#690]
In the downloads section, when there are many playlists downloaded, there is no way to scroll around for all of your downloaded playlists.I try scrolling and tapping the "Playlists" title to see if it would take me to a list of my playlists but nothing happens.
Please fix this issue.
Thank you.

**Comment by Kelvin-FUTO** [comment]
Scrolling should be fixed in upcoming version 278+ (release tomorrow).
