### ISSUE TITLE
[Bug] YouTube not working when using mobile data

### ISSUE THREAD

**Issue by SleepyFalcon** [futo-org/grayjay-android#692]
Android version of the app. Whenever I try to play a YouTube video when not connected to a WiFi. It will return this screen shot below. Works normally when connected to WiFi. 

I don't have problems playing on other platforms in the Grayjay app or on it's own YouTube rumble Odyssey twitch.

![Screenshot_20240116-104344](https://github.com/futo-org/grayjay-android/assets/22643209/2f189dcc-8125-40e6-b02a-07f122ee0d35)

**Comment by Noisy-Koi** [comment]
I have also been running into it this morning

**Comment by Startingfresher** [comment]
Same, my device is a moto g play 2021, on cricket data.

**Comment by SleepyFalcon** [comment]
I think this might be a deeper issue but I don't want to say this like I know for sure. When connected to my mobile data for my Linux laptop. The WiFi doesn't work. For the windows laptop it works just fine. Might be off subject. Will delete this comment after updating my OS.

**Comment by SleepyFalcon** [comment]
Yes, I think there seems to be a failure to connect when trying to connect to my Ubuntu laptop. Windows, works fine. Apple is unknown.

Service provider for Mobile is AT&T.
