### ISSUE TITLE
[Feature request] ad the possibility to creat subfeed

### ISSUE THREAD

**Issue by zoqin** [futo-org/grayjay-android#70]
Hello, i always haved dream of this feature on every plateform and especialy with grayjay app

I have more then 700 channel that im subscribe too and i would love to creat subfeed that i can customise for exemple i would be able to creat a feed with creator of tutorial
One about lifestyle
One about science
Etc

So not only i can focus more on the type of content i want to consume but at the same time i wont risk to break a limite of request by updating my feed

Thanks for your work the app is amazing

Sorry for my english im French

**Comment by prat89** [comment]
Great idea, I was going to add the same request! Please consider it!

**Comment by zoqin** [comment]
I found a chrome plugin for this call PocketTube
It add the possibility to creat subfeed with folder of creator 
If you can make it work on grayjay or alongside it or developpe something like it

**Comment by Kelvin-FUTO** [comment]
This has been added a few updates back through Subscription Groups. Additional features related to subscription groups will be added over time, but should cover this case atleast.
