### ISSUE TITLE
[Bug] Infinite Skip When Rotating Screen

### ISSUE THREAD

**Issue by Dillpickleschmidt** [futo-org/grayjay-android#71]
I've found a bug I've been able to reproduce repeatedly. If you double-tap to skip just as you rotate your phone, it will continuously skip non-stop as though you're still double-tapping. The only way to stop it is by closing the video and reopening.
It's kinda tricky to do, you have to get the timing just right, but if you do, you'll notice. Double-tap right as you're rotating.

**Comment by Zvonimir-FUTO** [comment]
Can't reproduce on the latest version. Is there still an issue on your side?

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
