### ISSUE TITLE
Brightness control in Fullscreen does not allow to fully turn off the screen anymore.

### ISSUE THREAD

**Issue by GERJanB** [futo-org/grayjay-android#719]
Until the last update I was able to black out the screen by turning the brightness to zero. This was usefull with just listening to audio without locking my phone. Now when I turn the brightness all the way down, the video is still visible.

**Comment by JustCryen** [comment]
Hi, when you disable "System brightness" in the settings, the app should allow you to black out the screen once again.

That'll be basically setting the video brightness independently from system brightness, like it was before.

**Comment by GERJanB** [comment]
Oh thanks. Yes that fixed it. Seems like i was just blind and did not find the setting.

**Comment by JustCryen** [comment]
It's new, maybe you haven't checked since it was implemented.
I'm glad I could help :)
