### ISSUE TITLE
[Feature request] Feed shows only videos from one group

### ISSUE THREAD

**Issue by RedAiluridae** [futo-org/grayjay-android#722]
In the feed there could be the option that the feed only shows videos from one group.

**Comment by Kelvin-FUTO** [comment]
Tapping a group in your subscriptions feed will only show videos from that group? 
Could you elaborate what you mean?

**Comment by RedAiluridae** [comment]
> Tapping a group in your subscriptions feed will only show videos from that group? Could you elaborate what you mean?

I mean when you open the app that only the subscribers of a certain group are displayed so that you are not distracted by other videos. For example, I only want to see gaming videos when I click on them and more useful videos immediately.

**Comment by RedAiluridae** [comment]
> Tapping a group in your subscriptions feed will only show videos from that group? Could you elaborate what you mean?

I subscribed to about 150 people but normally I only want to see something from about 20 but the other 130 people are in the feed before I tab into a group it would be better when I can choose a group which displays their videos at the beginning.

**Comment by B00fie** [comment]
I guess this is the same issue as #547

**Comment by Zvonimir-FUTO** [comment]
Subscription groups have been implemented which solve this issue.
