### ISSUE TITLE
Fullscreen UI Bug - Inconsistent Visibility of Bottom Buttons

### ISSUE THREAD

**Issue by HiteshAroraCool** [futo-org/grayjay-android#726]
I have observed an issue where, in fullscreen mode, the three bottom buttons remain visible throughout video playback. I'm unsure if this is a device-specific problem or a bug within the app. Please watch the attached video to get a clearer understanding of the problem. Your assistance in resolving this issue would be greatly appreciated. 

https://github.com/futo-org/grayjay-android/assets/76745725/e2f000d9-e858-43e6-bd07-cd629e5bfa5c

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
