### ISSUE TITLE
Images in this repo readme (in GitLab) look ugly on mobile

### ISSUE THREAD

**Issue by teaalltr** [futo-org/grayjay-android#754]
Well see here
![Screenshot_20240130-181135](https://github.com/futo-org/grayjay-android/assets/11365978/22b971aa-d5c4-49f3-9b82-805e44eefa06)

**Comment by Zvonimir-FUTO** [comment]
This is kinda intended because Gitlab flavored markdown doesn't support CSS so to put screenshots next to each other they have to be inside a table.
