### ISSUE TITLE
YouTube plug-in, login, "This browser app may not be secure"

### ISSUE THREAD

**Issue by Bod9001** [futo-org/grayjay-android#764]
app version :  233
youtube plug-in version : 165
android 10, lineageOS 17.1, (no Google play services)

When trying to login, I put in my email for the Google login, and then go to next page and it returns this, (URL covered up)
![image](https://github.com/futo-org/grayjay-android/assets/27101670/31e0fcc6-1bfe-45a6-a344-512a4cc221b1)

**Comment by Kelvin-FUTO** [comment]
I pushed an update to the Youtube plugin (v166) that increases the user-agent (Android 12). This may help.
I could not re-produced it myself, but let me know if it helped you.

**Comment by Bod9001** [comment]
yeah, that seems to have worked, can login all okay, thanks
