### ISSUE TITLE
[Feature request] Share from +Options

### ISSUE THREAD

**Issue by bruceschaff** [futo-org/grayjay-android#794]
Would be great if there was a share or copy link button in options so you don't have to open a video to do it.

**Comment by Kelvin-FUTO** [comment]
I've added this option, and should be deployed in an upcoming version. (v234+)

**Comment by bruceschaff** [comment]
Awesome thanks ❤️!

**Comment by MRDGH2821** [comment]
How do I access this share option?
I don't see it in settings menu at channel profile view.

I'm on v278

**Comment by Zvonimir-FUTO** [comment]
> How do I access this share option? I don't see it in settings menu at channel profile view.
> 
> I'm on v278

It's second option under **Actions** section, right after **Download**.
If it's not clear how I got to here, clicked on **Options** pill under the video in **Home** tab.

**Comment by MRDGH2821** [comment]
> It's second option under **Actions** section, right after **Download**. If it's not clear how I got to here, clicked on **Options** pill under the video in **Home** tab.

Sorry my bad, my actual question was - how do I share channel link?

I can see the share menu in Video's action section by tapping on the Options button.

For example:
I want to share a YouTube channel's link. But cannot as I don't see any option/button in channel profile view.
Although sharing video link does give them channel, I specifically want to share channel link as that is more useful for the circumstance I find myself in (i.e. while talking with friends on Discord, etc)

**Comment by Zvonimir-FUTO** [comment]
That is unfortunately not implemented in Grayjay yet. However this issue is not about that specific feature so could you please open a new feature request for that?

**Comment by MRDGH2821** [comment]
> That is unfortunately not implemented in Grayjay yet. However this issue is not about that specific feature so could you please open a new feature request for that?

Done #1780
