### ISSUE TITLE
Exiting fullscreen can be bugged

### ISSUE THREAD

**Issue by Matti-Koopa** [futo-org/grayjay-android#8]
If you exit fullscreen mode a different way (like with the triangle/back Android button), subsequent videos will be broken in fullscreen mode. For example, the menu bar will be visible.
Other effects can include the whole app beeing stuck in landscape mode instead of portrait.
Please see attached video for an example. In this video I first exit fullscreen mode normally (no side effects), then exit it a different way, then opening another video and demonstrating the effect,

https://github.com/futo-org/grayjay-android/assets/10476794/ff0012ea-28e2-40d1-b3a0-44089cce7ea2

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
