### ISSUE TITLE
Hide or downvote polycentric posts

### ISSUE THREAD

**Issue by mattvisa** [futo-org/grayjay-android#80]
I get and fully want polycentric integration, but I also want the option to not see some of the garbage people have started to post. If it's about sovereign identity and freedom of speech, maybe a way to mark stuff as spam and/or the original reddit model of up and down voting? I don't know. I'd hate to see free speech and thinking options once again become limited because of the noise of people filling up comment feeds with garbage.

**Comment by koen-futo** [comment]
Disproportionality disliked posts are now faded and posts now take likes into account when ordering them.
