### ISSUE TITLE
Links in the comments open too soon.

### ISSUE THREAD

**Issue by JustCryen** [futo-org/grayjay-android#804]
Basically the same issue as this one https://github.com/futo-org/grayjay-android/issues/10 but instead of the description, the the link is in the comments.

**Comment by rob-fi** [comment]
Was about to open an issue for this but I was surprised to find one already existed. Well, the issue still exists, it's quite annoying when the first comment is, for example, one that's pinned by the content creator with a whole bunch of links. You have to tread (tap) very carefully to scroll.

**Comment by Philippe-Choquette** [comment]
This should be closed and flagged as duplicate of #1391, in which a fix has already been announced (hurray)

**Comment by Zvonimir-FUTO** [comment]
Duplicate of #1391. We are looking into this but it probably won't land in next release.
