### ISSUE TITLE
Cannot auto rotate smoothly on home screen

### ISSUE THREAD

**Issue by dzahr** [futo-org/grayjay-android#81]
On the home screen and on the video screen, I cannot get the app to turn landscape mode, which is helpful because the headphone jack is on the bottom of the device in portrait mode. For context, I'm using a Samsung Galaxy tab A7.

**Comment by EricsenSemedo** [comment]
I think it happens for everyone but it happens on the zfold too. Not only that it also happens to the other tabs in the tabs bar.

**Comment by Zvonimir-FUTO** [comment]
Will be resolved through #67
