### ISSUE TITLE
IP ban from YouTube when using Grayjay

### ISSUE THREAD

**Issue by wjk82** [futo-org/grayjay-android#812]
Hello!

I tried Grayjay with YT login (to import subscription) and it worked fine. The subscriptions load slow but that is not the issue.

Immediately after I used the app I started to see "suspicious behavior from my IP warnings" on YT pages when using regular browser on mobile and PC. I need to pass reCaptcha validation to access YT. It is fine for some time but after longer inactivity when I visit YT, I got same warning and I need to pass validation again. Videos from YT embedded on websites do not work because of that (reCaptcha goes in a loop). 

I didn't know about that "feature" of Grayjay. I know it's not straight an app issue, but I don't know how to deal with it. Also I don't know why it happened. What I did was install the app, login using YT credentials, grab the subscriptions and refresh them. Then everyone using my home WiFi start having trouble. Not only my account, everyone from my IP.

**Comment by teambvd** [comment]
This is mostly YT trying to be as obstructive/painful as possible without blatantly calling out the user for something they can't prove (imo).

I'd recommend you unregister your YT account, then power cycle your modem+router to get a (hopefully) new IP address.

**Comment by wjk82** [comment]
I realize this is intimidation tactic from YT. It's been 24 hrs since it happened and it looks like it stopped. But I pay for static IP because I need it for my job so I can't use Grayjay from home, only from mobile random IP's. Simple subscriptions refresh cause the app to give me popup errors because of many requests it need to handle this task. I guess there is some limit set up by YT.

**Comment by teambvd** [comment]
> guess there is some limit set up by YT.

I dont use YT's subscription system, just local sub via app (backing up and converting as needed to import into other apps), and have some ~150 unique subscriptions at current - I can refresh them all back to back numerous times without issue, so if they are limiting account based subscription refreshes, at least its a fairly easy thing to work around 👍

**Comment by Kelvin-FUTO** [comment]
We are indeed doing a bit of a balancing act when it comes to rate-limits. Importing effectively tries to stay under the rate-limit. But the subscription refresh after that doesn't account for that previous import usage.

Subscriptions themselves try to select important channels to update and stay under the limit under normal usage. So should generally not cause any issues. If it does, you can adjust the rate-limit for Youtube specifically under the Youtube settings (Sources => Youtube).

It generally doesn't have much to do with your account, its mostly ip-based. We don't use YT subscriptions directly. And don't even use your logged in account unless you turn on "Use login for channels".
The IP effect is temporary. It does go away on its own (in a day or 2 at most).

We actually do have something half in production for a while that would help this issue (using rss feeds with its own issues), but it hasn't gotten priority over Desktop version. As the subscription system seems works decent under normal conditions.

**Comment by wjk82** [comment]
Thanx for clarification.
