### ISSUE TITLE
Elon Musk Double Money Scam Twitch Streams

### ISSUE THREAD

**Issue by Bnmnns** [futo-org/grayjay-android#816]
For some reason I'm getting, well look in the title, even though I never subscribed to this channel nor elon musk. 
![Screenshot_20240220_144431_Grayjay](https://github.com/futo-org/grayjay-android/assets/160616092/022e393b-4427-4ec4-b478-2c0b287d7655)
I noticed such stream a few weeks ago, but didn't gave it much of a thought. Now I think this is bs.

**Comment by McIrco95** [comment]
If you only want to see videos from channels you subscribed to you can disable the Home or move the Subscriptions tab to the first position.
