### ISSUE TITLE
Grayjay set top box (concept) please make!

### ISSUE THREAD

**Issue by theStyleWithin** [futo-org/grayjay-android#819]
I'm just putting this out there. Grayjay is already a great app as it it is. but if your aim is too illuminate the ads. You need to compete with smart TV's and roku too! I suggest that you make grayjay into an entire electronic plug and play media box that you can plug-in to your TV. I've thought about side loading grayjay onto Roku before. But why should that be our only option. and we can't escape from the ads if we don't have the ability to install grayjay on our TV's easily! So the best solution that I can think of is an electronic media box! Now, I know the app is supposed to be "free' but you know what? i would pay dollars! for a Grayjay set top box! And here are some more ideas for you: 

You can make it have various onboard storage options
128gb
256gb
500gb
1Tb 

you should also have the ability to plug in an sd card, micro sd card or an external ssd. some people might already have a big external storage so they might not want to pay more for a grayjay box with most storage. 

oh and make it so that way there is no configuration for the grayjay box to use external ssds. that way you can plug it back into your computer seamlessly. Plex users would love THIS! 

One of my dreams is to have my own personal "offline" version of YouTube! So, I have been trying to rip videos for my own personal use to enjoy and prevent them from falling into the category of "filed under Youtubes list of deleted videos for no reason."

if you make a grayjay set top box. you can bet that your audience would be willing to forgive that it's not free like the app is free. The app is only great for your phone or when the desktop version releases. The set top box is a replacement for roku which still forces users to watch ads. imagine you're watching a sermon and then an ad plays. it's like how rude! their basically saying to us our ads are more important then what you're currently watching right now.

**Comment by koen-futo** [comment]
In the short term, we are at least planning FCast Receiver apps for Roku, TizenOS, WebOS and AppleTV.

**Comment by theStyleWithin** [comment]
Casting is great for some people. But you have to keep in mind some people do gravitate towards their Roku. So, if they have a phone with Grayjay on it and a Roku. It's more likely they might forget that they have grayjay on their phone especially, the nontechy socker mom. I don't want to push it too much. I just want to stress that when my family starts turning on their Roku instead of using their Grayjay app. The ads will show up. I'm just saying you may want to consider making a roku competitor using Grayjay as a UI. 

If anything just please put it on your to-do list.
