### ISSUE TITLE
[Feature Request] Allow choosing which tab the app starts with. For example either subscriptions or playlists instead of Home

### ISSUE THREAD

**Issue by MrDowntempo** [futo-org/grayjay-android#820]
Personally, I use a script to make sure YouTube in my browser, always skips the home page and goes right to subscriptions (like the good ol days) would love it if GrayJay could be configured to do the same.

**Comment by McIrco95** [comment]
Already possible 
more/settings/ manage tabs/
Whatever is on top will open when opening the app
