### ISSUE TITLE
Issue with YouTube home page

### ISSUE THREAD

**Issue by bledo22** [futo-org/grayjay-android#823]
For the last two days my "Home" feed has random videos and not the usual suggestions based on my history. Tried logging in again and checking for updates for both Grayjay and the YouTube plugin but no luck. Also tried reinstalling the plugin and app but nothing worked.

**Comment by Blotz** [comment]
Check to see if you are still logged in. You dont get a notification when youtube logs you out. it just stops showing you recommended videos.

**Comment by bledo22** [comment]
Well I'll be damned!, turns out I wasn't logged in. The first thing I tried when the issue appeared was to log out - in, but it turns out that the last screen of the process, in my phone at least, looked like a desktop page of my YouTube profile, so I assumed that the login had ended, turns out it wasn't finished, I logged in a 3rd time and read every screen carefully and finally got it work, just selected my own YouTube profile on the very last screen. Thanks Blotz!,  I can go use the amazing app again!
