### ISSUE TITLE
[BUG] date of video uploaded

### ISSUE THREAD

**Issue by GenericUsernameIsNotAvailable** [futo-org/grayjay-android#834]
Using the Yotube Plugin. First and only time seeing this issue. See image attached
Date of upload is displaying "0 years"
![SmartSelect_20240229_192559_Grayjay](https://github.com/futo-org/grayjay-android/assets/157112907/01cb6cfc-1559-443d-9b48-f13dc967570c)

**Comment by birdup000** [comment]
I'm getting that problem too

**Comment by max-ishere** [comment]
Another video with this
https://www.youtube.com/watch?v=nSlGTVInDOI

![Imagepipe_6.jpg](https://github.com/futo-org/grayjay-android/assets/47008271/7bab515c-5c5a-43b9-bf33-b637ada1e333)
