### ISSUE TITLE
Rumble failure "too many requests"

### ISSUE THREAD

**Issue by Sigfried9** [futo-org/grayjay-android#838]
Rumble plugin is up to date. Play Store version of the app is up to date. However, I received this message upon every attempt to view Rumble videos recently. Retrying makes no difference.

![Screenshot_20240301-224414](https://github.com/futo-org/grayjay-android/assets/161915035/acfe7149-8351-4523-805c-950622c368fe)

**Comment by joeshavesde** [comment]
I just started getting the same error this morning.

**Comment by gpertea** [comment]
Same here.

**Comment by swankwc** [comment]
Failed to load video
Plugin [Rumble] [Rumble] Too many follow-up requests: 21 (202) [18-19] source.getConten tDetails(.. .)

**Comment by AceODay** [comment]
I've been getting the same since this morning.

**Comment by koen-futo** [comment]
Hey guys, I have been trying to reproduce this but have not been able to. Is this an issue that still exists? If so, can you please provide more details?

1. Does it always happen?
2. Does it start happening after a while of using the app?
3. Does it happen for every video or specific videos? If it is specific videos, can you please send over the problematic videos?

**Comment by Matti-Koopa** [comment]
It was always and on every video. It would load the title, description and so on, but video playback would display a loading animation and then would pop this message after 2 seconds.
But this happened a few days ago. It hasn't happened for at least 2 days.

**Comment by koen-futo** [comment]
OK great, thank you. If there is anybody that still has this issue, please reopen.

**Comment by AceODay** [comment]
The issue was resolved the very next day for me.

**Comment by swankwc** [comment]
> Hey guys, I have been trying to reproduce this but have not been able to. Is this an issue that still exists? If so, can you please provide more details?
> 
> 1. Does it always happen? No.
> 2. Does it start happening after a while of using the app? Yes.
> 3. Does it happen for every video or specific videos? If it is specific videos, can you please send over the problematic videos? No, it'll come up but usually resolved itself. Not always requiring me to even restart the app.
