### ISSUE TITLE
Upload date and likes are wrong

### ISSUE THREAD

**Issue by Dezzmotion** [futo-org/grayjay-android#84]
All my Youtube videos were uploaded 53 years ago, have -1 likes and a lot of dislikes.

**Comment by pearcebasmanm** [comment]
Also experiencing this. 53 years ago means the unix timestamp is 0 (1970-01-01 00:00:00). It's probably failing to get the date for some reason and defaulting to 0. Not sure what causes the -1 likes. Maybe a sentinel error value in the API which shouldn't be getting displayed? I can't find where the where any plugins like the YouTube one have their code.

**Comment by Kelvin-FUTO** [comment]
This has been fixed in version 193 (Youtube plugin version 148).
Was related to non-english youtube accounts.

**Comment by pearcebasmanm** [comment]
Interesting, I didn't know my account was non-English. Can confirm it's fixed for me.
