### ISSUE TITLE
Homepage filled with unrelated random content 

### ISSUE THREAD

**Issue by bagojan9898** [futo-org/grayjay-android#840]
It's been a few months now that my homepage is full of unrelated content from content creators that i never watch or watched .  I am signed in with my youtube account and have the subscriptions imported . However the homepage remains unrelated .
![Screenshot_2024-03-02-13-34-28-650_com futo platformplayer-edit](https://github.com/futo-org/grayjay-android/assets/39407516/d349b08e-4927-43fe-81b1-55476afb32ed)

**Comment by Robbylikes** [comment]
Use subscriptions to see your feed if you want what's to follow your content creators. The home is where you'd see just what's been uploaded with high view count; basically stupid people content.

**Comment by ThePrivacyPlayer** [comment]
I mean, it would be nice to have some kind of local-only personalization (without the need to share any data online) based on subscriptions and video views. I'm sure there's a way to that to some degree.

Also, even though I did watch one of the videos, it still remains in my home feed as viewed, it doesn't remove it, and there's no way to scroll past the first 10-20 items. This makes discovering new interesting content basically impossible.

**Comment by bagojan9898** [comment]
I don't think it was like this before though , hence I opened this issue thread .

**Comment by Blotz** [comment]
Check to see if you are logged in. I had this issue too. [Issue](https://github.com/futo-org/grayjay-android/issues/809)

**Comment by bagojan9898** [comment]
> Check to see if you are logged in. I had this issue too. [Issue](https://github.com/futo-org/grayjay-android/issues/809)

Well I checked and I was logged in so i logged out and in which fixed the issue . Thanks for the tip!

Log out and log back in your YouTube channel for a fix on this issue .
