### ISSUE TITLE
[Feature Request] Enter the creator channels from a specific platform

### ISSUE THREAD

**Issue by Alvaro-sD** [futo-org/grayjay-android#86]
When I access a creatos channel I can only access the polycentric channel, which doesn't show videos in the platform or any of the created playlists so that they can be imported.
It would be nice to acces e.g. the youtube channel and be able to save a playlist that they have created (or search from their videos)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
