### ISSUE TITLE
App freeze upon start when system brightness gesture is enabled

### ISSUE THREAD

**Issue by sn0wD4N** [futo-org/grayjay-android#862]
In version 236 on Android 14, enabling the System brightness gesture occasionally results in the app freezing upon opening, leading to a system-wide hang for 3-5 seconds. To address this issue, users must close the app, wait 2-3 seconds, and then start the app again.

**Comment by Allvaldrsson** [comment]
Same problem for me. App v236, Android 14, Pixel 6a. However, toggling any and all brightness settings on or off didn't offer resolution. App continues to freeze on initial launch after a break in operation.

**Comment by sn0wD4N** [comment]
The issue still persists.

**Comment by sn0wD4N** [comment]
I think it's gone with the arrival of 240. Thanks Devs!
