### ISSUE TITLE
YouTube continually asks for captcha and refuse to work 

### ISSUE THREAD

**Issue by Mohamed6935** [futo-org/grayjay-android#865]
Every day for the last week it asks me to fill out the captcha and doesnt work even if filled.
Usually got to log out and log in to the YouTube source for it to work but even that got 50% odds of working.
Sometimes it fixes it self and other times it breaks it self randomly mid usage

Latest grayjay, YouTube source, twitch source

**Comment by JDog2pt0** [comment]
Are you using a VPN? When I had that issue I switched servers and all was well again
