### ISSUE TITLE
Vertical videos not showing fulscreen properly.

### ISSUE THREAD

**Issue by JustCryen** [futo-org/grayjay-android#899]
Vertical videos, while a bit annoying, are getting somewhat more common (and are still better than "vertical" videos rendered as a horizontal one with black bars on the sides).

Unfortunately the app can't really handle vertical videos at all, entering fullscreen with a gesture or a button always rotates the screen instead of enlarging the image.

Reference video:
https://www.youtube.com/watch?v=upLSYyprib8

**Comment by KagamiyaMihn** [comment]
hello JustCryen,

open grayjay settings and search for "fullscreen portrait", turn that on. might solve your issue. 

regards,
Kagamiya
