### ISSUE TITLE
"&"-character not escaped on video detail page on Rumble

### ISSUE THREAD

**Issue by Matti-Koopa** [futo-org/grayjay-android#9]
Certain characters are not HTML-escaped on the detail page for Rumble videos and will appear in their HTML-escaped-form like "&amp;". This proble doesn't appear in the feed.
![Unbenannt](https://github.com/futo-org/grayjay-android/assets/10476794/5859fff0-e476-407a-b83a-458ed98775d2)

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
