### ISSUE TITLE
YouTube not showing comments

### ISSUE THREAD

**Issue by antifreak** [futo-org/grayjay-android#902]
Since a few weeks YouTube only load 20 comments without an option to extend/ view all.
In the beginning updating or reinstalling the YouTube plugin helped, but this doesn't do the trick anymore.

Would love a fix, can't search for timestamp comments in long videos anymore which is really inconvenient.

Thank you for your otherwise outstanding Application.

**Comment by GamingWithFusion** [comment]
+1

**Comment by Doc-4** [comment]
Same issue here!

**Comment by ThePrivacyPlayer** [comment]
You guys see YT comments on the app? Is there a setting for that? It doesn't show any comment for me...

**Comment by ThePrivacyPlayer** [comment]
Same here as well.

**Comment by Kelvin-FUTO** [comment]
Issue should be fixed.
No update of the app required, just the Youtube plugin update.
