### ISSUE TITLE
Home page not showing any videos when logged in

### ISSUE THREAD

**Issue by Basztek** [futo-org/grayjay-android#903]
After logging in to YouTube all videos on home page are not shown. Videos on subscriptions tab and any other work, searching on home page works, showing videos like normal.

I've tried the following:

- Logging out and in to YouTube.

- Reinstalling GrayJay

- Reinstalling plugin

- Restarting my phone

- Clearing cache/all data

The issue still persists.
Using Redmi Note 8 pro.

![Screenshot_2024-04-09-05-56-27-959_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/156368791/fcd7dacd-405c-4829-ab82-f92774fc1139)

![Screenshot_2024-04-09-05-59-14-235_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/156368791/fe26e904-67bc-4dd5-abc0-bc085bc607b9)

**Comment by jasonstone20** [comment]
I I have the same issue

**Comment by Kelvin-FUTO** [comment]
We've tried to reproduce this and were unable to.
In the next release (237+) we're adding the ability to send plugin data back to the plugin developer. 
Probably release early next week.

If you like to help us solve this (and trust us with the data). 
I recommend after the next update, you enable Developer Submission inside the Youtube plugin (option below check for updates toggle), and reproduce the exception. 
You'll see "DevSubmit [getHome]", which means it sent the data.
Afterwards you can disable it again. 
Finally post the date/time when you did it so we can easily find it.
Hopefully we know more about what goes wrong afterwards.

I'm assuming that if you login normally on the Youtube website, and go to your home page, it does display content?

**Comment by Basztek** [comment]
On YouTube I'm able to watch normally, on app as well as on web. The thing is when on GrayJay  home page has this missing content thing, i just checked and it is still there, but when i log in as different account home page works just as it should be. Perhaps it is a problem with my main YT account? but i'm can watch on YouTube app normally.

**Comment by Basztek** [comment]
It is a solution but i would rather not use another account

**Comment by Danilado** [comment]
I am facing this issue too
(The smartphone model is vivo iqoo neo 8, but I doubt it changes anything)

I enabled the developer submission option and it did in fact pop-up with DevSubmit [getHome]

It was 26th of April 2024 6:14 GMT+03

I also think it might be helpful to say that in my country the YouTube cdn for channel avatars and community post pictures is blocked
(the https://yt3.ggpht.com/* and yt4.ggpht.com domains)

**Comment by Kelvin-FUTO** [comment]
@Danilado I checked your DevSubmit, and looking at the response, Youtube does not appear to give a home page at all (no content whatsoever).

Could you give me any more info about your account which *might* cause this?
Do you have a homepage when you go to the website?

**Comment by Danilado** [comment]
@Kelvin-FUTO

So, first of all
> Do you have a homepage when you go to the website?
Yes, I have a homepage on website, official youtube app and youtube revanced

> Could you give me any more info about your account which _might_ cause this? 
I did change my google account name (of course I did log out and log in again), but I think I did it after the bug started appearing (just tried to change the nickname also -> no change)
Aside of that, I don't think I did anything to my google or youtube account which could cause the issue

I also tried the following in my efforts to fix the problem
- reinstalling the app - no effect
- installing different versions of the app (google, website, f-droid, older versions from f-droid) - no effect
- different phone, same account - no effect
- using a VPN - no effect
- friend's account - works perfectly

so I guess this is account-specific problem, however I have no idea what causes it. It just appeared for seemingly no reason

**Comment by Chreutz** [comment]
I also have had this problem for a while and I just sent a devsubmit two minutes ago.

**Comment by Chreutz** [comment]
I have a suspicion of something that might be related. I was subscribed to Hames Joffmann, a James Hoffmann parody account. This account was hard-deleted by youtube, and this issue appearing in grayjay roughly aligned with that time. Don't know if that helps.

**Comment by Basztek** [comment]
My home page is working after plugin update. hope that's the case for everyone
