### ISSUE TITLE
Queued items stuck

### ISSUE THREAD

**Issue by zjDrummond** [futo-org/grayjay-android#911]
Downloaded a video, and exported it. Not sure why this is stuck in notifications. ![Screenshot_20240417-154740_GitHub.jpg](https://github.com/futo-org/grayjay-android/assets/5123555/e9768115-81da-4e6d-87e5-d10ea6e81924)

**Comment by TheWheee** [comment]
Same :(

**Comment by Kelvin-FUTO** [comment]
Upcoming Grayjay version (237+) should fix several issues with notifications getting stuck after download/export.

**Comment by Kelvin-FUTO** [comment]
Version 240 released.
