### ISSUE TITLE
Question on Export

### ISSUE THREAD

**Issue by jpalcantara** [futo-org/grayjay-android#912]
I imported the subscriptions while my Youtube account was still active and I have now deleted the account.  Now I am looking at wiping the phone where Grayjay is installed, but I don't know where I could export all channels to be able to reimport them back into GrayJay.

**Comment by Kelvin-FUTO** [comment]
Grayjay offers an export function in settings (Backup=>Export Data), this provides you with a zip file containing the relevant data.
This file (.zip) can then be opened on the target phone, opened with Grayjay, and it will then attempt to import all your data.

I recommend first finishing importing on your new device, making sure it works, before wiping your phone of course.
