### ISSUE TITLE
Crash on screen lock

### ISSUE THREAD

**Issue by jchoneandonly** [futo-org/grayjay-android#928]
Whenever my screen gets turned off, grayjay crashes and loses my entire queue. Running latest update, this happens when playing in background mode or picture mode, I don't know if it'll happen when I'm doing something else on my phone.

**Comment by jchoneandonly** [comment]
Apparently that was a one time issue right after the update. Hasn't come up again.

**Comment by jchoneandonly** [comment]
It stopped on its own apparently

**Comment by dimyself** [comment]
this happens to me occasionally as well. 

it is currently happening right now. 

everytime i turn my screen off , with grayjay as the latest running app... grayjay stops 1-2 seConds after turn screen off.

when I turn the screen back on... grayjay automatically relaunches.

is there a way i can get a log for the crash?

i'm on the latest app and plugin versions

Thanks

**Comment by Zvonimir-FUTO** [comment]
@dimyself Please open a new bug report for this so we get all the needed information on versions and device info from you.

You can enable logging in settings by setting **Log Level** to _Verbose_. 
After the crash, you can Submit logs and copy the UUID and paste it inside the bug report.
