### ISSUE TITLE
Rate Limit Warning

### ISSUE THREAD

**Issue by CosmicIndustries** [futo-org/grayjay-android#93]
Rate Limit Warning

This is a temporary measure to prevent people from
hitting rate limit until we have better support for lots of
subscriptions.
You have too many subscriptions for the following plugins:

Youtube : 995 Subscriptions
Refresh Anyway/OK

I only reached the L's lol

**Comment by greengeckowizard** [comment]
Fr I'm having the same issue it like freezes on my side and I can't hit anything. I have around that amount of subscriptions in GrayJay too

**Comment by jpalcantara** [comment]
Is there a way to import a google takeout and skip the classic import.  After the B it stops.

**Comment by JustCryen** [comment]
> Is there a way to import a google takeout and skip the classic import.  After the B it stops.

This will probably work beautifully if implemented but I have a really old account that I lost count of who am I actually subscribed to.  
I would really like to still be able to interactively check / uncheck channels with their avatar and username visible, just like it is implemented now but working for a takeout backup as well.

**Comment by jpalcantara** [comment]
I wonder?  If I import all the channels 75 channel at a time, can I then delete the YouTube account?

**Comment by Kelvin-FUTO** [comment]
This week we released a new subscription system that should be able to deal better with loads of subscriptions (>150).
The import dialog also has a load more button now. Note that you should not import too fast or you can still hit rate limits.
