### ISSUE TITLE
Buy menu's price does not look right for Japanese JPY

### ISSUE THREAD

**Issue by Disctanger** [futo-org/grayjay-android#935]
The first page of Buy menu does not show correct amount(14.00 JPY). The text formatting needs to be fixed
![Screenshot_20240428-054759_Grayjay](https://github.com/futo-org/grayjay-android/assets/10447714/58839723-39b7-405e-999b-98491a40a925)

The second page(Stripe) does show correct price (1400 JPY). I guess its just string formating issue.

![Screenshot_20240428-054900_Grayjay](https://github.com/futo-org/grayjay-android/assets/10447714/b3c356f9-1ebb-49a5-9190-b65c9c29082b)

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the next release.
