### ISSUE TITLE
Import Playlist Not Pruning Duplicate Entries

### ISSUE THREAD

**Issue by CosmicIndustries** [futo-org/grayjay-android#94]
**Issue:**
When importing a playlist into the "GrayJay" app, it does not properly prune duplicate entries, leading to a cluttered and redundant playlist.

**Steps to Reproduce:**
1. Open the "GrayJay" app.
2. Navigate to the playlist import feature.
3. Select a playlist to import.
4. Observe that duplicate entries from the source playlist are not removed.

**Expected Behavior:**
The import playlist feature should detect and remove duplicate playlist entries to maintain a clean and organized playlist.

**Actual Behavior:**
Duplicate playlist entries are retained in the imported playlists, causing clutter.

**Comment by francis2054** [comment]
Can confirm, the newly imported playlists are the updated ones, the duped ones that stay are the old non-refreshed ones, without recent videos added to playlist.

**Comment by sadamczyk** [comment]
I could see someone having the same video in a playlist multiple times *on purpose*, so I'm not sure removing duplicates should really be the job of Grayjay. It should probably keep the playlists as close to the source as possible.

For example for a music playlist I can imagine having different music videos and then roughly every hour play the same music as a break/intermission.

Why do you have duplicates in the source playlist in the first place if you don't want them there? Can't you edit the source playlist then?

**Comment by francis2054** [comment]
> I could see someone having the same video in a playlist multiple times _on purpose_, so I'm not sure removing duplicates should really be the job of Grayjay. It should probably keep the playlists as close to the source as possible.
> 
> For example for a music playlist I can imagine having different music videos and then roughly every hour play the same music as a break/intermission.
> 
> Why do you have duplicates in the source playlist in the first place if you don't want them there? Can't you edit the source playlist then?

The dupes aren't from the source, OP means that if you import playlists twice, you get two of the same playlist, not sure why anyone would want that, you want updated playlists, not reimport again, if so add a duplicate button instead.

**Comment by sadamczyk** [comment]
@francis2054 Ah right, so you're talking about the Playlists themselves being duplicated when you're importing the same playlist multiple times. That does indeed seem like an annoying behavior. Maybe there should be a refresh/sync function for the playlists itself, preferably even an automatic refresh (daily, weekly or whatever).

But I'm not sure if that's what @CosmicIndustries was actually talking about. The reproduction steps don't mention anything about importing playlists multiple times. The word "entries" in the description is unclear to me. Are "entries" the videos etc. *inside* of a playlist **or** the playlists themselves? Can you please clarify?

**Comment by CosmicIndustries** [comment]
Apologies yes when re-importing the same playlists are given as options.
