### ISSUE TITLE
[Feature Request] Add a confirmation option for deleting groups

### ISSUE THREAD

**Issue by MRDGH2821** [futo-org/grayjay-android#943]
I was browsing through the app's UI & found the groups section.

And due to accidentally tapping on the delete button, one of the groups got deleted....

Can we have a confirmation button to prevent such accidents?

Or something like this:
Hide the delete button. 
Add a settings icon besides the `+` button which will have an option called `Delete groups`.
And now select the groups to delete.
Click on confirm button or ✔️ icon to delete the groups.

**Comment by Zvonimir-FUTO** [comment]
This has been implemented in the upcoming release (v265).
