### ISSUE TITLE
Media controls do not work

### ISSUE THREAD

**Issue by hack-wizard** [futo-org/grayjay-android#949]
I've notices that media control buttons (pause/play, etc) are not working with Grayjay.  They work with most other media apps I've used, including NewPipe/Tubular so I'm not sure if this is an actual bug or just a feature that isn't implemented.

Only tested on ChromeOS and Android so far, but it is quite annoying for me, not to mention part of the reason I'm not using Grayjay more often.  It also doesn't work from headset buttons, or standard keyboard implementations so I'm leaning towards it being a missing feature.  Where might I request this?

**Comment by hack-wizard** [comment]
To clarify, as I just realized I may not have been clear, I'm talking about physical buttons on external devices.  I really don't like tapping at my screen just for playback controls.

**Comment by hack-wizard** [comment]
Is this going to be considered as a potential feature or am I possibly in the wrong place?

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
