### ISSUE TITLE
[Issue] Unusual Spike in Battery usage

### ISSUE THREAD

**Issue by johnnycarlson** [futo-org/grayjay-android#96]
#### Description
Unusual pattern of battery usage in foreground and background even if the app is left in idle. I am certain that the total playback time has been less than 10 mins however it would have been left idle. I suspect something to do with background play. Not sure tho.

#### Screenshots
![Screenshot_20231027-062707](https://github.com/futo-org/grayjay-android/assets/149109275/65f68b6e-d981-4e2d-9269-45a4a3e6db5b)

#### App Details
Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release})
Device information (brand= google, manufacturer = Google, device = panther, version-sdk = 34, version-os = )

#### To Reproduce
Open the app. 
Play a video and minimize it in picture in picture mode.
Kill the video player but the leave the app in background.
See the battery usage.

Let me know if anything else is need. Great app already bought the license. Cheers.

**Comment by koen-futo** [comment]
We will investigate. Note that Android will sometimes attribute battery usage to an app simply because it has a ForegroundService running even if it does not actually add any battery consumption. FairEmail is one of the other programs on my phone that suffers from this.

Regardless, we will investigate.

**Comment by ProgrammerWhoPrograms** [comment]
This is affecting me too. Much more starkly.
![Used: 50%; Screen time: 1hr 15mins; Background: 6hrs 22mins](https://github.com/futo-org/grayjay-android/assets/38004699/1db44479-2ed6-4315-8aa5-b2e6d1b47613)

Please let me know if saying that was not useful and bad issue tracker etiquette.

**Comment by ProgrammerWhoPrograms** [comment]
Oh. I forgot. I'm using GrapheneOS UQ1A.240205.002.2024020500 on bluejay (Pixel 6a). Grayjay version is 235.

**Comment by ProgrammerWhoPrograms** [comment]
Not sure if it came about the same way as it did for johnnycarlson though. I rarely use picture-in-picture mode. So maybe it's a different issue.

**Comment by Zvonimir-FUTO** [comment]
Are you still experiencing the same issue? Do you _feel_ the battery drain, like is it discharging faster then usual? It seems to be reporting similarly on my Pixel 7 Pro with GrapheneOS but I didn't notice any battery issues.

**Comment by Zvonimir-FUTO** [comment]
Closing issue as stale.
