### ISSUE TITLE
Not able to start video while Bering logged in to YouTube plugin

### ISSUE THREAD

**Issue by PawelGilecki** [futo-org/grayjay-android#965]
Whenever I'd like to start video while being logged in to YouTube plugin there's na error displayed.
![Screenshot_2024-05-07-21-22-29-526_com futo platformplayer](https://github.com/futo-org/grayjay-android/assets/64919317/c51f21a7-aaaf-47a6-ba6c-20a628b094d5)
Reinstalling plugin and relogging does not help either. Same video van be accessed without aby issues when I'm not logged on to plugin

**Comment by PawelGilecki** [comment]
Disabling setting marked below allows video to be player while being logged in to YouTube plugin
![IMG_20240507_221610](https://github.com/futo-org/grayjay-android/assets/64919317/c3605639-b2a3-44da-a20b-35a3f5c9989a)
However, than a different error pops up. Luckily it does not prevent from running video
![IMG_20240507_221703](https://github.com/futo-org/grayjay-android/assets/64919317/0782e1a6-f7c7-4bdb-b44d-648723764cae)

**Comment by GenericUsernameIsNotAvailable** [comment]
Same issue here. Wondering if Youtube is trying to snuff GrayJay out....

**Comment by VonChair** [comment]
I can confirm the same issue with playing youtube videos.

**Comment by PawelGilecki** [comment]
Updating plugin to version 174 resolves the problem
