### ISSUE TITLE
New plugin update causes problems

### ISSUE THREAD

**Issue by dcalitri** [futo-org/grayjay-android#970]
Whenever I load up replies on a platform comment, I get a throwable parameter error. And whenever I refresh my subscription page, I get a captcha required error even though I have captcha already. Deleting captcha and redoing it didn't work either.

![Screenshot_20240508_165710_Grayjay](https://github.com/futo-org/grayjay-android/assets/71895943/df53e7ac-f363-4569-b2a2-af0e2ff975dc)
![Screenshot_20240508_132521_Grayjay](https://github.com/futo-org/grayjay-android/assets/71895943/5f0ed82d-6519-4fb2-931f-8a868afc5e3c)

**Comment by dcalitri** [comment]
The captcha error is gone, but the throwable parameter error is still an issue when loading up replies.

**Comment by Kelvin-FUTO** [comment]
@dcalitri Is this still an issue? 
If so, is it on all videos? (If not, which video)
Also, what are your settings for the Youtube plugin? Do you have "Use Login for video details" enabled?

**Comment by dcalitri** [comment]
@Kelvin-FUTO It seems to still be a problem with all of the videos. And I don't have "Use login for video details" enabled? Could that be the issues?

**Comment by dcalitri** [comment]
@Kelvin-FUTO I just disabled the "Use login for video details" settings and I can view replies.

**Comment by Kelvin-FUTO** [comment]
@dcalitri That sounds like it could correlate with a fix that was added to authenticated detail requests used to support membership content comments.
If you do not have any YouTube channel memberships, enabling those settings have no added value. 

I will investigate what might cause it.

**Comment by Kelvin-FUTO** [comment]
Issue found, will be released hopefully together with the new plugin update flow next week.

**Comment by dcalitri** [comment]
Okay cool.
