### ISSUE TITLE
Failed to load video

### ISSUE THREAD

**Issue by KaiO3031** [futo-org/grayjay-android#971]
![Screenshot_20240509-044313](https://github.com/futo-org/grayjay-android/assets/169315435/92a58124-b897-43ed-ab98-0289e10a742e)

**Comment by Xyeenie** [comment]
same issue here, android 14 - OnePlus 11 5G - OxygenOS 14.0. happens on all videos, eventually goes away after many retries.

**Comment by Santanu074** [comment]
s
![Screenshot_20240510_130735_Grayjay](https://github.com/futo-org/grayjay-android/assets/103441705/55c78dcf-7b75-4280-b831-cab7dddc9bfc)
Same issue facing in Samsung S23  (6.1),

**Comment by DSchaedler** [comment]
Samsung Galaxy S9 while loading this specific video.

![Screenshot_20240513-115746_Grayjay](https://github.com/futo-org/grayjay-android/assets/20712246/c2304e7b-2207-461f-ba2c-5e4d831c678c)
![Screenshot_20240513-115752_Grayjay](https://github.com/futo-org/grayjay-android/assets/20712246/61ce4d1a-1cab-4360-8505-6a279f28ebfa)

**Comment by Kelvin-FUTO** [comment]
This was solved last week. Updating the Youtube plugin should solve it.

A more forceful update prompt for enabled plugins will be added to an upcoming version of the app.
