### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Redneckcmb** [futo-org/grayjay-android#974]
![Screenshot_20240509_080214_Grayjay](https://github.com/futo-org/grayjay-android/assets/169368721/5516a73a-378b-46c6-aa7a-f8fcb593a3ef)

**Comment by Ser-Bul** [comment]
Man, I understand you're a newbie. Unfortunately just sharing the screenshot of the app showing the error message is not enough to get the bug fixed. Please complete the description of the issue with more details:

- Grayjay app version number (e.g. 420)
- Youtube plugin version (e.g. 176)
- a step-by-step list of actions you perform that lead to the error message popping up
- ideally - a link to the video opening which causes the error

**Comment by Kelvin-FUTO** [comment]
This was solved last week. Update your Youtube plugin.
In an upcoming version of the app we will more forcefully prompt for updating an enabled plugin.
