### ISSUE TITLE
Failed to load video (Script Exception)

### ISSUE THREAD

**Issue by macosali** [futo-org/grayjay-android#988]
![SmartSelect_20240513_222931_Grayjay.jpg](https://github.com/futo-org/grayjay-android/assets/74787929/a56c8ed9-ad97-4d5d-b491-8e85cea1768b)

Youtube version :172
App Version :240

Its occurs in every video when i try to open from anywhere

**Comment by 10acimport** [comment]
Same problem

**Comment by alenookej** [comment]
Samé here

**Comment by macosali** [comment]
Solved after reinstall YT plugin.
