### ISSUE TITLE
Videos don't load, exception thrown

### ISSUE THREAD

**Issue by tanmay1100** [futo-org/grayjay-android#990]
![Screenshot_2024-05-14-10-04-57-712](https://github.com/futo-org/grayjay-android/assets/77286251/be8d13f0-6318-483a-bf04-7a3ed862209e)

**Comment by venthewolf** [comment]
Duplicate of https://github.com/futo-org/grayjay-android/issues/988

**Comment by tanmay1100** [comment]
Solved after updating to the new version of the youtube plugin
