### ISSUE TITLE
YouTube errors

### ISSUE THREAD

**Issue by Redneckcmb** [futo-org/grayjay-android#992]
Every time I try to play a YouTube video I get an error message Rumble will play YouTube will not

**Comment by maverick-1983** [comment]
I'm also having the very same issue. Nothing can be played! I think YouTube has gotten aggressive with Futon! 😤

**Comment by tanmay1100** [comment]
Did you try updating the source plugin?

**Comment by lucina-da-lucario** [comment]
Strange. I can view YouTube videos just fine.

**Comment by XtratoS** [comment]
> Did you try updating the source plugin?
> 

How do you update the plugin?

**Comment by tanmay1100** [comment]
> > Did you try updating the source plugin?
> 
> How do you update the plugin?

Go to the sources tab, if there is an update available for your source, it will be saying that in the List Tile of your source

**Comment by Kelvin-FUTO** [comment]
Youtube indeed required a login last week. 
Upcoming version of the app will more forcefully prompt an update is available if you have a plugin enabled, and even allow for automatic updating (if enabled) if no permissions changed.
