### ISSUE TITLE
Playlist not importing

### ISSUE THREAD

**Issue by mjain234** [futo-org/grayjay-android#993]
I am trying to import playlist but it isn't importing any playlist for past 1 minute. Is it a known issue?
https://github.com/futo-org/grayjay-android/assets/70900505/4a6ed08c-d343-4212-bae8-64b13c598cb3

**Comment by Ser-Bul** [comment]
Seems like: https://github.com/futo-org/grayjay-android/issues/85

**Comment by Zvonimir-FUTO** [comment]
Closing since more information is in #85 and is still active.
