### ISSUE TITLE
i can't read youtube comment replies 

### ISSUE THREAD

**Issue by Heroknight18** [futo-org/grayjay-android#998]
when I'm trying to open youtube replies it shows throwable

**Comment by codebymatter** [comment]
Ive noticed this issue as well. If you Reinstall the YT plugin, Grayjay will rollback the YT plugin to its previous build version which doesn't gave the YT comments issue. We'll gave to wait until it is addressed in a future plugin update.

**Comment by B00fie** [comment]
![Screenshot_2024-05-21-00-47-09-626_com futo platformplayer-edit](https://github.com/futo-org/grayjay-android/assets/159699305/4c308cba-60dc-40c8-86a1-62c26d861dda)
Error is as above

**Comment by Kelvin-FUTO** [comment]
This is an issue if you enable "use login for details".
However, in a recent Youtube plugin update, this was fixed.
